'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{boot131}=require('./helpers/expansions131.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),R=C.Arsenal134Rules,D=R.catalog;
function fresh(){const{g}=boot131();require('../src/succession133.js').install(g);require('../src/arsenal134.js').install(g);g.startNew('standard','17117');g.phaseTime=999;standAt(g,g.player,g.core());g.player.invulnerable=0;return g;}
function step(g,s){for(let n=0;n<Math.ceil(s/.1);n++)g.arsenal134.step(.1);}
function craft(g,id){const q=g.arsenal134.preview('craft',id);assert.ok(q.ok,q.reason);assert.equal(g.arsenal134.begin('craft',id).ok,true);step(g,q.seconds+.1);assert.equal(g.arsenal134.busy(),false);return g.arsenal134.view().locker.at(-1);}
function obtain(g,id){const i=craft(g,id);assert.ok(g.arsenal134.transfer(i.uid,'carried').ok);return i;}
function fixtureItem(g,id,{condition=100,rounds=0,equip=true}={}){const raw=g.serialize(),a=raw.expansions127.modules.arsenal134,i={uid:a.next++,id,condition,rounds};a.carried.push(i);if(equip){a.equipped=i.uid;raw.player.weapon=D[id].base;raw.player.magazine={pistol:0,rifle:0,shotgun:0};if(D[id].category==='firearm')raw.player.magazine[D[id].base]=rounds;}raw.succession133.current.weapons=[...new Set(a.carried.filter(i=>D[i.id].category==='firearm').map(i=>D[i.id].base))];g.restoreSave(raw);return i;}
function zombie(g,x,y,hp=200){g.spawnZombie('walker');const z=g.zombies.at(-1);Object.assign(z,{x,y,health:hp,maxHealth:hp});g.rebuildZombieGrid?.();g.zombieGrid?.clear?.();return z;}

test('arsenal134: 40 usable balanced profiles, finite ammo and no modification to historic weapon IDs',()=>{assert.equal(Object.keys(D).length,40);assert.deepEqual(Object.keys(C.WEAPONS),['pistol','rifle','shotgun']);assert.deepEqual([...new Set(Object.values(D).map(d=>d.category))].sort(),['deployed','firearm','improvised','melee','tool']);for(const d of Object.values(D)){assert.ok(d.range>0&&d.damage>0&&d.fireRate>0&&d.wear>0&&d.kg>0);assert.ok(Object.values(d.cost).every(n=>n>0));if(d.category==='firearm')assert.ok(d.magazine<=C.WEAPONS[d.base].magazine&&d.ammoPerReload>0);}});
test('arsenal134: assemblies consume actual depot stocks after timed work, never grant rounds',()=>{const g=fresh(),before={...g.resources},i=craft(g,'revolver');assert.equal(g.resources.scrap,before.scrap-D.revolver.cost.scrap);assert.equal(g.resources.ammo,before.ammo);assert.equal(i.rounds,0);assert.ok(g.arsenal134.transfer(i.uid,'carried').ok);assert.ok(g.arsenal134.equip(i.uid).ok);assert.equal(g.player.magazine.pistol,0);g.startReload();assert.equal(g.player.reload,D.revolver.reload);g.player.reload=0;g.finishReload();assert.equal(g.player.magazine.pistol,6);assert.equal(g.resources.ammo,before.ammo-6);});
test('arsenal134: damage and wear apply to actual new profile, repair pays without filling magazine',()=>{const g=fresh(),i=fixtureItem(g,'revolver',{rounds:5,condition:20});g.player.shootCooldown=0;g.shootPlayer();assert.equal(g.projectiles.at(-1).damage,D.revolver.damage);assert.equal(g.player.magazine.pistol,4);assert.ok(Math.abs(g.arsenal134.view().carried.find(x=>x.uid===i.uid).condition-(20-D.revolver.wear))<1e-7);const stock=g.resources.scrap,q=g.arsenal134.preview('repair','revolver');assert.ok(g.arsenal134.begin('repair','revolver',i.uid).ok);step(g,4);const repaired=g.arsenal134.view().carried.find(x=>x.uid===i.uid);assert.equal(repaired.condition,100);assert.equal(repaired.rounds,4);assert.equal(g.resources.scrap,stock-q.cost.scrap);});
test('arsenal134: switching different magazine sizes preserves each exact loaded count',()=>{const g=fresh(),small=fixtureItem(g,'pocket',{rounds:7,equip:false}),large=fixtureItem(g,'revolver',{rounds:3,equip:false});assert.ok(g.arsenal134.equip(small.uid).ok);assert.equal(g.player.magazine.pistol,7);assert.ok(g.arsenal134.equip(large.uid).ok);assert.equal(g.player.magazine.pistol,3);g.restoreSave(g.serialize());assert.equal(g.player.magazine.pistol,3);assert.ok(g.arsenal134.equip(small.uid).ok);assert.equal(g.player.magazine.pistol,7);});
test('arsenal134: pause and interrupted work spend nothing, loaded or broken guns cannot fire for free',()=>{const g=fresh(),before={...g.resources};assert.ok(g.arsenal134.begin('craft','pipe').ok);g.paused=true;step(g,30);assert.equal(g.arsenal134.view().task.progress,0);g.paused=false;g.player.x+=8;step(g,1);assert.equal(g.arsenal134.busy(),false);assert.deepEqual(g.resources,before);fixtureItem(g,'pocket',{rounds:4,condition:0});g.player.shootCooldown=0;const count=g.projectiles.length;g.shootPlayer();assert.equal(g.projectiles.length,count);assert.equal(g.player.magazine.pistol,4);});
test('arsenal134: hand weapons spend stamina once and cannot bypass empty stamina or pause',()=>{const g=fresh(),i=fixtureItem(g,'spear');g.player.meleeCooldown=0;g.player.stamina=100;g.melee();assert.equal(g.player.stamina,100-D.spear.stamina);assert.equal(g.player.meleeCooldown,1/D.spear.fireRate);const value=g.arsenal134.view().carried.find(x=>x.uid===i.uid).condition;g.player.meleeCooldown=0;g.player.stamina=0;assert.equal(g.arsenal134.melee(),true);assert.equal(g.arsenal134.view().carried.find(x=>x.uid===i.uid).condition,value);g.paused=true;g.player.stamina=100;g.melee();assert.equal(g.player.stamina,100);});
test('arsenal134: death keeps loaded magazines and wear at exact corpse, successor receives nothing',()=>{const g=fresh(),i=fixtureItem(g,'revolver',{rounds:4,condition:57}),old=g.arsenal134.view().carried;g.damagePlayer(1000);const r=g.succession133.remains().at(-1);assert.equal(g.arsenal134.view().carried.length,0);assert.deepEqual(r.magazine,{pistol:0,rifle:0,shotgun:0});assert.deepEqual(g.arsenal134.view().fallen[0].items,old);assert.ok(g.succession133.select('porter'));assert.equal(g.arsenal134.view().carried.length,0);g.restoreSave(g.serialize());Object.assign(g.player,{x:r.point.x,y:r.point.y});assert.equal(g.succession133.loot(r.id),true);const item=g.arsenal134.view().carried.find(x=>x.uid===i.uid);assert.equal(item.condition,57);assert.equal(item.rounds,4);assert.equal(g.arsenal134.view().fallen.length,0);assert.equal(g.succession133.loot(r.id),false);});
test('arsenal134: carry weight and malformed records rejected without replacing world',()=>{const g=fresh(),raw=g.serialize(),a=raw.expansions127.modules.arsenal134;a.locker.push({uid:a.next++,id:'heavyNest',condition:100,rounds:0});g.restoreSave(raw);const post=g.arsenal134.view().locker[0];fixtureItem(g,'pickaxe',{equip:false});assert.equal(g.arsenal134.transfer(post.uid,'carried').ok,false);const world=g.world,bad=g.serialize();bad.expansions127.modules.arsenal134.carried[0].condition=101;assert.throws(()=>g.restoreSave(bad));assert.equal(g.world,world);});
test('arsenal134: portable defense costs, separate ammunition and damaged retrieval cannot heal for free',()=>{const g=fresh();for(const i of [...g.arsenal134.view().carried])assert.ok(g.arsenal134.transfer(i.uid,'locker').ok);const i=fixtureItem(g,'tripod',{equip:false});g.player.x=2700;g.player.y=2000;g.player.facing=0;assert.ok(g.arsenal134.deploy(i.uid).ok);const post=g.arsenal134.view().posts[0];assert.equal(post.item.rounds,0);g.player.carry.ammo=12;assert.ok(g.arsenal134.servicePost(i.uid,'ammo').ok);assert.equal(g.player.carry.ammo,0);assert.equal(g.arsenal134.view().posts[0].item.rounds,12);const raw=g.serialize();raw.expansions127.modules.arsenal134.posts[0].health=80;g.restoreSave(raw);assert.ok(g.arsenal134.servicePost(i.uid,'pickup').ok);assert.equal(g.arsenal134.view().carried[0].condition,50);assert.ok(g.arsenal134.deploy(i.uid).ok);assert.equal(g.arsenal134.view().posts[0].health,80);const dead=g.serialize();dead.expansions127.modules.arsenal134.posts[0].health=0;g.restoreSave(dead);assert.ok(g.arsenal134.servicePost(i.uid,'clear').ok);assert.equal(g.arsenal134.view().posts.length,0);});
test('arsenal134: held functional tools accelerate their real work and wear finitely',()=>{const g=fresh(),i=fixtureItem(g,'hatchet');assert.equal(g.arsenal134.toolFactor('wood'),1.25);assert.equal(g.arsenal134.toolFactor('stone'),1);assert.equal(g.arsenal134.wearTool('wood',10),true);assert.equal(g.arsenal134.view().carried.find(x=>x.uid===i.uid).condition,100-10*R.toolWear);assert.equal(g.arsenal134.wearTool('wood',Infinity),false);});
test('arsenal134: old preparation cannot service hands or melee and does not replace durability repair',()=>{const g=fresh();fixtureItem(g,'hatchet',{condition:30});assert.equal(g.playerOps131.preview('service').ok,false);const pistol=g.arsenal134.view().carried.find(i=>i.id==='pistol');assert.ok(g.arsenal134.equip(pistol.uid).ok);assert.equal(g.playerOps131.preview('service').ok,true);});
test('arsenal134: real contact hits respect reach, facing and walls before consuming a target',()=>{const g=fresh();fixtureItem(g,'spear');g.player.x=2700;g.player.y=2000;g.player.facing=0;g.player.stamina=100;g.player.meleeCooldown=0;const front=zombie(g,2760,2000),back=zombie(g,2660,2000);g.buckets.clear();for(const z of [front,back]){const key=Math.floor(z.x/g.bucketSize)+Math.floor(z.y/g.bucketSize)*1000;const rows=g.buckets.get(key)||[];rows.push(z);g.buckets.set(key,rows);}g.arsenal134.melee();assert.equal(front.health,200-D.spear.damage);assert.equal(back.health,200);g.player.meleeCooldown=0;const clear=g.hostileLineClear;g.hostileLineClear=()=>false;g.arsenal134.melee();g.hostileLineClear=clear;assert.equal(front.health,200-D.spear.damage);});
test('arsenal134: deployed guns consume their own ammo, stop without light, and survive save unchanged',()=>{const g=fresh();for(const i of [...g.arsenal134.view().carried])g.arsenal134.transfer(i.uid,'locker');const i=fixtureItem(g,'tripod',{equip:false});g.player.x=2700;g.player.y=2000;g.player.facing=0;assert.ok(g.arsenal134.deploy(i.uid).ok);g.player.carry.ammo=5;assert.ok(g.arsenal134.servicePost(i.uid,'ammo').ok);const target=zombie(g,2820,2000);g.buckets.clear();g.buckets.set(Math.floor(target.x/g.bucketSize)+Math.floor(target.y/g.bucketSize)*1000,[target]);const stock=g.resources.ammo,watch=g.nightwatch;g.nightwatch={visible:()=>false};g.arsenal134.step(.1);assert.equal(target.health,200);assert.equal(g.arsenal134.view().posts[0].item.rounds,5);g.nightwatch={visible:()=>true};g.arsenal134.step(.1);assert.equal(target.health,200-D.tripod.damage);assert.equal(g.arsenal134.view().posts[0].item.rounds,4);assert.equal(g.resources.ammo,stock);g.nightwatch=watch;const saved=g.arsenal134.snapshot();g.restoreSave(g.serialize());assert.deepEqual(g.arsenal134.snapshot(),saved);});
