'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),P=require('../src/atlas-projection.js'),Save=require('../src/save.js');
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function state(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
test('atlas : 4096 unités locales correspondent exactement à 128 mètres',()=>{assert.deepEqual(P.toRegion(0,0),{x:4032,y:4032});assert.deepEqual(P.toRegion(4096,4096),{x:4160,y:4160});assert.deepEqual(P.toRegion(2048,2048),{x:4096,y:4096});assert.equal(C.TILE/P.RULES.unitsPerMetre,1);});
test('atlas : transformations réversibles sur la grille et hors cases entières',()=>{for(const x of [0,13.7,32,1077.25,2048,4095.125,4096])for(const y of [0,71.5,2048,4096]){const w=P.toRegion(x,y),p=P.toLocal(w.x,w.y);assert.ok(Math.abs(p.x-x)<1e-8);assert.ok(Math.abs(p.y-y)<1e-8);}});
test('atlas : valeurs non finies refusées',()=>{for(const n of [NaN,Infinity,-Infinity]){assert.throws(()=>P.toRegion(n,0));assert.throws(()=>P.toLocal(0,n));}});
test('atlas : emprise des bâtiments depuis la rotation et non depuis le sprite',()=>{const{game:g}=fresh();const B=g.core().constructor,b=new B(888,'house',70,65,1,1);g.world.add(b);const p=P.footprint(b);assert.equal(p.w,b.w);assert.equal(p.h,b.h);assert.equal(p.x,4032+70);assert.equal(p.y,4032+65);assert.equal(p.id,b.id);});
test('atlas : chantier, état électrique et dommages lus dans le bâtiment réel',()=>{const{game:g}=fresh();const B=g.core().constructor,b=new B(887,'house',72,68,0,.4);g.world.add(b);b.powered=false;b.health=50;const m=P.model(g),p=m.buildings.find(p=>p.id===b.id);assert.equal(p.complete,false);assert.equal(p.progress,.4);assert.equal(p.powered,false);assert.equal(p.health,50);});
test('atlas : destruction et déplacement suivis, sans fantôme ni nouvelle copie',()=>{const{game:g}=fresh(),B=g.core().constructor,b=new B(885,'house',72,68,0,1);g.world.add(b);assert.ok(P.model(g).buildings.some(p=>p.id===b.id));g.world.remove(b);assert.ok(!P.model(g).buildings.some(p=>p.id===b.id));b.gx=76;g.world.add(b);assert.equal(P.model(g).buildings.find(p=>p.id===b.id).x,4108);});
test('atlas : position exacte du joueur local et position régionale distincte',()=>{const{game:g}=fresh();g.player.x=1789;g.player.y=1901;assert.deepEqual(P.playerPosition(g,{active:false}),{...P.toRegion(1789,1901),z:0});assert.deepEqual(P.playerPosition(g,{active:true,x:5000,y:5001,z:1}),{x:5000,y:5001,z:1});});
test('atlas : lecture du modèle ne modifie ni ressources ni RNG ni sauvegarde',()=>{const{game:g}=fresh();const before=state(g);for(let i=0;i<10;i++)P.model(g);assert.equal(state(g),before);});
test('atlas : règle graduée bornée pour tous les niveaux de zoom',()=>{for(const s of [.02,.073,1,3.6,10,25]){const b=P.scaleBar(s,130);assert.ok(b.pixels<=130+1e-8&&b.pixels>25);assert.ok(Math.abs(b.pixels-b.metres*s)<1e-8);assert.ok(/ m$| km$/.test(b.label));}});
test('atlas : zoom ancré sous le pointeur, pas au centre de la carte',()=>{const cam=P.camera(850,600),before=cam.world(610,410);cam.zoomAt(2,610,410);const after=cam.world(610,410);assert.ok(Math.hypot(before.x-after.x,before.y-after.y)<1e-8);assert.equal(cam.zoom,2);});
test('atlas : zoom D-17 et dessin d’une voiture utilisent le même facteur',()=>{const cam=P.camera(850,600);cam.fit(4096,4096,190);const a=cam.screen(4032,4032),b=cam.screen(4160,4160);assert.ok(Math.abs((b.x-a.x)/128-cam.scale)<1e-8);assert.ok(4.6*cam.scale>14);});
test('atlas : pan et limites de zoom ne modifient pas la campagne',()=>{const cam=P.camera(850,600);cam.zoomAt(1e6);assert.equal(cam.zoom,256);cam.pan(1e6,1e6);assert.equal(cam.x,0);assert.equal(cam.y,0);cam.zoomAt(.000001);assert.equal(cam.zoom,1);});
test('atlas : les quatre sorties gardent la coordonnée tangentielle',()=>{for(const [side,p]of [['east',{x:4058,y:2071}],['west',{x:38,y:2033}],['north',{x:2057,y:38}],['south',{x:2039,y:4058}]]){const q=P.exitPosition(p,side);assert.equal(P.exitSide(p),side);if(side==='east'||side==='west')assert.equal(q.y,4032+p.y/32);else assert.equal(q.x,4032+p.x/32);}});
test('atlas : les quatre entrées utilisent les points locaux historiques',()=>{const points=[{x:4160,y:4096,z:0},{x:4032,y:4096,z:0},{x:4096,y:4032,z:0},{x:4096,y:4160,z:0}],expect=[[4036,2048],[60,2048],[2048,60],[2048,4036]];for(let i=0;i<4;i++){const p=P.entryTarget(points[i]);assert.equal(p.x,expect[i][0]);assert.equal(p.y,expect[i][1]);}});
test('atlas : pas de retour depuis un étage ou depuis le milieu de la région',()=>{assert.equal(P.entryTarget({x:4160,y:4096,z:1}),null);assert.equal(P.entryTarget({x:5000,y:5000,z:0}),null);assert.equal(P.entryTarget({x:4160,y:4100,z:0}),null);});
test('atlas : une jonction bloquée ne permet plus de traverser le centre fictif',()=>{assert.equal(P.homeBarrier(4096,4096),true);assert.equal(P.homeBarrier(4155,4096),true);assert.equal(P.homeBarrier(4159,4096),false);assert.equal(P.homeBarrier(4163,4096),false);});
test('atlas : le contrat de projection reste compatible avec la sauvegarde courante',()=>{const{game:g}=fresh(),d=g.serialize();assert.equal(d.version,20);assert.equal(Save.validate(d).version,C.SAVE_VERSION);assert.equal('atlas' in d,false);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.serialize().version,20);});
test('atlas : itinéraire et budget de carburant partent du même point local projeté',()=>{const{game:g}=fresh(),d=g.serialize();d.frontier.seen=[g.frontier.world().pois[0].id];g.restoreSave(d);g.player.x=1700;g.player.y=2055;assert.ok(g.frontier.pin(d.frontier.seen[0]));const line=g.frontier.guidance(),budget=g.fieldSupplies.routePlan();assert.ok(line&&budget);assert.ok(Math.abs(line.metres-budget.outwardMetres)<1e-8);const pos=P.toRegion(g.player.x,g.player.y);assert.deepEqual(line.path[0],pos);});
