'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),Kit=require('../src/expansion-kit.js'),E=require('../src/exploration-125.js'),B=require('../src/barricades134.js');
function fresh(){const env=bootGame(),g=env.game;E.install(g,globalThis.document);Kit.install(g);B.install(g);g.startNew('standard','17117');g.paused=false;g.activeOverlay=null;g.units=[];g.zombies=[];g.player.carry={wood:20,scrap:16,stone:0,food:0,fuel:0,ammo:0,medicine:0};g.world.nodes.forEach(n=>n.depleted=true);return g;}
function approach(g,t,side=1){const s=t.domain==='local'?32:1,p={x:t.x-Math.sin(t.angle)*s*side,y:t.y+Math.cos(t.angle)*s*side};if(t.domain==='local'){g.player.x=p.x;g.player.y=p.y;}return p;}
function first(g,kind='door'){return B.localTargets(g.exploration125.plan).find(t=>t.kind===kind);}
function work(g,seconds=20){for(let i=0;i<seconds*4&&g.barricades134.busy();i++)g.barricades134.step(.25);}
function build(g,t,type='planks'){approach(g,t);const q=g.barricades134.begin('build',t.id,type);assert.equal(q.ok,true,q.reason);work(g);assert.ok(g.barricades134.snapshot().records.some(r=>r.target===t.id));}
test('barricades: all three paid physical variants have coherent work and resistance tradeoffs',()=>{const ds=Object.values(C.BarricadeRules134.types);assert.equal(ds.length,3);assert.ok(ds[0].health<ds[1].health&&ds[1].health<ds[2].health);for(const d of ds){assert.ok(d.seconds>0);assert.ok(C.bagTotal(d.cost)>0);}});
test('barricades: station doors, broken windows and courtyard gates map to genuinely free apertures',()=>{const g=fresh(),targets=B.localTargets(g.exploration125.plan);for(const kind of['door','window','gate'])assert.ok(targets.some(t=>t.kind===kind));for(const t of targets){assert.equal(g.exploration125.plan.solids.some(b=>E.circleIntersectsRect(t.x,t.y,8,b)),false,t.id);}});
test('barricades: construction is timed, pays bag once and obstructs allied, hostile and sight geometry',()=>{const g=fresh(),t=first(g),start={...g.player.carry};approach(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);g.barricades134.step(.25);assert.deepEqual(g.player.carry,start);work(g);assert.equal(g.player.carry.wood,start.wood-6);assert.equal(g.player.carry.scrap,start.scrap-1);assert.equal(g.friendlyPositionClear(g.player,t.x,t.y),false);assert.equal(g.hostilePositionClear({radius:10},t.x,t.y),false);const a=approach(g,t,1),b=approach(g,t,-1);assert.equal(g.hostileLineClear(a,b),false);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,false);});
test('barricades: real broken window is barricaded and can be reopened from the other face',()=>{const g=fresh(),t=first(g,'window');build(g,t,'sheet');approach(g,t,-1);assert.equal(g.barricades134.begin('dismantle',t.id).ok,true);work(g);assert.equal(g.barricades134.snapshot().records.length,0);assert.equal(g.barricades134.collision('local',t.x,t.y,10),false);});
test('barricades: no remote construction, no wall-crossing work, no spawn over occupant',()=>{const g=fresh(),t=first(g);g.player.x=2048;g.player.y=2048;assert.equal(g.barricades134.begin('build',t.id,'planks').ok,false);g.player.x=t.x;g.player.y=t.y;assert.equal(g.barricades134.begin('build',t.id,'planks').ok,false);approach(g,t);g.player.carry.wood=0;assert.equal(g.barricades134.begin('build',t.id,'planks').ok,false);});
test('barricades: pause freezes work, movement and death cancel without spending',()=>{const g=fresh(),t=first(g),before={...g.player.carry};approach(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);g.paused=true;g.barricades134.step(.25);assert.equal(g.barricades134.job.elapsed,0);g.paused=false;g.player.x+=20;g.barricades134.step(.25);assert.equal(g.barricades134.busy(),false);assert.deepEqual(g.player.carry,before);approach(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);g.player.dead=true;g.player.health=0;g.barricades134.step(.25);assert.equal(g.barricades134.busy(),false);assert.deepEqual(g.player.carry,before);});
test('barricades: repairs paid and capped; dismantle preserves inventory capacity and cannot duplicate refunds',()=>{const g=fresh(),t=first(g);build(g,t);assert.equal(g.barricades134.damage(t.id,100),true);const scrap=g.player.carry.scrap;assert.equal(g.barricades134.begin('repair',t.id).ok,true);work(g);assert.equal(g.barricades134.snapshot().records[0].hp,90);assert.equal(g.player.carry.scrap,scrap-1);g.player.carryCapacity=C.bagTotal(g.player.carry);assert.equal(g.barricades134.begin('dismantle',t.id).ok,true);work(g);assert.equal(C.bagTotal(g.player.carry),g.player.carryCapacity);assert.equal(g.barricades134.begin('dismantle',t.id).ok,false);});
test('barricades: enemy contact destroys physical block, cooldown prevents damage every frame',()=>{const g=fresh(),t=first(g);build(g,t);const p=approach(g,t),z={id:g.nextId++,x:p.x,y:p.y,kind:'walker',health:60,radius:10,dead:false,attackCooldown:0};g.zombies=[z];const hp=g.barricades134.snapshot().records[0].hp;g.barricades134.pressure('local',.04);assert.ok(g.barricades134.snapshot().records[0].hp<hp);const next=g.barricades134.snapshot().records[0].hp;g.barricades134.pressure('local',.04);assert.equal(g.barricades134.snapshot().records[0].hp,next);g.barricades134.damage(t.id,999);assert.equal(g.barricades134.snapshot().records.length,0);assert.equal(g.barricades134.collision('local',t.x,t.y,10),false);});
test('barricades: saved damage roundtrips, legacy absence migrates empty, malformed target rejects transactionally',()=>{const g=fresh(),t=first(g);build(g,t);g.barricades134.damage(t.id,17);const raw=g.serialize(),before=g.barricades134.snapshot();g.restoreSave(raw);assert.deepEqual(g.barricades134.snapshot(),before);assert.equal(g.friendlyPositionClear(g.player,t.x,t.y),false);const bad=g.serialize(),world=g.world;bad.expansions127.modules.barricades134.records[0].target='local:fake:door';assert.throws(()=>g.restoreSave(bad),/Barricades/);assert.equal(g.world,world);const old=g.serialize();delete old.expansions127.modules.barricades134;g.restoreSave(old);assert.deepEqual(g.barricades134.snapshot(),B.initial());});
test('barricades: new campaign clears barricades and old world collision closures',()=>{const g=fresh(),t=first(g);build(g,t);g.startNew('standard','17117');assert.deepEqual(g.barricades134.snapshot(),B.initial());assert.equal(g.barricades134.collision('local',t.x,t.y,10),false);});
test('barricades: region gap identity, geometry and floor contract derive from shared walls',()=>{const g=fresh(),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex');const ts=B.regionTargets(w,p,0),upper=B.regionTargets(w,p,1);assert.ok(ts.length>=2);assert.ok(upper.length>=2);for(const t of ts){assert.equal(w.blocked(t.x,t.y,.15,t.z,p.id),false,t.id);assert.ok(t.width>=.7&&t.width<=4.5);}assert.equal(new Set([...ts,...upper].map(t=>t.id)).size,ts.length+upper.length);});
function regionAt(g,t){const raw=g.serialize();raw.frontier.active=true;raw.frontier.anchor={x:raw.player.x,y:raw.player.y};raw.frontier.x=t.x-Math.sin(t.angle);raw.frontier.y=t.y+Math.cos(t.angle);raw.frontier.z=t.z;raw.frontier.inside=t.z?t.inside:null;g.restoreSave(raw);g.paused=false;g.activeOverlay=null;}
test('barricades: regional build uses actual player position, shared physical world and persistent floor',()=>{const g=fresh(),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex'),t=B.regionTargets(w,p,0).find(t=>t.kind==='door');regionAt(g,t);const q=g.barricades134.begin('build',t.id,'planks');assert.equal(q.ok,true,q.reason);work(g);const currentWorld=g.frontier.world();assert.equal(currentWorld.blocked(t.x,t.y,.2,0,p.id),true);assert.equal(g.barricades134.collision('region',t.x,t.y,.2,1,p.id),false);const a={x:t.x-Math.sin(t.angle),y:t.y+Math.cos(t.angle)},b={x:t.x+Math.sin(t.angle),y:t.y-Math.cos(t.angle)};assert.equal(currentWorld.line(a,b,0,p.id),false);const raw=g.serialize(),before=g.barricades134.snapshot();g.restoreSave(raw);assert.deepEqual(g.barricades134.snapshot(),before);assert.equal(g.frontier.world().blocked(t.x,t.y,.2,0,p.id),true);assert.equal(g.barricades134.begin('dismantle',t.id).ok,true);work(g);assert.equal(g.frontier.world().blocked(t.x,t.y,.2,0,p.id),false);});
test('barricades: upstairs passage can be reinforced independently of ground floor',()=>{const g=fresh(),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex'),t=B.regionTargets(w,p,1).find(t=>t.kind==='opening');assert.ok(t);regionAt(g,t);const q=g.barricades134.begin('build',t.id,'planks');assert.equal(q.ok,true,q.reason);work(g);assert.equal(g.barricades134.collision('region',t.x,t.y,.3,1,p.id),true);assert.equal(g.barricades134.collision('region',t.x,t.y,.3,0,p.id),false);assert.equal(g.barricades134.collision('region',t.x,t.y,.3,1,'P9999'),false);});
test('barricades: local shots hit the board before an enemy behind it and reduce its integrity',()=>{const g=fresh(),t=first(g);build(g,t);const nx=-Math.sin(t.angle),ny=Math.cos(t.angle),p={id:333,x:t.x+nx*30,y:t.y+ny*30,vx:-nx*900,vy:-ny*900,range:300,travelled:0,damage:19,radius:2,owner:'friendly',dead:false};g.projectiles=[p];const enemy={id:g.nextId++,x:t.x-nx*30,y:t.y-ny*30,radius:10,kind:'walker',health:60,dead:false,stagger:0};g.zombies=[enemy];g.rebuildBuckets();const hp=g.barricades134.snapshot().records[0].hp;g.updateProjectiles(.08);assert.equal(g.projectiles.length,0);assert.equal(g.barricades134.snapshot().records[0].hp,hp-19);assert.equal(enemy.health,60);});
test('barricades: duplicate, excess HP and foreign opening records reject before restore',()=>{const g=fresh(),t=first(g);build(g,t);const raw=g.serialize(),world=g.world;raw.expansions127.modules.barricades134.records.push({...raw.expansions127.modules.barricades134.records[0]});assert.throws(()=>g.restoreSave(raw),/Barricades/);assert.equal(g.world,world);const bad=g.serialize();bad.expansions127.modules.barricades134.records[0].hp=121;assert.throws(()=>g.restoreSave(bad),/Barricades/);assert.equal(g.world,world);});
test('barricades: swept resolver hits an enemy before a farther barricade',()=>{const g=fresh(),t=first(g);build(g,t);const nx=-Math.sin(t.angle),ny=Math.cos(t.angle),enemy={id:g.nextId++,x:t.x+nx*50,y:t.y+ny*50,radius:10,kind:'walker',health:60,dead:false,stagger:0};g.zombies=[enemy];g.rebuildBuckets();g.projectiles=[{id:334,x:t.x+nx*100,y:t.y+ny*100,vx:-nx*900,vy:-ny*900,range:300,travelled:0,damage:19,radius:2,owner:'friendly',dead:false}];g.updateProjectiles(.2);assert.equal(enemy.health,41);assert.equal(g.barricades134.snapshot().records[0].hp,120);});
test('barricades: recreated regional group contacts cannot attack every frame',()=>{const g=fresh(),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex'),t=B.regionTargets(w,p,0).find(t=>t.kind==='door');regionAt(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);work(g);const group={contacts:{0:{cool:0}}};let enemy={id:'test-group:0',index:0,group,x:t.x-Math.sin(t.angle),y:t.y+Math.cos(t.angle),hp:60,z:0,cool:0};g.frontier={...g.frontier,contacts:()=>[enemy]};g.barricades134.pressure('region',.04);assert.equal(g.barricades134.snapshot().records[0].hp,112);assert.equal(group.contacts[0].cool,C.BarricadeRules134.regionAttackSeconds);for(let i=0;i<10;i++){enemy={...enemy,cool:0};g.barricades134.pressure('region',.04);}assert.equal(g.barricades134.snapshot().records[0].hp,112);for(let i=0;i<25;i++){enemy={...enemy,cool:0};g.barricades134.pressure('region',.04);}assert.equal(g.barricades134.snapshot().records[0].hp,104);});
test('barricades: optional tool accelerates work and wears only when successfully used',()=>{const g=fresh(),t=first(g);let worn=0;g.arsenal134={toolFactor:()=>1.25,wearTool:(_,seconds)=>{worn+=seconds;}};approach(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);assert.equal(g.barricades134.job.seconds,4);g.barricades134.cancel();assert.equal(worn,0);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);work(g);assert.equal(worn,4);});
test('barricades: destroyed regional support cannot leave floating collision or accept new reinforcement',()=>{const g=fresh(),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex'),t=B.regionTargets(w,p,0).find(t=>t.kind==='door');regionAt(g,t);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,true);work(g);g.worldEvolution={...g.worldEvolution,structureDestroyed:id=>id===p.id};g.barricades134.bind();assert.equal(g.barricades134.snapshot().records.length,0);assert.equal(g.barricades134.collision('region',t.x,t.y,.3,0,p.id),false);assert.equal(g.barricades134.begin('build',t.id,'planks').ok,false);});
