import {createGameServer} from '../scripts/server.mjs';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=process.env.DEADWALL_PLAYWRIGHT?require(process.env.DEADWALL_PLAYWRIGHT):require(path.resolve('.qa-tools/node_modules/playwright'));
const server=createGameServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));server.unref();const base='http://127.0.0.1:'+server.address().port;
const browser=await chromium.launch({headless:true,...(process.env.DEADWALL_CHROMIUM?{executablePath:process.env.DEADWALL_CHROMIUM}:{}),args:['--no-sandbox']});
const out=path.resolve('reports/1.22/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/browser');fs.mkdirSync(out,{recursive:true});const reports=[];
async function profile(name,width,height,touch,run){const context=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch,deviceScaleFactor:1,serviceWorkers:'block'}),page=await context.newPage(),checks=[],errors=[],failedHTTP=[];
 page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failedHTTP.push(r.url())});
 await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;window.cancelAnimationFrame=()=>{}});
 const check=async(label,fn)=>{try{await fn();checks.push({label,ok:true})}catch(e){checks.push({label,ok:false,error:String(e)});console.log(name,'FAIL',label,String(e).slice(0,450))}};
 const test=(label,fn,arg)=>check(label,()=>page.evaluate(fn,arg));
 const shot=async(label)=>{await page.evaluate(()=>DEADWALL.render());await page.screenshot({path:path.join(out,label+'.png')})};
 try{await page.goto(base);await page.evaluate(()=>DEADWALL.art.ready);await page.fill('#mapSeed','17117');await page.click('#newGameButton');
 await page.evaluate(()=>{window.qa={assert:(v,s='assertion')=>{if(!v)throw Error(s)},reveal:(all=true)=>{const g=DEADWALL,d=g.serialize();for(const [i,s]of d.dayworks.sites.entries())if(all||i===0)s.seen=true;g.restoreSave(d)},step:n=>{for(let i=0;i<n&&!DEADWALL.gameOver&&!DEADWALL.paused&&!DEADWALL.activeOverlay;i++){DEADWALL.update(.04);DEADWALL.input.pressed.clear()}},put:(t,x,y)=>{const g=DEADWALL,b=new(g.core().constructor)(g.nextId++,t,x,y,0,1);g.world.add(b);return b;},clean:()=>{const d=DEADWALL.serialize();delete d.timestamp;return JSON.stringify(d)}}});
 await test('Jeu complet, modules cartographiques et dix atlas disponibles',()=>{qa.assert(DEADWALL.recon&&DEADWALL.reconUI&&DeadwallReconArt);qa.assert(DEADWALL.art.diagnostics.ready.length===10);qa.assert(!DEADWALL.art.diagnostics.failed.length);qa.assert(DeadwallCore.SAVE_VERSION===20)});
 await run({page,context,check,test,shot});
 await check('Aucune exception de page ou de console',async()=>{if(errors.length)throw Error(errors.join('\n'))});await check('Aucune dépendance HTTP manquante',async()=>{if(failedHTTP.length)throw Error(failedHTTP.join('\n'))});
 }catch(e){checks.push({label:'Parcours interrompu',ok:false,error:String(e)})}
 try{await shot(name)}catch{}reports.push({name,viewport:{width,height},touch,checks,errors,failedHTTP});await context.close();console.log(name,checks.filter(c=>c.ok).length+'/'+checks.length);
}
await Promise.all([
profile('01-cartographe',1440,1000,false,async({page,test,check,shot})=>{
 await check('M ouvre la carte en pause sans révéler les découvertes',async()=>{await page.locator('#game').focus();await page.keyboard.press('m');await page.evaluate(()=>{qa.assert(DEADWALL.paused);qa.assert(!document.getElementById('reconPanel').classList.contains('hidden'));qa.assert(DEADWALL.recon.points().length===1);qa.assert(document.querySelectorAll('#reconPointList .recon-point').length===1)})});
 await test('Dix-huit points de test révélés, registres inchangés à la lecture',()=>{qa.reveal();DEADWALL.recon.open();const before=qa.clean();for(let i=0;i<15;i++)DEADWALL.recon.overview(true);qa.assert(before===qa.clean());qa.assert(DEADWALL.recon.points().length===19)});
 await check('Liste consultable, zoom au bouton et recentrage',async()=>{await page.click('#reconPoint-site-housing-1');await page.evaluate(()=>qa.assert(DEADWALL.recon.overview().selected.ref==='housing-1'));const before=await page.locator('#reconMap').evaluate(c=>c.toDataURL());await page.click('#reconZoomIn');const after=await page.locator('#reconMap').evaluate(c=>c.toDataURL());if(before===after)throw Error('Zoom sans effet');await page.click('#reconPlayer');await page.evaluate(()=>{qa.assert(DEADWALL.reconUI.view().cx===DEADWALL.player.x);qa.assert(DEADWALL.reconUI.view().zoom===3)});await page.click('#reconFit')});
 await check('Sélection du dépôt par ses coordonnées sur la carte',async()=>{await page.locator('#reconMap').scrollIntoViewIfNeeded();const where=await page.evaluate(()=>{const c=DEADWALL.core(),r=document.getElementById('reconMap').getBoundingClientRect();return{x:r.left+(400+(c.x-2048)*640/4096)*r.width/800,y:r.top+(320+(c.y-2048)*640/4096)*r.height/640}});await page.mouse.click(where.x,where.y);await page.evaluate(()=>qa.assert(DEADWALL.recon.overview().selected.kind==='depot'))});
 await test('Quatre étapes, doublon et cinquième refusés sans paiement',()=>{const g=DEADWALL,ps=g.recon.points().filter(p=>p.kind==='site'),before=qa.clean();for(const p of ps.slice(0,4))qa.assert(g.recon.enqueue(p.id));qa.assert(!g.recon.enqueue(ps[0].id));qa.assert(!g.recon.enqueue(ps[4].id));qa.assert(before===qa.clean());g.reconUI.refresh(true)});
 await check('Réorganiser puis retirer une étape par les vrais boutons',async()=>{const before=await page.evaluate(()=>DEADWALL.recon.overview().queue.map(p=>p.id));await page.click('#reconDown-0');await page.evaluate(id=>qa.assert(DEADWALL.recon.overview().queue[1].id===id),before[0]);await page.click('#reconRemove-0');await page.evaluate(()=>qa.assert(DEADWALL.recon.overview().queue.length===3))});
 await check('Recherche sans accent et filtre des points épuisés',async()=>{await page.fill('#reconSearch','rechaud');if(await page.locator('#reconPointList .recon-point').count()!==1)throw Error('recherche');await page.fill('#reconSearch','');await page.selectOption('#reconFilter','done');if(await page.locator('#reconPointList .recon-point').count()!==0)throw Error('épuisés');await page.selectOption('#reconFilter','all')});
 await check('Treize dossiers exclusifs, aucun système retiré',async()=>{for(const b of await page.locator('.field-nav button').all()){await b.click();await page.evaluate(()=>qa.assert([...document.querySelectorAll('#commandPanel-field>section')].filter(s=>!s.classList.contains('hidden')).length===1))}await page.click('#reconTab');await page.evaluate(()=>qa.assert(document.querySelectorAll('.field-nav button').length===13));await shot('carte-et-parcours')});
}),
profile('02-eclaireur',1366,900,false,async({page,test,check,shot})=>{
 await test('Découverte par présence sur la vraie carte, inconnus toujours cachés',()=>{const g=DEADWALL,s=g.dayworks.snapshot().sites[0];g.player.x=s.x;g.player.y=s.y;qa.step(15);qa.assert(g.recon.points().some(p=>p.ref===s.id));qa.assert(g.recon.points().filter(p=>p.kind==='site').length<18);window.siteId=s.id});
 await test('Dix-huit silhouettes distinctes sans consommer le RNG',()=>{const g=DEADWALL,seed=g.random.state,hashes=[];for(const d of DeadwallCore.Dayworks.SITES){const c=document.createElement('canvas');c.width=c.height=96;qa.assert(DeadwallReconArt.draw(c.getContext('2d'),{id:d.id,x:48,y:48,survey:0,remaining:d.amount}));hashes.push(c.toDataURL())}qa.assert(new Set(hashes).size===18);qa.assert(g.random.state===seed)});
 await test('Silhouette dessinée dans le monde à sa position réelle',()=>{const g=DEADWALL,s=g.dayworks.snapshot().sites.find(p=>p.id===siteId);g.camera.x=s.x;g.camera.y=s.y;g.camera.zoom=2;g.setBuildCollapsed(true);g.render();qa.assert(g.recon.enqueue('site:'+s.id));});await shot('lieu-de-terrain');
 await check('Depuis la carte, activer le relevé puis revenir au jeu',async()=>{await page.evaluate(()=>{DEADWALL.recon.open();DEADWALL.recon.choose('site:'+siteId);DEADWALL.reconUI.refresh(true)});await page.click('#reconSurvey');await page.evaluate(()=>{qa.assert(!DEADWALL.paused);qa.assert(DEADWALL.dayworks.overview().tool==='survey');DEADWALL.input.keys.add('KeyE');qa.step(160);DEADWALL.input.keys.clear();qa.assert(DEADWALL.dayworks.snapshot().sites.find(s=>s.id===siteId).survey===6)})});
 await test('Sac et réserves réellement modifiés, reprise sans réinitialisation',()=>{const g=DEADWALL,before=g.dayworks.snapshot().sites.find(s=>s.id===siteId).remaining;g.input.keys.add('KeyE');qa.step(45);g.input.keys.clear();qa.assert(g.dayworks.snapshot().sites.find(s=>s.id===siteId).remaining<before);qa.assert(DeadwallCore.bagTotal(g.player.carry)>0);const d=g.serialize();qa.assert(g.save(false));qa.assert(g.load());qa.assert(g.dayworks.snapshot().sites.find(s=>s.id===siteId).remaining===d.dayworks.sites.find(s=>s.id===siteId).remaining);qa.assert(g.recon.overview().queue.length===0)});
 await test('Retour indiqué : aucune téléportation ni livraison à distance',()=>{const g=DEADWALL,before=qa.clean();qa.assert(g.recon.returnHome());qa.assert(qa.clean()===before);qa.assert(g.recon.route(true).ok);qa.assert(DeadwallCore.bagTotal(g.player.carry)>0)});
 await test('Lieu épuisé consultable, mais pas ajouté comme récolte',()=>{const g=DEADWALL,d=g.serialize(),s=d.dayworks.sites.find(s=>s.id===siteId);s.remaining=0;s.survey=6;s.seen=true;g.restoreSave(d);qa.assert(g.recon.points().find(p=>p.ref===siteId).done);qa.assert(!g.recon.enqueue('site:'+siteId));g.recon.open()});
 await check('Filtre exploitable exclut réellement le lieu épuisé',async()=>{await page.selectOption('#reconFilter','site');const id=await page.evaluate(()=>siteId);if(await page.locator('#reconPoint-site-'+id).count())throw Error('point épuisé visible');await page.selectOption('#reconFilter','done');if(await page.locator('#reconPointList .recon-point').count()!==1)throw Error('point épuisé absent')});
}),
profile('03-portes-et-nuit',1600,1000,false,async({test,shot})=>{
 await test('Double enceinte et destination arrangées hors remparts',()=>{const g=DEADWALL;for(const [a,b]of [[59,68],[54,73]]){for(let y=a;y<=b;y++)for(let x=a;x<=b;x++)if(x===a||x===b||y===a||y===b){if(y===a&&(x===63||x===64))continue;qa.put('woodWall',x,y)}}const inner=qa.put('gate',63,59),outer=qa.put('gate',63,54);inner.gateMode=outer.gateMode='closed';g.world.navigationVersion++;Object.assign(g.player,g.fieldcraft.service(g.player,g.core()));window.inner=inner.id;window.outer=outer.id;window.goal={x:2048,y:1600,reach:54};qa.assert(!DeadwallRecon.routeBetween(g,g.player,goal).ok)});
 await test('Ouvrir seulement la ligne intérieure ne suffit pas',()=>{const g=DEADWALL;qa.assert(g.setGateMode('auto',g.world.buildings.get(inner)));qa.assert(!DeadwallRecon.routeBetween(g,g.player,goal).ok)});
 await test('Deux accès alliés ouverts : chemin sans couper les murs',()=>{const g=DEADWALL;qa.assert(g.setGateMode('auto',g.world.buildings.get(outer)));const r=DeadwallRecon.routeBetween(g,g.player,goal);qa.assert(r.ok,r.reason);qa.assert(r.path.slice(1).every((p,i)=>DeadwallRecon.segmentClear(g,r.path[i],p)))});
 await test('Le passage du commandant utilise les collisions normales',()=>{const g=DEADWALL,r=DeadwallRecon.routeBetween(g,g.player,goal);for(const p of r.path.slice(1)){for(let i=0;i<150&&Math.hypot(p.x-g.player.x,p.y-g.player.y)>1;i++){const dx=p.x-g.player.x,dy=p.y-g.player.y,d=Math.hypot(dx,dy);g.moveFriendly(g.player,dx/d*Math.min(3,d),dy/d*Math.min(3,d))}}qa.assert(Math.hypot(g.player.x-goal.x,g.player.y-goal.y)<60)});
 await test('Retour marqué puis porte verrouillée : trajet refusé/recalculé',()=>{const g=DEADWALL;qa.assert(g.recon.returnHome());qa.assert(g.recon.route(true).ok);qa.assert(g.setGateMode('closed',g.world.buildings.get(outer)));qa.assert(!g.recon.route(true).ok);qa.assert(g.setGateMode('auto',g.world.buildings.get(outer)));qa.assert(g.recon.route(true).ok)});
 await test('Alerte réelle : seulement les fronts annoncés, pas de radar ajouté',()=>{const g=DEADWALL;g.phaseTime=.01;g.updateDirector(.04);qa.assert(g.phase==='warning');qa.assert(g.fronts.length>0);window.planTotal=g.wavePlan.total;g.recon.open();const before=qa.clean();g.recon.overview(true);qa.assert(before===qa.clean());g.reconUI.refresh(true)});await shot('carte-aux-portes-de-la-nuit');
 await test('La carte suspend la simulation sans annuler la horde',()=>{const g=DEADWALL,n=g.phaseTime;qa.step(20);qa.assert(g.phaseTime===n);g.showCommand(false);qa.step(420);qa.assert(g.phase==='assault');qa.assert(g.zombies.length>0);qa.assert(g.remainingAssault+g.stats.kills===planTotal)});
 await test('Reprise d’assaut : contacts et réserves identiques',()=>{const g=DEADWALL,n=g.remainingAssault,before={...g.resources};qa.assert(g.save(false));qa.assert(g.load());qa.assert(g.remainingAssault===n);qa.assert(JSON.stringify(g.resources)===JSON.stringify(before));qa.assert(g.recon.overview().queue.length===0)});
}),
profile('04-tactile-et-reprises',390,844,true,async({page,context,test,check,shot})=>{
 await test('Lieux connus arrangés : interface sans débordement horizontal',()=>{qa.reveal();DEADWALL.recon.open();qa.assert(document.documentElement.scrollWidth<=innerWidth+1)});
 await check('Zoom et glisser tactiles déplacent seulement la carte',async()=>{await page.click('#reconZoomIn');await page.locator('#reconMap').scrollIntoViewIfNeeded();const pos=await page.locator('#reconMap').boundingBox(),before=await page.evaluate(()=>({view:DEADWALL.reconUI.view(),p:{x:DEADWALL.player.x,y:DEADWALL.player.y}}));const client=await context.newCDPSession(page);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:pos.x+pos.width/2,y:pos.y+pos.height/2,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:pos.x+pos.width/2+45,y:pos.y+pos.height/2+30,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await client.detach();await page.evaluate(before=>{qa.assert(DEADWALL.reconUI.view().cx!==before.view.cx);qa.assert(DEADWALL.player.x===before.p.x&&DEADWALL.player.y===before.p.y);qa.assert(!DEADWALL.reconUI.view().dragging)},before)});
 await check('Interruption de geste : plus de capture active',async()=>{await page.locator('#reconMap').dispatchEvent('pointerdown',{pointerId:5,pointerType:'touch',isPrimary:true,button:0,clientX:100,clientY:200});await page.locator('#reconMap').dispatchEvent('pointercancel',{pointerId:5,pointerType:'touch'});await page.evaluate(()=>qa.assert(!DEADWALL.reconUI.view().dragging))});
 await check('Liste et clavier comme alternative au glisser',async()=>{await page.click('#reconPoint-site-market-1');await page.click('#reconAdd');await page.evaluate(()=>qa.assert(DEADWALL.recon.overview().queue[0].ref==='market-1'));await page.locator('#reconMap').focus();await page.keyboard.press('Home');await page.evaluate(()=>qa.assert(DEADWALL.reconUI.view().zoom===1));await page.keyboard.press('ArrowRight');await page.evaluate(()=>qa.assert(DEADWALL.reconUI.view().cx>2048))});
 await check('Focus conservé dans le dialogue',async()=>{for(let i=0;i<16;i++){await page.keyboard.press('Tab');await page.evaluate(()=>qa.assert(DEADWALL.activeOverlay.contains(document.activeElement)))}});
 await test('Import invalide : parcours et stocks inchangés',()=>{const g=DEADWALL,w=g.world,ids=g.recon.overview().queue.map(p=>p.id),money=JSON.stringify(g.resources);try{g.restoreSave({version:8})}catch{}qa.assert(g.world===w);qa.assert(JSON.stringify(g.resources)===money);qa.assert(JSON.stringify(g.recon.overview().queue.map(p=>p.id))===JSON.stringify(ids))});
 await test('Quatre reprises : aucune nouvelle découverte ou réserve',()=>{const g=DEADWALL,data=g.serialize();for(let i=0;i<4;i++){qa.assert(g.save(false));qa.assert(g.load())}qa.assert(JSON.stringify(g.dayworks.snapshot().sites)===JSON.stringify(data.dayworks.sites));qa.assert(g.recon.overview().queue.length===0);g.recon.open()});await shot('carte-mobile');
 await test('Nouvelle partie : filtres et destinations remis à zéro',()=>{DEADWALL.startNew('standard','42');DEADWALL.recon.open();qa.assert(DEADWALL.recon.points().filter(p=>p.kind==='site').length===0);qa.assert(DEADWALL.reconUI.view().zoom===1);qa.assert(!document.getElementById('reconSearch').value);qa.assert(DEADWALL.recon.overview().queue.length===0)});
})]);
const result={version:'1.23.0-rc.1',browser:browser.version(),scope:'Four parallel Chromium contexts, real engine/DOM/atlases, deterministic time. Advanced fixtures explicitly prepared.',profiles:reports.sort((a,b)=>a.name.localeCompare(b.name)),passed:reports.flatMap(p=>p.checks).filter(c=>c.ok).length,failed:reports.flatMap(p=>p.checks).filter(c=>!c.ok).length};
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));await browser.close();server.closeAllConnections();server.close();console.log(JSON.stringify({passed:result.passed,failed:result.failed}));if(result.failed)process.exitCode=1;
