import {createGameServer} from '../scripts/server.mjs';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=process.env.DEADWALL_PLAYWRIGHT?require(process.env.DEADWALL_PLAYWRIGHT):require(path.resolve('.qa-tools/node_modules/playwright'));
const server=createGameServer();await new Promise(r=>server.listen(0,'127.0.0.1',r));server.unref();
const base='http://127.0.0.1:'+server.address().port,out=path.resolve('reports/1.22/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/regression/browser');fs.mkdirSync(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.DEADWALL_CHROMIUM?{executablePath:process.env.DEADWALL_CHROMIUM}:{}),args:['--no-sandbox']}),reports=[];
async function profile(name,width,height,touch,run){const context=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch,serviceWorkers:'block'}),page=await context.newPage(),checks=[],errors=[],failedHTTP=[];
 page.setDefaultTimeout(5000);page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});page.on('response',r=>{if(r.status()>=400)failedHTTP.push(r.url())});
 await page.addInitScript(()=>{window.requestAnimationFrame=()=>0;window.cancelAnimationFrame=()=>{}});
 const check=async(label,fn)=>{try{await fn();checks.push({label,ok:true})}catch(e){checks.push({label,ok:false,error:String(e)});console.log(name,'FAIL',label,String(e).slice(0,450))}};
 const test=(label,fn,arg)=>check(label,()=>page.evaluate(fn,arg));
 const shot=async(label)=>{await page.evaluate(()=>DEADWALL.render());await page.screenshot({path:path.join(out,label+'.png')})};
 try{await page.goto(base);await page.evaluate(()=>DEADWALL.art.ready);await page.fill('#mapSeed','17117');await page.click('#newGameButton');
 await page.evaluate(()=>{window.qa={assert:(v,t='assertion')=>{if(!v)throw Error(t)},step:n=>{for(let i=0;i<n&&!DEADWALL.gameOver&&!DEADWALL.paused&&!DEADWALL.activeOverlay;i++){DEADWALL.update(.04);DEADWALL.input.pressed.clear()}},until:(fn,n=2400)=>{for(let i=0;i<n;i++){if(fn())return i;qa.step(1)}qa.assert(fn(),'condition non atteinte');},put:(type,x,y)=>{const g=DEADWALL,b=new(g.core().constructor)(g.nextId++,type,x,y,0,1);g.world.add(b);g.refreshMetrics(true);return b;},fixture:(all=false)=>{const g=DEADWALL;qa.put('planningOffice',68,58);qa.put('warehouse',68,65);if(!all)g.units=[g.units[0]];g.refreshMetrics(true);const d=g.serialize();Object.assign(d.dayworks.sites[1],{x:2460,y:2150,seen:true,survey:6});g.restoreSave(d);window.jobSite=d.dayworks.sites[1].id;window.workerId=g.units[0].id;},worker:()=>DEADWALL.units.find(u=>u.id===workerId),remaining:()=>DEADWALL.dayworks.snapshot().sites.find(s=>s.id===jobSite).remaining};});
 await test('Vrai moteur, dix atlas, récupération et sauvegarde v9',()=>{qa.assert(!!DEADWALL.salvage&&!!DEADWALL.salvageUI);qa.assert(DEADWALL.art.diagnostics.ready.length===10);qa.assert(DEADWALL.lastSaveStatus.ok);qa.assert(DeadwallCore.SAVE_VERSION===20)});
 await run({page,context,check,test,shot});
 await check('Aucune exception JavaScript',async()=>{if(errors.length)throw Error(errors.join('\n'))});await check('Aucune dépendance HTTP manquante',async()=>{if(failedHTTP.length)throw Error(failedHTTP.join('\n'))});
 }catch(e){checks.push({label:'Parcours interrompu',ok:false,error:String(e)})}
 try{await shot(name)}catch{}reports.push({name,viewport:{width,height},touch,checks,errors,failedHTTP});await context.close();console.log(name,checks.filter(c=>c.ok).length+'/'+checks.length);
}
await Promise.all([
profile('01-logistique',1440,1000,false,async({page,test,check,shot})=>{
 await test('Scène préparée : relevé terminé, bureau et entrepôt existants',()=>{qa.fixture();const g=DEADWALL;g.recon.open();g.recon.choose('site:'+jobSite);window.beforeFood=g.resources.food;window.beforeWood=g.resources.wood;qa.assert(!document.getElementById('salvageAssign').disabled)});
 await check('Affecter depuis la vraie carte, quatre rations et aucune unité créée',async()=>{await page.click('#salvageAssign');await page.evaluate(()=>{qa.assert(DEADWALL.salvage.snapshot().crews[0].id===workerId);qa.assert(DEADWALL.resources.food===beforeFood-4);qa.assert(DEADWALL.units.length===1);qa.assert(qa.remaining()===32);qa.assert(DEADWALL.resources.wood===beforeWood)})});
 await test('La consultation en pause ne fait pas travailler à distance',()=>{const g=DEADWALL,t=g.elapsed;qa.step(50);qa.assert(g.elapsed===t);qa.assert(qa.worker().carry===0);g.showCommand(false)});
 await test('Aller physique et chargement au contact du lieu',()=>{const g=DEADWALL;qa.until(()=>qa.worker().carry>=3);const u=qa.worker(),s=g.dayworks.snapshot().sites.find(s=>s.id===jobSite);qa.assert(Math.hypot(u.x-s.x,u.y-s.y)<=48);qa.assert(g.resources.wood===beforeWood);g.camera.x=u.x;g.camera.y=u.y;g.camera.zoom=1.5;g.setBuildCollapsed(true);g.render()});await shot('recuperateur-sur-le-terrain');
 await test('Retour réel, livraison de dix unités seulement au centre',()=>{const g=DEADWALL;qa.until(()=>g.salvage.snapshot().stats.returned===1);qa.assert(Math.abs(g.resources.wood-beforeWood-10)<1e-6);qa.assert(Math.abs(qa.remaining()-22)<1e-6);qa.assert(qa.worker().carry===0);qa.assert(g.salvage.snapshot().crews.length===0)});
 await test('Deuxième chargement : nouveaux frais, sauvegarde et reprise au milieu',()=>{const g=DEADWALL;qa.assert(g.salvage.assign(jobSite).ok);qa.until(()=>qa.worker().carry>=2);const s=g.salvage.snapshot(),carry=qa.worker().carry,left=qa.remaining();for(let i=0;i<3;i++){qa.assert(g.save(false));qa.assert(g.load());qa.assert(JSON.stringify(g.salvage.snapshot())===JSON.stringify(s));qa.assert(qa.worker().carry===carry);qa.assert(qa.remaining()===left)}});
 await test('Dépôt saturé conserve le sac et accepte une livraison partielle',()=>{const g=DEADWALL;qa.until(()=>qa.worker().carry>=9.999);g.resources.wood=g.storage;qa.until(()=>g.workerCanWorkAt(qa.worker(),g.core(),65));qa.step(5);qa.assert(qa.worker().carry>9.99);qa.assert(g.salvage.snapshot().crews.length===1);g.resources.wood-=3;qa.step(2);qa.assert(Math.abs(qa.worker().carry-7)<1e-6)});
 await check('La vraie interface signale le blocage et propose le rappel',async()=>{await page.evaluate(()=>{DEADWALL.recon.open();DEADWALL.salvageUI.refresh(true)});const text=await page.locator('#salvageCrews').innerText();if(!text.includes('saturé')||!text.includes('7.0'))throw Error(text);await shot('recuperation-depot-sature');await page.click('#commandClose')});
 await test('Dernier déchargement ne double pas la récompense',()=>{const g=DEADWALL;g.resources.wood-=20;const stock=g.resources.wood;qa.until(()=>g.salvage.snapshot().stats.returned===2);qa.assert(Math.abs(g.resources.wood-stock-7)<1e-6);qa.assert(g.save(false));qa.assert(g.load());qa.assert(g.salvage.snapshot().stats.returned===2)});
}),
profile('02-batisseur',1600,1000,false,async({page,test,check,shot})=>{
 await test('Neuf plans illustrés dans le dossier existant, treize onglets conservés',()=>{const g=DEADWALL;qa.put('planningOffice',70,59);for(let i=0;i<6;i++)qa.put('barracks',20+i*6,25);for(let i=0;i<4;i++)qa.put('warehouse',20+i*5,32);for(const k of DeadwallCore.RESOURCE_KEYS)g.resources[k]=2000;g.refreshMetrics(true);g.dayworks.open();qa.assert(DeadwallCore.Dayworks.PLANS.length===9);qa.assert(document.querySelectorAll('.worksite-sketch').length===9);qa.assert(document.querySelectorAll('.field-nav button').length===13)});await shot('neuf-plans-de-chantier');
 await test('Relais de retour : devis sans dépense avant confirmation',()=>{const g=DEADWALL;window.findPlan=(id)=>{for(let y=40;y<106;y+=5)for(let x=30;x<106;x+=5){const q=g.dayworks.planStatus(id,x,y);if(q.ok)return{x,y,q}}throw Error('Aucun emplacement '+id)};window.planPos=findPlan('returnRelay');const before={...g.resources},r=g.dayworks.anchorPlan('returnRelay',planPos.x,planPos.y);qa.assert(r.ok);qa.assert(JSON.stringify(g.resources)===JSON.stringify(before));window.planCost=r.cost;window.oldResources=before;window.oldCount=g.world.buildings.size;g.dayworksUI.refresh()});
 await check('Le bouton finance les trois vrais chantiers, sans achèvement instantané',async()=>{await page.click('#dayworksCommit');await page.evaluate(()=>{const g=DEADWALL;qa.assert(g.world.buildings.size===oldCount+3);for(const[k,n]of Object.entries(planCost))qa.assert(g.resources[k]===oldResources[k]-n);const buildings=[...g.world.buildings.values()].filter(b=>!b.completed);qa.assert(buildings.length===3&&buildings.every(b=>b.progress===0));qa.assert(g.lastSaveStatus.ok)})});
 await test('Cour nourricière et cour des matériaux : devis et coûts intégraux',()=>{const g=DEADWALL;for(const id of ['foodCourt','materialsCourt']){const p=findPlan(id),before={...g.resources},count=g.world.buildings.size;g.dayworks.anchorPlan(id,p.x,p.y);qa.assert(g.dayworks.commitPlan());qa.assert(g.world.buildings.size===count+4);for(const[k,n]of Object.entries(p.q.cost))qa.assert(g.resources[k]===before[k]-n)}});
 await test('Un sol devenu occupé fait refuser le financement complet',()=>{const g=DEADWALL,p=findPlan('entryBastion');g.dayworks.anchorPlan('entryBastion',p.x,p.y);qa.put('woodWall',p.x,p.y);const before=JSON.stringify(g.resources),count=g.world.buildings.size;qa.assert(!g.dayworks.commitPlan());qa.assert(JSON.stringify(g.resources)===before&&g.world.buildings.size===count);g.dayworks.cancelPlan()});
 await test('Entrée : 19 palissades, une porte et deux miradors financés',()=>{const g=DEADWALL,p=findPlan('entryBastion'),ids=new Set(g.world.buildings.keys());g.dayworks.anchorPlan('entryBastion',p.x,p.y);qa.assert(g.dayworks.commitPlan());const bs=[...g.world.buildings.values()].filter(b=>!ids.has(b.id));qa.assert(bs.length===22);qa.assert(bs.filter(b=>b.type==='woodWall').length===19);qa.assert(bs.filter(b=>b.type==='gate').length===1);qa.assert(bs.filter(b=>b.type==='watchtower').length===2);window.bastion={x:p.x,y:p.y,ids:bs.map(b=>b.id)}});
 await test('Les chantiers acceptent le travail du joueur et restent sauvegardés',()=>{const g=DEADWALL;g.showCommand(false);g.player.x=(bastion.x+2)*32;g.player.y=(bastion.y+3)*32;g.input.keys.add('KeyE');qa.step(60);g.input.keys.clear();qa.assert(bastion.ids.some(id=>g.world.buildings.get(id).progress>0));const data=g.serialize();qa.assert(g.save(false));qa.assert(g.load());qa.assert(g.serialize().buildings.length===data.buildings.length);g.camera.x=(bastion.x+4.5)*32;g.camera.y=(bastion.y+3.5)*32;g.camera.zoom=1.6;g.setBuildCollapsed(true)});await shot('bastion-en-construction');
 await test('Pas de plan payé pendant l’assaut ni de réduction des coûts',()=>{const g=DEADWALL;g.phase='assault';const money=JSON.stringify(g.resources);qa.assert(!g.dayworks.planStatus('returnRelay',10,10).ok);qa.assert(!g.dayworks.beginPlan('returnRelay'));qa.assert(money===JSON.stringify(g.resources))});
}),
profile('03-repli-nocturne',1440,1000,false,async({test,shot})=>{
 await test('Départ réel à travers une enceinte préparée et sa porte alliée',()=>{qa.fixture();const g=DEADWALL;for(let y=54;y<=75;y++)for(let x=54;x<=75;x++)if(x===54||x===75||y===54||y===75){if(y===54&&(x===63||x===64))continue;qa.put('woodWall',x,y)}window.gateId=qa.put('gate',63,54).id;qa.assert(g.salvage.assign(jobSite).ok);qa.until(()=>qa.worker().carry>=1);qa.assert(qa.worker().x>2400)});
 await test('L’avertissement de fin de journée mentionne les récupérateurs dehors',()=>{const r=DEADWALL.dayworks.finishDay();qa.assert(r.confirm&&r.reason.includes('récupérateurs'));qa.assert(DEADWALL.phase==='calm')});
 await test('Porte verrouillée : rappel bloqué, cargaison conservée',()=>{const g=DEADWALL;qa.assert(g.setGateMode('closed',g.world.buildings.get(gateId)));qa.assert(g.salvage.recall(workerId));window.held=qa.worker().carry;qa.until(()=>qa.worker().navigation?.cells===null);qa.step(50);qa.assert(qa.worker().carry===held);qa.assert(g.salvage.snapshot().crews.length===1);qa.assert(g.salvage.snapshot().stats.returned===0);g.camera.x=qa.worker().x;g.camera.y=qa.worker().y;g.camera.zoom=1.3;g.setBuildCollapsed(true)});await shot('retour-bloque-par-la-porte');
 await test('Reprise avec passage fermé : aucun crédit prématuré',()=>{const g=DEADWALL,stock=g.resources.wood;qa.assert(g.save(false));qa.assert(g.load());qa.assert(qa.worker().carry===held);qa.assert(g.resources.wood===stock);qa.assert(g.salvage.snapshot().crews[0].returning)});
 await test('Réouverture et crépuscule : le retour se poursuit réellement',()=>{const g=DEADWALL;qa.assert(g.setGateMode('auto',g.world.buildings.get(gateId)));g.phaseTime=.01;qa.step(1);qa.assert(g.phase==='warning');qa.until(()=>g.salvage.snapshot().stats.returned===1);qa.assert(qa.worker().carry===0);qa.assert(g.workerCanWorkAt(qa.worker(),g.core(),65))});
 await test('La horde annoncée reste active après la fin de la récupération',()=>{const g=DEADWALL;qa.step(360);qa.assert(g.phase==='assault');qa.assert(g.zombies.length>0);qa.assert(g.remainingAssault+g.stats.kills===g.wavePlan.total);qa.assert(!g.salvage.assign(jobSite).ok)});
 await test('Scène danger : repli immédiat devant un infecté visible',()=>{const g=DEADWALL;g.startNew('standard','17117');qa.fixture();g.salvage.assign(jobSite);qa.until(()=>qa.worker().carry>=1);g.spawnZombie('walker');const z=g.zombies.at(-1);z.x=qa.worker().x+25;z.y=qa.worker().y;g.rebuildBuckets();g.salvage.updateAssignedUnit(qa.worker(),.04);qa.assert(g.salvage.snapshot().crews[0].returning);window.leftBeforeLoss=qa.remaining();window.stockBeforeLoss=g.resources.wood;qa.worker().health=0;qa.worker().dead=true;qa.assert(g.salvage.snapshot().stats.lost===1)});
 await test('Perte définitive : ressource non recréée et sauvegarde valide',()=>{const g=DEADWALL;qa.assert(qa.remaining()===leftBeforeLoss);qa.assert(g.resources.wood===stockBeforeLoss);qa.assert(g.salvage.snapshot().crews.length===0);qa.assert(g.save(false));qa.assert(g.load());qa.assert(g.salvage.snapshot().stats.lost===1)});
}),
profile('04-tactile-et-migrations',390,844,true,async({page,test,check,shot})=>{
 await test('Quatre ouvriers et cinq relevés préparés, aucune duplication',()=>{qa.fixture(true);const g=DEADWALL;qa.put('warehouse',72,65);qa.assert(g.recruit('worker'));const d=g.serialize();for(let i=0;i<5;i++)Object.assign(d.dayworks.sites[i],{seen:true,survey:6});g.restoreSave(d);window.availableSites=d.dayworks.sites.slice(0,5).map(s=>s.id);qa.assert(g.units.length===4);qa.assert(g.salvage.overview().slots===4);g.recon.open();g.recon.choose('site:'+availableSites[0]);qa.assert(document.documentElement.scrollWidth<=innerWidth+1)});
 await check('Affectation tactile depuis la carte, sans panneau superposé',async()=>{await page.locator('#salvageAssign').scrollIntoViewIfNeeded();await page.tap('#salvageAssign');await page.evaluate(()=>{qa.assert(DEADWALL.salvage.snapshot().crews.length===1);qa.assert([...document.querySelectorAll('#commandPanel-field>section')].filter(n=>!n.classList.contains('hidden')).length===1)})});
 await test('Quatre équipes maximum et quatre identités distinctes',()=>{const g=DEADWALL;for(const id of availableSites.slice(1,4))qa.assert(g.salvage.assign(id).ok);const s=g.salvage.snapshot();qa.assert(s.crews.length===4);qa.assert(new Set(s.crews.map(c=>c.id)).size===4);const before=g.resources.food;qa.assert(!g.salvage.assign(availableSites[4]).ok);qa.assert(g.resources.food===before);g.salvageUI.refresh(true)});await shot('recuperation-tactile');
 await check('Commandes au clavier et focus dans le dialogue',async()=>{await page.locator('#salvageRecall-'+await page.evaluate(()=>DEADWALL.salvage.snapshot().crews[0].id)).focus();for(let i=0;i<12;i++){await page.keyboard.press('Tab');await page.evaluate(()=>qa.assert(DEADWALL.activeOverlay.contains(document.activeElement)))}});
 await test('Un identifiant dupliqué et une double affectation sont refusés sans mutation',()=>{const g=DEADWALL,world=g.world,before=g.resources.food;const a=g.serialize();a.salvage.crews.push({...a.salvage.crews[0]});let refused=false;try{g.restoreSave(a)}catch{refused=true}qa.assert(refused&&g.world===world&&g.resources.food===before);const b=g.serialize();b.siege.crew=[{id:b.salvage.crews[0].id,water:0,release:false}];refused=false;try{g.restoreSave(b)}catch{refused=true}qa.assert(refused&&g.world===world)});
 await test('La reprise v9 garde les quatre équipes et ne paie pas une seconde fois',()=>{const g=DEADWALL,s=JSON.stringify(g.salvage.snapshot()),food=g.resources.food;g.showCommand(false);for(let i=0;i<4;i++){qa.assert(g.save(false));qa.assert(g.load());qa.assert(JSON.stringify(g.salvage.snapshot())===s);qa.assert(g.resources.food===food)}});
 await test('Migration depuis v8 : réserves identiques, aucun ordre ajouté',()=>{const g=DEADWALL;g.startNew('standard','17117');const old=g.serialize();old.version=8;delete old.salvage;old.resources.wood=111;g.restoreSave(old);qa.assert(g.resources.wood===111);qa.assert(g.serialize().version===20);qa.assert(g.salvage.snapshot().crews.length===0);qa.assert(g.salvage.snapshot().stats.dispatched===0)});
 await test('Nouvelle campagne : aucun ancien travailleur retenu',()=>{const g=DEADWALL;qa.fixture();g.salvage.assign(jobSite);g.startNew('standard','42');qa.assert(g.salvage.snapshot().crews.length===0);qa.assert(g.salvage.snapshot().stats.dispatched===0);qa.assert(g.lastSaveStatus.ok);g.recon.open();qa.assert(document.documentElement.scrollWidth<=innerWidth+1)});
})]);
const result={version:'1.23.0-rc.1',browser:browser.version(),scope:'Real game/DOM/atlases. Four parallel contexts, controlled simulation, prepared cities/revealed survey fixtures explicitly listed per check.',profiles:reports.sort((a,b)=>a.name.localeCompare(b.name)),passed:reports.flatMap(p=>p.checks).filter(c=>c.ok).length,failed:reports.flatMap(p=>p.checks).filter(c=>!c.ok).length};
fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(result,null,2));await browser.close();server.closeAllConnections();server.close();console.log(JSON.stringify({passed:result.passed,failed:result.failed}));if(result.failed)process.exitCode=1;
