'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),Pack=require('../src/campaign-pack.js'),G=require('../src/frontier-geometry.js');
const clone=x=>JSON.parse(JSON.stringify(x)),kinds=['medical','recovery'];
// Controlled campaign fixtures: discovered existing POIs, clear contacts at their real
// exterior service point, and explicit actor relocation. Work, payments, delivery,
// carrying conflicts and serialization all use the production controllers.
function fresh(){const {game:g}=boot127();g.startNew('standard','17117');g.units=[];standAt(g,g.player,g.core());g.resources.food=400;g.resources.medicine=40;g.resources.scrap=100;return g;}
function tick(g,seconds){for(let i=0;i<Math.ceil(seconds/.04);i++){g.update(.04);g.input.pressed.clear();}}
function discover(g){const raw=g.serialize();raw.frontier.seen=g.frontier.world().pois.map(p=>p.id);assert.equal(g.restoreSave(raw),true);standAt(g,g.player,g.core());}
function supplies(g,kind){for(const [key,amount] of Object.entries(C.CampaignPackRules.definitions[kind].fieldCost))assert.equal(g.fieldSupplies.transfer('depot',key,'withdraw',amount).ok,true);}
function start(g,kind){discover(g);supplies(g,kind);const before={...g.resources},q=g.campaignPack.start(kind);assert.equal(q.ok,true,q.reason);for(const [key,n] of Object.entries(C.CampaignPackRules.definitions[kind].fee))assert.equal(g.resources[key],before[key]-n);return g.campaignPack.snapshot().active;}
function field(g){const p=g.campaignPack.overview().target;assert.ok(p);if(!g.frontier.active()){g.player.x=4058;g.player.y=2048;assert.equal(g.frontier.enter(),true);}const w=g.frontier.world(),raw=g.serialize();Object.assign(raw.frontier,{x:p.x,y:p.y,z:0,inside:null});for(const poi of w.nearPOI(p.x,p.y,110))for(let i=0;i<1+G.hash(w.seed,poi.id,'threat')%4;i++)raw.frontier.enemies[poi.id+':e'+i]=0;raw.frontier.kills=Object.values(raw.frontier.enemies).filter(n=>n===0).length;assert.equal(g.restoreSave(raw),true);return p;}
function home(g){if(g.frontier.active()){const raw=g.serialize();Object.assign(raw.frontier,{active:false,anchor:null,inside:null});assert.equal(g.restoreSave(raw),true);}standAt(g,g.player,g.core());}
function ready(g,kind){start(g,kind);field(g);const q=g.campaignPack.begin();assert.equal(q.ok,true,q.reason);tick(g,C.CampaignPackRules.definitions[kind].seconds);assert.equal(g.campaignPack.snapshot().active.stage,'return');home(g);}
function noMutation(g,raw,pattern){const world=g.world,resources={...g.resources},registry=clone(g.expansions.snapshot());assert.throws(()=>g.restoreSave(raw),pattern);assert.equal(g.world,world);assert.deepEqual(g.resources,resources);assert.deepEqual(g.expansions.snapshot(),registry);}

test('146 contrats : deux devis de lieux existants, coûts physiques et délai visibles sans mutation',()=>{const g=fresh();assert.equal(g.campaignPack.start('medical').ok,false);discover(g);const before=clone(g.campaignPack.snapshot()),stocks={...g.resources};for(const kind of kinds){const d=C.CampaignPackRules.definitions[kind],q=g.campaignPack.previewStart(kind);assert.equal(q.ok,true,q.reason);assert.equal(d.unique,true);assert.equal(d.waveLimit,3);assert.equal(q.sites.length,1);const poi=g.frontier.world().pois.find(p=>p.id===q.sites[0]);assert.ok(d.types.includes(poi.type));const action=g.campaignPack.actions().find(a=>a.id==='start-'+kind);assert.match(action.reason,/tentative.*campagne/i);assert.match(action.reason,/trois changements/i);assert.match(action.reason,new RegExp(d.seconds+' s'));assert.match(action.reason,/Sac : .*ferraille/i);}assert.deepEqual(g.campaignPack.snapshot(),before);assert.deepEqual(g.resources,stocks);});

test('146 contrats : registre 1.45 à cinq entrées conservé, nouvelles entrées vides sans gain',()=>{const g=fresh();discover(g);assert.equal(g.campaignPack.start('aid').ok,true);const raw=g.serialize(),expected=clone(raw.expansions127.modules.campaign),stocks={...raw.resources};for(const key of ['lastStarted','finished','usedSites'])for(const kind of kinds)delete raw.expansions127.modules.campaign[key][kind];assert.equal(g.restoreSave(raw),true);assert.deepEqual(g.campaignPack.snapshot(),expected);assert.deepEqual(g.resources,stocks);assert.equal(g.campaignPack.carrying(),true);assert.equal(g.campaignPack.snapshot().active.kind,'aid');});

test('146 contrats : registre ancien incomplet, mixte et compteur unique forgé refusés avant mutation',()=>{const g=fresh();for(const mutate of [s=>delete s.lastStarted.aid,s=>delete s.usedSites.recovery,s=>s.finished.medical=2,s=>s.usedSites.medical.push('P0001'),s=>s.lastStarted.constructor=1,s=>{for(const kind of kinds)delete s.lastStarted[kind];}]){const raw=clone(g.serialize());mutate(raw.expansions127.modules.campaign);raw.resources.scrap=1;noMutation(g,raw);}});

test('146 relais sanitaire : colis sortant, paiement terrain différé, pause et reprise sans double frais',()=>{const g=fresh();start(g,'medical');assert.equal(g.campaignPack.carrying(),true);assert.equal(g.campaignPack.movementFactor(),C.CampaignPackRules.cargoSpeed);field(g);assert.equal(g.campaignPack.begin().ok,true);tick(g,1);const bag={...g.player.carry},progress=g.campaignPack.overview().task.progress;g.paused=true;tick(g,2);assert.equal(g.campaignPack.overview().task.progress,progress);assert.deepEqual(g.player.carry,bag);g.paused=false;assert.equal(g.save(false),true);assert.equal(g.load(),true);assert.equal(g.campaignPack.busy(),false);assert.equal(g.campaignPack.snapshot().active.stage,'field');assert.deepEqual(g.player.carry,bag);assert.equal(g.campaignPack.begin().ok,true);tick(g,11.96);assert.equal(g.player.carry.scrap,2);tick(g,.04);assert.equal(g.player.carry.scrap,0);assert.equal(g.campaignPack.carrying(),false);assert.equal(g.campaignPack.snapshot().active.stage,'return');home(g);g.research.insight=C.RESEARCH_INSIGHT_MAX-1;const before={...g.resources};assert.equal(g.campaignPack.finish().ok,false);assert.deepEqual(g.resources,before);assert.equal(g.campaignPack.snapshot().finished.medical,0);g.research.insight=C.RESEARCH_INSIGHT_MAX-2;g.morale=99;assert.equal(g.campaignPack.finish().ok,true);assert.equal(g.research.insight,C.RESEARCH_INSIGHT_MAX);assert.equal(g.morale,100);assert.equal(g.campaignPack.finish().ok,false);assert.equal(g.campaignPack.snapshot().finished.medical,1);});

test('146 retour de réserve : colis entrant, récompense entière après place libérée et unique après reprise',()=>{const g=fresh();ready(g,'recovery');assert.equal(g.player.carry.scrap,0);assert.equal(g.campaignPack.carrying(),true);g.resources.medicine=g.storage-4;g.resources.ammo=g.storage;const before={...g.resources},state=clone(g.campaignPack.snapshot());assert.equal(g.campaignPack.finish().ok,false);assert.deepEqual(g.resources,before);assert.deepEqual(g.campaignPack.snapshot(),state);assert.equal(g.save(false),true);assert.equal(g.load(),true);home(g);assert.equal(g.campaignPack.carrying(),true);assert.equal(g.campaignPack.finish().ok,false);g.resources.medicine=g.storage-8;g.resources.ammo=g.storage-18;assert.equal(g.campaignPack.finish().ok,true);assert.equal(g.resources.medicine,g.storage);assert.equal(g.resources.ammo,g.storage);assert.equal(g.campaignPack.carrying(),false);const received={...g.resources};assert.equal(g.campaignPack.finish().ok,false);assert.equal(g.save(false),true);assert.equal(g.load(),true);assert.deepEqual(g.resources,received);g.wave++;assert.equal(g.campaignPack.start('recovery').ok,false);assert.equal(g.campaignPack.snapshot().finished.recovery,1);});

for(const kind of kinds)test('146 '+kind+' : expiration au troisième changement, aucune reprise ni récompense tardive',()=>{const g=fresh();ready(g,kind);const state=g.campaignPack.snapshot(),before={...g.resources};g.wave=state.active.wave+2;assert.equal(g.campaignPack.previewFinish().ok,true);g.wave++;assert.equal(g.campaignPack.finish().ok,false);assert.deepEqual(g.resources,before);assert.equal(g.save(false),true);assert.equal(g.load(),true);home(g);assert.equal(g.campaignPack.finish().ok,false);assert.match(g.campaignPack.overview().rows.find(r=>r.label==='Délai').value,/0 changements/);tick(g,.04);assert.equal(g.campaignPack.snapshot().active,null);assert.equal(g.campaignPack.snapshot().history.at(-1).result,'lost');assert.equal(g.campaignPack.carrying(),false);assert.equal(g.campaignPack.start(kind).ok,false);assert.equal(g.campaignPack.snapshot().finished[kind],0);assert.equal(g.resources.medicine,before.medicine);assert.equal(g.resources.ammo,before.ammo);});

test('146 relais sanitaire : délai expiré refuse aussi le travail sans consommer les fournitures',()=>{const g=fresh();const a=start(g,'medical');field(g);g.wave=a.wave+3;const bag={...g.player.carry};assert.equal(g.campaignPack.begin().ok,false);assert.deepEqual(g.player.carry,bag);tick(g,.04);assert.equal(g.campaignPack.snapshot().active,null);assert.deepEqual(g.player.carry,bag);});

for(const kind of kinds)test('146 '+kind+' : transport endommagé puis perdu, budget et site non réarmés',()=>{const g=fresh();if(kind==='medical')start(g,kind);else ready(g,kind);const a=g.campaignPack.snapshot().active,sites=[...g.campaignPack.snapshot().usedSites[kind]],old=g.updatePlayer;g.player.invulnerable=0;g.updatePlayer=()=>g.damagePlayer(20);tick(g,.04);g.updatePlayer=old;assert.ok(g.campaignPack.snapshot().active.integrity<100);const damaged=clone(g.campaignPack.snapshot());assert.equal(g.save(false),true);assert.equal(g.load(),true);home(g);assert.deepEqual(g.campaignPack.snapshot(),damaged);g.player.invulnerable=0;g.damagePlayer(10000);tick(g,.04);assert.equal(g.campaignPack.snapshot().active,null);assert.equal(g.campaignPack.snapshot().history.at(-1).result,'lost');assert.deepEqual(g.campaignPack.snapshot().usedSites[kind],sites);assert.equal(g.campaignPack.snapshot().lastStarted[kind],a.wave);assert.equal(g.campaignPack.snapshot().finished[kind],0);assert.equal(g.campaignPack.finish().ok,false);});

test('146 contrat abandonné : tentative et frais restent perdus à la vague suivante',()=>{const g=fresh();start(g,'medical');const stocks={...g.resources},used=[...g.campaignPack.snapshot().usedSites.medical];assert.equal(g.campaignPack.abandon().ok,true);assert.deepEqual(g.resources,stocks);g.wave++;assert.equal(g.campaignPack.start('medical').ok,false);assert.deepEqual(g.campaignPack.snapshot().usedSites.medical,used);assert.equal(g.campaignPack.snapshot().history.at(-1).result,'abandoned');assert.equal(g.campaignPack.finish().ok,false);});

for(const kind of kinds)test('146 '+kind+' : import de deux chargements refuse atomiquement le nouveau contrat',()=>{const g=fresh();if(kind==='medical')start(g,kind);else ready(g,kind);const raw=clone(g.serialize()),target=g.essentials.targets()[0];raw.frontier.seen=[...new Set([...raw.frontier.seen,target.poi])];raw.essentials.jobs[target.id]={stage:'player'};raw.resources.scrap=1;noMutation(g,raw,/seul chargement/);assert.equal(g.campaignPack.carrying(),true);});

test('146 portages : déposer puis récupérer un ballot respecte le colis sanitaire sans duplication',()=>{const g=fresh();discover(g);standAt(g,g.player,g.core());assert.equal(g.fieldSupplies.transfer('depot','food','withdraw',1).ok,true);const node=g.world.nodes.find(n=>n.type==='wood'&&!n.depleted&&n.amount>C.ExplorePackRules.cargoAmount);assert.ok(node);standAt(g,g.player,node);assert.equal(g.explorationPack.survey(node.id).ok,true);tick(g,C.ExplorePackRules.surveySeconds);assert.equal(g.explorationPack.extract(node.id).ok,true);tick(g,C.ExplorePackRules.extractSeconds);assert.equal(g.explorationPack.carrying(),true);const amount=g.explorationPack.snapshot().cargo[0].amount;home(g);const stocks={...g.resources};assert.equal(g.campaignPack.start('medical').ok,false);assert.deepEqual(g.resources,stocks);assert.equal(g.explorationPack.drop().ok,true);const ballot=g.explorationPack.snapshot().cargo[0];assert.equal(g.campaignPack.start('medical').ok,true);assert.equal(g.explorationPack.recover(ballot.id).ok,false);assert.equal(g.explorationPack.snapshot().cargo[0].amount,amount);assert.equal(g.campaignPack.abandon().ok,true);assert.equal(g.explorationPack.recover(ballot.id).ok,true);tick(g,C.ExplorePackRules.recoverSeconds);assert.equal(g.explorationPack.carrying(),true);assert.equal(g.explorationPack.snapshot().cargo[0].amount,amount);});
