'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs'),C=require('../src/core.js'),Kit=require('../src/expansion-kit.js'),Pack=require('../src/campaign-pack.js'),G=require('../src/frontier-geometry.js');
const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){const e=bootGame(),g=e.game;Kit.install(g);Pack.install(g);g.startNew('standard','17117');standAt(g,g.player,g.core());g.resources.food=400;g.resources.ammo=400;g.resources.medicine=40;return e;}
function discover(g){const d=g.serialize();d.frontier.seen=g.frontier.world().pois.map(p=>p.id);g.restoreSave(d);standAt(g,g.player,g.core());}
function step(g,n){for(let i=0;i<n;i++){g.update(.04);g.input.pressed.clear();}}
function field(g){const target=g.campaignPack.overview().target;assert.ok(target);if(!g.frontier.active()){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}const w=g.frontier.world(),d=g.serialize();Object.assign(d.frontier,{x:target.x,y:target.y,z:0,inside:null});for(const p of w.nearPOI(target.x,target.y,110))for(let i=0;i<1+G.hash(w.seed,p.id,'threat')%4;i++)d.frontier.enemies[p.id+':e'+i]=0;d.frontier.kills=Object.values(d.frontier.enemies).filter(h=>h===0).length;g.restoreSave(d);return target;}
function home(g){if(g.frontier.active()){const d=g.serialize();d.frontier.active=false;d.frontier.anchor=null;d.frontier.inside=null;g.restoreSave(d);}standAt(g,g.player,g.core());}
function operation(g,kind){discover(g);assert.ok(g.campaignPack.start(kind).ok);for(let i=0;i<C.CampaignPackRules.definitions[kind].sites;i++){field(g);Object.assign(g.player.carry,C.CampaignPackRules.definitions[kind].fieldCost);const q=g.campaignPack.begin();assert.equal(q.ok,true,q.reason);step(g,C.CampaignPackRules.definitions[kind].seconds*25);assert.equal(g.campaignPack.busy(),false);}home(g);}

test('campagne : migration vide, aucune ressource offerte, sept opérations raccordées',()=>{const{game:g}=fresh(),before={...g.resources};assert.deepEqual(Pack.normalize(undefined),Pack.initial());assert.deepEqual(g.resources,before);assert.deepEqual(g.campaignPack.actions().map(a=>a.id),Object.keys(C.CampaignPackRules.definitions).map(k=>'start-'+k));assert.equal(g.expansions.get('campaign').title,'Campagne et secours');assert.equal(g.campaignPack.previewStart('constructor').ok,false);});
test('campagne : découvrir les lieux avant engagement et payer une seule fois',()=>{const{game:g}=fresh();assert.equal(g.campaignPack.start('aid').ok,false);discover(g);const before=g.resources.food;assert.ok(g.campaignPack.start('aid').ok);assert.equal(g.resources.food,before-18);assert.equal(g.campaignPack.start('salvage').ok,false);assert.ok(g.campaignPack.abandon().ok);assert.equal(g.campaignPack.start('aid').ok,false);g.wave++;assert.ok(g.campaignPack.start('aid').ok);});
test('campagne : patrouille physique de trois accès, récompense unique au dépôt',()=>{const{game:g}=fresh(),n=g.research.insight;operation(g,'patrol');assert.equal(g.campaignPack.snapshot().active.index,3);assert.equal(g.research.insight,n);assert.ok(g.campaignPack.finish().ok);assert.equal(g.research.insight,n+1);assert.equal(g.campaignPack.finish().ok,false);assert.equal(g.campaignPack.snapshot().finished.patrol,1);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.research.insight,n+1);});
test('campagne : colis humanitaire réellement consommé et moral plafonné',()=>{const{game:g}=fresh();g.morale=98;operation(g,'aid');assert.equal(g.campaignPack.carrying(),false);assert.ok(g.campaignPack.finish().ok);assert.equal(g.morale,100);assert.equal(g.campaignPack.snapshot().finished.aid,1);});
test('campagne : caisse industrielle avec outils du sac, dépôt et place libre requis',()=>{const{game:g}=fresh();discover(g);assert.ok(g.campaignPack.start('salvage').ok);field(g);assert.equal(g.campaignPack.begin().ok,false);g.player.carry.scrap=3;assert.ok(g.campaignPack.begin().ok);step(g,224);assert.equal(g.player.carry.scrap,3);step(g,1);assert.equal(g.player.carry.scrap,0);assert.ok(g.campaignPack.carrying());assert.equal(g.campaignPack.movementFactor(),.82);assert.equal(g.campaignPack.finish().ok,false);home(g);g.resources.scrap=g.storage;assert.equal(g.campaignPack.finish().ok,false);assert.ok(g.campaignPack.carrying());g.resources.scrap=100;g.resources.fuel=10;assert.ok(g.campaignPack.finish().ok);assert.equal(g.resources.scrap,124);assert.equal(g.resources.fuel,16);});
test('campagne : évacuation accueille un vrai ouvrier, jamais au-delà des logements',()=>{const{game:g}=fresh();operation(g,'evacuation');assert.ok(g.campaignPack.carrying());assert.equal(g.campaignPack.movementFactor(),.72);g.housing=g.population;assert.equal(g.campaignPack.finish().ok,false);const count=g.units.length;g.housing=g.population+1;assert.ok(g.campaignPack.finish().ok);assert.equal(g.units.length,count+1);assert.equal(g.units.at(-1).kind,'worker');assert.equal(g.campaignPack.finish().ok,false);});
test('campagne : travail annulé par déplacement, consommation différée',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('salvage');field(g);g.player.carry.scrap=3;g.campaignPack.begin();step(g,20);g.input.keys.add('KeyD');step(g,1);g.input.keys.clear();assert.equal(g.campaignPack.busy(),false);assert.equal(g.player.carry.scrap,3);assert.equal(g.campaignPack.snapshot().active.stage,'field');});
test('campagne : pause gèle le travail, reprise annule la tâche sans dépenses',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('evacuation');field(g);g.player.carry.medicine=2;g.campaignPack.begin();step(g,10);const before=g.campaignPack.overview().task.progress;g.paused=true;step(g,300);assert.equal(g.campaignPack.overview().task.progress,before);g.paused=false;assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.campaignPack.busy(),false);assert.equal(g.player.carry.medicine,2);assert.equal(g.campaignPack.snapshot().active.stage,'field');});
test('campagne : pin utilise le lieu découvert et remonte le vrai résultat',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('aid');const p=g.campaignPack.overview().target;assert.ok(g.campaignPack.actions().find(a=>a.id==='pin').run().ok);assert.equal(g.frontier.snapshot().pin,p.id);});
test('campagne : dégâts de transport sans résurrection, décès fait échouer le contrat',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('aid');const saved=g.updatePlayer;g.updatePlayer=()=>{g.player.health-=20;};step(g,1);assert.equal(g.campaignPack.snapshot().active.integrity,80);g.updatePlayer=saved;g.player.dead=true;g.player.health=0;step(g,1);assert.equal(g.campaignPack.snapshot().active,null);assert.equal(g.campaignPack.snapshot().history.at(-1).result,'lost');assert.equal(g.campaignPack.finish().ok,false);});
test('campagne : financement de garnison exige une vague réellement repoussée',()=>{const{game:g}=fresh(),ammo=g.resources.ammo,n=g.research.insight;assert.ok(g.campaignPack.start('defense').ok);assert.equal(g.resources.ammo,ammo-24);assert.equal(g.campaignPack.finish().ok,false);step(g,1);assert.equal(g.campaignPack.snapshot().active.stage,'defending');g.stats.wavesSurvived++;step(g,1);assert.equal(g.campaignPack.snapshot().active.stage,'ready');assert.ok(g.campaignPack.finish().ok);assert.equal(g.research.insight,n+1);assert.equal(g.resources.ammo,ammo-12);});
test('campagne : engagement perdu si le centre franchit son seuil même réparé ensuite',()=>{const{game:g}=fresh();g.campaignPack.start('defense');g.core().health=g.core().maxHealth*.64;step(g,1);assert.equal(g.campaignPack.snapshot().active,null);g.core().health=g.core().maxHealth;g.stats.wavesSurvived++;step(g,1);assert.equal(g.campaignPack.finish().ok,false);assert.equal(g.campaignPack.snapshot().history.at(-1).result,'lost');});
test('campagne : mort, pause et menus étrangers interdisent tout engagement',()=>{const{game:g}=fresh();g.paused=true;assert.equal(g.campaignPack.start('defense').ok,false);g.paused=false;g.activeOverlay={};assert.equal(g.campaignPack.start('defense').ok,false);g.activeOverlay=null;g.player.health=0;assert.equal(g.campaignPack.start('defense').ok,false);});
test('campagne : portages lourds exclusifs dans les deux prises en charge',()=>{const{game:g}=fresh();discover(g);g.explorationPack={carrying:()=>true};assert.equal(g.campaignPack.start('aid').ok,false);assert.ok(g.campaignPack.start('salvage').ok);field(g);g.player.carry.scrap=3;assert.equal(g.campaignPack.begin().ok,false);g.explorationPack={carrying:()=>false};assert.ok(g.campaignPack.begin().ok);});
test('campagne : refus transactionnel des registres forgés et sites non découverts',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('aid');const before=g.serialize(),bad=copy(before);bad.expansions127.modules.campaign.active.integrity=101;assert.throws(()=>g.restoreSave(bad));assert.deepEqual(g.campaignPack.snapshot(),before.expansions127.modules.campaign);const q=copy(before);q.frontier.seen=[];assert.throws(()=>g.restoreSave(q));assert.deepEqual(g.resources,before.resources);for(const value of [null,[],{version:2}, {...Pack.initial(),lastStarted:{...Pack.initial().lastStarted,constructor:1}}])assert.throws(()=>Pack.normalize(value));});
test('campagne : sauvegarde/reprise de toutes les étapes sans répéter les gains',()=>{for(const kind of ['aid','salvage','evacuation','patrol']){const{game:g}=fresh();operation(g,kind);const before=g.campaignPack.snapshot();assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.campaignPack.snapshot(),before);home(g);g.housing=g.population+1;assert.ok(g.campaignPack.finish().ok,kind);const after={...g.resources};assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.campaignPack.finish().ok,false);assert.deepEqual(g.resources,after);}});
test('campagne : vingt-quatre engagements bornent le journal et ne réarment pas une vague',()=>{const{game:g}=fresh();for(let n=0;n<24;n++){g.wave=n+1;g.phase='calm';g.resources.food=300;g.resources.ammo=300;assert.ok(g.campaignPack.start('defense').ok);g.stats.wavesSurvived++;step(g,1);home(g);assert.ok(g.campaignPack.finish().ok);assert.equal(g.campaignPack.start('defense').ok,false);}assert.equal(g.campaignPack.snapshot().history.length,16);assert.equal(g.campaignPack.snapshot().finished.defense,24);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.campaignPack.snapshot().finished.defense,24);});
test('campagne : démarrage neuf supprime contrats, opportunités et historique',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('aid');g.startNew('standard','42');assert.deepEqual(g.campaignPack.snapshot(),Pack.initial());});
test('campagne : une horde sauvage empêche le travail au marqueur visible',()=>{const{game:g}=fresh();discover(g);g.campaignPack.start('aid');const p=field(g),old=g.worldEvolution;g.worldEvolution={...old,overview:()=>({...old.overview(),groups:[{x:p.x,y:p.y,alive:80}]}),groupRadius:()=>8};assert.equal(g.campaignPack.begin().ok,false);g.worldEvolution=old;assert.ok(g.campaignPack.begin().ok);g.campaignPack.cancel();assert.doesNotThrow(()=>g.campaignPack.draw(g.ctx,'region',g.frontier.overview()));});
test('campagne : les aperçus répétés ne modifient ni stocks ni progression',()=>{const{game:g}=fresh();discover(g);const before=g.campaignPack.snapshot(),resources={...g.resources};for(let i=0;i<100;i++){g.campaignPack.overview();g.campaignPack.actions();}assert.deepEqual(g.campaignPack.snapshot(),before);assert.deepEqual(g.resources,resources);});
