'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const Kit=require('../src/expansion-kit.js'),Pack=require('../src/chronicles131.js'),D=require('../src/chronicles131-data.js'),UI=require('../src/chronicles131-ui.js'),C=require('../src/core.js');
const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){const env=bootGame(),g=env.game;Kit.install(g);Pack.install(g);g.startNew('standard','17117');standAt(g,g.player,g.core());return env;}
function deposit(g,amount=1){standAt(g,g.player,g.core());g.player.carry.wood=amount;g.input.keys.add('KeyE');g.updateInteraction(.04);g.input.keys.delete('KeyE');}
function ticks(g,count){for(let i=0;i<count;i++){g.update(.04);g.input.pressed.clear();}}
function finish(g,id){const q=g.chronicles131.begin(id);assert.ok(q.ok,q.reason);ticks(g,76);assert.ok(g.chronicles131.snapshot().collected.includes(id));}
function atField(g,id){const p=g.chronicles131.location(id);assert.ok(p);if(!g.frontier.active()){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}const s=g.serialize();Object.assign(s.frontier,{x:p.x,y:p.y,z:0,inside:null});if(!s.frontier.seen.includes(p.poi))s.frontier.seen.push(p.poi);g.restoreSave(s);return p;}
test('chroniques : 24 copies originales, 8 arcs de 3 traces et trois transcriptions sans fausse piste audio',()=>{assert.equal(D.records.length,24);assert.equal(new Set(D.records.map(r=>r.id)).size,24);assert.equal(D.arcs.length,8);assert.ok(D.arcs.every(a=>a.records.length===3));assert.equal(D.records.filter(r=>r.kind==='transcription').length,3);for(const r of D.records)assert.ok(r.text.length<520);assert.equal(Object.keys(D.scenes).length,3);});
test('chroniques : migration sans prologue ni séquence imposée ; reset les propose sans ouvrir une fenêtre',()=>{const{game:g}=fresh();const old=Pack.normalize(undefined);assert.equal(old.prologue.status,'skipped');assert.equal(old.scenes.length,3);assert.equal(g.chronicles131.snapshot().prologue.status,'available');assert.equal(g.activeOverlay,null);assert.equal(g.chronicles131.scene(),null);const s=g.serialize();delete s.expansions127.modules.lore131;g.restoreSave(s);assert.equal(g.chronicles131.snapshot().prologue.status,'skipped');});
test('chroniques : accès déterministes et physiquement libres, un lieu par trace, sans coût de rendu global répété',()=>{const{game:g}=fresh(),w=g.frontier.world(),a=g.chronicles131.placements(),b=g.chronicles131.placements();assert.equal(a.size,16);assert.equal(new Set([...a.values()].map(p=>p.poi)).size,16);assert.deepEqual(a,b);for(const[id,p]of a){const record=D.records.find(r=>r.id===id),poi=w.pois.find(x=>x.id===p.poi);assert.ok(record.types.includes(poi.type));assert.equal(w.blocked(p.x,p.y,C.Chronicles131Rules.markerRadius,0,null),false);assert.ok(w.line(p,poi.drive.a,0,null,null,.05));}const s=g.serialize();g.restoreSave(s);assert.deepEqual(g.chronicles131.placements(),a);});
test('chroniques : archives relevées avec du temps actif et lues après la sauvegarde, sans récompense',()=>{const{game:g}=fresh(),before={...g.resources};const q=g.chronicles131.begin('doors-0');assert.ok(q.ok);g.paused=true;for(let i=0;i<100;i++)g.chronicles131.tick(.04);assert.equal(g.chronicles131.snapshot().collected.length,0);g.paused=false;for(let i=0;i<76;i++)g.chronicles131.tick(.04);assert.equal(g.chronicles131.busy(),false);assert.ok(g.chronicles131.snapshot().collected.includes('doors-0'));assert.equal(g.chronicles131.snapshot().read.length,0);assert.ok(g.save(false));assert.ok(g.load());assert.ok(g.chronicles131.snapshot().collected.includes('doors-0'));assert.equal(g.chronicles131.snapshot().read.length,0);assert.ok(g.chronicles131.read('doors-0').ok);assert.equal(g.chronicles131.begin('doors-0').ok,false);for(const k of C.RESOURCE_KEYS)assert.ok(g.resources[k]<=before[k]+1e-6,'Lecture ne crée pas '+k);});
test('chroniques : déplacement, blessure, décès et ordre des documents interrompent ou refusent le relevé',()=>{const{game:g}=fresh();assert.ok(g.chronicles131.begin('doors-0').ok);g.player.x+=8;ticks(g,1);assert.equal(g.chronicles131.busy(),false);standAt(g,g.player,g.core());assert.ok(g.chronicles131.begin('doors-0').ok);g.player.health-=1;ticks(g,1);assert.equal(g.chronicles131.busy(),false);assert.equal(g.chronicles131.begin('doors-1').ok,false);finish(g,'doors-0');atField(g,'doors-1');assert.ok(g.chronicles131.preview('doors-1').ok);g.player.dead=true;assert.equal(g.chronicles131.preview('doors-1').ok,false);});
test('chroniques : une trace régionale exige découverte et accès puis reste lue lors des allers-retours',()=>{const{game:g}=fresh();finish(g,'doors-0');assert.equal(g.chronicles131.preview('doors-1').ok,false);atField(g,'doors-1');finish(g,'doors-1');assert.ok(g.chronicles131.read('doors-1').ok);const state=g.serialize();g.restoreSave(state);assert.ok(g.chronicles131.snapshot().read.includes('doors-1'));assert.equal(g.chronicles131.begin('doors-1').ok,false);});
test('chroniques : décisions uniques, dossiers requis, textes suivants modifiés et état repris',()=>{const{game:g}=fresh();assert.equal(g.chronicles131.choose('doors','public').ok,false);const state=g.chronicles131.snapshot();state.collected=['doors-0','doors-1','doors-2','radio-0','radio-1','radio-2'];g.chronicles131.restore(state);assert.ok(g.chronicles131.choose('doors','public').ok);assert.equal(g.chronicles131.choose('doors','reserve').ok,false);assert.ok(g.chronicles131.choose('radio','uncertain').ok);const s=g.chronicles131.snapshot();s.selected=D.arcs.findIndex(a=>a.id==='neighbors');g.chronicles131.restore(s);assert.match(g.chronicles131.overview().summary,/masquer les noms/);s.selected=D.arcs.findIndex(a=>a.id==='care');g.chronicles131.restore(s);assert.match(g.chronicles131.overview().summary,/colonne séparée/);assert.ok(g.save(false));g.load();assert.equal(g.chronicles131.snapshot().choices.radio,'uncertain');});
test('chroniques : validation refuse état corrompu, lectures impossibles, ordre et décision gratuite',()=>{for(const alter of [s=>s.collected=['doors-1'],s=>s.read=['doors-0'],s=>s.collected=['doors-0','doors-0'],s=>s.choices.doors='public',s=>s.choices.hacked='yes',s=>s.prologue.status='done',s=>s.scenes=['unknown'],s=>s.selected=8,s=>s.prologue.completed=[1,1]]){const s=Pack.initial();alter(s);assert.throws(()=>Pack.normalize(s));}const{game:g}=fresh(),before=g.serialize(),bad=copy(before);bad.expansions127.modules.lore131.read=['doors-2'];assert.throws(()=>g.restoreSave(bad));const after=g.serialize();delete after.timestamp;delete before.timestamp;assert.deepEqual(after,before);});
test('chroniques : prologue progresse sur les compteurs du moteur, ne récompense pas un simple clic et se passe',()=>{const{game:g}=fresh();assert.ok(g.chronicles131.startPrologue().ok);assert.equal(g.chronicles131.startPrologue().ok,false);ticks(g,1);assert.equal(g.chronicles131.snapshot().prologue.stage,0);g.stats.gathered+=8;ticks(g,1);assert.equal(g.chronicles131.snapshot().prologue.stage,1);deposit(g,8);ticks(g,1);assert.equal(g.chronicles131.snapshot().prologue.stage,2);assert.ok(g.chronicles131.skipPrologue().ok);assert.equal(g.chronicles131.snapshot().prologue.status,'skipped');assert.equal(g.chronicles131.skipPrologue().ok,false);});
test('chroniques : trois scènes déclenchées par actions réelles, skippables, sans pause et sans répétition à la reprise',()=>{const{game:g}=fresh();deposit(g);ticks(g,1);assert.equal(g.chronicles131.scene().id,'return');assert.equal(g.paused,false);const elapsed=g.elapsed;ticks(g,20);assert.ok(g.elapsed>elapsed);assert.ok(g.chronicles131.dismissScene());g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());ticks(g,1);assert.equal(g.chronicles131.scene().id,'road');g.chronicles131.dismissScene();g.stats.wavesSurvived++;ticks(g,1);assert.equal(g.chronicles131.scene().id,'dawn');const s=g.serialize();g.restoreSave(s);assert.equal(g.chronicles131.scene(),null);ticks(g,1);assert.equal(g.chronicles131.scene(),null);assert.equal(g.chronicles131.snapshot().scenes.length,3);});
test('chroniques : carte de séquence non modale, cachée sous une pause et paramètres mouvement respectés',()=>{const{game:g}=fresh(),ui=UI.install(g,document);deposit(g);ticks(g,1);ui.refresh();assert.equal(ui.element.classList.contains('hidden'),false);assert.equal(g.activeOverlay,null);g.settings.reducedMotion=true;ui.refresh();assert.ok(ui.element.classList.contains('chronicles-static'));g.paused=true;ui.refresh();assert.ok(ui.element.classList.contains('hidden'));g.paused=false;g.chronicles131.dismissScene();ui.refresh();assert.ok(ui.element.classList.contains('hidden'));});
test('chroniques : peinture uniquement de la couche extérieure avec culling et pas de trace dupliquée après collecte',()=>{const{game:g}=fresh();finish(g,'doors-0');const p=atField(g,'doors-1'),v=g.frontier.overview(),view={l:p.x-8,r:p.x+8,t:p.y-8,b:p.y+8};let entries=g.chronicles131.depthEntries(v,view);assert.ok(entries.some(e=>e.id==='record:doors-1'));assert.deepEqual(g.chronicles131.depthEntries({...v,z:1},view),[]);assert.deepEqual(g.chronicles131.depthEntries({...v,inside:p.poi},view),[]);finish(g,'doors-1');assert.equal(g.chronicles131.depthEntries(g.frontier.overview(),view).some(e=>e.id==='record:doors-1'),false);});
test('chroniques : une tâche est annulée avant une réanimation au même tick',()=>{const{game:g}=fresh();assert.ok(g.chronicles131.begin('doors-0').ok);g.player.dead=true;g.player.health=0;g.player.downTimer=.001;g.update(.04);assert.equal(g.player.dead,false);assert.equal(g.chronicles131.busy(),false);assert.equal(g.chronicles131.snapshot().collected.length,0);});
test('chroniques : les livraisons des ouvriers ne remplacent pas le geste personnel du prologue',()=>{const{game:g}=fresh();assert.ok(g.chronicles131.startPrologue().ok);g.stats.gathered+=8;g.chronicles131.tick(.04);const u=g.units[0];standAt(g,u,g.core());u.carryType='wood';u.carry=10;g.depositWorker(u,g.core(),.04);assert.ok(g.depositedResources>=10);g.chronicles131.tick(.04);assert.equal(g.chronicles131.snapshot().prologue.stage,1);assert.equal(g.chronicles131.scene(),null);deposit(g,8);g.chronicles131.tick(.04);assert.equal(g.chronicles131.snapshot().prologue.stage,2);const B=g.core().constructor,b=new B(g.nextId++,'woodWall',70,70,0,1);g.world.add(b);g.chronicles131.tick(.04);assert.equal(g.chronicles131.snapshot().prologue.status,'done');});
test('chroniques : parole d’un compagnon réel vivant, reprise comme archive après sa mort, jamais de résurrection',()=>{const{game:g}=fresh();finish(g,'doors-0');assert.equal(g.chronicles131.speak('malik').ok,false);assert.ok(g.worldEvolution.assignCompanion('malik'));assert.ok(g.chronicles131.speak('malik').ok);assert.equal(g.chronicles131.speak('malik').ok,false);let s=g.serialize();s.worldEvolution.companions.find(c=>c.id==='malik').health=0;g.restoreSave(s);assert.equal(g.chronicles131.speak('malik').ok,false);assert.equal(g.worldEvolution.snapshot().companions.find(c=>c.id==='malik').health,0);assert.ok(g.chronicles131.overview().rows.some(r=>r.label.includes('Propos recueillis auparavant')));});
