'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs');
const C=require('../src/core.js'),Pack=require('../src/companions-pack.js'),G=require('../src/frontier-geometry.js');
function fresh(ids=['samir','malik'],region=false){
 const {game:g}=bootGame();
 if(!g.expansions){const K=require('../src/expansion-kit.js');K.install(g);}
 Pack.install(g);g.startNew('standard','17117');g.worldEvolution.enableWorld4();g.population=10;g.resources.food=100;g.resources.scrap=100;
 for(const id of ids)assert.ok(g.worldEvolution.assignCompanion(id));
 g.player.x=g.core().x+80;g.player.y=g.core().y;
 if(region){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());step(g,4);}
 return g;
}
const step=(g,n)=>{for(let i=0;i<n;i++)g.update(.05);};
function moveTo(g,p,pos,z=0,kill=true){const d=g.serialize();if(z===0&&d.expansions127?.modules?.companions)d.expansions127.modules.companions.positions={};Object.assign(d.frontier,{x:pos.x,y:pos.y,z,inside:p?.id||null,seen:p?[...new Set([...d.frontier.seen,p.id])]:d.frontier.seen});if(kill)for(const place of g.frontier.world().nearPOI(pos.x,pos.y,150))for(let i=0;i<1+G.hash(d.worldSeed,place.id,'threat')%4;i++){d.frontier.enemies[place.id+':e'+i]=0;delete d.frontier.tracks[place.id+':e'+i];}d.frontier.kills=Object.values(d.frontier.enemies).filter(v=>v===0).length;g.restoreSave(d);}
const members=g=>g.worldEvolution.overview().companions;

test('1.27 équipe : ancien registre migre sans ressources ni entraînement gratuit',()=>{const s=Pack.validate(undefined);assert.equal(s.trained.length,0);assert.equal(s.training,null);assert.equal(Object.values(s.reserves).flatMap(Object.values).reduce((a,b)=>a+b,0),0);assert.deepEqual(Pack.validate(s),s);});
test('1.27 équipe : import refuse valeurs invalides, duplications et positions non bornées',()=>{for(const mutate of [s=>s.order='teleport',s=>s.training={id:'samir',left:Infinity},s=>s.reserves.lea.ammo=-1,s=>s.trained=['samir','samir'],s=>s.positions.lea={x:30000,y:500,z:0,inside:null},s=>s.order='rally',s=>s.reserves.enemy={ammo:8},s=>s.formation='magic']){const s=Pack.initial();mutate(s);assert.throws(()=>Pack.validate(s));}});
test('1.27 équipe : tenir conserve la position et suivre reprend un déplacement physique',()=>{const g=fresh(['samir'],true);assert.ok(g.companionsPack.setOrder('hold').ok);const p=members(g)[0];g.input.keys.add('KeyD');step(g,30);g.input.keys.clear();const held=members(g)[0];assert.equal(held.x,p.x);assert.equal(held.y,p.y);assert.ok(g.companionsPack.setOrder('follow').ok);step(g,20);const following=members(g)[0];assert.ok(Math.hypot(following.x-p.x,following.y-p.y)>.2);assert.equal(g.frontier.world().blocked(following.x,following.y,.30,following.z,following.inside),false);});
test('1.27 équipe : trois formations distinctes et regroupement conserve son point',()=>{const g=fresh(['samir','malik'],true),f=g.frontier.snapshot(),v=[];for(const name of ['line','file','spread']){assert.ok(g.companionsPack.setFormation(name).ok);v.push(g.companionsPack.control('malik',f,1,members(g)[1]).goal);}assert.equal(new Set(v.map(v=>JSON.stringify(v))).size,3);assert.ok(g.companionsPack.setOrder('rally').ok);const saved=g.companionsPack.snapshot().anchor;g.input.keys.add('KeyD');step(g,40);g.input.keys.clear();assert.deepEqual(g.companionsPack.snapshot().anchor,saved);assert.ok(Math.hypot(g.frontier.snapshot().x-saved.x,g.frontier.snapshot().y-saved.y)>1);});
test('1.27 équipe : silence empêche Malik de tirer et défense limite sa portée',()=>{const g=fresh(['malik'],true),w=g.frontier.world(),p=w.pois.find(p=>p.type==='house');moveTo(g,p,G.global(p,p.w/2,p.h/2-3),0,false);g.player.carry.ammo=8;g.player.invulnerable=20;assert.ok(g.companionsPack.setDiscipline('silent').ok);step(g,35);assert.equal(g.player.carry.ammo,8);assert.equal(g.companionsPack.control('malik',g.frontier.snapshot(),0,members(g)[0]).fire,false);assert.ok(g.companionsPack.setDiscipline('defensive').ok);assert.equal(g.companionsPack.control('malik',g.frontier.snapshot(),0,members(g)[0]).shotRange,C.CompanionPackRules.defenseRange);assert.ok(g.companionsPack.setDiscipline('free').ok);step(g,35);assert.ok(g.player.carry.ammo<8);});
test('1.27 équipe : entraînement payé une fois, suspendu loin du dépôt et pendant la pause',()=>{const g=fresh(['samir']);const before={...g.resources};assert.ok(g.companionsPack.train('samir').ok);assert.equal(before.food-g.resources.food,C.CompanionPackRules.training.cost.food);assert.equal(before.scrap-g.resources.scrap,C.CompanionPackRules.training.cost.scrap);assert.equal(g.companionsPack.train('samir').ok,false);g.paused=true;step(g,20);assert.equal(g.companionsPack.snapshot().training.left,C.CompanionPackRules.training.seconds);g.paused=false;g.player.x=1000;step(g,20);assert.equal(g.companionsPack.snapshot().training.left,C.CompanionPackRules.training.seconds);g.player.x=g.core().x+80;g.phase='calm';g.phaseTimer=1000;step(g,910);assert.equal(g.companionsPack.snapshot().training,null);assert.ok(g.companionsPack.snapshot().trained.includes('samir'));assert.equal(g.companionsPack.train('samir').ok,false);});
test('1.27 équipe : bonus médical accélère les soins sans modifier leur coût',()=>{const g=fresh(['samir'],true),s=g.companionsPack.snapshot();s.trained=['samir'];g.companionsPack.restore(s);g.player.health=60;g.player.carry.medicine=2;const before=g.player.health;step(g,20);const healed=g.player.health-before;assert.ok(Math.abs(healed-C.WorldEvolution.RULES.companionRules.healPerSecond*C.CompanionPackRules.training.bonus.samir)<.001);assert.ok(Math.abs((2-g.player.carry.medicine)-healed*C.WorldEvolution.RULES.companionRules.medicinePerHealth)<.00001);});
test('1.27 équipe : sacoche déduit les stocks et partage sans perte lorsque le sac est presque plein',()=>{const g=fresh(['samir']);g.resources.ammo=100;g.resources.medicine=10;const before={...g.resources};assert.ok(g.companionsPack.fill('samir').ok);for(const k of ['ammo','medicine','scrap'])assert.equal(before[k]-g.resources[k],C.CompanionPackRules.reserve[k]);assert.equal(g.companionsPack.fill('samir').ok,false);g.player.carry.wood=g.player.carryCapacity-3;assert.ok(g.companionsPack.share('samir').ok);assert.equal(C.bagTotal(g.player.carry),g.player.carryCapacity);assert.equal(g.player.carry.ammo,3);assert.equal(g.companionsPack.snapshot().reserves.samir.ammo,5);const saved=g.companionsPack.snapshot();assert.equal(g.companionsPack.share('samir').ok,false);assert.deepEqual(g.companionsPack.snapshot(),saved);});
test('1.27 équipe : partage refusé en région si le partenaire est trop loin',()=>{const g=fresh(['samir']);g.resources.ammo=100;g.resources.medicine=10;assert.ok(g.companionsPack.fill('samir').ok);g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());step(g,2);assert.ok(g.companionsPack.setOrder('hold').ok);g.input.keys.add('KeyD');step(g,100);g.input.keys.clear();const before=g.companionsPack.snapshot().reserves;assert.equal(g.companionsPack.share('samir').ok,false);assert.deepEqual(g.companionsPack.snapshot().reserves,before);});
test('1.27 équipe : sauvegarde réelle conserve tactique, formation, sacoches et entraînement',()=>{const g=fresh(['samir']);g.resources.ammo=100;g.resources.medicine=10;assert.ok(g.companionsPack.fill('samir').ok);assert.ok(g.companionsPack.train('samir').ok);assert.ok(g.companionsPack.setFormation('file').ok);assert.ok(g.companionsPack.setDiscipline('silent').ok);step(g,20);const state=g.companionsPack.snapshot();assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.companionsPack.snapshot(),state);g.startNew('standard','42');assert.deepEqual(g.companionsPack.snapshot(),Pack.initial());});
test('1.27 équipe : tenir survit à la reprise sans téléporter le compagnon sur le commandant',()=>{const g=fresh(['samir'],true);assert.ok(g.companionsPack.setOrder('hold').ok);g.input.keys.add('KeyD');step(g,40);g.input.keys.clear();const before=members(g)[0];assert.ok(g.save(false));assert.ok(g.load());step(g,2);const after=members(g)[0];assert.equal(after.x,before.x);assert.equal(after.y,before.y);});
test('1.27 équipe : changer d’étage annule une consigne restée au niveau précédent',()=>{const g=fresh(['samir'],true),w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex');assert.ok(g.companionsPack.setOrder('hold').ok);const stair=w.plan(p,1).stairs[0];moveTo(g,p,G.global(p,stair.x+stair.w/2,stair.y+stair.h/2),1);step(g,4);assert.equal(members(g)[0].z,1);assert.equal(g.companionsPack.snapshot().order,'follow');assert.equal(w.blocked(members(g)[0].x,members(g)[0].y,.30,1,p.id),false);});
test('1.27 équipe : annulation libère les tâches sans rembourser les fournitures consommées',()=>{const g=fresh(['samir']);assert.ok(g.companionsPack.train('samir').ok);const stock={...g.resources};assert.ok(g.companionsPack.busy());assert.ok(g.companionsPack.cancelTraining().ok);assert.equal(g.companionsPack.busy(),false);assert.equal(g.companionsPack.snapshot().training,null);assert.deepEqual(g.resources,stock);assert.equal(g.companionsPack.cancelTraining().ok,false);});
test('1.27 équipe : import d’une position dans un lieu inexistant échoue avant mutation',()=>{const g=fresh(['samir'],true),before=g.world,d=g.serialize();d.expansions127.modules.companions.positions.samir={x:4000,y:4000,z:1,inside:'P9999',a:0};assert.throws(()=>g.restoreSave(d));assert.equal(g.world,before);});
test('1.27 équipe : embarquer annule tenir, puis débarquer replace près du véhicule',()=>{const g=fresh(['samir']);g.world.add(new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1));g.refreshMetrics(true);g.fieldcraft.setup();g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const car=g.expeditions.car();g.player.x=car.x+35;g.player.y=car.y;assert.ok(g.expeditions.board().ok);car.x=g.player.x=4058;car.y=g.player.y=2048;assert.ok(g.frontier.enter());assert.ok(g.frontier.board());step(g,4);assert.ok(g.companionsPack.setOrder('hold').ok);assert.ok(g.frontier.board());step(g,4);assert.equal(g.companionsPack.snapshot().order,'follow');assert.equal(g.companionsPack.snapshot().positions.samir,undefined);assert.ok(g.frontier.board());step(g,4);const f=g.frontier.snapshot(),p=members(g)[0];assert.ok(Math.hypot(f.x-p.x,f.y-p.y)<4);assert.equal(g.frontier.world().blocked(p.x,p.y,.3),false);});
test('1.27 équipe : tenir à plus de 180 mètres survit à la reprise sans rappel magique',()=>{const g=fresh(['samir'],true);assert.ok(g.companionsPack.setOrder('hold').ok);const before=members(g)[0],d=g.serialize(),w=g.frontier.world();let q;for(const r of w.roads){const p={x:(r.a.x+r.b.x)/2,y:(r.a.y+r.b.y)/2};if(Math.hypot(p.x-before.x,p.y-before.y)>250&&!w.blocked(p.x,p.y,.4,0,null)){q=p;break;}}assert.ok(q);Object.assign(d.frontier,{...q,z:0,inside:null});g.restoreSave(d);step(g,2);const after=members(g)[0];assert.equal(after.x,before.x);assert.equal(after.y,before.y);});
test('1.27 équipe : entraînement ne progresse ni dans une interface ni commandant à zéro vie',()=>{const g=fresh(['samir']);assert.ok(g.companionsPack.train('samir').ok);const left=g.companionsPack.snapshot().training.left;g.activeOverlay={};g.companionsPack.update(.05);assert.equal(g.companionsPack.snapshot().training.left,left);g.activeOverlay=null;g.player.health=0;g.companionsPack.update(.05);assert.equal(g.companionsPack.snapshot().training.left,left);});
test('1.27 équipe : aucun entraînement ni ravitaillement depuis le siège du véhicule',()=>{const g=fresh(['samir']);g.world.add(new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1));g.refreshMetrics(true);g.fieldcraft.setup();g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const car=g.expeditions.car();g.player.x=car.x+35;g.player.y=car.y;assert.ok(g.expeditions.board().ok);car.x=g.player.x=g.core().x+80;car.y=g.player.y=g.core().y;assert.equal(g.companionsPack.train('samir').ok,false);assert.equal(g.companionsPack.fill('samir').ok,false);assert.equal(g.companionsPack.share('samir').ok,false);});
test('1.27 équipe : Samir réserve les médicaments pendant un pansement du module Survie',()=>{const g=fresh(['samir'],true);require('../src/survival-pack.js').install(g);g.player.health=60;g.player.carry.medicine=2;const before={...g.player.carry};assert.ok(g.survivalPack.begin('dressing').ok);step(g,98);assert.equal(g.player.health,60);assert.deepEqual(g.player.carry,before);step(g,3);assert.equal(g.survivalPack.busy(),false);assert.equal(g.player.carry.medicine,0);assert.ok(g.survivalPack.snapshot().dressing.remaining>0);});

test('1.31 équipe : coordonnées lointaines autorisées uniquement en génération5',()=>{const s=Pack.initial();s.positions.lea={x:9000,y:500,z:0,inside:null};assert.throws(()=>Pack.validate(s,{worldSeed:17117,frontier:{generation:4}}));assert.equal(Pack.validate(s,{worldSeed:17117,frontier:{generation:5}}).positions.lea.x,9000);});
