'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const F=require('./deadwall-siege/siege.js'),R=F.RULES;
const b=(id,type='house',x=500,y=500)=>({id,type,x,y,w:2,h:2,health:1000,maxHealth:1000,progress:1,completed:true,powered:true,dead:false,def:{health:1000,size:[2,2]}});
const unit=id=>({id,kind:'worker',health:90,dead:false});
const setup=()=>{const e=new F.Engine(),tank=b(2,'fireCistern'),house=b(3),units=[unit(10)];e.reconcile([tank,house],units);return{e,tank,house,units};};
const step=(e,bs,units=[],dt=.25,extra={})=>e.step(dt,{buildings:bs,units,resources:{fuel:100},running:true,damage:(b,n)=>{b.health-=n;if(b.health<=0)b.dead=true;},...extra});
test('registre initial vide, aucune eau gratuite',()=>{const e=new F.Engine();assert.equal(e.state.playerWater,0);assert.deepEqual(e.state.tanks,[]);assert.equal(e.state.stats.ignitions,0);});
test('snapshot et normalisation détachent leurs données',()=>{const {e}=setup(),s=e.snapshot();s.tanks[0].water=100;assert.equal(e.tank(2).water,0);assert.deepEqual(F.normalize(e.snapshot()),e.snapshot());});
for(const [label,mutate]of [
 ['version',s=>s.version=2],['eau négative',s=>s.playerWater=-1],['eau infinie',s=>s.playerWater=Infinity],['seau trop plein',s=>s.playerWater=9],
 ['citerne trop pleine',s=>s.tanks=[{id:2,water:121}]],['identifiant dupliqué',s=>s.tanks=[{id:2,water:1},{id:2,water:2}]],
 ['chaleur NaN',s=>s.fires=[{id:3,heat:NaN,age:0,spread:0,origin:'blast'}]],['foyer éteint dans la liste',s=>s.fires=[{id:3,heat:0,age:0,spread:0,origin:'blast'}]],
 ['origine fictive',s=>s.fires=[{id:3,heat:3,age:0,spread:0,origin:'magic'}]],['trop de secouristes',s=>s.crew=Array.from({length:17},(_,i)=>({id:i+1,water:0,release:false}))],
 ['eau secouriste surchargée',s=>s.crew=[{id:10,water:13,release:false}]],['ordre de repli invalide',s=>s.crew=[{id:10,water:0,release:'yes'}]],
 ['journal inconnu',s=>s.history=[{id:0,type:'reward',at:0}]],['statistique négative',s=>s.stats.waterUsed=-1],
 ['bonus d’alerte cumulatif',s=>s.lastWave={wave:8,id:'rush',bonus:14}],['profil inconnu',s=>s.lastWave={wave:8,id:'fake',bonus:0}]
])test('refus : '+label,()=>{const s=F.create();mutate(s);assert.throws(()=>F.normalize(s));});
test('quatre bâtiments avec coûts, paliers et profils distincts',()=>{assert.equal(Object.keys(F.BUILDINGS).length,4);for(const d of Object.values(F.BUILDINGS)){assert.ok(d.health>0&&d.score>0&&d.buildTime>0);assert.ok(Object.values(d.cost).every(n=>n>0));assert.ok(d.size.every(Number.isInteger));}assert.equal(F.BUILDINGS.fireScreen.wall,true);});
test('les deux premières vagues restent identiques',()=>{const plan={wave:2};assert.equal(F.adaptPlan(plan,{},0).plan,plan);assert.equal(F.profileFor(1,0),null);});
const enemies=require('../src/core.js').ENEMIES;
test('1680 plans : total, seuils, fronts et points de vie conservés',()=>{
 const original=JSON.stringify(enemies);for(const seed of [0,17117,0xffffffff])for(let wave=1;wave<=280;wave++)for(const total of [17,720]){
  const unlocked=Object.keys(enemies).filter(k=>enemies[k].unlockWave<=wave),composition=Object.fromEntries(Object.keys(enemies).map(k=>[k,0]));for(let i=0;i<total;i++)composition[unlocked[i%unlocked.length]]++;
  const p={wave,total,fronts:Math.min(4,1+Math.floor((wave-1)/3)),composition,spawnInterval:.12},old=JSON.stringify(p),a=F.adaptPlan(p,enemies,seed).plan;
  assert.equal(Object.values(a.composition).reduce((a,b)=>a+b,0),total);assert.equal(a.fronts,p.fronts);assert.equal(JSON.stringify(p),old);for(const [k,n]of Object.entries(a.composition)){assert.ok(Number.isInteger(n)&&n>=0);if(wave<enemies[k].unlockWave)assert.equal(n,0);}
 }assert.equal(JSON.stringify(enemies),original);
});
test('tous les profils visités sur une rotation tardive et déterministe',()=>{for(const seed of [0,17117,42]){const set=new Set();for(let n=30;n<30+F.PROFILES.length;n++){set.add(F.profileFor(n,seed).id);assert.deepEqual(F.profileFor(n,seed),F.profileFor(n,seed));}assert.deepEqual([...set].sort(),F.PROFILES.map(p=>p.id).sort());}});
test('une citerne commence vide et pompe contre carburant',()=>{const {e,tank}=setup(),resources={fuel:10};step(e,[tank],[],.25,{resources});assert.equal(e.tank(2).water,R.pumpRate*.25);assert.ok(Math.abs(resources.fuel-(10-R.pumpRate*.25*R.fuelPerWater))<1e-9);});
test('une citerne pleine ne consomme plus de carburant',()=>{const {e,tank}=setup();e.tank(2).water=120;const r={fuel:10};step(e,[tank],[],.25,{resources:r});assert.equal(r.fuel,10);});
test('production fractionnelle : zéro carburant négatif',()=>{const {e,tank}=setup(),r={fuel:.0001};step(e,[tank],[],.25,{resources:r});assert.equal(r.fuel,0);assert.ok(Math.abs(e.tank(2).water-.0001/R.fuelPerWater)<1e-10);});
test('sans électricité la pluie reste une alimentation lente',()=>{const {e,tank}=setup(),r={fuel:10};tank.powered=false;step(e,[tank],[],.25,{resources:r,weather:1});assert.equal(e.tank(2).water,R.rainRate*.25);assert.equal(r.fuel,10);});
test('ni pompe ni pluie : aucune eau produite',()=>{const {e,tank}=setup();tank.powered=false;step(e,[tank]);assert.equal(e.tank(2).water,0);});
test('citerne détruite : perte de sa réserve, pas de transfert distant',()=>{const {e,tank}=setup();e.tank(2).water=45;tank.dead=true;e.reconcile([tank]);assert.equal(e.state.tanks.length,0);assert.equal(e.state.stats.waterLost,45);});
test('ni pause ni pas de temps invalide ne font avancer le feu ou la pompe',()=>{const {e,tank,house}=setup();e.ignite(house,'blast');const s=e.snapshot();for(const dt of [0,-1,NaN,Infinity,1])step(e,[tank,house],[],dt);step(e,[tank,house],[],.25,{running:false});assert.deepEqual(e.snapshot(),s);});
test('un logement ne s’enflamme pas spontanément sous un coup',()=>{const {e,house}=setup();house.health=100;assert.equal(e.ignite(house,'machinery'),false);});
test('machine chaude endommagée : foyer unique',()=>{const e=new F.Engine(),source=b(1,'generator');source.health=400;assert.equal(e.ignite(source),true);assert.equal(e.ignite(source),false);assert.equal(e.state.stats.ignitions,1);});
test('machine intacte : pas de départ de feu arbitraire',()=>{const e=new F.Engine();assert.equal(e.ignite(b(1,'generator')),false);});
test('chantiers, béton, acier, cloison ne brûlent pas',()=>{const e=new F.Engine();for(const type of ['concreteWall','steelWall','fireScreen'])assert.equal(e.ignite(b(1,type),'blast'),false);const h=b(2);h.completed=false;h.progress=.5;assert.equal(e.ignite(h,'blast'),false);});
test('dégâts continus et production à suspendre sans réparation gratuite',()=>{const {e,house}=setup();e.ignite(house,'blast');step(e,[house]);assert.ok(house.health<1000);const old=house.health;e.state.playerWater=8;e.suppress(house.id,0,.25,{running:true,accessible:true,secure:true});assert.equal(house.health,old);});
test('propagation de voisinage, pas de téléportation au quartier distant',()=>{const e=new F.Engine(),a=b(1),near=b(2,'warehouse',575,500),far=b(3,'house',900,500);e.ignite(a,'blast');e.fire(1).heat=70;e.fire(1).spread=3.9;step(e,[a,near,far]);assert.ok(e.fire(2));assert.equal(e.fire(3),undefined);});
for(const type of ['fireScreen','steelWall','concreteWall'])test(type+' bloque la propagation directe',()=>{const a=b(1),c=b(2,'house',595,500),screen=b(3,type,548,500);screen.w=1;screen.h=1;assert.equal(F.heatClear(a,c,[a,c,screen]),false);screen.dead=true;assert.equal(F.heatClear(a,c,[a,c,screen]),true);});
test('pas d’obstruction inventée lorsque la cloison est hors du trajet',()=>{assert.equal(F.heatClear(b(1),b(2,'house',590,500),[b(3,'fireScreen',550,650)]),true);});
test('32 foyers simultanés au maximum',()=>{const e=new F.Engine();for(let n=1;n<100;n++)e.ignite(b(n),'blast');assert.equal(e.state.fires.length,32);});
test('fin naturelle du combustible sans destruction magique',()=>{const e=new F.Engine(),a=b(1);e.ignite(a,'blast');e.fire(1).age=179.9;step(e,[a]);assert.equal(e.state.fires.length,0);assert.equal(e.state.stats.burnedOut,1);assert.ok(a.health>0);});
test('remplissage local conserve exactement l’eau',()=>{const {e}=setup();e.tank(2).water=10;const n=e.fill(2,0,.25,{running:true,accessible:true});assert.equal(n,1);assert.equal(e.tank(2).water+e.state.playerWater,10);});
test('remplissage bloqué à travers une porte fermée',()=>{const {e}=setup();e.tank(2).water=10;assert.equal(e.fill(2,0,.25,{running:true,accessible:false}),0);assert.equal(e.tank(2).water,10);});
test('capacité de huit unités du seau respectée',()=>{const {e}=setup();e.tank(2).water=120;for(let n=0;n<100;n++)e.fill(2,0,.25,{running:true,accessible:true});assert.equal(e.state.playerWater,8);assert.equal(e.tank(2).water,112);});
test('arroser exige eau, accès et sécurité',()=>{const {e,house}=setup();e.ignite(house,'blast');assert.equal(e.suppress(3,0,.25,{running:true,accessible:true,secure:true}),0);e.state.playerWater=8;for(const ctx of [{running:false,accessible:true,secure:true},{running:true,accessible:false,secure:true},{running:true,accessible:true,secure:false}])assert.equal(e.suppress(3,0,.25,ctx),0);assert.equal(e.state.playerWater,8);});
test('extinction utilise seulement l’eau nécessaire et crée un délai humide',()=>{const {e,house}=setup();e.ignite(house,'blast');e.state.playerWater=8;for(let i=0;i<20;i++)e.suppress(3,0,.25,{running:true,accessible:true,secure:true});assert.equal(e.fire(3),undefined);assert.equal(e.state.stats.extinguished,1);assert.ok(Math.abs(e.state.stats.waterUsed-R.initialHeat/R.coolingPerWater)<1e-8);assert.equal(e.ignite(house,'blast'),false);});
test('humidification se termine en simulation, pas lors de la sauvegarde',()=>{const {e,house}=setup();e.ignite(house,'blast');e.state.playerWater=8;for(let i=0;i<10;i++)e.suppress(3,0,.25,{running:true,accessible:true,secure:true});const f=new F.Engine(e.snapshot());assert.equal(f.ignite(house,'blast'),false);for(let i=0;i<100;i++)step(f,[house]);assert.equal(f.ignite(house,'blast'),true);});
test('chute du commandant perd son eau une seule fois',()=>{const e=new F.Engine();e.state.playerWater=7;e.playerDown();e.playerDown();assert.equal(e.state.stats.waterLost,7);assert.equal(e.state.playerWater,0);});
test('brigade réutilise un ID existant et respecte les places',()=>{const e=new F.Engine();assert.equal(e.assign(10,{canCommand:true,available:true,slots:2}),true);assert.equal(e.assign(10,{canCommand:true,available:true,slots:2}),false);assert.equal(e.assign(11,{canCommand:true,available:true,slots:2}),true);assert.equal(e.assign(12,{canCommand:true,available:true,slots:2}),false);});
test('réaffectation indisponible ou pause hors commandement refusée',()=>{const e=new F.Engine();assert.equal(e.assign(10,{canCommand:false,available:true,slots:2}),false);assert.equal(e.assign(10,{canCommand:true,available:false,slots:2}),false);});
test('rappel conserve le porteur jusqu’à son retour',()=>{const e=new F.Engine();e.assign(10,{canCommand:true,available:true,slots:2});e.member(10).water=8;e.release(10);assert.equal(e.member(10).water,8);assert.equal(e.arriveHome(10),true);assert.equal(e.member(10),undefined);assert.equal(e.state.stats.waterLost,8);});
test('perte de secouriste ne ressuscite personne au chargement',()=>{const e=new F.Engine();e.assign(10,{canCommand:true,available:true,slots:2});e.member(10).water=6;e.reconcile([],[]);assert.equal(e.state.crew.length,0);assert.equal(new F.Engine(e.snapshot()).state.crew.length,0);assert.equal(e.state.stats.waterLost,6);});
test('cent reprises conservent eau, chaleur, progression et statistiques',()=>{const {e,tank,house,units}=setup();e.assign(10,{canCommand:true,available:true,slots:2});e.tank(2).water=73;e.ignite(house,'blast');for(let i=0;i<40;i++)step(e,[tank,house],units);const saved=e.snapshot();for(let n=0;n<100;n++)assert.deepEqual(new F.Engine(saved).snapshot(),saved);});
test('longue simulation : mémoire bornée, ressources finies',()=>{const {e,tank,house}=setup(),resources={fuel:2};e.ignite(house,'blast');for(let i=0;i<4000;i++)step(e,[tank,house],[],.25,{resources});assert.ok(e.state.history.length<=R.historyLimit);assert.ok(e.state.fires.length<=R.maxFires);assert.ok(e.tank(2).water<=120);assert.ok(resources.fuel>=0);F.normalize(e.snapshot());});
