'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),D=require('../src/defense-pack131.js');
function fresh(){const {game:g}=boot127();D.install(g);g.startNew('standard','17117');for(const k of C.RESOURCE_KEYS)g.resources[k]=300;g.world.nodes.forEach(n=>n.depleted=true);g.units=[];g.phase='calm';return g;}
function add(g,type='gate',gx=72,gy=72,progress=1){const b=new(g.core().constructor)(g.nextId++,type,gx,gy,0,progress);g.world.add(b);g.refreshMetrics(true);g.selectBuilding(b);standAt(g,g.player,b);return b;}
function post(g,b){return g.defense131.snapshot().posts.find(p=>p.id===b.id);}
function advance(g,seconds){for(let n=0;n<Math.ceil(seconds/.1);n++)g.defense131.step(.1);}
function person(g,kind,b){const point=g.fieldcraft.service(g.player,b),u=g.createProtectedSurvivor(kind,point.x,point.y);assert.ok(u);return u;}
function zombie(g,x,y){const z={id:g.nextId++,kind:'walker',x,y,health:60,maxHealth:60,dead:false,radius:10,vx:0,vy:0,think:0,attackCooldown:0,speedFactor:1,facing:0};g.zombies.push(z);g.rebuildBuckets();return z;}
test('D17 preparation: empty migration has no gifts or automatic policies',()=>{const g=fresh(),resources={...g.resources},raw=g.serialize();delete raw.expansions127.modules.defense131;g.restoreSave(raw);assert.deepEqual(g.defense131.snapshot(),D.initial());assert.deepEqual(g.resources,resources);});
test('gate policy: installation is paid once, changes modes after physical delay',()=>{const g=fresh(),b=add(g),before={...g.resources};assert.equal(g.defense131.configureGate(b.id).ok,true);assert.equal(g.resources.scrap,before.scrap-C.Defense131Rules.gateCost.scrap);g.phase='warning';advance(g,1);assert.equal(b.gateMode,'auto');advance(g,1.1);assert.equal(b.gateMode,'closed');g.phase='calm';advance(g,2.1);assert.equal(b.gateMode,'auto');const paid={...g.resources};assert.equal(g.defense131.configureGate(b.id,false).ok,true);assert.equal(g.defense131.configureGate(b.id,true).ok,true);assert.deepEqual(g.resources,paid);});
test('gate policy: commander, workers, zombies and vehicles prevent occupied closure',()=>{const g=fresh(),b=add(g);assert.equal(g.defense131.configureGate(b.id).ok,true);g.phase='warning';g.player.x=b.x;g.player.y=b.y;advance(g,3);assert.equal(b.gateMode,'auto');standAt(g,g.player,b);const worker=person(g,'worker',b);worker.x=b.x;worker.y=b.y;advance(g,3);assert.equal(b.gateMode,'auto');standAt(g,worker,b);const z=zombie(g,b.x,b.y);advance(g,3);assert.equal(b.gateMode,'auto');z.dead=true;const original=g.expeditions;g.expeditions={...original,entity:()=>({health:100,x:b.x,y:b.y,radius:20})};advance(g,3);assert.equal(b.gateMode,'auto');g.expeditions=original;advance(g,.1);assert.equal(b.gateMode,'closed');});
test('gate policy: manual mode takes priority through current phase, no pause or overlay ticking',()=>{const g=fresh(),b=add(g);g.defense131.configureGate(b.id);g.phase='warning';advance(g,2.1);assert.equal(g.setGateMode('open',b),true);advance(g,8);assert.equal(b.gateMode,'open');g.phase='assault';g.paused=true;advance(g,5);assert.equal(b.gateMode,'open');g.paused=false;g.activeOverlay={};advance(g,5);assert.equal(b.gateMode,'open');g.activeOverlay=null;advance(g,2.1);assert.equal(b.gateMode,'closed');});
test('gate policy: autonomous during expedition and player incapacitation, offline powered gate waits',()=>{const g=fresh(),b=add(g,'armoredGate');g.defense131.configureGate(b.id);g.player.x=2048;g.player.y=20;assert.equal(g.frontier.enter('north'),true);g.player.dead=true;g.player.health=0;g.phase='warning';b.powered=false;advance(g,3);assert.equal(b.gateMode,'auto');b.powered=true;advance(g,.1);assert.equal(b.gateMode,'closed');});
test('maintenance contract: physical engineer consumes prepaid material, common stock unchanged',()=>{const g=fresh(),b=add(g,'woodWall');b.health=b.maxHealth*.4;const u=person(g,'engineer',b);assert.equal(g.defense131.startMaintenance(b.id).ok,true);const stock={...g.resources},remaining=post(g,b).maintenance.scrap,hp=b.health;assert.equal(g.engineerTargetValid(u,b),true);assert.ok(g.repairWithEngineer(u,b,.1)>0);assert.ok(b.health>hp);assert.ok(post(g,b).maintenance.scrap<remaining);assert.deepEqual(g.resources,stock);g.resources.scrap=g.resources.wood=0;assert.equal(g.engineerTargetValid(u,b),true);assert.ok(g.repairWithEngineer(u,b,.1)>0);});
test('maintenance contract: no instant healing; stops at 90 percent, remote and paused work rejected',()=>{const g=fresh(),b=add(g,'woodWall');b.health=b.maxHealth*.89;const u=person(g,'engineer',b),hp=b.health;g.defense131.startMaintenance(b.id);assert.equal(b.health,hp);u.x=100;u.y=100;assert.equal(g.repairWithEngineer(u,b,.1),0);standAt(g,u,b);g.paused=true;assert.equal(g.repairWithEngineer(u,b,.1),0);g.paused=false;for(let i=0;i<200;i++)g.repairWithEngineer(u,b,.1);assert.ok(Math.abs(b.health-b.maxHealth*.9)<1e-8);assert.equal(g.engineerTargetValid(u,b),false);});
test('maintenance contract: real specialist update moves and works through engine, finite stock lasts no longer than paid',()=>{const g=fresh(),b=add(g,'woodWall');b.health=40;const u=person(g,'engineer',b);g.defense131.startMaintenance(b.id);g.resources.scrap=g.resources.wood=0;const hp=b.health,initial=post(g,b).maintenance.scrap;for(let i=0;i<500;i++)g.updateUnits(.04);assert.ok(b.health>hp);assert.ok(post(g,b).maintenance.scrap<initial);assert.ok(b.health<=b.maxHealth*.9+1e-8);assert.equal(g.resources.scrap,0);assert.equal(g.resources.wood,0);assert.ok(u.health>0);});
test('maintenance contract: remaining material recovery respects capacity and cannot be claimed twice',()=>{const g=fresh(),b=add(g,'woodWall');g.defense131.startMaintenance(b.id);const paid=post(g,b).maintenance;g.resources.scrap=g.storage-1;g.resources.wood=g.storage;g.resources.stone=g.storage;assert.equal(g.defense131.recoverMaintenance(b.id).ok,true);assert.equal(g.resources.scrap,g.storage);assert.equal(post(g,b).maintenance.scrap,paid.scrap-1);assert.equal(g.defense131.recoverMaintenance(b.id).ok,false);g.resources.scrap=g.resources.wood=g.resources.stone=0;assert.equal(g.defense131.recoverMaintenance(b.id).ok,true);assert.equal(post(g,b),undefined);assert.equal(g.defense131.recoverMaintenance(b.id).ok,false);});
test('worksite tooling: costs do not construct and passive or player work gets no boost',()=>{const g=fresh(),b=add(g,'warehouse',72,72,.1),before=b.progress;assert.equal(g.defense131.equipWorksite(b.id).ok,true);assert.equal(b.progress,before);const budget=post(g,b).work;b.work(.1);assert.ok(Math.abs(b.progress-before-.1/b.def.buildTime)<1e-8);assert.equal(post(g,b).work,budget);g.updateBuildings(.04);assert.equal(post(g,b).work,budget);});
test('worksite tooling: live workers get bounded boost; suspension and retreat preserve reserve',()=>{const g=fresh(),b=add(g,'warehouse',72,72,.1),u=person(g,'worker',b);g.defense131.equipWorksite(b.id);const before=b.progress,budget=post(g,b).work;u.state='build';u.targetBuilding=b.id;u.think=10;g.updateUnits(.04);assert.ok(b.progress-before>.04*1.05/b.def.buildTime);assert.ok(post(g,b).work<budget);assert.equal(g.citadel.suspend(b.id,true),true);const saved=post(g,b).work,progress=b.progress;for(let i=0;i<20;i++)g.updateUnits(.04);assert.equal(b.progress,progress);assert.equal(post(g,b).work,saved);g.citadel.suspend(b.id,false);g.setWorkerOrder('retreat');g.updateUnits(.04);assert.equal(post(g,b).work,saved);});
test('worksite tooling: completing a prepared occupied gate still waits for clear footprint',()=>{const g=fresh(),b=add(g,'gate',72,72,.997),u=person(g,'worker',b);b.gateMode='closed';g.defense131.equipWorksite(b.id);g.player.x=b.x;g.player.y=b.y;u.state='build';u.targetBuilding=b.id;u.think=10;g.updateUnits(.04);assert.equal(b.completed,false);assert.equal(b.completionBlocked,true);standAt(g,g.player,b);for(let i=0;i<20;i++)g.updateUnits(.04);assert.equal(b.completed,true);assert.equal(post(g,b),undefined);});
test('fire sector: no enemy outside arc consumes rounds; farther valid target selected',()=>{const g=fresh(),b=add(g,'watchtower');g.defense131.setArc(b.id,0);const west=zombie(g,b.x-40,b.y),east=zombie(g,b.x+100,b.y),ammo=g.resources.ammo;assert.equal(g.nightwatch.target(b.x,b.y,b.def.range),east);g.updateBuildings(.04);assert.equal(g.resources.ammo,ammo-1);east.dead=true;g.rebuildBuckets();b.fireCooldown=0;assert.equal(g.nightwatch.target(b.x,b.y,b.def.range),null);g.updateBuildings(.04);assert.equal(g.resources.ammo,ammo-1);assert.equal(west.dead,false);});
test('fire sector: caisson uses same arc; manual direct fire stays manually aimed',()=>{const g=fresh(),b=add(g,'watchtower');g.defense131.setArc(b.id,0);g.fortificationPack.equip('ammo',b.id);g.resources.ammo=0;zombie(g,b.x-70,b.y);g.updateBuildings(.04);assert.equal(g.fortificationPack.snapshot().fittings.find(f=>f.id===b.id).ammo,24);zombie(g,b.x+100,b.y);g.updateBuildings(.04);assert.equal(g.fortificationPack.snapshot().fittings.find(f=>f.id===b.id).ammo,23);const n=g.projectiles.length;g.fireFriendly(b.x,b.y,Math.PI,10,100,'#fff');assert.equal(g.projectiles.length,n+1);});
test('fire sector: blackout never grants visibility, reorienting costs nothing extra',()=>{const g=fresh(),b=add(g,'watchtower');g.defense131.setArc(b.id,0);const stock={...g.resources};g.defense131.setArc(b.id,1);assert.deepEqual(g.resources,stock);g.phase='assault';g.wave=4;const z=zombie(g,b.x,b.y+100);assert.equal(g.nightwatch.isBlackout(),true);assert.equal(g.nightwatch.target(b.x,b.y,b.def.range),null);g.phase='calm';assert.equal(g.nightwatch.target(b.x,b.y,b.def.range),z);z.dead=true;g.rebuildBuckets();assert.equal(g.defense131.setArc(b.id,null).ok,true);});
test('preparations: dead, distant, regional and insufficient-stock commands are rejected without spending',()=>{const g=fresh(),b=add(g);g.resources.scrap=0;const stock={...g.resources};assert.equal(g.defense131.configureGate(b.id).ok,false);assert.deepEqual(g.resources,stock);g.resources.scrap=100;g.player.dead=true;assert.equal(g.defense131.configureGate(b.id).ok,false);g.player.dead=false;g.player.x=100;g.player.y=100;assert.equal(g.defense131.configureGate(b.id).ok,false);g.player.x=2048;g.player.y=20;assert.equal(g.frontier.enter('north'),true);assert.equal(g.defense131.configureGate(b.id).ok,false);});
test('preparations: save roundtrip retains exact finite budgets; malformed references reject transactionally',()=>{const g=fresh(),gate=add(g);g.defense131.configureGate(gate.id);g.defense131.startMaintenance(gate.id);const tower=add(g,'watchtower',80,72);g.defense131.setArc(tower.id,3);const work=add(g,'warehouse',88,72,.2);g.defense131.equipWorksite(work.id);const raw=g.serialize(),before=g.defense131.snapshot();g.restoreSave(raw);assert.deepEqual(g.defense131.snapshot(),before);assert.deepEqual(g.resources,raw.resources);const bad=g.serialize(),world=g.world;bad.expansions127.modules.defense131.posts[0].id=123456;assert.throws(()=>g.restoreSave(bad),/support absent/);assert.equal(g.world,world);const huge=g.serialize();huge.expansions127.modules.defense131.posts[2].work=999;assert.throws(()=>g.restoreSave(huge),/poste invalide/);assert.equal(g.world,world);});
test('preparations: destroyed supports lose reserves, new campaign has no inherited policy or budgets',()=>{const g=fresh(),b=add(g,'watchtower');g.defense131.startMaintenance(b.id);const stock={...g.resources};g.destroyBuilding(b);assert.deepEqual(g.defense131.snapshot(),D.initial());assert.deepEqual(g.resources,stock);const gate=add(g);g.defense131.configureGate(gate.id);g.startNew('standard','123');assert.deepEqual(g.defense131.snapshot(),D.initial());});
test('preparations: unknown fields, duplicate posts and reserve corruption are rejected',()=>{const p={id:42,gate:null,maintenance:null,work:1,arc:null};assert.throws(()=>D.normalize({version:1,posts:[p,p]}),/poste invalide/);assert.throws(()=>D.normalize({version:1,posts:[{...p,free:true}]}),/poste invalide/);assert.throws(()=>D.normalize({version:1,posts:[{...p,maintenance:{scrap:100,wood:0,stone:0}}]}),/matériaux/);assert.throws(()=>D.normalize({version:1,posts:[{...p,work:NaN}]}),/poste invalide/);});
test('preparations: concurrent physical repair prevents equipment and recovery transactions',()=>{const g=fresh(),b=add(g,'watchtower');g.defense131.startMaintenance(b.id);g.fortificationPack.equip('repair',b.id);b.health-=50;assert.equal(g.fortificationPack.startRepair(b.id).ok,true);const before={...g.resources},budget=post(g,b).maintenance;assert.equal(g.defense131.setArc(b.id,0).ok,false);assert.equal(g.defense131.recoverMaintenance(b.id).ok,false);assert.deepEqual(g.resources,before);assert.deepEqual(post(g,b).maintenance,budget);g.fortificationPack.stop();assert.equal(g.defense131.setArc(b.id,0).ok,true);});
test('maintenance contract: repeated late-game damage exhausts paid stock without switching to common reserve',()=>{const g=fresh(),b=add(g,'woodWall'),u=person(g,'engineer',b);g.defense131.startMaintenance(b.id);const stock={...g.resources},rate=g.engineerRepairRates(b),limit=Math.min(...Object.entries(rate).filter(([,v])=>v>0).map(([k,v])=>C.Defense131Rules.maintenanceCost[k]/v));let repaired=0;for(let i=0;i<20000;i++){b.health=b.maxHealth*.3;repaired+=g.repairWithEngineer(u,b,.1);}assert.ok(Math.abs(repaired-limit)<1e-6);assert.deepEqual(g.resources,stock);b.health=b.maxHealth*.3;assert.equal(g.repairWithEngineer(u,b,.1),0);assert.equal(g.engineerTargetValid(u,b),false);});
test('preparations: invalid API types and registry overflow cannot commit',()=>{const g=fresh(),b=add(g),stock={...g.resources};assert.equal(g.defense131.configureGate(b.id,false).ok,false);assert.equal(g.defense131.check('unknown',b.id).ok,false);assert.equal(g.defense131.setArc(b.id,NaN).ok,false);assert.deepEqual(g.resources,stock);assert.throws(()=>D.normalize({version:1,posts:Array.from({length:C.Defense131Rules.maxPosts+1},(_,i)=>({id:i+1,gate:null,maintenance:null,work:1,arc:null}))}),/registre invalide/);});
