'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs'),C=require('../src/core.js'),G=require('../src/frontier-geometry.js'),W=require('../src/frontier-world.js'),V=require('../src/frontier-survey.js'),Save=require('../src/save.js');const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function step(g,n){for(let i=0;i<n;i++){g.update(.04);g.input.pressed.clear();}}
function field(g,id='light-grid'){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const w=g.frontier.world(),t=g.essentials.targets().find(t=>t.id===id),p=w.pois.find(p=>p.id===t.poi),o=t.object;let a;for(let y=o.y-1.2;y<=o.y+o.h+1.2&&!a;y+=.3)for(let x=o.x-1.2;x<=o.x+o.w+1.2&&!a;x+=.3){const q=G.global(p,x,y),f={...g.frontier.snapshot(),...q,inside:p.id,z:0};if(!w.blocked(q.x,q.y,.32)&&V.targets(w,f,f.taken,1.6).some(b=>b.id===o.id))a=q;}assert.ok(a,'accès de service réel');const d=g.serialize();Object.assign(d.frontier,{...a,inside:p.id,z:0,seen:[p.id]});for(let i=0;i<1+G.hash(w.seed,p.id,'threat')%4;i++)d.frontier.enemies[p.id+':e'+i]=0;d.frontier.kills=Object.values(d.frontier.enemies).filter(h=>h===0).length;g.restoreSave(d);return t;}
function unlocked(g,k){const t=g.essentials.targets().find(t=>t.family===k),d=g.serialize();d.frontier.seen=[t.poi];d.essentials.jobs[t.id]={stage:'delivered'};d.essentials.stock[k]=2;g.restoreSave(d);standAt(g,g.player,g.core());return t;}
test('services : douze objectifs uniques sur les trois générations',()=>{for(const generation of [1,2,3])for(const seed of [17117,42,903145]){const ts=C.Essentials.targets(W.create(seed,generation));assert.equal(ts.length,12);assert.equal(new Set(ts.map(t=>t.poi)).size,12);}});
test('services : migration sans mission gratuite ni kit offert',()=>{const{game:g}=fresh(),d=g.serialize();for(let v=1;v<=18;v++){const q=copy(d);q.version=v;delete q.essentials;const r=Save.validate(q);assert.equal(r.version,20);assert.deepEqual(r.resources,d.resources);assert.deepEqual(r.essentials,C.Essentials.initial());}});
test('services : relevé et récupération au meuble, chronomètres et coûts',()=>{const{game:g}=fresh(),t=field(g);assert.equal(g.essentials.begin('recover',t.id).ok,false);assert.ok(g.essentials.begin('inspect',t.id).ok);step(g,99);assert.equal(g.essentials.snapshot().jobs[t.id],undefined);step(g,1);assert.equal(g.essentials.snapshot().jobs[t.id].stage,'surveyed');g.player.carry.scrap=3;assert.ok(g.essentials.begin('recover',t.id).ok);step(g,199);assert.equal(g.player.carry.scrap,3);step(g,1);assert.equal(g.player.carry.scrap,0);assert.equal(g.essentials.snapshot().jobs[t.id].stage,'player');assert.equal(g.essentials.begin('recover',t.id).ok,false);});
test('services : bouger annule sans coût et sans extraction',()=>{const{game:g}=fresh(),t=field(g);g.essentials.begin('inspect',t.id);g.input.keys.add('KeyD');step(g,1);g.input.keys.clear();step(g,150);assert.equal(g.essentials.snapshot().jobs[t.id],undefined);assert.equal(g.essentials.busy(),false);});
test('services : nuit et mauvaise position refusées',()=>{const{game:g}=fresh(),t=field(g);g.phase='assault';assert.equal(g.essentials.begin('inspect',t.id).ok,false);g.phase='calm';g.player.reload=1;assert.equal(g.essentials.begin('inspect',t.id).ok,false);const d=g.serialize();d.frontier.x+=90;d.frontier.inside=null;g.restoreSave(d);assert.equal(g.essentials.begin('inspect',t.id).ok,false);});
test('services : la consultation ne change pas la sauvegarde',()=>{const{game:g}=fresh();const a=g.serialize();delete a.timestamp;for(let i=0;i<3;i++)g.essentials.overview();const b=g.serialize();delete b.timestamp;assert.deepEqual(b,a);});
test('services : la pause et la reprise ne terminent pas un travail gratuit',()=>{const{game:g}=fresh(),t=field(g);g.essentials.begin('inspect',t.id);step(g,40);g.paused=true;step(g,200);assert.ok(g.essentials.busy());g.paused=false;g.save(false);g.load();assert.equal(g.essentials.busy(),false);step(g,100);assert.equal(g.essentials.snapshot().jobs[t.id],undefined);});
test('portage : sauvegarde du module et vitesse réduite sans sprint',()=>{const{game:g}=fresh(),t=field(g),d=g.serialize();d.essentials.jobs[t.id]={stage:'player'};d.frontier.x=4180;d.frontier.y=4096;d.frontier.inside=null;g.restoreSave(d);assert.ok(g.save(false));assert.ok(g.load());const x=g.frontier.snapshot().x;g.input.keys.add('KeyD');g.input.keys.add('ShiftLeft');step(g,25);g.input.keys.clear();assert.ok(Math.abs(g.frontier.snapshot().x-x-3.5*.78)<.001);assert.ok(g.essentials.carrying());});
test('livraison : présence au dépôt, récompense unique, recette permanente',()=>{const{game:g}=fresh(),t=field(g),d=g.serialize();d.essentials.jobs[t.id]={stage:'player'};g.restoreSave(d);assert.equal(g.essentials.deliver().ok,false);const q=g.serialize();q.frontier.active=false;q.frontier.inside=null;q.frontier.anchor=null;g.restoreSave(q);standAt(g,g.player,g.core());assert.ok(g.essentials.deliver().ok);assert.equal(g.essentials.snapshot().stock.light,2);assert.equal(g.essentials.deliver().ok,false);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.essentials.snapshot().stock.light,2);assert.equal(g.essentials.snapshot().jobs[t.id].stage,'delivered');});
test('kits : assemblage payé au dépôt puis équipement, plafond de huit',()=>{const{game:g}=fresh();unlocked(g,'light');g.resources.scrap=50;g.resources.fuel=30;assert.ok(g.essentials.begin('craft','light').ok);step(g,124);assert.equal(g.essentials.snapshot().stock.light,2);step(g,1);assert.equal(g.essentials.snapshot().stock.light,3);assert.equal(g.resources.scrap,45);assert.equal(g.resources.fuel,28);assert.ok(g.essentials.transferKit('light','equip').ok);assert.equal(g.essentials.snapshot().belt.light,1);assert.equal(g.essentials.snapshot().stock.light,2);});
test('kits : pas de recette gratuite, de consommation à distance ou de quantité négative',()=>{const{game:g}=fresh();assert.equal(g.essentials.begin('craft','light').ok,false);assert.equal(g.essentials.use('light').ok,false);assert.equal(g.essentials.transferKit('light','equip').ok,false);assert.equal(g.essentials.transferKit('__proto__','equip').ok,false);});
test('lumière : éclaire pour les défenseurs et expire sans réinitialisation',()=>{const{game:g}=fresh();unlocked(g,'light');g.essentials.transferKit('light','equip');g.wave=4;g.phase='assault';assert.ok(g.essentials.use('light').ok);assert.equal(g.essentials.snapshot().belt.light,0);assert.ok(g.nightwatch.sources(false).some(l=>String(l.id).startsWith('kit-')));step(g,100);const left=g.essentials.snapshot().effects[0].left;assert.ok(left<57);g.save(false);g.load();assert.ok(Math.abs(g.essentials.snapshot().effects[0].left-left)<.00001);step(g,1500);assert.equal(g.essentials.snapshot().effects.length,0);});
test('soins : un kit ne ressuscite pas et ne dépasse pas le budget de soin',()=>{const{game:g}=fresh();unlocked(g,'aid');g.essentials.transferKit('aid','equip');g.player.health=70;const before=g.resources.medicine;assert.ok(g.essentials.use('aid').ok);assert.equal(g.player.health,100);assert.equal(g.resources.medicine,before);assert.equal(g.essentials.snapshot().belt.aid,0);g.essentials.transferKit('aid','equip');assert.equal(g.essentials.use('aid').ok,false);assert.equal(g.essentials.snapshot().belt.aid,1);});
test('étai : réparation physique de la porte sans dépasser son maximum',()=>{const{game:g}=fresh();unlocked(g,'brace');g.essentials.transferKit('brace','equip');const b=new(g.core().constructor)(g.nextId++,'gate',72,62,0,1);g.world.add(b);b.health=b.maxHealth-100;standAt(g,g.player,b);g.phase='assault';assert.ok(g.essentials.use('brace').ok);assert.equal(b.health,b.maxHealth);assert.equal(g.essentials.snapshot().belt.brace,0);});
test('diversion : réservée à la région, pas un aimant sur la horde locale',()=>{const{game:g}=fresh();unlocked(g,'decoy');g.essentials.transferKit('decoy','equip');assert.equal(g.essentials.use('decoy').ok,false);assert.equal(g.essentials.snapshot().belt.decoy,1);g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());assert.ok(g.essentials.use('decoy').ok);assert.equal(g.essentials.snapshot().effects[0].kind,'decoy');step(g,451);assert.equal(g.essentials.snapshot().effects.length,0);});
test('lumière : pas de torche fantôme du commandant parti en région',()=>{const{game:g}=fresh();g.player.x=4058;g.player.y=2048;g.frontier.enter();assert.ok(!g.nightwatch.sources(false).some(s=>s.id==='player'||s.id==='ambient-player'));});
test('sécurité du registre : clés détournées et double portage refusés',()=>{const s=C.Essentials.initial();s.jobs=JSON.parse('{"__proto__":{"stage":"surveyed"}}');assert.throws(()=>C.Essentials.normalize(s));s.jobs={'light-grid':{stage:'player'},'light-exit':{stage:'player'}};assert.throws(()=>C.Essentials.normalize(s));});
test('limites : ceinture globale, recette et dispositifs contrôlés',()=>{const{game:g}=fresh(),t=unlocked(g,'light'),d=g.serialize();d.essentials.belt.light=8;d.essentials.belt.aid=1;assert.throws(()=>g.restoreSave(d));const q=g.serialize();q.essentials.stock.aid=1;assert.throws(()=>g.restoreSave(q));});
test('mort : le module porté tombe au sol et ne se duplique pas au retour',()=>{const{game:g}=fresh(),t=field(g),d=g.serialize();d.essentials.jobs[t.id]={stage:'player'};g.restoreSave(d);g.player.dead=true;g.player.health=0;step(g,1);const j=g.essentials.snapshot().jobs[t.id];assert.equal(j.stage,'ground');assert.equal(j.point.domain,'region');assert.equal(g.essentials.takeGround(t.id).ok,false);g.player.dead=false;g.player.health=80;assert.ok(g.essentials.takeGround(t.id).ok);assert.equal(g.essentials.takeGround(t.id).ok,false);});
test('portage véhicule : charger, reprendre et perdre le râtelier sans duplication',()=>{const{game:g}=fresh(),b=new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1);g.world.add(b);g.refreshMetrics(true);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const t=g.essentials.targets()[0],d=g.serialize();d.frontier.seen=[t.poi];d.essentials.jobs[t.id]={stage:'player'};g.restoreSave(d);Object.assign(g.player,{x:g.expeditions.car().x+40,y:g.expeditions.car().y});assert.ok(g.essentials.movePack('load').ok);assert.equal(g.essentials.snapshot().jobs[t.id].carId,g.expeditions.car().id);assert.ok(g.save(false));assert.ok(g.load());assert.ok(g.essentials.movePack('take').ok);assert.equal(g.essentials.movePack('take').ok,false);assert.ok(g.essentials.movePack('load').ok);g.expeditions.car().health=0;step(g,1);assert.equal(g.essentials.snapshot().jobs[t.id].stage,'ground');});
test('missions : les douze interventions peuvent être effectuées et reprises',()=>{for(const definition of C.Essentials.content.jobs){const{game:g}=fresh(),t=field(g,definition.id);g.essentials.begin('inspect',t.id);step(g,100);for(const[k,n]of Object.entries(C.Essentials.RULES.workCost[t.family]))g.player.carry[k]=n;assert.ok(g.essentials.begin('recover',t.id).ok,t.id);step(g,C.Essentials.RULES.workSeconds[t.family]*25);assert.equal(g.essentials.snapshot().jobs[t.id].stage,'player',t.id);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.essentials.snapshot().jobs[t.id].stage,'player');}});
test('diversion : les infectés mémorisent le dispositif plutôt que sa destination suivante',()=>{const{game:g}=fresh();unlocked(g,'decoy');g.essentials.transferKit('decoy','equip');g.player.x=4058;g.player.y=2048;g.frontier.enter();const w=g.frontier.world(),p=w.pois.find(p=>p.type==='warehouse'),d=g.serialize(),q=G.global(p,p.w/2,6);Object.assign(d.frontier,{x:q.x,y:q.y,inside:p.id,seen:[...d.frontier.seen,p.id]});g.restoreSave(d);step(g,1);const e=g.frontier.overview().enemies.find(e=>e.poi===p.id);assert.ok(e);assert.ok(g.essentials.use('decoy').ok);step(g,1);const signal=g.essentials.snapshot().effects[0];assert.equal(e.mode,'investigate');assert.ok(Math.hypot(e.gx-signal.x,e.gy-signal.y)<.001);});
