'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),Save=require('../src/save.js');
const clone=v=>JSON.parse(JSON.stringify(v));
function fresh(){const{game:g}=boot127();g.startNew('standard','17117');g.phaseTime=9999;g.units=[];return g;}
function step(g,seconds,safety=false){for(let i=0;i<Math.ceil(seconds/.04);i++){if(safety)for(const z of g.zombies)if(!z.dead&&(C.dist(z,g.core())<560||C.dist(z,g.player)<320))g.killZombie(z,false);g.update(.04);g.input.pressed.clear();}}
function supplies(g){g.player.carry=C.makeBag({wood:20,scrap:15,food:10,fuel:5,medicine:2});}
function openGround(g){for(let y=2300;y<3000;y+=64)for(let x=2300;x<3000;x+=64){g.player.x=x;g.player.y=y;if(g.survivalPack.preview('camp').ok)return;}assert.fail('Sol libre de bivouac');}
test('1.27 integration: all five packs register and migration preserves existing lighting and stocks',()=>{const g=fresh();assert.deepEqual(g.expansions.entries().map(d=>d.id),['exploration','survival','fortification','companions','campaign']);const raw=clone(g.serialize());raw.nightGear={version:1,serial:2,devices:[{id:1,kind:'torch',location:'belt',on:false,used:false,left:180}]};delete raw.expansions127;g.restoreSave(raw);assert.deepEqual(g.resources,raw.resources);assert.deepEqual(g.nightGear.snapshot(),raw.nightGear);assert.ok(g.save(false));const before=g.expansions.snapshot();assert.ok(g.load());assert.deepEqual(g.expansions.snapshot(),before);});
test('1.27 integration: task exclusivity spans new operations, lights and essential workshop',()=>{const g=fresh();supplies(g);openGround(g);const before={...g.player.carry};assert.ok(g.survivalPack.begin('camp').ok);assert.equal(g.explorationPack.placeCache().ok,false);assert.equal(g.nightGear.craft('torch').ok,false);assert.equal(g.expansions.busy('exploration'),true);assert.equal(g.expansions.busy('survival'),false);step(g,C.SurvivalPackRules.camp.seconds);assert.equal(g.survivalPack.snapshot().camps.length,1);assert.equal(g.player.carry.wood,before.wood-C.SurvivalPackRules.camp.cost.wood);assert.equal(g.expansions.busy(),false);assert.ok(g.nightGear.craft('torch').ok);assert.equal(g.survivalPack.begin('cover').ok,false);g.nightGear.cancel();assert.ok(g.survivalPack.begin('cover').ok);step(g,C.SurvivalPackRules.cover.seconds);assert.ok(g.survivalPack.snapshot().camps[0].cover>0);});
test('1.27 integration: corrupt module cannot partially replace another module or world',()=>{const g=fresh();const mutations=[m=>m.exploration.serial=NaN,m=>m.survival.meal.left=-1,m=>m.fortification.fittings=[{id:123456,ammo:1,repair:0,net:0,regulator:false}],m=>m.companions.trained=['samir','samir'],m=>m.campaign.lastStarted.defense=999];for(const mutate of mutations){const raw=clone(g.serialize()),world=g.world,before=clone(g.expansions.snapshot());mutate(raw.expansions127.modules);raw.resources.food=1;assert.throws(()=>g.restoreSave(raw));assert.equal(g.world,world);assert.notEqual(g.resources.food,1);assert.deepEqual(g.expansions.snapshot(),before);}});
test('1.27 integration: essential module and new ballot share one carrying slot, including imports',()=>{const g=fresh(),n=g.world.nodes.find(n=>n.type==='wood'&&!n.depleted&&n.amount>60);standAt(g,g.player,n);g.player.carry.food=4;assert.ok(g.explorationPack.survey(n.id).ok);step(g,C.ExplorePackRules.surveySeconds);assert.ok(g.explorationPack.extract(n.id).ok);step(g,C.ExplorePackRules.extractSeconds);assert.ok(g.explorationPack.carrying());const raw=clone(g.serialize()),target=g.essentials.targets()[0];raw.frontier.seen=[...new Set([...raw.frontier.seen,target.poi])];raw.essentials.jobs[target.id]={stage:'player'};const world=g.world;assert.throws(()=>g.restoreSave(raw),/seul chargement/);assert.equal(g.world,world);assert.ok(g.explorationPack.carrying());});
test('1.27 integration: multi-pack states survive eight checkpoints, timed effects expire and pause is inert',()=>{const g=fresh();supplies(g);openGround(g);assert.ok(g.survivalPack.begin('camp').ok);step(g,C.SurvivalPackRules.camp.seconds);const camp=clone(g.survivalPack.snapshot().camps[0]);g.player.x+=120;assert.ok(g.explorationPack.markRoute().ok);step(g,C.ExplorePackRules.markerSeconds);g.player.x+=120;let q=g.explorationPack.preview('cache');for(let y=2350;y<3200&&!q.ok;y+=64)for(let x=2350;x<3200&&!q.ok;x+=64){g.player.x=x;g.player.y=y;q=g.explorationPack.preview('cache');}assert.ok(q.ok,q.reason);assert.ok(g.explorationPack.placeCache().ok);step(g,C.ExplorePackRules.cacheSeconds);const cache=g.explorationPack.snapshot().caches[0];assert.ok(g.explorationPack.cacheTransfer(cache.id,'store').ok);
 standAt(g,g.player,g.core());assert.ok(g.campaignPack.start('defense').ok);const core=g.core();assert.ok(g.fortificationPack.equip('repair',core.id).ok);const before=clone(g.expansions.snapshot());g.paused=true;step(g,3);assert.deepEqual(g.expansions.snapshot(),before);g.paused=false;
 for(let i=0;i<8;i++){step(g,80,true);const saved=Save.validate(g.serialize());assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.expansions.snapshot(),saved.expansions127);assert.ok(C.bagTotal(g.explorationPack.snapshot().caches[0].stock)>0);for(const n of Object.values(g.resources))assert.ok(Number.isFinite(n)&&n>=0);}
 assert.equal(g.survivalPack.snapshot().camps.length,0);assert.equal(g.explorationPack.snapshot().markers.length,1);assert.equal(g.fortificationPack.snapshot().fittings[0].repair,C.FortificationPackRules.repairCapacity);assert.ok(['defending','ready'].includes(g.campaignPack.snapshot().active.stage));assert.ok(camp.left<=600);assert.ok(g.elapsed>640);
});

test('1.27 integration: rejected new-game inputs preserve the entire active equipment state',()=>{const g=fresh(),raw=clone(g.serialize());raw.nightGear={version:1,serial:2,devices:[{id:1,kind:'torch',location:'belt',on:false,used:false,left:180}]};g.restoreSave(raw);const before=clone(g.serialize()),world=g.world;for(const [seed,scenario] of [['invalid-seed','classic'],['42','bad-scenario']]){assert.equal(g.startNew('standard',seed,scenario),false);assert.equal(g.world,world);assert.deepEqual(g.expansions.snapshot(),before.expansions127);assert.deepEqual(g.nightGear.snapshot(),before.nightGear);}});

test('1.27 performance: compatible restore retains geometry, changed seed and generation invalidate it',()=>{const g=fresh(),w=g.frontier.world(),raw=clone(g.serialize());g.restoreSave(raw);assert.equal(g.frontier.world(),w);g.update(.04);assert.equal(g.frontier.world(),w);const old=clone(g.serialize());old.frontier.generation=3;old.exploration125=undefined;g.restoreSave(old);assert.notEqual(g.frontier.world(),w);assert.equal(g.frontier.world().generation,3);g.startNew('standard','42');assert.notEqual(g.frontier.world(),w);assert.equal(g.frontier.world().seed,42);});

test('1.27 performance: reused geometry still follows restored destruction and repaired walls',()=>{const g=fresh(),w=g.frontier.world(),G=require('../src/frontier-geometry.js'),p=w.pois.find(p=>p.type==='house'),plan=w.plan(p,0);const wall=plan.walls.find(b=>!plan.objects.some(o=>G.circleRect(b.x+b.w/2,b.y+b.h/2,.01,o))),point=G.global(p,wall.x+wall.w/2,wall.y+wall.h/2);assert.ok(w.blocked(point.x,point.y,.01,0,p.id));const raw=clone(g.serialize());raw.worldEvolution.structures[p.id]=0;g.restoreSave(raw);assert.equal(g.frontier.world(),w);assert.equal(w.blocked(point.x,point.y,.01,0,p.id),false);raw.worldEvolution.structures[p.id]=1;g.restoreSave(raw);assert.equal(g.frontier.world(),w);assert.equal(w.blocked(point.x,point.y,.01,0,p.id),true);});
