'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs');
const Kit=require('../src/expansion-kit.js');
function fresh(){const {game:g}=bootGame();Kit.install(g);let value=0;const d={id:'exploration',title:'Test',overview:()=>({}),actions:()=>[],validate:raw=>{if(raw===undefined)return{value:0};if(!raw||!Number.isSafeInteger(raw.value)||raw.value<0||raw.value>100)throw Error('compteur invalide');return{value:raw.value};},snapshot:()=>({value}),restore:raw=>{value=raw.value;},reset:()=>{value=0;}};g.expansions.register(d);g.startNew('standard','17117');return{g,d,set:n=>{value=n;},value:()=>value};}
test('registry: descriptor contract and duplicate IDs fail before registration',()=>{const {g,d}=fresh();assert.equal(Kit.install(g),g.expansions);assert.equal(g.expansions.entries().length,1);assert.throws(()=>g.expansions.register(d));assert.throws(()=>g.expansions.register({...d,id:'__proto__'}));assert.equal(g.expansions.entries().length,1);});
test('registry: round trip and isolated snapshots',()=>{const {g,set,value}=fresh();set(12);const d=g.serialize();d.expansions127.modules.exploration.value=22;assert.equal(value(),12);g.restoreSave(d);assert.equal(value(),22);assert.ok(g.save(false));set(9);assert.ok(g.load());assert.equal(value(),22);});
test('registry: malformed module or unknown key fails without mutating active world',()=>{const {g,set,value}=fresh();set(19);for(const bad of [null,{version:2,modules:{}},{version:1,modules:[]},{version:1,modules:{unknown:{}}},{version:1,modules:{exploration:{value:Infinity}}},{version:1,modules:{},extra:1}]){const raw=JSON.parse(JSON.stringify(g.serialize())),world=g.world,resources={...g.resources};raw.expansions127=bad;raw.resources.wood=2;assert.throws(()=>g.restoreSave(raw));assert.equal(g.world,world);assert.equal(value(),19);assert.deepEqual(g.resources,resources);}});
test('registry: legacy save migrates empty without reward',()=>{const {g,set,value}=fresh();set(22);const old=g.serialize(),r={...old.resources};delete old.expansions127;g.restoreSave(old);assert.equal(value(),0);assert.deepEqual(g.resources,r);});
test('registry: valid new run resets before first save, rejected seed keeps state',()=>{const {g,set,value}=fresh();set(22);const world=g.world;assert.equal(g.startNew('standard','invalid-seed'),false);assert.equal(value(),22);assert.equal(g.world,world);g.startNew('standard','17118');assert.equal(value(),0);assert.ok(g.load());assert.equal(value(),0);});
test('registry: actions permitted in command hub, blocked by death and other pause menus',()=>{const {g}=fresh();assert.ok(g.expansions.canAct());g.paused=true;assert.equal(g.expansions.canAct(),false);g.ui.commandModal={};g.activeOverlay=g.ui.commandModal;assert.ok(g.expansions.canAct());g.activeOverlay={};assert.equal(g.expansions.canAct(),false);g.paused=false;assert.equal(g.expansions.canAct(),false);g.activeOverlay=null;g.player.dead=true;assert.equal(g.expansions.canAct(),false);});
