'use strict';
const {standAt}=require('./helpers/physical-fixtures.cjs');
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/core.js'),Save=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs');
const clone=o=>JSON.parse(JSON.stringify(o)),near=(a,b,msg='')=>assert.ok(Math.abs(a-b)<1e-6,msg+': '+a+' / '+b);
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function put(g,t,x=72,y=65){const b=new(g.core().constructor)(g.nextId++,t,x,y,0,1);g.world.add(b);g.refreshMetrics(true);return b;}
function setup(){const e=fresh(),g=e.game;put(g,'expeditionOffice',72,65);put(g,'expeditionGarage',77,65);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=g.resources.food=300;g.resources.fuel=50;assert.ok(g.expeditions.buildCar().ok);const v=g.expeditions.car();g.player.x=v.x;g.player.y=v.y;return {...e,v};}
function atSite(g,id='roseraie'){const d={...C.Expeditions.BY_ID[id],renderSize:86,fixture:true},v=g.expeditions.car(),p=g.fieldcraft.service({x:d.x-140,y:d.y,radius:C.Expeditions.RULES.carRadius},d);assert.ok(p);Object.assign(v,p);v.driving=false;g.player.x=v.x;g.player.y=v.y;standAt(g,g.player,d);}
function work(g,n){g.input.keys.add('KeyE');for(let i=0;i<n;i++)g.expeditions.work(.25);g.input.keys.clear();}
function stable(g){const d=g.serialize();delete d.timestamp;delete d.wavePlan; /* Legacy restore rebuilds this derived plan. */ return JSON.stringify(d);}
test('expéditions: 12 destinations, 3 connues et aucun véhicule cadeau',()=>{const {game:g}=fresh(),s=g.expeditions.snapshot();assert.equal(s.sites.length,12);assert.equal(s.sites.filter(s=>s.known).length,3);assert.equal(s.vehicle,null);assert.equal(C.SAVE_VERSION,20);assert.equal(Object.keys(C.BUILDINGS).length,71)});
test('expéditions: les deux nouveaux bâtiments sont cachés avant le camp',()=>{const{game:g}=fresh();g.currentCategory='colony';g.refreshBuildMenu(true);assert.ok(!g.ui.buildList.children.some(b=>b.dataset.buildId==='expeditionOffice'));put(g,'house');g.refreshBuildMenu(true);assert.ok(g.ui.buildList.children.some(b=>b.dataset.buildId==='expeditionOffice'))});
test('véhicule: payé une fois, réservoir et coffre vides',()=>{const{game:g,v}=setup();assert.equal(g.resources.wood,260);assert.equal(g.resources.scrap,210);assert.equal(v.fuel,0);assert.equal(C.bagTotal(v.cargo),0);assert.equal(g.expeditions.buildCar().ok,false);assert.equal(g.expeditions.snapshot().stats.built,1)});
test('véhicule: refus sans garage ou argent, aucun prélèvement',()=>{const{game:g}=fresh(),before=clone(g.resources);assert.equal(g.expeditions.buildCar().ok,false);assert.deepEqual(g.resources,before)});
test('carburant: transfert au centre conserve la somme réserve-réservoir',()=>{const{game:g,v}=setup();const n=g.resources.fuel+v.fuel;assert.ok(g.expeditions.refuel().ok);assert.equal(v.fuel,24);near(g.resources.fuel+v.fuel,n);assert.equal(g.expeditions.refuel().ok,false)});
test('carburant: hors du centre seuls sac/coffre peuvent ravitailler',()=>{const{game:g,v}=setup();atSite(g);const stock=g.resources.fuel;assert.equal(g.expeditions.refuel().ok,false);g.player.carry.fuel=7;v.cargo.fuel=3;assert.ok(g.expeditions.refuel().ok);assert.equal(v.fuel,10);assert.equal(g.player.carry.fuel,0);assert.equal(v.cargo.fuel,0);assert.equal(g.resources.fuel,stock)});
test('troc: achat payé, stocks limités et sans recharge au chargement',()=>{const{game:g}=setup();const money=g.resources.scrap,fuel=g.resources.fuel;assert.ok(g.expeditions.buyFuel().ok);assert.equal(g.resources.scrap,money-20);assert.equal(g.resources.fuel,fuel+5);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.expeditions.snapshot().trade.remaining,25);for(let i=0;i<5;i++)assert.ok(g.expeditions.buyFuel().ok);assert.equal(g.expeditions.buyFuel().ok,false)});
test('départ: journée, voiture, réservoir et 3 rations requis',()=>{const{game:g}=setup();assert.equal(g.expeditions.select('station').ok,false);g.expeditions.refuel();const food=g.resources.food;assert.ok(g.expeditions.select('station').ok);assert.equal(g.resources.food,food-3);assert.ok(g.expeditions.select('roseraie').ok);assert.equal(g.resources.food,food-3);g.phase='warning';assert.equal(g.expeditions.select('station').ok,false)});
test('départ: destination inconnue jamais activée à distance',()=>{const{game:g}=setup();g.expeditions.refuel();assert.equal(g.expeditions.select('terminal').ok,false);assert.equal(g.expeditions.snapshot().active,null)});
test('conduite: carburant proportionnel au chemin, aucune consommation à l’arrêt',()=>{const{game:g,v}=setup();g.expeditions.refuel();assert.ok(g.expeditions.board().ok);const fuel=v.fuel;g.expeditions.drive(.1);assert.equal(v.fuel,fuel);g.input.keys.add('KeyD');for(let i=0;i<20;i++)g.expeditions.drive(.1);g.input.keys.clear();const stats=g.expeditions.snapshot().stats;assert.ok(stats.distance>0);near(fuel-v.fuel,stats.distance*.003);assert.equal(g.player.x,v.x)});
test('conduite: réservoir nul bloque le mouvement, sortie à pied possible',()=>{const{game:g,v}=setup();assert.ok(g.expeditions.board().ok);const x=v.x;g.input.keys.add('KeyD');for(let i=0;i<30;i++)g.expeditions.drive(.1);assert.equal(v.x,x);assert.ok(g.expeditions.board().ok);assert.equal(v.driving,false);assert.ok(g.player.radius<22)});
test('conduite: armes, travaux et récolte indisponibles au volant',()=>{const{game:g}=setup();g.expeditions.board();const n=g.projectiles.length;assert.equal(g.shootPlayer(),false);assert.equal(g.startReload(),false);assert.equal(g.placeOne('house',70,70),false);assert.equal(g.projectiles.length,n)});
test('conduite: porte verrouillée bloque, réouverture permet le passage',()=>{const{game:g,v}=setup();const door=put(g,'gate',63,57);v.x=door.x;v.y=door.bottom+35;g.player.x=v.x;g.player.y=v.y;g.expeditions.refuel();v.fuel=10;assert.ok(g.setGateMode('closed',door));g.expeditions.board();g.input.keys.add('KeyW');for(let i=0;i<25;i++)g.expeditions.drive(.1);assert.ok(v.y>door.bottom);assert.ok(g.setGateMode('open',door));for(let i=0;i<15;i++)g.expeditions.drive(.1);assert.ok(v.y<door.top)});
test('conduite: aucun chantier ni fermeture de porte sur le véhicule stationné',()=>{const{game:g,v}=setup(),door=put(g,'gate',65,70);door.gateMode='open';v.x=door.x;v.y=door.y;assert.equal(g.setGateMode('closed',door),false);assert.equal(g.world.placement(C.BUILDINGS.house,64,69).valid,false)});
test('fouille: présence, pied à terre, ACTION et durée réellement requis',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('roseraie');assert.equal(g.expeditions.work(.25),false);atSite(g);g.expeditions.work(.25);assert.equal(g.expeditions.snapshot().sites.find(s=>s.id==='roseraie').progress,0);work(g,24);const s=g.expeditions.snapshot();assert.equal(s.sites.find(s=>s.id==='roseraie').progress,6);assert.equal(s.intel,2);assert.equal(s.stats.reports,1);assert.equal(s.sites.filter(s=>s.known).length,4)});
test('fouille: réserve transférée au sac, pas aux ressources centrales',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('station');atSite(g,'station');work(g,24);const before=g.resources.fuel;work(g,8);assert.equal(g.player.carry.fuel,6);assert.equal(g.expeditions.snapshot().sites.find(s=>s.id==='station').stock.fuel,16);assert.equal(g.resources.fuel,before)});
test('fouille: sac plein préserve le reliquat et le renseignement est unique',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('roseraie');atSite(g);work(g,24);g.player.carry.wood=g.player.carryCapacity;const before=clone(g.expeditions.snapshot().sites);work(g,40);assert.deepEqual(g.expeditions.snapshot().sites,before);assert.equal(g.expeditions.snapshot().intel,2)});
test('fouille: ennemis visibles et nuit interrompent le travail',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('station');atSite(g,'station');g.spawnZombie('walker');const z=g.zombies[0];z.x=g.player.x+20;z.y=g.player.y;work(g,20);assert.equal(g.expeditions.snapshot().sites[0].progress,0);z.dead=true;g.phase='warning';work(g,20);assert.equal(g.expeditions.snapshot().sites[0].progress,0)});
test('coffre: transferts bornés, réserve pleine garde le reliquat',()=>{const{game:g,v}=setup();v.cargo.wood=75;g.player.carry.scrap=10;assert.ok(g.expeditions.transfer().ok);assert.equal(C.bagTotal(v.cargo),80);assert.equal(g.player.carry.scrap,5);g.resources.wood=g.storage;g.resources.scrap=g.storage-2;g.expeditions.unload();assert.equal(v.cargo.wood,75);assert.equal(v.cargo.scrap,3)});
test('retour: crédit au dépôt uniquement, fermeture de sortie sans double récompense',()=>{const{game:g,v}=setup();g.expeditions.refuel();g.expeditions.select('roseraie');v.cargo.scrap=12;const before=g.resources.scrap;g.expeditions.unload();assert.equal(g.resources.scrap,before+12);assert.equal(g.expeditions.snapshot().stats.returned,1);g.expeditions.unload();assert.equal(g.resources.scrap,before+12)});
test('destruction: coffre et essence perdus, équipage humain non dupliqué',()=>{const{game:g,v}=setup();g.expeditions.refuel();v.cargo.food=20;g.expeditions.board();g.expeditions.damage(999);assert.equal(v.health,0);assert.equal(v.fuel,0);assert.equal(C.bagTotal(v.cargo),0);assert.equal(v.driving,false);assert.equal(g.units.length,3);assert.equal(g.expeditions.snapshot().stats.lost,1)});
test('analyste: un ouvrier existant, poste alimenté et coût réel',()=>{const{game:g}=setup(),n=g.units.length,food=g.resources.food;assert.ok(g.expeditions.assign().ok);assert.equal(g.units.length,n);assert.equal(g.resources.food,food-2);assert.equal(g.expeditions.assign().ok,false);const a=g.expeditions.snapshot().analyst,u=g.units.find(u=>u.id===a.id);assert.equal(u.kind,'worker')});
test('analyste: doit rejoindre le poste, 45 s et 2 rations par renseignement',()=>{const{game:g}=setup();g.expeditions.assign();const a=g.expeditions.snapshot().analyst,u=g.units.find(u=>u.id===a.id),p=g.world.buildings.get(a.post);u.carry=0;standAt(g,u,p);const food=g.resources.food;for(let i=0;i<180;i++)g.expeditions.updateAssignedUnit(u,.25);assert.equal(g.expeditions.snapshot().intel,1);assert.equal(g.resources.food,food-2);assert.equal(g.expeditions.snapshot().analyst.progress,0)});
test('analyste: coupure électrique ne produit ni progrès ni renseignements',()=>{const{game:g}=setup();g.expeditions.assign();const a=g.expeditions.snapshot().analyst,u=g.units.find(u=>u.id===a.id),p=g.world.buildings.get(a.post);u.carry=0;standAt(g,u,p);p.powered=false;for(let i=0;i<200;i++)g.expeditions.updateAssignedUnit(u,.25);assert.equal(g.expeditions.snapshot().intel,0)});
test('analyste: impossible de le prendre en même temps pour voirie et récupération',()=>{const{game:g}=setup();g.expeditions.assign();const a=g.expeditions.snapshot().analyst;put(g,'roadDepot',71,71);put(g,'generator',76,74);g.refreshMetrics(true);assert.equal(g.infrastructure.assign(a.id).ok,false)});
test('analyste: rappel ne téléporte pas le travailleur au dépôt',()=>{const{game:g}=setup();g.expeditions.assign();const a=g.expeditions.snapshot().analyst,u=g.units.find(u=>u.id===a.id);u.x=2600;u.y=2048;const before=u.x;assert.ok(g.expeditions.recall());g.expeditions.updateAssignedUnit(u,.1);assert.ok(Math.abs(u.x-before)<20);assert.ok(g.expeditions.snapshot().analyst)});
test('sauvegarde: conduite, essence, coffre et renseignements conservés',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('station');g.expeditions.board();g.input.keys.add('KeyD');for(let i=0;i<15;i++)g.expeditions.drive(.1);g.input.keys.clear();const before=stable(g);for(let i=0;i<4;i++){assert.ok(g.save(false));assert.ok(g.load());assert.equal(stable(g),before);assert.equal(g.player.radius,22)}});
test('sauvegarde: ancien format 11 migre sans véhicule ni renseignements offerts',()=>{const{game:g}=fresh(),d=g.serialize();d.version=11;delete d.expeditions;const next=Save.validate(d);assert.equal(next.version,C.SAVE_VERSION);assert.equal(next.expeditions.vehicle,null);assert.equal(next.expeditions.intel,0);assert.deepEqual(next.resources,d.resources)});
test('sauvegarde: registre v12 obligatoire et import invalide non destructif',()=>{const{game:g}=setup(),d=g.serialize(),w=g.world;delete d.expeditions;assert.throws(()=>g.restoreSave(d));assert.equal(g.world,w)});
test('sauvegarde: véhicule étranger, surchargé ou conducteur ailleurs refusés',()=>{const{game:g}=setup(),d=g.serialize();for(const change of [e=>e.vehicle.fuel=999,e=>e.vehicle.cargo.scrap=81,e=>e.vehicle.id=d.buildings[0].id,e=>{e.vehicle.driving=true;e.vehicle.x+=300},e=>e.vehicle.angle=Infinity]){const raw=clone(d);change(raw.expeditions);assert.throws(()=>Save.validate(raw))}});
test('sauvegarde: analyste occupé ou inexistant refusé',()=>{const{game:g}=setup();g.expeditions.assign();const d=g.serialize(),raw=clone(d);raw.expeditions.analyst.id=987654;assert.throws(()=>Save.validate(raw));const both=clone(d);both.infrastructure.crew=[{id:both.expeditions.analyst.id,returning:false}];assert.throws(()=>Save.validate(both))});
test('nouvelle partie: pas de voiture, contrat ni carburant résiduel',()=>{const{game:g}=setup();g.expeditions.refuel();g.expeditions.select('station');g.expeditions.board();g.startNew('standard','42');assert.equal(g.expeditions.snapshot().vehicle,null);assert.equal(g.expeditions.snapshot().active,null);assert.ok(g.player.radius<22)});
test('expéditions: pas de renseignement par lecture du dossier, ni de véhicule créé au rendu',()=>{const{game:g}=fresh(),before=stable(g);for(let i=0;i<40;i++)g.expeditions.overview();g.render();assert.equal(stable(g),before)});
test('pause: ni déplacement, ni consommation de carburant, ni fouille',()=>{const{game:g,v}=setup();g.expeditions.refuel();g.expeditions.board();g.togglePause(true);const fuel=v.fuel,x=v.x;g.input.keys.add('KeyD');g.expeditions.drive(.25);assert.equal(v.fuel,fuel);assert.equal(v.x,x);assert.equal(g.expeditions.select('station').ok,false)});
test('panne: collision répétée sur un mur ne brûle pas d’essence immobile',()=>{const{game:g,v}=setup(),gate=put(g,'gate',63,60);gate.gateMode='closed';v.x=gate.x;v.y=gate.bottom+23;g.player.x=v.x;g.player.y=v.y;v.fuel=10;g.expeditions.board();g.input.keys.add('KeyW');for(let i=0;i<20;i++)g.expeditions.drive(.1);const fuel=v.fuel,y=v.y;for(let i=0;i<30;i++)g.expeditions.drive(.1);assert.equal(v.y,y);assert.equal(v.fuel,fuel)});

// Regression 1.36: restoreSave calls UI readers that reconcile the vehicle before
// the outer expedition wrapper returns. That vehicle radius must not become the
// permanent radius of the survivor. Invalid starts used to overwrite it too.
test('1.36 conduite reprise : descente et destruction retrouvent le rayon à pied sans consommer un ID',()=>{
 const {game:g}=setup(),foot=g.makePlayer(0).radius;assert.ok(g.expeditions.board().ok);
 const next=g.nextId;assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.nextId,next);assert.equal(g.player.radius,22);
 assert.equal(g.startNew('standard','graine invalide'),false);assert.equal(g.expeditions.driving(),true);
 assert.ok(g.expeditions.board().ok);assert.equal(g.player.radius,foot);
 assert.ok(g.expeditions.board().ok);assert.ok(g.save(false));assert.ok(g.load());g.expeditions.damage(10000);assert.equal(g.player.radius,foot);assert.equal(g.expeditions.driving(),false);
});
