'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),P=require('../src/exploration-pack.js'),R=C.ExplorePackRules;
function fresh(){const {game:g}=bootGame();const Kit=require('../src/expansion-kit.js');Kit.install(g);P.install(g);g.startNew('standard','17117');g.units=[];g.phase='calm';g.phaseTime=9999;return g;}
function tick(g,n){for(let i=0;i<Math.ceil(n/.04);i++){g.update(.04);g.input.pressed.clear();}}
function node(g,type='wood'){const n=g.world.nodes.find(n=>n.type===type&&!n.depleted&&n.amount>60);assert.ok(n);standAt(g,g.player,n);g.zombies=[];return n;}
function survey(g,n){g.player.carry.food=4;assert.ok(g.explorationPack.survey(n.id).ok);tick(g,R.surveySeconds);assert.ok(g.explorationPack.snapshot().surveys.some(s=>s.nodeId===n.id));}
function extract(g,n){survey(g,n);const before=n.amount;assert.ok(g.explorationPack.extract(n.id).ok);tick(g,R.extractSeconds);assert.equal(before-n.amount,R.cargoAmount);assert.equal(g.explorationPack.snapshot().cargo[0].amount,R.cargoAmount);}
function clear(g){for(let x=2150;x<2300;x+=20)for(let y=2150;y<2400;y+=20)if(g.friendlyPositionClear(g.player,x,y)){g.player.x=x;g.player.y=y;return;}throw Error('Aucun sol libre');}
test('prospection : migration vide, relevé payé et extraction depuis une réserve réellement finie',()=>{const g=fresh(),n=node(g),amount=n.amount;extract(g,n);assert.equal(g.player.carry.food,3);assert.equal(g.stats.gathered,R.cargoAmount);assert.equal(n.amount,amount-R.cargoAmount);assert.equal(g.explorationPack.survey(n.id).ok,false);assert.equal(g.explorationPack.extract(n.id).ok,false);assert.equal(g.explorationPack.snapshot().cargo.length,1);});
test('prospection : cache vide payée par le sac, transferts bornés sans création',()=>{const g=fresh();clear(g);Object.assign(g.player.carry,{wood:20,scrap:10,food:6});assert.ok(g.explorationPack.placeCache().ok);tick(g,R.cacheSeconds);const c=g.explorationPack.snapshot().caches[0];assert.ok(c);assert.equal(C.bagTotal(c.stock),0);assert.equal(g.player.carry.wood,14);assert.equal(g.player.carry.scrap,7);const before=C.bagTotal(g.player.carry);assert.ok(g.explorationPack.cacheTransfer(c.id,'store').ok);assert.equal(C.bagTotal(g.player.carry),0);assert.equal(C.bagTotal(g.explorationPack.snapshot().caches[0].stock),before);assert.ok(g.explorationPack.cacheTransfer(c.id,'take').ok);assert.equal(C.bagTotal(g.player.carry),before);assert.equal(C.bagTotal(g.explorationPack.snapshot().caches[0].stock),0);assert.equal(g.explorationPack.cacheTransfer(c.id,'take').ok,false);});
test('prospection : mouvement et dégâts interrompent sans prélèvement, pause ne progresse pas',()=>{const g=fresh(),n=node(g);g.player.carry.food=3;assert.ok(g.explorationPack.survey(n.id).ok);tick(g,1);const p=g.explorationPack.overview().task.progress;g.paused=true;tick(g,1);assert.equal(g.explorationPack.overview().task.progress,p);g.paused=false;g.player.x+=3;tick(g,.04);assert.equal(g.explorationPack.busy(),false);assert.equal(g.player.carry.food,3);standAt(g,g.player,n);assert.ok(g.explorationPack.survey(n.id).ok);g.player.health-=1;tick(g,.04);assert.equal(g.explorationPack.busy(),false);assert.equal(g.player.carry.food,3);assert.equal(g.explorationPack.snapshot().surveys.length,0);});
test('prospection : ballot livré partiellement sans dépasser le stockage, reliquat conservé',()=>{const g=fresh(),n=node(g);extract(g,n);standAt(g,g.player,g.core());g.resources.wood=g.storage-10;const deposited=g.depositedResources;assert.ok(g.explorationPack.deliver().ok);tick(g,R.deliverySeconds);assert.equal(g.resources.wood,g.storage);assert.equal(g.explorationPack.snapshot().cargo[0].amount,14);assert.equal(g.depositedResources-deposited,10);assert.equal(g.explorationPack.deliver().ok,false);g.resources.wood-=20;assert.ok(g.explorationPack.deliver().ok);tick(g,R.deliverySeconds);assert.equal(g.explorationPack.snapshot().cargo.length,0);assert.equal(g.explorationPack.snapshot().delivered,24);});
test('prospection : abandon et récupération physique, aucun transfert à distance',()=>{const g=fresh(),n=node(g);extract(g,n);assert.ok(g.explorationPack.drop().ok);const p=g.explorationPack.snapshot().cargo[0];g.player.x+=200;assert.equal(g.explorationPack.recover(p.id).ok,false);Object.assign(g.player,{x:p.x,y:p.y});assert.ok(g.explorationPack.recover(p.id).ok);tick(g,R.recoverSeconds);assert.equal(g.explorationPack.snapshot().cargo[0].stage,'held');assert.equal(g.explorationPack.snapshot().cargo[0].amount,R.cargoAmount);});
test('prospection : chute du commandant laisse le ballot sur place après évacuation',()=>{const g=fresh(),n=node(g);extract(g,n);const location={x:g.player.x,y:g.player.y};g.player.invulnerable=0;g.damagePlayer(1000);tick(g,.04);const p=g.explorationPack.snapshot().cargo[0];assert.equal(p.stage,'ground');assert.ok(Math.hypot(p.x-location.x,p.y-location.y)<.01);tick(g,8.1);assert.equal(g.player.dead,false);assert.equal(g.explorationPack.snapshot().cargo[0].amount,R.cargoAmount);assert.equal(g.explorationPack.recover(p.id).ok,false);});
test('prospection : piquets payés, espacement minimum et archive uniquement au dépôt',()=>{const g=fresh();node(g);g.player.carry.wood=8;g.player.carry.scrap=4;assert.ok(g.explorationPack.markRoute().ok);tick(g,R.markerSeconds);assert.equal(g.explorationPack.snapshot().markers.length,1);assert.equal(g.player.carry.wood,6);assert.equal(g.explorationPack.markRoute().ok,false);assert.equal(g.explorationPack.clearRoute().ok,false);standAt(g,g.player,g.core());assert.ok(g.explorationPack.clearRoute().ok);assert.equal(g.explorationPack.snapshot().markers.length,0);assert.equal(g.player.carry.wood,6);});
test('prospection : charge ralentit le déplacement réel sans modifier le sac',()=>{const g=fresh(),n=node(g);extract(g,n);clear(g);const point={x:g.player.x,y:g.player.y};g.input.keys.add('KeyD');g.updatePlayer(.04);const loaded=g.player.x-point.x;g.input.keys.clear();g.explorationPack.drop();Object.assign(g.player,point);g.input.keys.add('KeyD');g.updatePlayer(.04);const empty=g.player.x-point.x;g.input.keys.clear();assert.ok(loaded>0&&empty>loaded);assert.ok(Math.abs(loaded/empty-R.cargoSpeed)<.01);});
test('prospection : sauvegarde/reprise conserve cache, marqueurs et colis ; nouvelle campagne vide',()=>{const g=fresh(),n=node(g);extract(g,n);g.explorationPack.drop();const before=g.explorationPack.snapshot();assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.explorationPack.snapshot(),before);g.startNew('standard','18118');assert.deepEqual(g.explorationPack.snapshot(),P.initial());assert.ok(g.load());assert.deepEqual(g.explorationPack.snapshot(),P.initial());});
test('prospection : enregistrements malformés refusés sans mutation, IDs étrangers et doubles porteurs',()=>{const g=fresh(),n=node(g);extract(g,n);const state=g.explorationPack.snapshot(),save=g.serialize();for(const modify of [s=>s.cargo[0].amount=25,s=>s.cargo[0].nodeId=999999999,s=>s.cargo.push({...s.cargo[0]}),s=>s.serial=1,s=>s.markers.push({id:s.serial++,x:NaN,y:0}),s=>s.caches.push({id:s.serial++,x:100,y:100,stock:{...C.makeBag(),wood:55}})]){const bad=structuredClone(state);modify(bad);assert.throws(()=>P.normalize(bad,save));assert.deepEqual(g.explorationPack.snapshot(),state);}});
test('prospection : profondeur des caches et ballots partagée avec personnages, file bornée',()=>{const g=fresh(),n=node(g);extract(g,n);g.explorationPack.drop();const entries=g.depthEntries({left:0,top:0,right:4096,bottom:4096}),item=entries.find(e=>e.entity.__explorationPack);assert.ok(item);assert.equal(item.kind,1);assert.ok(entries.every((e,i)=>!i||e.depth>=entries[i-1].depth));assert.doesNotThrow(()=>g.render());});

test('prospection : région atteinte avec un ballot, abandon à la dernière position locale',()=>{const g=fresh(),n=node(g);extract(g,n);g.player.x=4058;g.player.y=2048;tick(g,.04);const point={x:g.player.x,y:g.player.y};assert.ok(g.frontier.enter());tick(g,.04);const p=g.explorationPack.snapshot().cargo[0];assert.equal(p.stage,'ground');assert.equal(p.x,point.x);assert.equal(p.y,point.y);assert.equal(g.explorationPack.placeCache().ok,false);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.explorationPack.snapshot().cargo[0].amount,R.cargoAmount);});
test('prospection : une intervention essentielle empêche les actions concurrentes',()=>{const g=fresh(),n=node(g);g.player.carry.food=3;const old=g.essentials;g.essentials={...old,busy:()=>true};assert.equal(g.explorationPack.survey(n.id).ok,false);g.essentials=old;assert.ok(g.explorationPack.survey(n.id).ok);});
test('prospection : une sauvegarde invalide est refusée avant de remplacer le monde',()=>{const g=fresh(),n=node(g);extract(g,n);const before=g.world,raw=g.serialize(),state=g.explorationPack.snapshot();raw.expansions127.modules.exploration.cargo[0].amount=25;assert.throws(()=>g.restoreSave(raw));assert.equal(g.world,before);assert.deepEqual(g.explorationPack.snapshot(),state);});

test('prospection : reprise à terre avec évacuation immédiate laisse le ballot au point de chute',()=>{const g=fresh(),n=node(g);extract(g,n);const before={x:g.player.x,y:g.player.y};g.player.dead=true;g.player.health=0;g.player.downTimer=0;g.update(.04);assert.equal(g.player.dead,false);const p=g.explorationPack.snapshot().cargo[0];assert.equal(p.stage,'ground');assert.equal(p.x,before.x);assert.equal(p.y,before.y);});
test('prospection : le type du ballot et du relevé reste celui du gisement de la carte',()=>{const g=fresh(),n=node(g);extract(g,n);for(const collection of ['cargo','surveys']){const raw=g.serialize();raw.expansions127.modules.exploration[collection][0].type='medicine';assert.throws(()=>g.restoreSave(raw));assert.equal(g.explorationPack.snapshot()[collection][0].type,n.type);}});
