'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),P=require('../src/exploration-pack131.js'),G=require('../src/frontier-geometry.js'),R=C.Travel131Rules;
function fresh(){const {game:g}=boot127();P.install(g);g.startNew('standard','17117');g.units=[];g.phase='calm';g.phaseTime=9999;g.zombies=[];return g;}
function ticks(g,seconds){for(let i=0;i<Math.ceil(seconds/.04);i++){g.travel131.step(.04);g.input.pressed.clear();}}
function emptyBag(g){for(const key of C.RESOURCE_KEYS)g.player.carry[key]=0;}
function vehicle(g,regional=false){const b=new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1);g.world.add(b);g.refreshMetrics(true);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const v=g.expeditions.car();emptyBag(g);v.fuel=8;if(regional){g.player.x=v.x=4058;g.player.y=v.y=2048;v.driving=true;g.player.radius=22;assert.ok(g.frontier.enter());assert.ok(g.frontier.board());}else{g.player.x=v.x+36;g.player.y=v.y;}return v;}
function service(g){g.player.carry.scrap=8;g.player.carry.fuel=1;assert.ok(g.travel131.begin('service').ok);ticks(g,R.serviceSeconds);assert.equal(g.travel131.busy(),false);assert.ok(g.travel131.snapshot().tuning);}
function wreck(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const world=g.frontier.world();for(const p of world.pois){for(const v of p.parking){for(const side of [-1,1]){const q=G.global(v,v.w/2,side<0?-.75:v.h+.75);if(world.blocked(q.x,q.y,.32,0,null)||!world.line(q,require('../src/frontier-survey.js').edge(q,v),0,null,v.id,.025))continue;const raw=g.serialize();Object.assign(raw.frontier,{x:q.x,y:q.y,z:0,inside:null,seen:[p.id]});raw.frontier.taken[v.id]=v.amount;for(const near of world.nearPOI(q.x,q.y,40)){for(let i=0;i<1+G.hash(raw.worldSeed,near.id,'threat')%4;i++){raw.frontier.enemies[near.id+':e'+i]=0;delete raw.frontier.tracks[near.id+':e'+i];}}raw.frontier.kills=Object.values(raw.frontier.enemies).filter(h=>h===0).length;g.restoreSave(raw);if(g.travel131.preview('dismantle',v.id).reason==='Préparez 1 ferraille dans le sac pour l’outillage consommable.')return v;}}}throw Error('Aucune épave accessible');}
test('voyages : préparation au dépôt transfère chaque quantité réelle et ne remplit pas le sac à distance',()=>{const g=fresh();emptyBag(g);standAt(g,g.player,g.core());const before={...g.resources};assert.ok(g.travel131.begin('pack','motor').ok);ticks(g,R.packingSeconds);for(const[key,amount]of Object.entries(R.manifests.motor.stock)){assert.equal(g.player.carry[key],amount);assert.equal(before[key]-g.resources[key],amount);}assert.equal(g.travel131.begin('pack','motor').ok,false);g.player.x+=400;assert.equal(g.travel131.begin('pack','foot').ok,false);});
test('voyages : sac partiellement plein et dépôt presque vide conservent tous les reliquats',()=>{const g=fresh();standAt(g,g.player,g.core());emptyBag(g);g.player.carry.wood=g.player.carryCapacity-3;g.resources.fuel=1;const before=g.resources.scrap;assert.ok(g.travel131.begin('pack','motor').ok);ticks(g,R.packingSeconds);assert.equal(g.player.carry.fuel,1);assert.equal(g.resources.fuel,0);assert.equal(g.player.carry.scrap,2);assert.equal(g.resources.scrap,before-2);assert.equal(C.bagTotal(g.player.carry),g.player.carryCapacity);});
test('voyages : mouvement, dégâts et rechargement interrompent sans payer ; pause suspend',()=>{const g=fresh();standAt(g,g.player,g.core());const stock={...g.resources};assert.ok(g.travel131.begin('pack','foot').ok);ticks(g,1);g.paused=true;ticks(g,4);assert.ok(Math.abs(g.travel131.overview().task.progress-1/R.packingSeconds)<1e-12);g.paused=false;g.player.x+=4;ticks(g,.04);assert.equal(g.travel131.busy(),false);assert.deepEqual(g.resources,stock);standAt(g,g.player,g.core());assert.ok(g.travel131.begin('pack','foot').ok);g.player.health--;ticks(g,.04);assert.equal(g.travel131.busy(),false);assert.deepEqual(g.resources,stock);assert.ok(g.travel131.begin('pack','foot').ok);g.input.pressed.add('KeyR');ticks(g,.04);assert.equal(g.travel131.busy(),false);});
test('voyages : siphonnage fini local, capacité du sac et conservation du carburant',()=>{const g=fresh(),v=vehicle(g);g.player.carry.wood=g.player.carryCapacity-2;const total=v.fuel+g.player.carry.fuel;assert.ok(g.travel131.begin('siphon').ok);ticks(g,R.siphonSeconds);assert.equal(v.fuel,6);assert.equal(g.player.carry.fuel,2);assert.equal(v.fuel+g.player.carry.fuel,total);assert.equal(g.travel131.begin('siphon').ok,false);emptyBag(g);assert.ok(g.travel131.begin('siphon').ok);ticks(g,R.siphonSeconds);assert.equal(v.fuel,0);assert.equal(g.travel131.begin('siphon').ok,false);});
test('voyages : siphonnage et révision physique régionale, refus à distance',()=>{const g=fresh();vehicle(g,true);service(g);assert.equal(g.travel131.snapshot().tuning.remaining,R.serviceDistance);assert.equal(g.player.carry.scrap,0);assert.equal(g.player.carry.fuel,0);assert.equal(g.travel131.begin('service').ok,false);assert.ok(g.travel131.begin('siphon').ok);ticks(g,R.siphonSeconds);assert.equal(g.player.carry.fuel,6);const raw=g.serialize();raw.frontier.x+=100;g.restoreSave(raw);assert.equal(g.travel131.begin('siphon').ok,false);});
test('voyages : tarif moteur mixte exact, révision épuisée au dernier mètre et aucune remise sur autre voiture',()=>{const g=fresh(),v=vehicle(g);service(g);const rate=.004;assert.equal(g.travel131.fuelCost(1000,rate,v.id),3.2);assert.equal(g.travel131.fuelDistance(3.2,rate,v.id),1000);assert.equal(g.travel131.fuelCost(3000,rate,v.id),10.4);assert.equal(g.travel131.fuelDistance(10.4,rate,v.id),3000);assert.equal(g.travel131.fuelCost(1000,rate,v.id+1),4);g.travel131.consumeDistance(1999,v.id);assert.ok(Math.abs(g.travel131.fuelCost(2,rate,v.id)-.0072)<1e-12);g.travel131.consumeDistance(2,v.id);assert.equal(g.travel131.snapshot().tuning,null);assert.equal(g.travel131.fuelCost(1000,rate,v.id),4);});
test('voyages : véhicule détruit et révision étrangère ne créent aucun bonus',()=>{const g=fresh(),v=vehicle(g);service(g);const before=g.travel131.snapshot();g.expeditions.damage(1000);assert.equal(g.travel131.snapshot().tuning,null);assert.equal(g.travel131.begin('service').ok,false);const raw=g.serialize();raw.expansions127.modules.exploration131=before;assert.throws(()=>g.restoreSave(raw));assert.equal(g.travel131.snapshot().tuning,null);});
test('voyages : épave mécanique après coffre vidé, prélèvement fini, coût, bruit, reprise et épuisement',()=>{const g=fresh(),v=wreck(g);g.player.carry.scrap=1;let noise=0;const signal=g.frontier.signalAt;g.frontier={...g.frontier,signalAt:(...args)=>{noise++;signal(...args);}};const total=P.wreckReserve(g.world.seed,v.id),original=g.frontier.snapshot().taken[v.id];let recovered=0;while(g.travel131.wreckStatus(v.id).remaining){emptyBag(g);g.player.carry.scrap=1;const left=g.travel131.wreckStatus(v.id).remaining;assert.ok(g.travel131.begin('dismantle',v.id).ok);ticks(g,R.dismantleSeconds);const n=Math.min(left,R.dismantleBatch);assert.equal(g.player.carry.scrap,n);recovered+=n;assert.equal(g.frontier.snapshot().taken[v.id],original);}assert.equal(recovered,total);assert.ok(noise>=R.dismantleSeconds);assert.equal(g.travel131.begin('dismantle',v.id).ok,false);const state=g.travel131.snapshot();assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.travel131.snapshot(),state);assert.equal(g.travel131.wreckStatus(v.id).remaining,0);});
test('voyages : coffre non vidé, autre épave et coûts manquants refusés',()=>{const g=fresh(),v=wreck(g);g.player.carry.scrap=1;const raw=g.serialize();raw.frontier.taken[v.id]=v.amount-1;g.restoreSave(raw);assert.equal(g.travel131.begin('dismantle',v.id).ok,false);assert.equal(g.travel131.begin('dismantle','P9999:car:0').ok,false);});
test('voyages : imports forgés sont refusés transactionnellement sans remplacer la carte',()=>{const g=fresh(),v=wreck(g);g.player.carry.scrap=1;assert.ok(g.travel131.begin('dismantle',v.id).ok);ticks(g,R.dismantleSeconds);const raw=g.serialize(),before=g.world,state=g.travel131.snapshot();for(const mutate of [x=>x.wrecks.push({...x.wrecks[0]}),x=>x.wrecks[0].recovered=100,x=>x.wrecks[0].recovered=.5,x=>x.wrecks[0].id='P9999:car:0',x=>x.tuning={id:9999,remaining:2000},x=>x.extra=1]){const bad=structuredClone(raw);mutate(bad.expansions127.modules.exploration131);assert.throws(()=>g.restoreSave(bad));assert.equal(g.world,before);assert.deepEqual(g.travel131.snapshot(),state);}});
test('voyages : travaux non sauvés, migration vide et campagne suivante sans bonus hérité',()=>{const g=fresh(),v=vehicle(g);service(g);assert.ok(g.travel131.begin('siphon').ok);ticks(g,1);const before=v.fuel;g.save(false);g.load();assert.equal(g.travel131.busy(),false);assert.equal(g.expeditions.car().fuel,before);g.startNew('standard','81818');assert.deepEqual(g.travel131.snapshot(),P.initial());assert.deepEqual(P.normalize(undefined),P.initial());});
test('voyages : exclusivité croisée des interventions et mort immédiatement réanimée',()=>{const g=fresh();standAt(g,g.player,g.core());const old=g.nightGear;g.nightGear={...old,busy:()=>true};assert.equal(g.travel131.begin('pack','foot').ok,false);g.nightGear=old;assert.ok(g.travel131.begin('pack','foot').ok);assert.ok(g.expansions.busy('survival'));g.player.dead=true;g.player.health=0;g.player.downTimer=0;g.update(.04);assert.equal(g.travel131.busy(),false);assert.equal(C.bagTotal(g.player.carry),0);});
test('voyages : conduite locale applique vraiment la remise et compte uniquement les mètres parcourus',()=>{const g=fresh(),v=vehicle(g);service(g);assert.ok(g.expeditions.board().ok);const before={x:v.x,y:v.y,fuel:v.fuel};g.input.keys.add('KeyD');for(let i=0;i<5;i++)g.expeditions.drive(.04);g.input.keys.clear();const travelled=Math.hypot(v.x-before.x,v.y-before.y)/C.Frontier.RULES.metreUnits;assert.ok(travelled>0);const localRate=C.Expeditions.RULES.fuelPerUnit*(g.worldEvolution.vehicleProfile().fuel/.004)*C.Frontier.RULES.metreUnits;assert.ok(Math.abs(before.fuel-v.fuel-travelled*localRate*(1-R.fuelDiscount))<1e-10);assert.ok(Math.abs(g.travel131.snapshot().tuning.remaining-(R.serviceDistance-travelled))<1e-8);});
test('voyages : conduite régionale applique le tarif mixte avec derniers décimètres de révision',()=>{const g=fresh();vehicle(g,true);service(g);const v=g.expeditions.car();g.travel131.consumeDistance(R.serviceDistance-.1,v.id);assert.ok(g.frontier.board());const before={...g.frontier.position(),fuel:v.fuel};g.input.keys.add('KeyD');g.updatePlayer(.04);g.input.keys.clear();const after=g.frontier.position(),distance=Math.hypot(after.x-before.x,after.y-before.y);assert.ok(distance>.1);const expected=g.worldEvolution.vehicleProfile().fuel*(distance-.1*R.fuelDiscount);assert.ok(Math.abs(before.fuel-v.fuel-expected)<1e-10);assert.equal(g.travel131.snapshot().tuning,null);});
test('voyages : vélo sans réservoir ne peut ni siphonner ni recevoir une révision moteur',()=>{const g=fresh();assert.ok(g.worldEvolution.selectVehicle('bike'));const v=vehicle(g);v.fuel=0;g.player.carry.scrap=8;g.player.carry.fuel=1;assert.equal(g.travel131.begin('siphon').ok,false);assert.equal(g.travel131.begin('service').ok,false);assert.equal(g.travel131.fuelDistance(0,0,v.id),Infinity);assert.equal(g.travel131.fuelCost(100,0,v.id),0);});
test('voyages : coût disparu au dernier instant et étage supérieur refusent toute révision',()=>{const g=fresh(),v=vehicle(g,true);g.player.carry.scrap=8;g.player.carry.fuel=1;assert.ok(g.travel131.begin('service').ok);ticks(g,8.8);g.player.carry.scrap=7;ticks(g,.3);assert.equal(g.travel131.busy(),false);assert.equal(g.travel131.snapshot().tuning,null);assert.equal(g.player.carry.scrap,7);assert.equal(g.player.carry.fuel,1);const world=g.frontier.world(),p=world.pois.find(p=>p.levels.includes(1));let point;for(let x=1;x<p.w-1&&!point;x+=.5)for(let y=1;y<p.h-1&&!point;y+=.5){const q=G.global(p,x,y);if(!world.blocked(q.x,q.y,.32,1,p.id))point=q;}assert.ok(point);const raw=g.serialize();Object.assign(raw.frontier,{...point,z:1,inside:p.id,seen:[...new Set([...raw.frontier.seen,p.id])]});g.restoreSave(raw);assert.equal(g.travel131.begin('service').ok,false);assert.equal(g.travel131.begin('siphon').ok,false);assert.equal(g.expeditions.car().id,v.id);});
