'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),T=require('../src/tactics.js'),Save=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(seed=17117){const e=bootGame();e.game.startNew('standard',String(seed));return e;}
function put(g,type,x=70,y=64,progress=1){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,progress);g.world.add(b);g.refreshMetrics(true);return b;}
function beside(g,u,b){const p=g.fieldcraft.service(u,b);assert.ok(p,'accès de service trouvé');Object.assign(u,p);assert.ok(g.friendlyPositionClear(u,u.x,u.y));return p;}
function emptySite(g,type,except){const d=C.BUILDINGS[type];for(let y=55;y<77;y++)for(let x=55;x<80;x++)if((!except||x!==except.gx||y!==except.gy)&&g.world.placement(d,x,y).valid){const a={x:x*32-30,y:y*32-30};if(!except||Math.hypot(a.x-g.player.x,a.y-g.player.y)>150)return{x,y};}throw Error('emplacement de test introuvable');}
function steady(g,seconds){for(let i=0;i<Math.ceil(seconds/.04)&&!g.gameOver;i++){g.update(.04);g.input.pressed.clear();}}
test('terrain : version 13, identifiants et stocks initiaux préservés',()=>{const{game:g}=fresh();assert.equal(C.SAVE_VERSION,20);assert.equal(g.resources.wood,180);assert.equal(g.units.length,3);assert.equal(g.world.nodes.length,new g.world.constructor(17117).nodes.length);assert.equal(g.fieldcraft.snapshot().nodes.length,g.world.nodes.length)});
for(const seed of [17117,42,99,777,123456])test('terrain : aucune superposition de décors actifs, graine '+seed,()=>{const{game:g}=fresh(seed),nodes=g.world.nodes.filter(n=>!n.depleted);for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++)assert.equal(g.fieldcraft.overlap(g.fieldcraft.rect(nodes[i]),g.fieldcraft.rect(nodes[j])),false,nodes[i].id+'/'+nodes[j].id);for(const n of nodes)for(const b of g.world.buildings.values())assert.equal(g.fieldcraft.overlap(g.fieldcraft.rect(n),g.fieldcraft.rect(b)),false)});
test('terrain : mêmes quantités et positions reproductibles sans consommer le RNG',()=>{const{game:g}=fresh(),raw=new g.world.constructor(17117),map=new Map(raw.nodes.map(n=>[n.id,n.amount]));for(const n of g.world.nodes)assert.equal(n.amount,map.get(n.id));const before=g.random.state,nodes=copy(g.fieldcraft.snapshot().nodes);g.fieldcraft.setup(nodes);assert.equal(g.random.state,before);assert.deepEqual(g.fieldcraft.snapshot().nodes,nodes)});
test('terrain : les stations sont sur le bas-côté, la chaussée centrale reste dégagée',()=>{const{game:g}=fresh();for(const id of ['station','roseraie','relais','tri']){const s=C.Expeditions.BY_ID[id],a=g.fieldcraft.rect({...s,renderSize:86});assert.ok(!(a.l<2100&&a.r>1996));assert.ok(!(a.t<2100&&a.b>1996));assert.equal(g.friendlyPositionClear(g.player,s.x,s.y),false);}for(const n of g.world.nodes.filter(n=>!n.depleted)){const a=g.fieldcraft.rect(n);assert.ok(!(a.l<2100&&a.r>1996));assert.ok(!(a.t<2100&&a.b>1996))}});
test('collisions : les personnes débutent hors du centre devenu solide',()=>{const{game:g}=fresh();assert.equal(g.friendlyPositionClear(g.player,g.core().x,g.core().y),false);for(const p of [g.player,...g.units])assert.ok(g.friendlyPositionClear(p,p.x,p.y))});
test('collisions : les 71 structures respectent leur emprise et les portes leurs modes',()=>{const{game:g}=fresh();for(const d of Object.values(C.BUILDINGS)){if(d.id==='core')continue;const b=put(g,d.id,70,64);if(d.gate){b.gateMode='auto';assert.equal(T.blocksFriendly(b),false);b.gateMode='open';assert.equal(T.blocksFriendly(b),false);b.gateMode='closed';assert.equal(T.blocksFriendly(b),true);}else assert.equal(T.blocksFriendly(b),d.id!=='spikes',d.id);g.world.remove(b);}assert.equal(T.blocksFriendly(g.core()),true)});
test('collisions : un grand déplacement ne traverse pas un bâtiment',()=>{const{game:g}=fresh(),b=put(g,'warehouse');g.player.x=b.left-28;g.player.y=b.y;g.moveFriendly(g.player,300,0);assert.ok(g.player.x<b.left);assert.ok(g.friendlyPositionClear(g.player,g.player.x,g.player.y))});
test('collisions : un décor bloque joueur, ouvrier et véhicule',()=>{const{game:g}=fresh(),n=g.world.nodes.find(n=>!n.depleted&&n.type==='scrap');for(const radius of [g.player.radius,g.units[0].radius,C.Expeditions.RULES.carRadius]){const a={x:n.x-140,y:n.y,radius};g.moveFriendly(a,300,0);assert.ok(a.x<g.fieldcraft.rect(n).l);assert.ok(g.friendlyPositionClear(a,a.x,a.y))}});
test('services : récolte depuis l’extérieur et roue liée à la quantité réelle',()=>{const{game:g}=fresh(),n=g.world.nodes.find(n=>!n.depleted&&n.type==='wood');beside(g,g.player,n);const amount=n.amount;g.input.keys.add('KeyE');g.updateInteraction(.1);assert.equal(n.amount,amount-1);assert.equal(g.player.carry.wood,1);assert.equal(g.fieldcraft.context().action.label,'RÉCOLTE');assert.ok(g.fieldcraft.context().action.p>0);g.input.keys.clear();g.updateInteraction(.1);assert.equal(g.fieldcraft.context().action,null)});
test('services : dépôt du sac à la façade du centre sans y entrer',()=>{const{game:g}=fresh();g.player.carry.wood=10;beside(g,g.player,g.core());const before=g.resources.wood;g.input.keys.add('KeyE');g.updateInteraction(.1);assert.equal(g.resources.wood,before+10);assert.equal(g.player.carry.wood,0);assert.equal(g.depositedResources,10)});
test('services : dépôt ordinaire et reliquat dans un grand entrepôt',()=>{const{game:g}=fresh(),b=put(g,'logisticsHub'),u=g.units[0];beside(g,u,b);u.carry=10;u.carryType='wood';g.resources.wood=g.storage-3;g.depositWorker(u,b,.1);assert.equal(u.carry,7);assert.equal(g.resources.wood,g.storage)});
test('services : un recrutement payé apparaît à l’extérieur du centre',()=>{const{game:g}=fresh();put(g,'house');const before=g.resources.food;assert.ok(g.recruit('worker'));const u=g.units.at(-1);assert.ok(g.friendlyPositionClear(u,u.x,u.y));assert.equal(g.resources.food,before-C.SURVIVORS.worker.cost.food)});
test('construction : un bâtiment ne se solidifie pas sur un personnage',()=>{const{game:g}=fresh(),b=put(g,'house',70,64,0);g.player.x=b.x;g.player.y=b.y;b.work(b.def.buildTime);assert.equal(g.completeBuilding(b),false);assert.ok(b.progress<1);beside(g,g.player,b);b.work(b.def.buildTime);assert.equal(g.completeBuilding(b),true);assert.equal(g.friendlyPositionClear(g.player,b.x,b.y),false)});
test('réimplantation : aperçu puis coût exact, même identité et mêmes dégâts',()=>{const{game:g}=fresh(),b=put(g,'warehouse');beside(g,g.player,b);b.health=600;b.priority=3;const place=emptySite(g,b.type,b),before={...g.resources},id=b.id;assert.ok(g.fieldcraft.beginMove(b));const q=g.fieldcraft.plan(place.x,place.y);assert.ok(q.ok,q.reason);assert.deepEqual(g.resources,before);assert.ok(g.fieldcraft.commit());assert.equal(b.id,id);assert.equal(b.health,600);assert.equal(b.priority,3);assert.equal(b.gx,place.x);assert.equal(g.resources.wood,before.wood-Math.ceil(b.def.cost.wood*.2));assert.equal(g.resources.scrap,before.scrap-Math.ceil(b.def.cost.scrap*.2))});
test('réimplantation : annuler ne débite rien',()=>{const{game:g}=fresh(),b=put(g,'house');beside(g,g.player,b);const p=emptySite(g,b.type,b),before={...g.resources};g.fieldcraft.beginMove(b);g.fieldcraft.plan(p.x,p.y);g.fieldcraft.cancel();assert.equal(g.fieldcraft.commit(),false);assert.deepEqual(g.resources,before)});
test('réimplantation : nouveau personnage ou bâtiment sur l’aperçu invalide tout',()=>{const{game:g}=fresh(),b=put(g,'house');beside(g,g.player,b);const p=emptySite(g,b.type,b);g.fieldcraft.beginMove(b);assert.ok(g.fieldcraft.plan(p.x,p.y).ok);const before={...g.resources};const obstacle=put(g,'woodWall',p.x,p.y);assert.equal(g.fieldcraft.commit(),false);assert.deepEqual(g.resources,before);g.world.remove(obstacle)});
test('rotation : la grille est réécrite et la santé n’est pas rétablie',()=>{const{game:g}=fresh(),pos=emptySite(g,'watchtower'),b=put(g,'watchtower',pos.x,pos.y);beside(g,g.player,b);b.health=300;const before={...g.resources};const q=g.fieldcraft.rotate(b);assert.ok(q.ok,q.reason);assert.ok(g.fieldcraft.commit());assert.equal(b.rotation,1);assert.equal(b.health,300);assert.equal(g.resources.wood,before.wood-Math.ceil(b.def.cost.wood*.05))});
test('réimplantation : centre, poste territorial, combat et positions invalides refusés',()=>{const{game:g}=fresh(),b=put(g,'house');beside(g,g.player,g.core());assert.equal(g.fieldcraft.proposal(g.core(),70,60,0).ok,false);beside(g,g.player,b);g.phase='warning';assert.equal(g.fieldcraft.proposal(b,73,70,0).ok,false);g.phase='calm';assert.equal(g.fieldcraft.proposal(b,NaN,0,0).ok,false)});
test('mirador : contrôle manuel consomme la réserve, sans double tir automatique',()=>{const{game:g}=fresh(),b=put(g,'watchtower');beside(g,g.player,b);assert.ok(g.fieldcraft.control(b));const before=g.resources.ammo;g.input.mouseWorldX=b.x+200;g.input.mouseWorldY=b.y;g.input.mouseDown=true;g.updatePlayer(.04);assert.equal(g.resources.ammo,before-1);assert.equal(g.projectiles.length,1);g.updateBuildings(.04);assert.equal(g.resources.ammo,before-1);assert.equal(g.projectiles.length,1);g.input.keys.add('KeyD');g.updatePlayer(.04);assert.equal(g.fieldcraft.context().mounted,null)});
test('mirador : aucune munition ni tir depuis un bâtiment non armé',()=>{const{game:g}=fresh(),b=put(g,'house');beside(g,g.player,b);assert.equal(g.fieldcraft.control(b),false);const tower=put(g,'watchtower',74,64);beside(g,g.player,tower);assert.ok(g.fieldcraft.control(tower));g.resources.ammo=0;g.input.mouseDown=true;g.updatePlayer(.1);assert.equal(g.projectiles.length,0)});
test('rechargement : fenêtre parfaite accélère sans offrir de munitions',()=>{const{game:g}=fresh(),w=C.WEAPONS.pistol;g.player.magazine.pistol=0;const before=g.resources.ammo;g.startReload();g.player.reload=g.player.reloadTotal*.44;g.startReload();assert.equal(g.fieldcraft.reload().outcome,'perfect');assert.equal(g.player.reload,.04);assert.equal(g.resources.ammo,before);g.updatePlayer(.05);assert.equal(g.player.magazine.pistol,w.magazine);assert.equal(g.resources.ammo,before-w.magazine*w.ammoPerReload)});
test('rechargement : un seul échec, sans cumul par martèlement de R',()=>{const{game:g}=fresh();g.player.magazine.pistol=0;g.startReload();const before=g.player.reload;g.startReload();const failed=g.player.reload;assert.ok(Math.abs(failed-before-.8)<1e-8);for(let i=0;i<10;i++)g.startReload();assert.equal(g.player.reload,failed);assert.equal(g.fieldcraft.reload().outcome,'failed')});
test('rechargement : ignorer le timing garde la durée ordinaire',()=>{const{game:g}=fresh();g.player.magazine.pistol=0;g.startReload();assert.equal(g.player.reload,C.WEAPONS.pistol.reload);for(let i=0;i<40;i++)g.updatePlayer(.04);assert.equal(g.player.reload,0);assert.equal(g.player.magazine.pistol,C.WEAPONS.pistol.magazine)});
test('rechargement : une reprise ne donne pas un deuxième essai',()=>{const{game:g}=fresh();g.player.magazine.pistol=0;g.startReload();g.startReload();const time=g.player.reload;assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.fieldcraft.reload().attempt,true);g.startReload();assert.equal(g.player.reload,time)});
test('jour/nuit : le masque rejoint progressivement la nuit noire puis l’aube',()=>{const{game:g}=fresh();g.wave=4;g.phase='warning';g.prepareWave();g.phase='assault';g.startAssault();g.spawnTimer=1000;const initial=g.fieldcraft.opacity(1);assert.ok(initial<1);g.update(.1);assert.ok(g.fieldcraft.opacity(1)>initial&&g.fieldcraft.opacity(1)<initial+.02);for(let i=0;i<90;i++)g.update(.1);assert.equal(g.fieldcraft.opacity(1),1);g.phase='calm';g.phaseTime=200;g.update(.1);assert.ok(g.fieldcraft.opacity(0)>.9);for(let i=0;i<90;i++)g.update(.1);assert.ok(g.fieldcraft.opacity(0)<.4)});
test('météo : les fronts aléatoires existants et leur interpolation restent actifs',()=>{const{game:g}=fresh();g.weather=0;g.weatherTarget=1;g.update(.04);assert.ok(g.weather>0&&g.weather<.01);const before=g.weather;g.update(.04);assert.ok(g.weather>before);for(const sec of [94.99,189.99,284.99]){g.elapsed=sec;g.update(.04);assert.ok(g.weatherTarget>=0&&g.weatherTarget<=1)}});
test('reprise : les quantités et positions des décors ne changent pas au chargement',()=>{const{game:g}=fresh();const before=g.fieldcraft.snapshot().nodes,amounts=g.serialize().nodes;for(let i=0;i<3;i++){assert.ok(g.save(false));assert.ok(g.load());}assert.deepEqual(g.fieldcraft.snapshot().nodes,before);assert.deepEqual(g.serialize().nodes,amounts)});
test('migration : une sauvegarde v12 passe en terrain physique sans cadeau',()=>{const{game:g}=fresh();const raw=g.serialize();raw.version=12;delete raw.fieldcraft;const money=copy(raw.resources),sites=copy(raw.expeditions.sites);assert.ok(g.restoreSave(raw));assert.equal(g.serialize().version,20);assert.deepEqual(g.resources,money);assert.deepEqual(g.expeditions.snapshot().sites,sites);assert.ok(g.fieldcraft.snapshot().nodes.length>0)});
test('import invalide : aucun remplacement de monde ni de stocks',()=>{const{game:g}=fresh(),raw=g.serialize(),world=g.world,money=copy(g.resources);raw.fieldcraft.nodes[0][1]=NaN;assert.throws(()=>g.restoreSave(raw));assert.equal(g.world,world);assert.deepEqual(g.resources,money);const duplicate=g.serialize();duplicate.fieldcraft.nodes[1]=duplicate.fieldcraft.nodes[0];assert.throws(()=>g.restoreSave(duplicate));assert.equal(g.world,world)});
test('nouvelle partie : contrôle, réimplantation et tentative de recharge réinitialisés',()=>{const{game:g}=fresh(),b=put(g,'house');beside(g,g.player,b);g.fieldcraft.beginMove(b);g.startNew('standard','99');assert.equal(g.fieldcraft.context().moving,null);assert.equal(g.fieldcraft.context().mounted,null);assert.equal(g.fieldcraft.reload().attempt,false)});

test('ouvriers : collecte autonome payante sans acteur sous un décor',()=>{const{game:g}=fresh(),before=g.resources.wood+g.resources.scrap;for(let i=0;i<2000;i++){g.update(.04);g.input.pressed.clear();}assert.ok(g.resources.wood+g.resources.scrap>before);for(const u of [g.player,...g.units])assert.ok(g.friendlyPositionClear(u,u.x,u.y));assert.ok(g.save(false));});
test('navigation : le trajet de retour cible la façade et non le centre solide',()=>{const{game:g}=fresh();g.player.x=2300;g.player.y=2048;assert.ok(g.recon.returnHome());const route=g.recon.route(true);assert.ok(route.ok);const end=route.path.at(-1);assert.ok(g.friendlyPositionClear(g.player,end.x,end.y));assert.ok(g.fieldcraft.distance(end,g.core())<=90);});
test('horde : la migration dégage un infecté chargé dans un décor devenu solide',()=>{const{game:g}=fresh(903145),n=g.world.nodes.find(n=>n.id===276);g.spawnZombie('walker');const z=g.zombies.at(-1);z.x=n.x;z.y=n.y;const h=z.health,c=g.zombies.length;g.fieldcraft.setup(g.fieldcraft.snapshot().nodes);assert.equal(g.zombies.length,c);assert.equal(z.health,h);assert.ok(![...g.fieldcraft.props(z.x,z.y,z.radius)].some(p=>require('../src/fieldcraft.js').collides(p,z.x,z.y,z.radius*.7)));});
test('horde : un infecté contourne le décor frontal sans traversée ni élimination artificielle',()=>{const{game:g}=fresh(903145);g.spawnZombie('walker');const z=g.zombies.at(-1);z.x=4066;z.y=1554.7;const before={x:z.x,y:z.y},hp=z.health;g.flow.rebuild(g.world,g.core());for(let i=0;i<1500&&!z.dead;i++){g.elapsed+=.04;g.rebuildBuckets();g.updateZombies(.04);assert.ok(![...g.fieldcraft.props(z.x,z.y,z.radius)].some(p=>require('../src/fieldcraft.js').collides(p,z.x,z.y,z.radius*.7)),'aucune traversée de prop');}assert.ok(Math.hypot(z.x-before.x,z.y-before.y)>350,'progression vers la cité');assert.equal(z.health,hp);});
