'use strict';const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/core.js'),Save=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs'),G=require('../src/frontier-geometry.js');const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function desk(){const e=fresh(),g=e.game,b=new(g.core().constructor)(g.nextId++,'expeditionOffice',72,65,0,1);g.world.add(b);g.refreshMetrics(true);g.fieldcraft.setup();g.resources.food=250;assert.ok(g.expeditions.assign().ok);const a=g.expeditions.snapshot().analyst,u=g.units.find(u=>u.id===a.id);standAt(g,u,b);return{...e,b,u};}
function work(g,u,n){for(let i=0;i<n;i++)g.expeditions.updateAssignedUnit(u,.25);}
function signal(){const e=desk();assert.ok(e.game.fieldAtlas.commission('t0').ok);work(e.game,e.u,160);return e;}
function enter(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}
function stable(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
function known(g,n=8){const d=g.serialize();d.frontier.seen=g.frontier.world().pois.slice(0,n).map(p=>p.id);g.restoreSave(d);return d.frontier.seen;}
test('reconnaissance : migration v17 sans zone parcourue, indice ni tournée offerte',()=>{const{game:g}=fresh(),d=g.serialize();d.version=17;delete d.fieldAtlas;const q=Save.validate(d);assert.equal(q.version,20);assert.deepEqual(q.fieldAtlas,C.FieldAtlas.initial());assert.deepEqual(q.resources,d.resources);assert.equal(q.frontier.generation,d.frontier.generation);});
test('reconnaissance : refus sans analyste et débit unique de cinq rations',()=>{const{game:g}=fresh(),before=g.resources.food;assert.equal(g.fieldAtlas.commission('t0').ok,false);assert.equal(g.resources.food,before);const e=desk(),food=e.game.resources.food;assert.ok(e.game.fieldAtlas.commission('t0').ok);assert.equal(e.game.resources.food,food-5);assert.equal(e.game.fieldAtlas.commission('t1').ok,false);assert.equal(e.game.resources.food,food-5);});
test('reconnaissance : cible de secteur invalide et manque de rations sans effet',()=>{const{game:g}=desk(),before=g.resources.food;assert.equal(g.fieldAtlas.commission('t999').ok,false);assert.equal(g.resources.food,before);g.resources.food=4;assert.equal(g.fieldAtlas.commission('t0').ok,false);assert.equal(g.fieldAtlas.snapshot().job,null);});
test('reconnaissance : quarante secondes effectives, aucun gain générique en parallèle',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');const intel=g.expeditions.snapshot().intel;work(g,u,159);assert.equal(g.fieldAtlas.snapshot().reports.length,0);assert.ok(g.fieldAtlas.snapshot().job.progress>39);work(g,u,1);assert.equal(g.fieldAtlas.snapshot().reports.length,3);assert.equal(g.expeditions.snapshot().intel,intel);assert.equal(g.frontier.snapshot().seen.length,0);});
test('reconnaissance : déplacement jusqu’au bureau requis',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');standAt(g,u,g.core());work(g,u,1);assert.equal(g.fieldAtlas.snapshot().job.progress,0);});
test('reconnaissance : pause et panne suspendent réellement la recherche',()=>{const{game:g,u,b}=desk();g.fieldAtlas.commission('t0');g.paused=true;work(g,u,160);g.paused=false;assert.equal(g.fieldAtlas.snapshot().job.progress,0);b.powered=false;work(g,u,160);assert.equal(g.fieldAtlas.snapshot().job.progress,0);b.powered=true;work(g,u,4);assert.equal(g.fieldAtlas.snapshot().job.progress,1);});
test('reconnaissance : menace visible au bureau bloque le travail',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');g.spawnZombie('walker');const z=g.zombies.at(-1);z.x=u.x+20;z.y=u.y;const progress=g.fieldAtlas.snapshot().job.progress;work(g,u,10);assert.equal(g.fieldAtlas.snapshot().job.progress,progress);});
test('reconnaissance : le rappel de l’ouvrier ne termine ni ne rembourse le dossier',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');work(g,u,20);const food=g.resources.food;g.expeditions.recall();work(g,u,10);assert.equal(g.fieldAtlas.snapshot().job.progress,5);assert.equal(g.resources.food,food);assert.equal(g.fieldAtlas.snapshot().reports.length,0);});
test('reconnaissance : abandon sans remboursement ni révélations',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');work(g,u,20);const n=g.resources.food;assert.ok(g.fieldAtlas.cancel());assert.equal(g.resources.food,n);assert.equal(g.fieldAtlas.snapshot().reports.length,0);work(g,u,180);assert.equal(g.expeditions.snapshot().intel,1);});
test('reconnaissance : progrès et cibles conservés après reprise, sans seconde facturation',()=>{const{game:g,u}=desk();g.fieldAtlas.commission('t0');work(g,u,80);const before=g.fieldAtlas.snapshot(),food=g.resources.food;assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.fieldAtlas.snapshot(),before);assert.equal(g.resources.food,food);const a=g.expeditions.snapshot().analyst,worker=g.units.find(u=>u.id===a.id);work(g,worker,80);assert.equal(g.fieldAtlas.snapshot().reports.length,3);assert.equal(g.resources.food,food);});
test('reconnaissance : un deuxième dossier ne duplique pas ses trois premiers indices',()=>{const{game:g,u}=signal();const first=g.fieldAtlas.snapshot().reports.map(p=>p.id);g.fieldAtlas.commission('t0');work(g,u,160);const ids=g.fieldAtlas.snapshot().reports.map(p=>p.id);assert.equal(ids.length,6);assert.equal(new Set(ids).size,6);assert.ok(first.every(id=>ids.includes(id)));});
test('reconnaissance : aucun nom précis, géométrie ou stock livré par un indice',()=>{const{game:g}=signal(),r=g.fieldAtlas.overview().reports[0],p=g.frontier.world().pois.find(p=>p.id===r.id);assert.equal(r.confirmed,false);assert.ok(!r.name.includes(p.name));assert.ok(Math.hypot(r.x-p.x,r.y-p.y)<=r.radius);assert.equal(r.w,undefined);assert.equal(r.stock,undefined);assert.equal(g.frontier.pin(r.id),false);});
test('terrain : consulter l’atlas et zoomer ne crée aucun secteur parcouru',()=>{const{game:g}=signal();const before=stable(g);g.fieldAtlas.overview();g.fieldAtlas.planning();assert.equal(stable(g),before);assert.deepEqual(g.fieldAtlas.snapshot().cells,[]);});
test('terrain : marche en région inscrite, pause et étage exclus',()=>{const{game:g}=fresh();enter(g);g.update(.04);assert.equal(g.fieldAtlas.snapshot().cells.length,1);g.input.keys.add('KeyD');for(let i=0;i<300;i++)g.update(.04);g.input.keys.clear();const before=copy(g.fieldAtlas.snapshot().cells);g.paused=true;for(let i=0;i<100;i++)g.update(.04);assert.deepEqual(g.fieldAtlas.snapshot().cells,before);g.paused=false;const d=g.serialize(),p=g.frontier.world().pois.find(p=>p.type==='duplex');Object.assign(d.frontier,{x:p.x,y:p.y,z:1,inside:p.id});g.restoreSave(d);g.update(.25);assert.deepEqual(g.fieldAtlas.snapshot().cells,before);});
test('terrain : indice confirmé par la visite sans remplir le sac ni la réserve',()=>{const{game:g}=signal();enter(g);const r=g.fieldAtlas.snapshot().reports[0],p=g.frontier.world().pois.find(p=>p.id===r.id),d=g.serialize();Object.assign(d.frontier,{x:p.x,y:p.y-p.h/2-2,z:0,inside:null});g.restoreSave(d);const bag=copy(g.player.carry);g.update(.04);assert.ok(g.frontier.snapshot().seen.includes(p.id));assert.ok(g.fieldAtlas.overview().reports.find(q=>q.id===p.id).confirmed);assert.deepEqual(g.player.carry,bag);});
test('tournée : six étapes maximum, aucun doublon ou lieu inconnu',()=>{const{game:g}=fresh(),ids=known(g);assert.equal(g.fieldAtlas.add('P9999'),false);for(const id of ids.slice(0,6))assert.ok(g.fieldAtlas.add(id));assert.equal(g.fieldAtlas.add(ids[0]),false);assert.equal(g.fieldAtlas.add(ids[6]),false);assert.equal(g.fieldAtlas.snapshot().tour.stops.length,6);});
test('tournée : réordonnancement au repos, progression explicite et arrêt sans téléportation',()=>{const{game:g}=fresh(),ids=known(g,3);ids.forEach(id=>g.fieldAtlas.add(id));assert.ok(g.fieldAtlas.reorder(ids[1],-1));assert.equal(g.fieldAtlas.snapshot().tour.stops[0],ids[1]);const pos={x:g.player.x,y:g.player.y};assert.ok(g.fieldAtlas.start());assert.equal(g.fieldAtlas.reorder(ids[1],1),false);assert.ok(g.fieldAtlas.next());assert.equal(g.fieldAtlas.snapshot().tour.index,1);assert.ok(g.fieldAtlas.stop());assert.deepEqual({x:g.player.x,y:g.player.y},pos);});
test('tournée : suppression de l’étape active et dernière étape cohérentes',()=>{const{game:g}=fresh(),ids=known(g,2);ids.forEach(id=>g.fieldAtlas.add(id));g.fieldAtlas.start();assert.ok(g.fieldAtlas.remove(ids[0]));assert.equal(g.fieldAtlas.snapshot().tour.stops[0],ids[1]);assert.ok(g.fieldAtlas.next());assert.equal(g.fieldAtlas.snapshot().tour.active,false);assert.equal(g.fieldAtlas.snapshot().tour.index,1);assert.equal(g.fieldAtlas.next(),false);});
test('tournée : signalement autorisé sans promotion artificielle en lieu découvert',()=>{const{game:g}=signal(),id=g.fieldAtlas.snapshot().reports[0].id;assert.ok(g.fieldAtlas.add(id));assert.ok(g.fieldAtlas.start());const before=g.frontier.snapshot();const p=g.fieldAtlas.planning();assert.ok(p.legs.length===1&&p.loopMetres>0);assert.equal(p.legs[0].target.confirmed,false);assert.deepEqual(g.frontier.snapshot(),before);});
test('tournée : budget régional distinct, marges et réserves non consommées',()=>{const{game:g}=fresh(),ids=known(g,3);ids.forEach(id=>g.fieldAtlas.add(id));g.fieldAtlas.configure('car','east');const before=stable(g),p=g.fieldAtlas.planning();assert.ok(p.loopMetres>=p.metres);assert.ok(Math.abs(p.required-p.fuel*1.25-2)<1e-8);assert.equal(p.vehicleUsable,false);assert.equal(p.excludesLocal,true);assert.equal(stable(g),before);});
test('tournée : tracé routier ne passe pas au centre de la copie régionale de D-17',()=>{const{game:g}=fresh(),ids=known(g,8);g.fieldAtlas.add(ids[6]);g.fieldAtlas.configure('foot','west');const p=g.fieldAtlas.planning();for(const leg of p.legs)for(const q of leg.path)assert.ok(!(q.x>4032.01&&q.x<4159.99&&q.y>4032.01&&q.y<4159.99));});
test('sauvegarde : doublons, fausses villes et étapes inconnues refusés avant remplacement',()=>{const{game:g}=signal(),d=g.serialize(),world=g.world;for(const edit of [x=>x.fieldAtlas.cells=[1,1],x=>x.fieldAtlas.cells=[4096],x=>x.fieldAtlas.reports[0].town='t9',x=>x.fieldAtlas.reports.push(copy(x.fieldAtlas.reports[0])),x=>x.fieldAtlas.tour.stops=['P9999'],x=>x.fieldAtlas.tour.index=9]){const b=copy(d);edit(b);assert.throws(()=>g.restoreSave(b));assert.equal(g.world,world);}});
test('sauvegarde : quatre reprises sans doublon de dossier ni remise à zéro de tournée',()=>{const{game:g}=signal(),id=g.fieldAtlas.snapshot().reports[0].id;g.fieldAtlas.add(id);g.fieldAtlas.start();const before=g.fieldAtlas.snapshot();for(let i=0;i<4;i++){assert.ok(g.save(false));assert.ok(g.load());}assert.deepEqual(g.fieldAtlas.snapshot(),before);});
test('campagne : nouvelle partie sans renseignement, trajet ou exploration hérités',()=>{const{game:g}=signal();g.fieldAtlas.add(g.fieldAtlas.snapshot().reports[0].id);g.fieldAtlas.start();g.startNew('standard','42');assert.deepEqual(g.fieldAtlas.snapshot(),C.FieldAtlas.initial());});
test('tournée : pause et reprise gardent la prochaine étape, fin permet de recommencer',()=>{const{game:g}=fresh(),ids=known(g,3);ids.forEach(id=>g.fieldAtlas.add(id));g.fieldAtlas.start();g.fieldAtlas.next();g.fieldAtlas.stop();assert.equal(g.fieldAtlas.snapshot().tour.index,1);assert.equal(g.fieldAtlas.planning().legs[0].target.id,ids[1]);g.fieldAtlas.start();assert.equal(g.fieldAtlas.snapshot().tour.index,1);g.fieldAtlas.next();g.fieldAtlas.next();assert.equal(g.fieldAtlas.snapshot().tour.active,false);g.fieldAtlas.start();assert.equal(g.fieldAtlas.snapshot().tour.index,0);});
test('reconnaissance : reprise après la nuit utilise le même dossier et le même coût',()=>{const{game:g,u,b}=desk();g.fieldAtlas.commission('t0');work(g,u,20);const targets=g.fieldAtlas.snapshot().job.targets,paid=g.resources.food;g.phase='warning';work(g,u,1);assert.equal(g.fieldAtlas.snapshot().job.progress,5);assert.ok(g.expeditions.snapshot().analyst.returning);g.phase='calm';standAt(g,u,g.core());work(g,u,1);assert.equal(g.expeditions.snapshot().analyst,null);assert.ok(g.expeditions.assign().ok);const a=g.expeditions.snapshot().analyst,next=g.units.find(v=>v.id===a.id);standAt(g,next,b);work(g,next,140);assert.deepEqual(g.fieldAtlas.snapshot().reports.map(r=>r.id),targets);assert.equal(g.resources.food,paid-2);});
