'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),Kit=require('../src/expansion-kit.js'),F=require('../src/fortification-pack.js');
function fresh(){const {game:g}=bootGame();Kit.install(g);F.install(g);g.startNew('standard','17117');g.resources.wood=g.resources.scrap=g.resources.stone=g.resources.ammo=300;g.world.nodes.forEach(n=>n.depleted=true);g.units=[];return g;}
function add(g,type,gx=72,gy=72){const b=new(g.core().constructor)(g.nextId++,type,gx,gy,0,1);g.world.add(b);g.refreshMetrics(true);g.selectBuilding(b);standAt(g,g.player,b);return b;}
function equip(g,kind,b){assert.equal(g.fortificationPack.equip(kind,b.id).ok,true,kind);}
function fit(g,b){return g.fortificationPack.snapshot().fittings.find(f=>f.id===b.id);}
function zombie(g,x,y){const z={id:g.nextId++,kind:'walker',x,y,health:60,maxHealth:60,dead:false,radius:10,vx:0,vy:0,think:0,attackCooldown:0,speedFactor:1,facing:0};g.zombies.push(z);g.rebuildBuckets();return z;}
test('fortifications: empty migration, module validation and resources unchanged',()=>{const g=fresh(),before={...g.resources},raw=g.serialize();delete raw.expansions127;g.restoreSave(raw);assert.deepEqual(g.fortificationPack.snapshot(),F.initial());assert.deepEqual(g.resources,before);});
test('fortifications: four paid fittings plus real destruction recovery form five features',()=>{const g=fresh(),b=add(g,'watchtower'),start=g.resources.ammo;equip(g,'ammo',b);assert.equal(fit(g,b).ammo,24);assert.equal(g.resources.ammo,start-24);assert.equal(g.fortificationPack.equip('ammo',b.id).ok,false);assert.equal(g.fortificationPack.equip('net',b.id).ok,false);equip(g,'repair',b);const wall=add(g,'woodWall',77,72);equip(g,'net',wall);const factory=add(g,'ammoFactory',82,72);equip(g,'regulator',factory);assert.equal(g.fortificationPack.actions().filter(a=>['ammo','repair','net','regulator','recover-debris'].includes(a.id)).length,5);});
test('fortifications: commands require physically reachable target, alive player and home scene',()=>{const g=fresh(),b=add(g,'watchtower');g.player.x=100;g.player.y=100;assert.equal(g.fortificationPack.equip('ammo',b.id).ok,false);standAt(g,g.player,b);g.player.dead=true;assert.equal(g.fortificationPack.equip('ammo',b.id).ok,false);g.player.dead=false;g.player.x=2048;g.player.y=20;assert.equal(g.frontier.enter('north'),true);assert.equal(g.fortificationPack.equip('ammo',b.id).ok,false);});
test('fortifications: locked wall between player and supply point rejects reach',()=>{const g=fresh(),b=add(g,'watchtower');g.player.x=b.left-55;g.player.y=b.y;const wall=add(g,'steelWall',71,73);g.player.x=b.left-55;g.player.y=b.y;g.selectBuilding(b);assert.equal(g.fortificationPack.equip('ammo',b.id).ok,false);assert.ok(wall.health>0);});
test('fortifications: caisson feeds real turret when common ammo is exhausted, once per cadence',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);g.resources.ammo=0;g.dayClock=.5;g.phase='calm';zombie(g,b.x+120,b.y);g.dayClock=.5;g.updateBuildings(.04);assert.equal(fit(g,b).ammo,23);assert.equal(g.projectiles.length,1);g.updateBuildings(.04);assert.equal(fit(g,b).ammo,23);assert.equal(g.resources.ammo,0);});
test('fortifications: normal ammo has priority and offline local turret cannot shoot',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);zombie(g,b.x+100,b.y);g.dayClock=.5;g.updateBuildings(.04);assert.equal(fit(g,b).ammo,24);g.resources.ammo=0;b.fireCooldown=0;b.siegeOffline=true;g.updateBuildings(.04);assert.equal(fit(g,b).ammo,24);});
test('fortifications: ammunition recovery respects stock capacity and cannot duplicate',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);g.resources.ammo=g.storage-5;assert.equal(g.fortificationPack.recoverAmmo(b.id).ok,true);assert.equal(g.resources.ammo,g.storage);assert.equal(fit(g,b).ammo,19);assert.equal(g.fortificationPack.recoverAmmo(b.id).ok,false);});
test('fortifications: manual repair uses finite purchased points, pauses and cancels on access loss',()=>{const g=fresh(),b=add(g,'woodWall');equip(g,'repair',b);b.health-=100;const hp=b.health,stock=g.resources.scrap;assert.equal(g.fortificationPack.startRepair(b.id).ok,true);g.fortificationPack.step(.25);assert.equal(b.health,hp+2);assert.equal(fit(g,b).repair,198);assert.equal(g.resources.scrap,stock);g.paused=true;g.fortificationPack.step(.25);assert.equal(b.health,hp+2);g.paused=false;g.player.x=100;g.player.y=100;g.fortificationPack.step(.25);assert.equal(g.fortificationPack.busy(),false);assert.equal(fit(g,b).repair,198);});
test('fortifications: corpse net holds finite real corpse pressure and then saturates',()=>{const g=fresh(),b=add(g,'woodWall');equip(g,'net',b);for(let i=0;i<14;i++)g.killZombie(zombie(g,b.x+12,b.y),false);assert.equal(b.corpseLoad,2);assert.equal(fit(g,b),undefined);assert.equal(g.corpses.length,14);});
test('fortifications: destroyed fittings are lost, demolition never generates duplicate rubble',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);g.destroyBuilding(b);assert.equal(fit(g,b),undefined);assert.equal(g.fortificationPack.snapshot().debris.length,1);g.destroyBuilding(b);assert.equal(g.fortificationPack.snapshot().debris.length,1);const c=add(g,'woodWall',80,80);g.demolishSelected();assert.equal(g.fortificationPack.snapshot().debris.length,1);assert.equal(c.dead,true);});
test('fortifications: ruin salvage requires approach, enters bag and leaves finite remainder',()=>{const g=fresh(),b=add(g,'watchtower'),point={x:g.player.x,y:g.player.y};g.destroyBuilding(b);const d=g.fortificationPack.snapshot().debris[0],total=C.bagTotal(d.remaining);g.player.x=point.x;g.player.y=point.y;assert.equal(g.fortificationPack.startRecovery(d.id).ok,true);for(let i=0;i<100;i++)g.fortificationPack.step(.25);assert.equal(g.fortificationPack.snapshot().debris.length,0);assert.ok(Math.abs(C.bagTotal(g.player.carry)-total)<1e-6);assert.equal(g.fortificationPack.startRecovery(d.id).ok,false);});
test('fortifications: regulator preserves intrants while retaining real power/production and cost',()=>{const g=fresh(),b=add(g,'ammoFactory');equip(g,'regulator',b);g.resources.ammo=0;g.resources.scrap=25.05;g.economyTick(1);assert.ok(g.resources.scrap>=25-1e-9);assert.ok(g.resources.ammo>0&&g.resources.ammo<.9);const ammo=g.resources.ammo;g.economyTick(1);assert.equal(g.resources.ammo,ammo);assert.equal(g.resources.scrap,25);assert.equal(b.dayOffline,undefined);});
test('fortifications: regulated factories share scarce intrants without duplication',()=>{const g=fresh(),a=add(g,'ammoFactory');equip(g,'regulator',a);const b=add(g,'ammoFactory',80,72);equip(g,'regulator',b);g.resources.ammo=0;g.resources.scrap=25.1;g.economyTick(1);assert.ok(g.resources.scrap>=25-1e-9);assert.ok(g.resources.ammo<=.9/.11*.1+1e-8);});
test('fortifications: save roundtrip retains fitted ammunition, damage and rubble once',()=>{const g=fresh(),a=add(g,'watchtower');equip(g,'ammo',a);const b=add(g,'warehouse',80,72);g.destroyBuilding(b);const raw=g.serialize(),before=g.fortificationPack.snapshot();g.restoreSave(raw);assert.deepEqual(g.fortificationPack.snapshot(),before);assert.deepEqual(g.resources,raw.resources);g.restoreSave(raw);assert.deepEqual(g.fortificationPack.snapshot(),before);});
test('fortifications: malformed records rejected transactionally before world replacement',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);const raw=g.serialize(),before=g.world;raw.expansions127.modules.fortification.fittings[0].ammo=25;assert.throws(()=>g.restoreSave(raw),/Fortifications/);assert.equal(g.world,before);const copy=g.serialize();copy.expansions127.modules.fortification.fittings[0].id=123456;assert.throws(()=>g.restoreSave(copy),/support/);assert.equal(g.world,before);assert.throws(()=>F.normalize({version:1,fittings:[],debris:[{id:55,type:'watchtower',x:100,y:100,w:64,h:64,remaining:{wood:NaN}}]}),/débris/);});
test('fortifications: new game clears all finite records and transient jobs',()=>{const g=fresh(),b=add(g,'woodWall');equip(g,'repair',b);b.health-=50;g.fortificationPack.startRepair(b.id);g.startNew('standard','123');assert.deepEqual(g.fortificationPack.snapshot(),F.initial());assert.equal(g.fortificationPack.busy(),false);});
test('fortifications: local caisson remains autonomous when commander falls and while outside D-17',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);g.resources.ammo=0;g.dayClock=.5;zombie(g,b.x+120,b.y);g.player.health=0;g.player.dead=true;g.updateBuildings(.04);assert.equal(fit(g,b).ammo,23);g.player.health=100;g.player.dead=false;g.zombies=[];g.player.x=2048;g.player.y=20;assert.equal(g.frontier.enter('north'),true);zombie(g,b.x+120,b.y);b.fireCooldown=0;g.dayClock=.5;g.updateBuildings(.04);assert.equal(fit(g,b).ammo,22);});
test('fortifications: manual repair freezes under any active overlay',()=>{const g=fresh(),b=add(g,'woodWall');equip(g,'repair',b);b.health-=100;assert.equal(g.fortificationPack.startRepair(b.id).ok,true);const hp=b.health;g.activeOverlay={};g.fortificationPack.step(.25);assert.equal(b.health,hp);assert.equal(fit(g,b).repair,200);g.activeOverlay=null;g.fortificationPack.step(.25);assert.equal(b.health,hp+2);});
test('fortifications: future ruin identifiers are rejected before replacing a campaign',()=>{const g=fresh(),b=add(g,'warehouse');g.destroyBuilding(b);const raw=g.serialize(),world=g.world;raw.expansions127.modules.fortification.debris[0].id=raw.nextId;assert.throws(()=>g.restoreSave(raw),/futur/);assert.equal(g.world,world);});
test('fortifications: cascading explosions cannot exceed the debris registry cap',()=>{const g=fresh(),factory=add(g,'ammoFactory',72,72),house=add(g,'house',75,72);house.health=1;g.nextId=10000;const s=F.initial();for(let id=1000;id<1127;id++)s.debris.push({id,type:'watchtower',x:100,y:100,w:64,h:64,remaining:{wood:1,scrap:0,stone:0}});g.expansions.get('fortification').restore(s);g.destroyBuilding(factory);assert.equal(house.dead,true);assert.equal(g.fortificationPack.snapshot().debris.length,128);assert.doesNotThrow(()=>globalThis.DeadwallSave.validate(g.serialize()));});
test('fortifications: sustained autonomous fire exhausts exactly 24 local rounds without regeneration',()=>{const g=fresh(),b=add(g,'watchtower');equip(g,'ammo',b);g.resources.ammo=0;g.dayClock=.5;zombie(g,b.x+120,b.y);for(let i=0;i<3000;i++)g.updateBuildings(.2);assert.equal(g.projectiles.length,24);assert.equal(g.resources.ammo,0);assert.equal(fit(g,b),undefined);assert.equal(g.fortificationPack.snapshot().fittings.length,0);});
