'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),G=require('../src/frontier-geometry.js'),W=require('../src/frontier-world.js'),S=require('../src/save.js');
const copy=x=>JSON.parse(JSON.stringify(x));function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function enter(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}
function fixture(g,p,z=0,point=null){const d=g.serialize(),f=d.frontier;if(!f.active){enter(g);return fixture(g,p,z,point);}f.z=z;f.inside=p.id;const q=point||G.global(p,p.w/2,p.h/2);f.x=q.x;f.y=q.y;f.seen=[p.id];for(let i=0;i<1+G.hash(d.worldSeed,p.id,'threat')%4;i++)f.enemies[p.id+':e'+i]=0;f.kills=Object.values(f.enemies).filter(h=>h===0).length;g.restoreSave(d);}
function step(g,n=1){for(let i=0;i<n;i++){g.update(.04);g.input.pressed.clear();}}
function stable(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
test('région : 8,192 km par côté, cache borné et types actifs',()=>{assert.equal(W.RULES.size,8192);assert.equal(G.PRESETS.length,62);const w=W.create(17117);assert.equal(w.pois.length,231);assert.equal(new Set(w.pois.map(p=>p.type)).size,42);for(let i=0;i<80;i++)w.chunk(i%32,Math.floor(i/32));assert.ok(w.cacheSize()<=25);});
test('région : mêmes routes, bâtiments et peuplement après éviction du cache',()=>{const a=W.create(17117),b=W.create(17117);assert.deepEqual(a.pois,b.pois);const c=copy(a.chunk(0,0));for(let i=0;i<80;i++)a.chunk(i%32,Math.floor(i/32));assert.deepEqual(a.chunk(0,0),c);assert.notDeepEqual(a.pois,W.create(42).pois)});
test('région : voitures 4,6 m, lits 2,05 m, maison bien plus grande que le personnage',()=>{assert.deepEqual(G.SHAPES.car,[4.6,1.85]);assert.equal(G.SHAPES.bed[0],2.05);assert.ok(G.BY.house.w>10);assert.ok(G.BY.mall.w>70);});
test('région : façades sur routes variées et voitures orientées selon les places',()=>{const w=W.create(17117);assert.ok(new Set(w.pois.map(p=>p.a.toFixed(2))).size>10);for(const p of w.pois)for(const car of p.parking)assert.ok(Math.abs(car.a-p.a-Math.PI/2)<.021);});
test('région : les parcelles ne se recouvrent pas, les stations sont hors chaussée',()=>{const w=W.create(17117);for(let i=0;i<w.pois.length;i++)for(let j=i+1;j<w.pois.length;j++)assert.equal(G.overlap(w.pois[i].reserve,w.pois[j].reserve),false);for(const p of w.pois.filter(p=>p.type==='fuel'))assert.ok(w.nearestRoad(p).d>p.h/2+10);});
test('région : ancienne sauvegarde migrée sans ressource ni découverte',()=>{const{game:g}=fresh(),d=g.serialize();for(let n=1;n<=13;n++){const raw=copy(d);raw.version=n;delete raw.frontier;const out=S.validate(raw);assert.equal(out.version,20);assert.deepEqual(out.resources,d.resources);assert.deepEqual(out.frontier.seen,[]);assert.equal(out.frontier.car,null)}});
test('région : une carte consultée ne transporte ni le joueur ni son stock',()=>{const{game:g}=fresh();const before=stable(g);g.frontier.overview();assert.equal(stable(g),before);assert.equal(g.frontier.enter(),false);});
test('région : sortie physique à pied et continuation du temps de D-17',()=>{const{game:g}=fresh();enter(g);const t=g.elapsed,day=g.phaseTime,x=g.frontier.snapshot().x;g.input.keys.add('KeyD');step(g,50);g.input.keys.clear();assert.ok(g.frontier.snapshot().x>x+6);assert.ok(g.elapsed>t);assert.ok(g.phaseTime<day);assert.equal(g.player.x,4058);assert.ok(g.player.regionAbsent);});
test('région : le joueur absent ne reçoit pas de soins locaux ni de coups de fantôme',()=>{const{game:g}=fresh();enter(g);g.player.health=50;const h=g.player.health;g.damagePlayer(20);assert.equal(g.player.health,h);assert.equal(g.workerCanWorkAt(g.player,g.core(),10000),false);assert.ok(!g.isolatedStalkerTargets().includes(g.player));});
test('région : retour par la route sans téléporter une destination lointaine',()=>{const{game:g}=fresh();enter(g);g.input.keys.add('KeyA');step(g,35);g.input.keys.clear();assert.equal(g.frontier.active(),false);assert.ok(g.player.x>3950);assert.equal(g.player.regionAbsent,false);assert.equal(g.frontier.leave(),false);});
test('région : une porte du refuge peut refuser le retour',()=>{const{game:g}=fresh();enter(g);const b=new(g.core().constructor)(g.nextId++,'woodWall',126,64,0,1);g.world.add(b);g.input.keys.add('KeyA');step(g,27);g.input.keys.clear();assert.ok(g.frontier.active());g.world.remove(b);assert.ok(g.frontier.leave());});
test('région : sauvegarde et reprise gardent la position réelle hors D-17',()=>{const{game:g}=fresh();enter(g);g.input.keys.add('KeyD');step(g,25);g.input.keys.clear();const before=g.frontier.snapshot();assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.frontier.snapshot(),before);assert.ok(g.player.regionAbsent);});
test('région : contenants vidés restent vides après cache et sauvegarde',()=>{const{game:g}=fresh();enter(g);const w=g.frontier.world(),p=w.pois[0],pl=w.plan(p,0),o=pl.objects[0];let access;for(let y=o.y-1.2;y<o.y+o.h+1.2&&!access;y+=.25)for(let x=o.x-1.2;x<o.x+o.w+1.2;x+=.25){const a=G.global(p,x,y),target=G.global(p,o.x+o.w/2,o.y+o.h/2);if(!w.blocked(a.x,a.y,.32,0,p.id)&&w.line(a,target,0,p.id,o.id)){access=a;break;}}assert.ok(access);fixture(g,p,0,access);g.input.keys.add('KeyE');step(g,80);g.input.keys.clear();assert.ok(C.bagTotal(g.player.carry)>0);const taken=copy(g.frontier.snapshot().taken),money=copy(g.resources),bag=copy(g.player.carry);for(let i=0;i<3;i++){assert.ok(g.save(false));assert.ok(g.load());}assert.deepEqual(g.frontier.snapshot().taken,taken);assert.deepEqual(g.player.carry,bag);assert.deepEqual(g.resources,money);});
test('région : les étages sont liés aux mêmes coordonnées et exigent un escalier',()=>{const{game:g}=fresh();enter(g);const w=g.frontier.world(),p=w.pois.find(p=>p.type==='duplex');fixture(g,p);assert.equal(g.frontier.stairs(1),false);const t=w.plan(p,0).stairs[0],pos=G.global(p,t.x+t.w/2,t.y+t.h/2);fixture(g,p,0,pos);assert.ok(g.frontier.stairs(1));assert.equal(g.frontier.snapshot().z,1);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.frontier.snapshot().z,1);assert.ok(g.frontier.stairs(-1));assert.equal(g.frontier.snapshot().z,0);});
test('région : sous-sol de bunker réel et retour au rez-de-chaussée',()=>{const{game:g}=fresh();enter(g);const w=g.frontier.world(),p=w.pois.find(p=>p.type==='bunker'),t=w.plan(p,0).stairs[0];fixture(g,p,0,G.global(p,t.x+t.w/2,t.y+t.h/2));assert.ok(g.frontier.stairs(-1));assert.equal(g.frontier.snapshot().z,-1);assert.equal(w.blocked(p.x+100,p.y,.32,-1,p.id),true);assert.ok(g.frontier.stairs(1));});
test('région : refus de stock falsifié et ancre invalide, campagne intacte',()=>{const{game:g}=fresh();enter(g);const before=g.world,d=g.serialize();const variants=[q=>q.frontier.x=NaN,q=>q.frontier.anchor=null,q=>q.frontier.seen=['P9999'],q=>q.frontier.taken['P0000:0:0']=999,q=>q.frontier.z=2];for(const mutate of variants){const bad=copy(d);mutate(bad);assert.throws(()=>g.restoreSave(bad));assert.equal(g.world,before)} });
test('région : tirs et rechargement utilisent les munitions existantes',()=>{const{game:g}=fresh();enter(g);const n=g.player.magazine.pistol,money=g.resources.ammo;assert.ok(g.frontier.shoot());assert.equal(g.player.magazine.pistol,n-1);assert.equal(g.resources.ammo,money);g.startReload();step(g,40);assert.equal(g.player.magazine.pistol,C.WEAPONS.pistol.magazine);assert.equal(g.resources.ammo,money-1);});
test('région : région plus ancienne conservée mais nouvelle partie réinitialisée',()=>{const{game:g}=fresh();enter(g);fixture(g,g.frontier.world().pois[0]);assert.ok(g.frontier.snapshot().seen.length);g.startNew('standard','42');assert.equal(g.frontier.active(),false);assert.equal(g.frontier.snapshot().seen.length,0);assert.equal(g.frontier.snapshot().car,null);assert.equal(g.player.regionAbsent,false);});
function carFixture(){const e=fresh(),g=e.game,{standAt}=require('./helpers/physical-fixtures.cjs');for(const[type,x]of [['expeditionOffice',72],['expeditionGarage',77]]){const b=new(g.core().constructor)(g.nextId++,type,x,65,0,1);g.world.add(b);}g.refreshMetrics(true);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const v=g.expeditions.car();v.x=g.player.x=4058;v.y=g.player.y=2048;v.fuel=24;v.driving=true;g.player.radius=C.Expeditions.RULES.carRadius;assert.ok(g.frontier.enter());return{...e,v};}
test('région : essence calculée sur la distance parcourue et pas sur attente',()=>{const{game:g,v}=carFixture(),before=v.fuel;g.input.keys.add('KeyD');step(g,50);g.input.keys.clear();const d=g.frontier.snapshot().distance;assert.ok(d>30);assert.ok(Math.abs(before-v.fuel-d*.004)<1e-6);const hold=v.fuel;step(g,20);assert.equal(v.fuel,hold);});
test('région : voiture absente de D-17, coffre et plein sur place seulement',()=>{const{game:g,v}=carFixture();assert.equal(g.expeditions.entity(),null);assert.ok(v.regionAway);assert.ok(g.frontier.board());g.player.carry.wood=10;assert.ok(g.frontier.transfer());assert.equal(v.cargo.wood,10);v.fuel=0;const money=g.resources.fuel;assert.equal(g.frontier.refuel(),false);g.player.carry.fuel=2;assert.ok(g.frontier.refuel());assert.equal(v.fuel,2);assert.equal(g.resources.fuel,money);assert.equal(g.expeditions.unload().ok,false);});
test('région : retour automobile garde le même véhicule et son coffre',()=>{const{game:g,v}=carFixture();v.cargo.food=8;g.input.keys.add('KeyA');step(g,20);g.input.keys.clear();assert.equal(g.frontier.active(),false);assert.equal(g.expeditions.car().id,v.id);assert.equal(g.expeditions.car().cargo.food,8);assert.ok(g.expeditions.driving());assert.equal(g.frontier.snapshot().car,null);});
test('région : à pied, le commandant ne traverse pas son propre véhicule garé',()=>{const{game:g}=carFixture();assert.ok(g.frontier.board());const v=g.frontier.snapshot().car;g.input.keys.add('KeyW');step(g,30);g.input.keys.clear();const p=g.frontier.snapshot(),q=G.local({...v,w:4.6,h:1.85},p.x,p.y);assert.equal(G.circleRect(q.x,q.y,.32,{x:0,y:0,w:4.6,h:1.85}),false);});
