'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootDocument134}=require('../scripts/qa-startup134.cjs');
let g,C,G,I,S;
test.before(()=>{({g}=bootDocument134());C=globalThis.DeadwallCore;G=globalThis.DeadwallFrontierGeometry;I=globalThis.DeadwallInterventions134;S=globalThis.DeadwallFrontierSurvey;});
function start(){g.startNew('standard','17117');g.campaignIntro132.skip();g.phaseTime=999;}
function visit(p,point,z=0,keep=null){const d=g.serialize(),w=g.frontier.world();Object.assign(d.frontier,{active:true,x:point.x,y:point.y,z,inside:p.id,anchor:{x:g.player.x,y:g.player.y},car:null});if(!d.frontier.seen.includes(p.id))d.frontier.seen.push(p.id);for(const site of w.nearPOI(point.x,point.y,220))for(let i=0;i<w.threatCount(site);i++){const id=site.id+':e'+i;if(id!==keep){d.frontier.enemies[id]=0;delete d.frontier.tracks[id];}}d.frontier.kills=Object.values(d.frontier.enemies).filter(v=>v===0).length;g.restoreSave(d);}
function generator(){const w=g.frontier.world();for(const p of w.pois.filter(p=>p.type==='generatorRoom'))for(const raw of w.plan(p,0).objects.filter(o=>o.kind==='generator')){const o=I.objectIn(w,raw.id);for(let d=.4;d<3;d+=.2)for(let i=0;i<32;i++){const q={x:o.x+Math.cos(i*Math.PI/16)*d,y:o.y+Math.sin(i*Math.PI/16)*d,z:0,inside:p.id};if(!w.blocked(q.x,q.y,.32,0,p.id)&&S.targets(w,q,{},C.InterventionRules134.reach).some(t=>t.id===o.id)){visit(p,q);g.player.carry=C.makeBag({scrap:18,fuel:8});return {p,o,q};}}}throw Error('No accessible generator');}
function solve(){for(let guard=0;guard<8&&g.interventions134.busy();guard++){const s=g.interventions134.view().session;assert.equal(s.type,'generator');assert.equal(g.interventions134.act('adjust',s.target-s.dial).ok,true);assert.equal(g.interventions134.act('confirm').ok,true);}assert.equal(g.interventions134.busy(),false);}
test('136 : un groupe cannibalisé refuse ravitaillement et redémarrage avant toute consommation',()=>{start();const {o}=generator();assert.equal(g.interventions134.begin(o.id).ok,true);solve();assert.equal(g.interventions134.refuel(o.id).ok,true);const d=g.serialize();d.frontier.taken[o.id]=.5;g.restoreSave(d);const bag={...g.player.carry},plant=g.interventions134.snapshot().plants[o.id];assert.equal(g.interventions134.refuel(o.id).ok,false);assert.equal(g.interventions134.toggle(o.id).ok,false);assert.deepEqual(g.player.carry,bag);assert.deepEqual(g.interventions134.snapshot().plants[o.id],plant);});
test('136 : la destruction du support invalide la révision active et ses commandes de service',()=>{start();const {p,o}=generator();assert.equal(g.interventions134.begin(o.id).ok,true);const before=g.interventions134.snapshot();const evolution=g.worldEvolution;g.worldEvolution={...evolution,structureDestroyed:id=>id===p.id};assert.equal(g.interventions134.act('adjust',1).ok,false);assert.equal(g.interventions134.busy(),false);assert.deepEqual(g.interventions134.snapshot().plants,before.plants);g.worldEvolution=evolution;assert.equal(g.interventions134.begin(o.id).ok,true);solve();g.worldEvolution={...evolution,structureDestroyed:id=>id===p.id};const bag={...g.player.carry};assert.equal(g.interventions134.refuel(o.id).ok,false);assert.equal(g.interventions134.toggle(o.id).ok,false);assert.deepEqual(g.player.carry,bag);g.worldEvolution=evolution;});
function encounter(){const w=g.frontier.world();for(const p of w.pois){for(let i=0;i<w.threatCount(p);i++){if(p.levels[G.hash(p.id,i)%p.levels.length]!==0)continue;const id=p.id+':e'+i;visit(p,G.global(p,p.w/2,-3),0,id);g.update(.04);const e=g.frontier.contacts().find(e=>e.id===id);if(!e)continue;for(let a=0;a<48;a++){const q={x:e.x+Math.cos(a*Math.PI/24)*1.1,y:e.y+Math.sin(a*Math.PI/24)*1.1};if(w.blocked(q.x,q.y,.32,0,p.id)||!w.line(q,e,0,p.id,null,.04))continue;visit(p,q,0,id);g.update(.04);const current=g.frontier.contacts().find(e=>e.id===id),d=g.serialize();d.frontier.a=Math.atan2(current.y-d.frontier.y,current.x-d.frontier.x);g.restoreSave(d);g.input.mouseX=g.width/2+Math.cos(d.frontier.a)*300;g.input.mouseY=g.height/2+Math.sin(d.frontier.a)*300;g.update(.04);g.player.meleeCooldown=0;return {p,id};}}}throw Error('No regional contact');}
test('136 : Espace en région frappe les infectés ordinaires avec la crosse, sans consommer une cartouche',()=>{start();const {id}=encounter();const hp=g.frontier.contacts().find(e=>e.id===id).hp,rounds=g.player.magazine[g.player.weapon];g.input.pressed.add('Space');g.handlePressed();g.input.pressed.clear();assert.equal(g.frontier.enemyHealth(id),hp-C.SuccessionRules.armedMeleeDamage);assert.equal(g.player.magazine[g.player.weapon],rounds);assert.ok(g.player.meleeCooldown>0);const after=g.frontier.enemyHealth(id);g.input.pressed.add('Space');g.handlePressed();g.input.pressed.clear();assert.equal(g.frontier.enemyHealth(id),after);assert.equal(g.save(false),true);});
test('136 : les mains libres en région emploient les dégâts sans arme même si un pistolet reste porté',()=>{start();const {id}=encounter();const d=g.serialize();d.expansions127.modules.arsenal134.equipped=null;d.player.magazine={pistol:0,rifle:0,shotgun:0};g.restoreSave(d);g.update(.04);g.player.meleeCooldown=0;const hp=g.frontier.contacts().find(e=>e.id===id).hp;g.input.pressed.add('Space');g.handlePressed();g.input.pressed.clear();assert.equal(g.frontier.enemyHealth(id),hp-C.SuccessionRules.unarmedDamage);});
test('136 : la frappe régionale respecte angle, obstacle, étage, pause et rechargement',()=>{
 start();const {id}=encounter(),e=g.frontier.contacts().find(e=>e.id===id),hp=e.hp,position=g.frontier.position(),angle=Math.atan2(e.y-position.y,e.x-position.x);
 const strike=()=>{g.player.meleeCooldown=0;g.arsenal134.melee();assert.equal(e.hp,hp);};
 g.paused=true;strike();g.paused=false;g.player.reload=1;strike();g.player.reload=0;
 const oldZ=e.z;e.z=1;strike();e.z=oldZ;
 const w=g.frontier.world(),line=w.line;w.line=()=>false;try{strike();}finally{w.line=line;}
 g.input.mouseX=g.width/2-Math.cos(angle)*300;g.input.mouseY=g.height/2-Math.sin(angle)*300;g.update(.04);strike();
 g.input.mouseX=g.width/2+Math.cos(angle)*300;g.input.mouseY=g.height/2+Math.sin(angle)*300;g.update(.04);g.player.meleeCooldown=0;g.arsenal134.melee();assert.equal(e.hp,hp-C.SuccessionRules.armedMeleeDamage);
});
