'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Ground=require('../src/ground135.js');
const pal={base:'#6e784b',secondary:'#647445',soil:'#a08b69',accent:'#b9aa75',rock:'#b2ad97',grass:'#8e9b69',water:'#5b7063'};
const world=(seed=17117)=>({seed,generation:6,biomeAt:(x,y)=>({id:'meadow',palette:pal})});
let native;try{native=require('@napi-rs/canvas');}catch{}
function render(w,v,scale=16){const width=Math.round((v.r-v.l)*scale),height=Math.round((v.b-v.t)*scale),c=native.createCanvas(width,height),ctx=c.getContext('2d');ctx.scale(scale,scale);ctx.translate(-v.l,-v.t);Ground.draw(ctx,w,v,{scale});return c;}
test('ground G6: absolute seed sampling stable across chunk load and world recreation',()=>{const a=world(),b=world();for(const p of [[0,0],[31.97,32.03],[255.999,256.001],[12444.92,23453.67],[-.03,-16.21]])assert.deepEqual(Ground.colorAt(a,...p),Ground.colorAt(b,...p));assert.notDeepEqual(Ground.colorAt(a,445,345),Ground.colorAt(world(84329),445,345));});
test('ground G6: soil stays continuous across terrain tile and streaming chunk boundaries',()=>{const w=world();for(const edge of [0,32,128,256,512,4096])for(const axis of ['x','y']){const p=axis==='x'?[edge,73.83]:[91.26,edge],a=Ground.colorAt(w,p[0]-(axis==='x'?.001:0),p[1]-(axis==='y'?.001:0)),b=Ground.colorAt(w,p[0]+(axis==='x'?.001:0),p[1]+(axis==='y'?.001:0));assert.ok(a.every((n,i)=>Math.abs(n-b[i])<=1),`${axis} edge ${edge}`);}});
test('ground G6: historical generations retain their original painter',()=>{let touched=false;assert.equal(Ground.draw(new Proxy({},{get(){touched=true;}}),{seed:4,generation:5},{l:0,r:30,t:0,b:30}),false);assert.equal(touched,false);assert.equal(Ground.drawScenery({}, {kind:'tree'}, {world:{generation:5}},false),false);});
test('ground G6: tree trunks and rocks are painted from the real collision radius',()=>{const arcs=[],c=new Proxy({arc(...a){arcs.push(a);},createRadialGradient(){return{addColorStop(){}};}}, {get:(o,k)=>k in o?o[k]:()=>{},set:(o,k,v)=>(o[k]=v,true)});Ground.drawScenery(c,{id:'test',x:10,y:20,r:.42,canopy:4,a:0,kind:'tree',species:'birch'},{world:world(),x:50,y:50},false);assert.ok(arcs.some(a=>a[0]===0&&a[1]===0&&a[2]===.42));arcs.length=0;Ground.drawScenery(c,{id:'stump',x:10,y:20,r:.42,canopy:4,a:0,kind:'tree',species:'birch'},{world:world(),x:50,y:50},true);assert.ok(arcs.some(a=>a[0]===0&&a[1]===0&&a[2]===.18));assert.ok(arcs.every(a=>a[2]<=.18));});
test('ground G6: native raster has no holes or camera-relative texture jump', {skip:!native},()=>{globalThis.document={createElement:()=>native.createCanvas(1,1)};Ground.reset();const w=world(),a=render(w,{l:28,r:36,t:252,b:260}),b=render(w,{l:26,r:38,t:250,b:262});const ca=a.getContext('2d').getImageData(0,0,128,128).data,cb=b.getContext('2d').getImageData(32,32,128,128).data;assert.deepEqual(ca,cb);for(let i=3;i<ca.length;i+=4)assert.equal(ca[i],255);});
test('ground G6: raster LRU bounded across long trips, eviction rebuild identical', {skip:!native},()=>{globalThis.document={createElement:()=>native.createCanvas(1,1)};Ground.reset();const w=world(),first=render(w,{l:0,r:2,t:0,b:2},1).toBuffer('image/png');for(let i=1;i<74;i++)render(w,{l:i*4096,r:i*4096+2,t:100,b:102},.1);assert.ok(Ground.cacheInfo().tiles<=64);assert.equal(Ground.cacheInfo().limit,64);assert.deepEqual(first,render(w,{l:0,r:2,t:0,b:2},1).toBuffer('image/png'));Ground.reset();assert.equal(Ground.cacheInfo().tiles,0);});
