'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{boot127}=require('./helpers/expansions127.cjs'),{standAt}=require('./helpers/physical-fixtures.cjs'),C=require('../src/core.js'),G=require('../src/frontier-geometry.js'),S=require('../src/frontier-survey.js'),Pack=require('../src/interventions134.js');
function boot(){const e=boot127(),g=e.game;require('../src/world-pack131.js').install(g);Pack.install(g);g.startNew('standard','17117');g.phaseTime=999;return g;}
function pointFor(g,o){const w=g.frontier.world();for(let d=.4;d<4;d+=.2)for(let i=0;i<48;i++){const p={x:o.x+Math.cos(i*Math.PI/24)*d,y:o.y+Math.sin(i*Math.PI/24)*d,z:o.z,inside:o.poi};if(!w.blocked(p.x,p.y,.32,o.z,o.poi)&&S.targets(w,p,{},C.InterventionRules134.reach).some(t=>t.id===o.id))return p;}throw Error('Accès absent '+o.id);}
function visit(g,o,p=pointFor(g,o)){const d=g.serialize();Object.assign(d.frontier,{active:true,x:p.x,y:p.y,z:o.z,inside:o.poi,anchor:{x:g.player.x,y:g.player.y},car:null});if(!d.frontier.seen.includes(o.poi))d.frontier.seen.push(o.poi);const site=g.frontier.world().pois.find(p=>p.id===o.poi);for(let i=0;i<g.frontier.world().threatCount(site);i++)d.frontier.enemies[o.poi+':e'+i]=0;d.frontier.kills=Object.values(d.frontier.enemies).filter(v=>v===0).length;g.restoreSave(d);g.player.carry=C.makeBag({scrap:18,fuel:8,wood:2});return o;}
function generator(g){const w=g.frontier.world(),p=w.pois.find(p=>p.type==='generatorRoom'),o=w.plan(p,0).objects.find(o=>o.kind==='generator');return Pack.objectIn(w,o.id);}
function lock(g){const w=g.frontier.world();for(const p of w.pois.slice(0,100))for(const z of p.levels)for(const o of w.plan(p,z).objects){const q=Pack.objectIn(w,o.id);if(g.interventions134.blocksLoot(q)){try{pointFor(g,q);return q;}catch{}}}throw Error('No lock');}
function solve(g){while(g.interventions134.busy()){const s=g.interventions134.view().session;if(s.type==='panel'){for(let i=0;i<4;i++)if(s.switches[i]!==s.desired[i])g.interventions134.act('toggle',i);}else if(s.type==='generator')g.interventions134.act('adjust',s.target-s.dial);else{for(let i=0;i<s.notches&&g.interventions134.view().session.feedback!=='souple';i++)g.interventions134.act('adjust',1);}const q=g.interventions134.act('confirm');assert.ok(q.ok,q.reason);}}
test('134 : ancien registre migre vide sans matériaux offerts',()=>{const g=boot(),d=g.serialize(),bag={...g.player.carry};delete d.expansions127.modules.interventions134;g.restoreSave(d);assert.deepEqual(g.interventions134.snapshot(),Pack.initial());assert.deepEqual(g.player.carry,bag);});
test('134 : crochetage physique ouvre le vrai contenant et conserve le prélèvement fini',()=>{const g=boot(),o=visit(g,lock(g)),n=g.player.carry.scrap;assert.ok(g.interventions134.begin(o.id).ok);assert.equal(g.player.carry.scrap,n-1);assert.equal(g.expansions.busy('survival'),true);solve(g);assert.equal(g.interventions134.blocksLoot(o),false);const saved=g.serialize();g.restoreSave(saved);assert.equal(g.interventions134.blocksLoot(o),false);assert.equal(g.interventions134.begin(o.id).ok,false);assert.equal(g.player.carry.scrap,n-1);});
test('134 : modes falsifiés refusés avant toute dépense ou pollution de sauvegarde',()=>{const g=boot(),o=visit(g,lock(g)),before={...g.player.carry};for(const kind of ['generator','panel','bogus'])assert.equal(g.interventions134.begin(o.id,kind).ok,false);assert.deepEqual(g.player.carry,before);assert.deepEqual(g.interventions134.snapshot().plants,{});g.restoreSave(g.serialize());});
test('134 : trois erreurs usent la tentative ; annulation et reprise ne rendent pas les consommables',()=>{const g=boot(),o=visit(g,lock(g));assert.ok(g.interventions134.begin(o.id).ok);for(let i=0;i<3;i++){if(g.interventions134.view().session.feedback==='souple')g.interventions134.act('adjust',1);g.interventions134.act('confirm');}assert.equal(g.interventions134.busy(),false);assert.ok(g.interventions134.begin(o.id).ok);const saved=g.serialize(),scrap=g.player.carry.scrap;g.restoreSave(saved);assert.equal(g.interventions134.busy(),false);assert.equal(g.player.carry.scrap,scrap);assert.equal(g.interventions134.snapshot().attempts[o.id],2);});
test('134 : déplacement, étage, blessure et menace de succession interrompent le travail',()=>{const g=boot(),o=visit(g,lock(g));assert.ok(g.interventions134.begin(o.id).ok);g.player.health-=1;g.interventions134.step(.04);assert.equal(g.interventions134.busy(),false);g.player.health=100;assert.ok(g.interventions134.begin(o.id).ok);const position=g.frontier.position();g.succession133={contacts:()=>[{hp:80,z:position.z,poi:position.inside,x:position.x+1,y:position.y}]};g.interventions134.step(.04);assert.equal(g.interventions134.busy(),false);assert.equal(g.interventions134.begin(o.id).ok,false);});
test('134 : réparer, ravitailler, démarrer et distribuer alimentent réellement l’étage avec autonomie finie',()=>{const g=boot(),o=visit(g,generator(g));assert.ok(g.interventions134.begin(o.id).ok);solve(g);assert.equal(g.interventions134.snapshot().plants[o.id].condition,100);assert.equal(g.interventions134.powered(o.poi,0),false);assert.ok(g.interventions134.refuel(o.id).ok);assert.equal(g.interventions134.snapshot().plants[o.id].fuel,4);assert.ok(g.interventions134.toggle(o.id).ok);assert.equal(g.interventions134.refuel(o.id).ok,false);const fuel=g.interventions134.snapshot().plants[o.id].fuel;g.interventions134.step(.1);assert.ok(g.interventions134.snapshot().plants[o.id].fuel<fuel);const site=g.frontier.world().pois.find(p=>p.id===o.poi),point=G.global(site,site.w/2,1.1);visit(g,o,point);const panel=g.interventions134.nearby().find(t=>t.kind==='panel');assert.ok(panel);assert.ok(g.interventions134.begin(panel.id).ok);solve(g);assert.equal(g.interventions134.powered(o.poi,0),true);assert.ok(g.interventions134.lights().length>0);assert.equal(g.interventions134.harvestFactor({kind:'machine',poi:o.poi,z:0}),1.25);assert.equal(g.interventions134.harvestFactor({kind:'crate',poi:o.poi,z:0}),1);const d=g.serialize();g.restoreSave(d);assert.equal(g.interventions134.powered(o.poi,0),true);});
test('134 : pause ne consomme pas de carburant et panne éteint la lumière',()=>{const g=boot(),o=visit(g,generator(g));g.interventions134.begin(o.id);solve(g);g.interventions134.refuel(o.id);g.interventions134.toggle(o.id);g.paused=true;const before=g.interventions134.snapshot();g.interventions134.step(.1);assert.deepEqual(g.interventions134.snapshot(),before);g.paused=false;const d=g.serialize();d.expansions127.modules.interventions134.plants[o.id].fuel=.0005;g.restoreSave(d);g.interventions134.step(.1);assert.equal(g.interventions134.snapshot().plants[o.id].on,false);assert.equal(g.interventions134.snapshot().plants[o.id].fuel,0);});
test('134 : groupe D-17 répare ses vrais PV et utilise le sac, sans changer la production nominale',()=>{const g=boot(),b=new(g.core().constructor)(g.nextId++,'generator',75,72,0,1);g.world.add(b);g.fieldcraft.setup();b.health=200;standAt(g,g.player,b);g.player.carry=C.makeBag({scrap:12});const stock=g.resources.scrap,gen=b.def.powerGen;assert.ok(g.interventions134.begin('local:'+b.id).ok);solve(g);assert.equal(b.health,400);assert.equal(g.player.carry.scrap,6);assert.equal(g.resources.scrap,stock);assert.equal(b.def.powerGen,gen);});
test('134 : aucun effet distant, à travers les murs, en véhicule ou après décès',()=>{const g=boot(),o=generator(g);assert.equal(g.interventions134.begin(o.id).ok,false);visit(g,o);g.player.dead=true;assert.equal(g.interventions134.begin(o.id).ok,false);g.player.dead=false;g.player.carry.scrap=0;assert.equal(g.interventions134.begin(o.id).ok,false);});
test('134 : validation rejette groupes sur fausses cibles, étages inexistants et données non finies atomiquement',()=>{const g=boot(),o=visit(g,generator(g));g.interventions134.begin(o.id);solve(g);const data=g.serialize(),oldWorld=g.world;for(const transform of [d=>d.expansions127.modules.interventions134.plants[o.id].fuel=Infinity,d=>d.expansions127.modules.interventions134.panels=[o.poi+':panel:999'],d=>d.expansions127.modules.interventions134.plants[o.poi+':0:999']={fuel:1,on:true,condition:100}]){const bad=JSON.parse(JSON.stringify(data));transform(bad);assert.throws(()=>g.restoreSave(bad));assert.equal(g.world,oldWorld);}});
test('134 : débutants ne perdent pas les réserves déjà partiellement fouillées après migration',()=>{const g=boot(),o=visit(g,lock(g)),d=g.serialize();d.frontier.taken[o.id]=1;g.restoreSave(d);assert.equal(g.interventions134.blocksLoot(o),false);});
module.exports={boot,visit,generator,lock,solve,pointFor};
test('134 : ancien bouton de réserve redirigé au mini-jeu ; aucune attente ne contourne le verrou',()=>{const g=boot(),w=g.frontier.world(),p=w.pois.find(p=>p.frontier131?.reserve),o=visit(g,Pack.objectIn(w,p.frontier131.reserve));assert.ok(g.worldOps131.begin('reserve',p.id).ok);assert.equal(g.worldOps131.busy(),false);assert.equal(g.interventions134.busy(),true);assert.equal(g.worldOps131.completeInterventionReserve(p.id),false);for(let i=0;i<20;i++)g.worldOps131.step(1);assert.equal(g.worldOps131.opened(p.id),false);solve(g);assert.equal(g.worldOps131.opened(p.id),true);assert.equal(g.interventions134.blocksLoot(o),false);g.restoreSave(g.serialize());assert.equal(g.worldOps131.opened(p.id),true);});
test('134 : minuterie active de mini-jeu ne sérialise pas le carnet régional à chaque image',()=>{const g=boot(),o=visit(g,lock(g));assert.ok(g.interventions134.begin(o.id).ok);const old=g.frontier;g.frontier=Object.freeze({...old,snapshot:()=>{throw Error('Copie du carnet interdit durant mise à jour');}});g.interventions134.step(.04);g.interventions134.view();assert.equal(g.interventions134.busy(),true);g.frontier=old;});
test('134 : groupes en marche interdisent révision et démontage, sans être traités comme des verrous',()=>{const g=boot(),o=visit(g,generator(g));g.interventions134.begin(o.id);solve(g);g.interventions134.refuel(o.id);g.interventions134.toggle(o.id);assert.equal(g.interventions134.blocksLoot(o),true);assert.equal(g.interventions134.begin(o.id).ok,false);assert.equal(g.interventions134.nearby().find(t=>t.id===o.id).type,'generator');assert.ok(g.interventions134.actions().find(a=>a.id==='toggle-'+o.id));g.interventions134.toggle(o.id);assert.equal(g.interventions134.blocksLoot(o),false);});
