'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),T=require('../src/tactics.js'),L=require('../src/linecare.js');
const{bootGame}=require('./helpers/browser.cjs');
function fresh(){const env=bootGame();env.game.startNew('standard','17117');return env;}
function add(g,type,x,y,progress=1,rotation=0){const b=new(g.core().constructor)(g.nextId++,type,x,y,rotation,progress);g.world.add(b);return b;}
function ring(g,min,max,gap=null){const all=[];for(let y=min;y<=max;y++)for(let x=min;x<=max;x++)if(x===min||y===min||x===max||y===max){if(gap&&gap.x===x&&gap.y===y)continue;all.push(add(g,'woodWall',x,y));}return all;}
const bag=g=>JSON.stringify(g.resources);
const near=(g,b,outer=true)=>{const p=g.workerCleanupPoint(g.player,b);Object.assign(g.player,outer?p:{x:b.x,y:b.bottom+17});return p;};
function active(g){assert.equal(g.linecare.equip(),true);g.input.keys.add('KeyE');}
function stable(g){const x=g.serialize();delete x.timestamp;return JSON.stringify(x);}
test('lignes: règles centralisées et migration vers sauvegarde v10',()=>{assert.equal(C.SAVE_VERSION,20);assert.equal(L.RULES,C.LINECARE_RULES);assert.ok(Object.isFrozen(L.RULES));assert.equal(C.LINECARE_RULES.shovelPerSecond,1.2)});
test('lignes: un terrain ouvert produit une chaîne cardinale jusqu’au centre',()=>{const{game:g}=fresh(),d=g.linecare.geometry();assert.equal(d.reachable,true);assert.ok(d.path.length);const a=d.path[0],z=d.path.at(-1);assert.ok(a.x===0||a.y===0||a.x===127||a.y===127);assert.ok(z.x>=g.core().gx&&z.x<g.core().gx+4);for(let i=1;i<d.path.length;i++)assert.equal(Math.abs(d.path[i].x-d.path[i-1].x)+Math.abs(d.path[i].y-d.path[i-1].y),1)});
test('lignes: deux enceintes concentriques, une brèche ne supprime pas la seconde',()=>{const{game:g}=fresh();const inner=ring(g,59,68),outer=ring(g,54,73);assert.equal(g.linecare.geometry().reachable,false);g.world.remove(outer.find(b=>b.gx===63&&b.gy===54));assert.equal(g.linecare.geometry().reachable,false);g.world.remove(inner.find(b=>b.gx===63&&b.gy===59));const d=g.linecare.geometry();assert.equal(d.reachable,true);assert.ok(d.path.every(p=>!d.barrier[p.y*128+p.x]))});
test('lignes: porte automatique fermée aux hordes, ouverture réactive le tracé',()=>{const{game:g}=fresh();ring(g,58,69,{x:62,y:58});const wall=g.world.atCell(63,58);g.world.remove(wall);const gate=add(g,'gate',62,58);assert.equal(g.linecare.geometry().reachable,false);assert.equal(g.setGateMode('open',gate),true);assert.equal(g.linecare.geometry().reachable,true);assert.equal(g.setGateMode('closed',gate),true);assert.equal(g.linecare.geometry().reachable,false)});
test('lignes: mur incomplet ou détruit ne ferme pas le diagnostic',()=>{const{game:g}=fresh(),bs=ring(g,58,69);let b=bs.find(b=>b.gx===63&&b.gy===58);b.progress=.5;g.world.navigationVersion++;assert.equal(g.linecare.geometry().reachable,true);b.progress=1;g.world.navigationVersion++;assert.equal(g.linecare.geometry().reachable,false);g.destroyBuilding(b);assert.equal(g.linecare.geometry().reachable,true)});
test('lignes: grille bornée et centre absent sans chemin imaginaire',()=>{assert.throws(()=>L.traceAccess([],null,129,128),RangeError);assert.throws(()=>L.traceAccess([],null,NaN,128),RangeError);assert.equal(L.traceAccess([],null).hasCore,false);assert.deepEqual(L.traceAccess([],null).path,[])});
test('lignes: mêmes conclusions que le diagnostic historique sur 80 configurations',()=>{const{game:g}=fresh(),rnd=new C.Random(8128),Ctor=g.core().constructor;for(let n=0;n<80;n++){const bs=[g.core()];for(let y=57;y<=70;y++)for(let x=57;x<=70;x++)if(x===57||y===57||x===70||y===70){if(rnd.chance(.03))continue;const b=new Ctor(1000+bs.length,'woodWall',x,y,0,rnd.chance(.015)?.8:1);bs.push(b);}const d=L.traceAccess(bs,g.core());const legacy=T.analyzeEnclosure({buildings:bs,target:g.core()});assert.equal(d.reachable,legacy.coreReachable);assert.ok(d.visited<=16384)}});
test('lignes: classification des seuils stricts sans modifier les remparts',()=>{const{game:g}=fresh(),b=add(g,'woodWall',61,56);for(const [load,risk]of [[0,'none'],[15,'none'],[15.001,'some'],[32,'some'],[32.001,'all']]){b.corpseLoad=load;assert.equal(g.linecare.inspect().find(x=>x.id===b.id).risk,risk);assert.equal(b.corpseLoad,load)}b.health=b.maxHealth*.3;assert.equal(g.linecare.inspect()[0].critical,true)});
test('pelle: délai actif exact, intégrité et ressources inchangées',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=25;b.health=140;near(g,b);const money=bag(g),hp=b.health;active(g);for(let i=0;i<25;i++)g.linecare.clear(.04);assert.ok(Math.abs(b.corpseLoad-23.8)<1e-8);assert.equal(b.health,hp);assert.equal(bag(g),money)});
test('pelle: aucun déblaiement depuis le côté intérieur d’un mur',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=24;near(g,b,false);active(g);assert.equal(g.linecare.clear(.04),0);assert.equal(b.corpseLoad,24)});
test('pelle: un infecté visible suspend le travail',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=24;near(g,b);active(g);g.spawnZombie('walker');Object.assign(g.zombies[0],{x:g.player.x+25,y:g.player.y});assert.equal(g.linecare.clear(.04),0);assert.equal(b.corpseLoad,24);assert.match(g.interactionText,/Infectés proches/)});
test('pelle: pause, morts, E relâché et temps invalides ne retirent rien',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=24;near(g,b);active(g);for(const dt of [0,-1,NaN,Infinity,undefined])assert.equal(g.linecare.clear(dt),0);g.input.keys.clear();assert.equal(g.linecare.clear(.1),0);g.input.keys.add('KeyE');g.paused=true;assert.equal(g.linecare.clear(.1),0);g.paused=false;g.player.dead=true;assert.equal(g.linecare.clear(.1),0);assert.equal(b.corpseLoad,24)});
test('pelle: un grand pas ne nettoie pas toute une enceinte',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=20;near(g,b);active(g);g.linecare.clear(999);assert.ok(Math.abs(b.corpseLoad-19.7)<1e-8)});
test('pelle: armes interdites, changement d’outil sans conflit',()=>{const{game:g}=fresh();active(g);const n=g.player.magazine.pistol;g.shootPlayer();assert.equal(g.player.magazine.pistol,n);g.player.magazine.pistol=2;g.startReload();assert.equal(g.player.reload,0);g.siege.toggleTool();assert.equal(g.linecare.toolActive(),false);assert.equal(g.siege.toolActive(),true);assert.equal(g.linecare.equip(),true);assert.equal(g.siege.toolActive(),false);g.dayworks.setTool('survey');assert.equal(g.linecare.toolActive(),false);assert.equal(g.dayworks.overview().tool,'survey')});
test('pelle: alerte range l’outil, nuit interdit l’équipement',()=>{const{game:g}=fresh();active(g);g.phaseTime=.01;g.updateDirector(.04);assert.equal(g.phase,'warning');assert.equal(g.linecare.toolActive(),false);assert.equal(g.input.keys.size,0);assert.equal(g.linecare.equip(),false);g.phase='aftermath';assert.equal(g.linecare.equip(),true)});
test('pelle: Échap range, sans ouvrir immédiatement la pause',()=>{const{game:g}=fresh();active(g);g.onEscape();assert.equal(g.linecare.toolActive(),false);assert.equal(g.paused,false);g.onEscape();assert.equal(g.paused,true)});
test('pelle: dégâts nettoyés persistants, outil transitoire non sérialisé',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=22;near(g,b);active(g);g.linecare.clear(.2);const left=b.corpseLoad;g.save(false);g.load();assert.equal(g.world.buildings.get(b.id).corpseLoad,left);assert.equal(g.linecare.toolActive(),false);assert.equal(g.linecare.overview().overlay,false)});
test('nettoyage natif: temps non fini et cibles absentes sont refusés',()=>{const{game:g}=fresh(),b=add(g,'woodWall',63,57);b.corpseLoad=20;near(g,b);assert.equal(g.clearCorpsesWithWorker(g.player,b,Infinity),0);assert.equal(g.clearCorpsesWithWorker(null,b,.1),0);assert.equal(g.clearCorpsesWithWorker(g.player,null,.1),0);assert.equal(b.corpseLoad,20)});
test('devis: somme exacte des coûts individuels, aucune mutation avant accord',()=>{const{game:g}=fresh(),a=add(g,'woodWall',61,57),b=add(g,'steelWall',62,57);a.health=150;b.health=400;const expected={};for(const wall of [a,b])for(const[k,v]of Object.entries(g.structureActionStatus('repair',wall).cost))expected[k]=(expected[k]||0)+v;const money=bag(g),q=g.linecare.preview([a.id,b.id]);assert.equal(q.ok,true);assert.deepEqual(q.cost,expected);assert.equal(bag(g),money);assert.equal(a.health,150);const result=g.linecare.confirm();assert.equal(result.ok,true);assert.equal(a.health,a.maxHealth);assert.equal(b.health,b.maxHealth);assert.equal(g.linecare.confirm().ok,false)});
test('devis: amas inchangés et une seule structure choisie réparée',()=>{const{game:g}=fresh(),a=add(g,'woodWall',61,57),b=add(g,'woodWall',62,57);a.health=100;b.health=100;a.corpseLoad=25;assert.equal(g.linecare.preview([a.id]).ok,true);assert.equal(g.linecare.confirm().ok,true);assert.equal(a.corpseLoad,25);assert.equal(b.health,100)});
test('devis: coût changé, stocks insuffisants ou cible détruite font tout refuser',()=>{for(const mutate of [(g,a)=>a.health-=1,(g)=>g.resources.scrap=0,(g,a)=>g.destroyBuilding(a)]){const{game:g}=fresh(),a=add(g,'woodWall',61,57),b=add(g,'woodWall',62,57);a.health=100;b.health=100;g.linecare.preview([a.id,b.id]);mutate(g,a);const money=bag(g);assert.equal(g.linecare.confirm().ok,false);assert.equal(b.health,100);assert.equal(bag(g),money)}});
test('devis: sélection répétée, trop grande, intacte ou autre bâtiment refusée',()=>{const{game:g}=fresh(),a=add(g,'woodWall',61,57);a.health=100;for(const ids of [[],[a.id,a.id],[g.core().id],[999999],Array(33).fill(a.id),['1'],null])assert.equal(g.linecare.preview(ids).ok,false);a.health=a.maxHealth;assert.equal(g.linecare.preview([a.id]).ok,false)});
test('devis: nouvelle campagne, reprise et menu annulent les confirmations',()=>{for(const transition of [g=>g.startNew('standard','99'),g=>g.restoreSave(g.serialize()),g=>g.returnToMenu()]){const{game:g}=fresh(),a=add(g,'woodWall',61,57);a.health=100;g.linecare.preview([a.id]);transition(g);assert.equal(g.linecare.overview().pending,null);assert.equal(g.linecare.confirm().ok,false)}});
test('inspection: lecture répétée sans dépense, récompense ou ordre',()=>{const{game:g}=fresh();add(g,'woodWall',61,57).corpseLoad=30;const before=stable(g);for(let i=0;i<50;i++)g.linecare.overview();assert.equal(stable(g),before)});
test('inspection: cache réutilisé, invalidation après modification de navigation',()=>{const{game:g}=fresh(),a=g.linecare.geometry();assert.equal(a,g.linecare.geometry());add(g,'woodWall',61,57);assert.notEqual(a,g.linecare.geometry());g.linecare.setOverlay(true);g.startNew();assert.equal(g.linecare.overview().overlay,false)});
test('lignes: retirer seulement le coin ne crée pas de passage cardinal',()=>{const{game:g}=fresh();ring(g,58,69);g.world.remove(g.world.atCell(58,58));assert.equal(g.linecare.geometry().reachable,false)});
test('pelle: les outils de voirie rendent la main sans travaux gratuits',()=>{const{game:g}=fresh();const before=stable(g);assert.equal(g.infrastructure.equip(),true);assert.equal(g.infrastructure.toolActive(),true);assert.equal(g.linecare.equip(),true);assert.equal(g.infrastructure.toolActive(),false);assert.equal(g.linecare.toolActive(),true);assert.equal(stable(g),before)});
test('devis: mutation de la copie retournée ne peut pas réduire le paiement',()=>{const{game:g}=fresh(),b=add(g,'woodWall',61,57);b.health=100;const expected=g.structureActionStatus('repair',b).cost,stock={...g.resources};const q=g.linecare.preview([b.id]);q.cost.scrap=0;const view=g.linecare.overview();view.pending.cost.wood=0;assert.equal(g.linecare.confirm().ok,true);for(const[k,v]of Object.entries(expected))assert.equal(g.resources[k],stock[k]-v)});
