'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs');
const L=require('../src/loadout129.js'),UI=require('../src/loadout-ui129.js');
function fixture(ui=false){const e=boot127(),g=e.game;g.startNew('standard','17117');L.install(g);g.save=()=>true;if(ui)UI.install(g,document);return{...e,g};}
function home(g){const c=g.core();for(let a=0;a<32;a++){const p={x:c.x+Math.cos(a)*90,y:c.y+Math.sin(a)*90};Object.assign(g.player,p);if(g.workerCanWorkAt(g.player,c,100))return;}throw Error('No accessible depot');}
test('loadout: shape stacks conserve every fractional resource and weight',()=>{const b={wood:13.5,scrap:4.25,stone:8,food:2,fuel:3,ammo:2,medicine:1.25},p=L.pack(b,36);assert.equal(p.overflow.length,0);for(const k of Object.keys(b))assert.equal(p.items.filter(i=>i.key===k).reduce((n,i)=>n+i.quantity,0),b[k]);assert.equal(L.mass(b),13.5*.25+4.25*.2+8*.35+2*.15+3*.2+2*.02+1.25*.08);});
test('loadout: all pure-resource bags at normal and vehicle capacities fit',()=>{for(const capacity of [4,12,18,36,55,80,140,210,260])for(const key of ['wood','scrap','stone','food','fuel','ammo','medicine'])assert.equal(L.pack({[key]:capacity},capacity).overflow.length,0,capacity+' '+key);});
test('loadout: placement and rotation persist without changing quantities',()=>{const{g}=fixture();g.player.carry.wood=8;const q=g.loadout.move('sac','wood:0',4,2,1);assert.equal(q.ok,true);const snapshot=g.serialize();assert.equal(snapshot.player.carry.wood,8);g.restoreSave(snapshot);const i=g.loadout.view().items.find(i=>i.id==='wood:0');assert.deepEqual([i.x,i.y,i.w,i.h],[4,2,1,2]);assert.equal(g.player.carry.wood,8);});
test('loadout: collisions, fractional cells and out-of-bounds placements are refused',()=>{const{g}=fixture();g.player.carry.wood=8;g.player.carry.stone=6;g.loadout.move('sac','wood:0',5,4,0);g.loadout.move('sac','stone:0',3,0,0);const before=g.loadout.snapshot();for(const args of [[3,0,0],[7,0,0],[.5,0,0],[0,-1,0],[0,0,3]])assert.equal(g.loadout.move('sac','wood:0',...args).ok,false);assert.deepEqual(g.loadout.snapshot(),before);});
test('loadout: collection and consumption reconcile layouts without inventing resources',()=>{const{g}=fixture();g.player.carry.food=8;g.loadout.move('sac','food:0',5,2,1);g.player.carry.food=9.25;let v=g.loadout.view();assert.equal(v.items.reduce((n,i)=>n+i.quantity,0),9.25);assert.deepEqual(v.items.find(i=>i.id==='food:0').x,5);g.player.carry.food=0;v=g.loadout.view();assert.equal(v.items.length,0);assert.equal(g.loadout.snapshot().layouts.length,0);});
test('loadout: bad layout is rejected transactionally before world replacement',()=>{const{g}=fixture();g.player.carry.wood=8;const good=g.serialize(),world=g.world;for(const mutate of [s=>s.loadout129.extra=1,s=>s.loadout129.layouts.push({container:'sac',item:'wood:0',x:8,y:0,rotation:0}),s=>s.loadout129.layouts[0].item='credits:0',s=>s.loadout129.layouts.push({...s.loadout129.layouts[0]})]){const bad=structuredClone(good);mutate(bad);assert.throws(()=>g.restoreSave(bad),/Rangement/);assert.equal(g.world,world);assert.equal(g.player.carry.wood,8);}});
test('loadout: legacy save migrates to empty layout without material gifts',()=>{const{g}=fixture();g.player.carry.medicine=1.125;const s=g.serialize();delete s.loadout129;g.restoreSave(s);assert.equal(g.player.carry.medicine,1.125);assert.equal(g.loadout.view().items[0].quantity,1.125);});
test('loadout: new campaign clears layout, invalid seed keeps campaign intact',()=>{const{g}=fixture();g.player.carry.wood=8;g.loadout.move('sac','wood:0',5,3,0);const before=g.world;g.startNew('standard','not a seed');assert.equal(g.world,before);assert.equal(g.loadout.snapshot().layouts[0].x,5);g.startNew('standard','1212');assert.equal(g.loadout.snapshot().layouts.length,0);});
test('loadout: depot transfers conserve quantity, capacity and statistics',()=>{const{g}=fixture();home(g);const start=g.resources.wood;let r=g.loadout.transfer('depot','sac','wood',8);assert.equal(r.ok,true,r.reason);assert.equal(g.resources.wood,start-8);assert.equal(g.player.carry.wood,8);g.resources.wood=g.storage-2;const total=g.player.carry.wood+g.resources.wood;r=g.loadout.transfer('sac','depot','wood',8);assert.equal(r.amount,2);assert.equal(g.player.carry.wood,6);assert.equal(g.resources.wood,g.storage);assert.equal(g.resources.wood+g.player.carry.wood,total);});
test('loadout: depot cannot be accessed remotely, while dead, driving or during work',()=>{const{g}=fixture();home(g);g.player.carry.food=5;g.player.x=20;assert.equal(g.loadout.transfer('sac','depot','food',1).ok,false);home(g);g.player.dead=true;assert.equal(g.loadout.transfer('sac','depot','food',1).ok,false);g.player.dead=false;const ex=g.expansions;g.expansions={...ex,busy:()=>true};assert.equal(g.loadout.transfer('sac','depot','food',1).ok,false);assert.equal(g.player.carry.food,5);});
test('loadout: refuses invalid quantities and unknown or prototype resource keys',()=>{const{g}=fixture();home(g);const before=JSON.stringify(g.resources);for(const n of [-1,0,NaN,Infinity])assert.equal(g.loadout.transfer('depot','sac','wood',n).ok,false);for(const key of ['__proto__','constructor','money'])assert.equal(g.loadout.transfer('depot','sac',key,1).ok,false);assert.equal(JSON.stringify(g.resources),before);});
test('loadout: only available weapons can be equipped, reloading stays protected',()=>{const{g}=fixture();assert.equal(g.loadout.equipWeapon('rifle').ok,false);g.tier={id:2};assert.equal(g.loadout.equipWeapon('rifle').ok,true);assert.equal(g.player.weapon,'rifle');g.player.reload=1;assert.equal(g.loadout.equipWeapon('pistol').ok,false);assert.equal(g.player.weapon,'rifle');});
test('loadout: modal uses actual bag, preserves pause and closes cleanly',()=>{const{g}=fixture(true);g.player.carry.wood=8;assert.equal(g.loadoutUI.open(),true);assert.equal(g.paused,true);assert.equal(g.activeOverlay,g.loadoutUI.overlay);assert.equal(g.ui.hud.inert,true);assert.equal(g.canIssueCommand(),true);assert.equal(g.loadoutUI.overlay.querySelectorAll('button').filter(x=>x.dataset.item==='wood:0').length,1);assert.equal(g.loadoutUI.close(),true);assert.equal(g.paused,false);assert.equal(g.activeOverlay,null);g.togglePause(true);assert.equal(g.loadoutUI.open(),true);g.loadoutUI.close();assert.equal(g.paused,true);assert.equal(g.activeOverlay,g.ui.pauseMenu);});
test('loadout: keyboard move and rotation operate grid and preserve focus',()=>{const{g}=fixture(true);g.player.carry.wood=8;g.loadoutUI.open();let b=g.loadoutUI.overlay.querySelectorAll('button').find(x=>x.dataset.item==='wood:0');b.focus();b.dispatch('keydown',{code:'ArrowRight'});let item=g.loadout.view().items[0];assert.equal(item.x,1);b=g.loadoutUI.overlay.querySelectorAll('button').find(x=>x.dataset.item==='wood:0');assert.equal(document.activeElement,b);b.dispatch('keydown',{code:'KeyR'});item=g.loadout.view().items[0];assert.equal(item.rotation,1);assert.equal(item.w,1);assert.equal(item.h,2);});
test('loadout: modal rejects dead player, closes on menu and avoids hidden rebuilds',()=>{const{g}=fixture(true);g.player.dead=true;assert.equal(g.loadoutUI.open(),false);g.player.dead=false;g.loadoutUI.open();g.returnToMenu();assert.equal(g.loadoutUI.isOpen(),false);assert.equal(g.loadoutUI.refresh(true),false);});
function carFixture(){const {g}=fixture();g.world.add(new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1));g.refreshMetrics(true);g.fieldcraft.setup();home(g);g.resources.wood=g.resources.scrap=300;assert.equal(g.expeditions.buildCar().ok,true);const car=g.expeditions.car();let access=false;for(let i=0;i<24;i++){g.player.x=car.x+Math.cos(i*Math.PI/12)*60;g.player.y=car.y+Math.sin(i*Math.PI/12)*60;if(!g.loadout.access({id:'car:'+car.id})){access=true;break;}}assert.equal(access,true,'vehicle has an accessible side');return{g,car};}
test('loadout: vehicle transfers in both directions preserve authoritative cargo',()=>{const{g,car}=carFixture(),id='car:'+car.id;g.player.carry.wood=20;assert.equal(g.loadout.transfer('sac',id,'wood',12).ok,true);assert.equal(car.cargo.wood,12);assert.equal(g.player.carry.wood,8);assert.equal(g.loadout.transfer(id,'sac','wood',4).ok,true);assert.equal(car.cargo.wood,8);assert.equal(g.player.carry.wood,12);const before=g.serialize();g.restoreSave(before);assert.equal(g.expeditions.car().cargo.wood,8);assert.equal(g.player.carry.wood,12);});
test('loadout: vehicle capacity, remoteness, driving and destruction deny transfers',()=>{const{g,car}=carFixture(),id='car:'+car.id;car.cargo.wood=79;g.player.carry.scrap=5;const moved=g.loadout.transfer('sac',id,'scrap',5);assert.equal(moved.amount,1,moved.reason);assert.equal(g.player.carry.scrap,4);car.driving=true;assert.equal(g.loadout.transfer(id,'sac','wood',1).ok,false);car.driving=false;g.player.x+=200;assert.equal(g.loadout.transfer(id,'sac','wood',1).ok,false);g.player.x=car.x+35;car.health=0;assert.equal(g.loadout.transfer(id,'sac','wood',1).ok,false);});
test('loadout: companion pouch is selective, bounded and bidirectional',()=>{const{g}=fixture();g.worldEvolution.enableWorld4();g.population=10;g.resources.food=g.resources.scrap=100;assert.equal(g.worldEvolution.assignCompanion('samir'),true);home(g);g.player.carry.ammo=12;g.player.carry.food=4;let r=g.loadout.transfer('sac','companion:samir','ammo',10);assert.equal(r.ok,true,r.reason);assert.equal(r.amount,8);assert.equal(g.companionsPack.snapshot().reserves.samir.ammo,8);assert.equal(g.player.carry.ammo,4);assert.equal(g.loadout.transfer('sac','companion:samir','food',4).ok,false);r=g.loadout.transfer('companion:samir','sac','ammo',3);assert.equal(r.amount,3);assert.equal(g.companionsPack.snapshot().reserves.samir.ammo,5);assert.equal(g.player.carry.ammo,7);assert.equal(g.player.carry.food,4);});
test('loadout: belt snapshot exposes real quantities without producing or consuming kits',()=>{const{g}=fixture();const before=g.essentials.snapshot();const e=g.loadout.equipment();assert.equal(e.beltCount,0);assert.equal(e.heavy,null);assert.deepEqual(g.essentials.snapshot(),before);assert.equal(e.weapons.filter(w=>w.available).length,1);});
test('loadout: modal makes detached regional docks inert and restores their state',()=>{const{g}=fixture(true);const dock=document.createElement('section'),busy=document.createElement('section');busy.inert=true;document.body.appendChild(dock);document.body.appendChild(busy);g.loadoutUI.open();assert.equal(dock.inert,true);assert.equal(busy.inert,true);g.loadoutUI.close();assert.equal(dock.inert,false);assert.equal(busy.inert,true);});
test('loadout: action focus is restored after weapon selection',()=>{const{g}=fixture(true);g.tier={id:2};g.loadoutUI.open();let b=g.loadoutUI.overlay.querySelectorAll('button').find(x=>x.dataset.action==='weapon:rifle');b.focus();b.click();assert.equal(g.player.weapon,'rifle');b=g.loadoutUI.overlay.querySelectorAll('button').find(x=>x.dataset.action==='weapon:rifle');assert.equal(document.activeElement,b);});
test('loadout: emptied selected pile returns focus to a live modal control',()=>{const{g}=fixture(true);g.player.carry.wood=8;g.loadoutUI.open();const b=g.loadoutUI.overlay.querySelectorAll('button').find(x=>x.dataset.item==='wood:0');b.focus();g.player.carry.wood=0;g.loadoutUI.refresh(true);assert.equal(g.loadoutUI.overlay.contains(document.activeElement),true);assert.match(document.activeElement.textContent,/FERMER/);});
test('loadout: real autosave validates fractional contents and restores grid metadata',()=>{const e=boot127(),g=e.game;g.startNew('standard','17117');L.install(g);g.player.carry.food=3.125;assert.equal(g.loadout.move('sac','food:0',4,3,1).ok,true);assert.equal(g.lastSaveStatus.ok,true);const raw=[...e.storage.values()].map(text=>{try{return JSON.parse(text);}catch{return null;}}).find(s=>s?.loadout129&&s.player?.carry?.food===3.125);assert.ok(raw);assert.equal(raw.loadout129.layouts.find(p=>p.item==='food:0').rotation,1);g.player.carry.food=0;g.restoreSave(raw);assert.equal(g.player.carry.food,3.125);const item=g.loadout.view().items[0];assert.deepEqual([item.x,item.y,item.rotation],[4,3,1]);});
test('loadout: resource weight ceiling is compatible with every existing portion capacity',()=>{const C=require('../src/core.js');for(const d of Object.values(C.LoadoutRules.resources))assert.ok(d.kg<=C.LoadoutRules.massPerCapacity);for(const capacity of [12,36,80,260])for(const key of C.RESOURCE_KEYS)assert.ok(L.mass({[key]:capacity})<=capacity*C.LoadoutRules.massPerCapacity+1e-9);});
