'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const{boot127}=require('./helpers/expansions127.cjs');
const L=require('../src/loadout129.js'),UI=require('../src/loadout-ui129.js');
function fixture(beforeInstall){const e=boot127(),g=e.game,doc=globalThis.document;const proto=Object.getPrototypeOf(doc.body);Object.defineProperty(proto,'className',{set(v){this.classList.values=new Set(String(v).split(/\s+/).filter(Boolean));},get(){return[...this.classList.values].join(' ');}});g.startNew('standard','17117');g.save=()=>true;beforeInstall?.(g);L.install(g);UI.install(g,doc);return{...e,g,doc};}
function atHome(g){const c=g.core();for(let a=0;a<32;a++){Object.assign(g.player,{x:c.x+Math.cos(a)*90,y:c.y+Math.sin(a)*90});if(g.workerCanWorkAt(g.player,c,100))return;}throw Error('Dépôt inaccessible');}

test('QA croisée : restauration refusée conserve le rangement courant',()=>{const{g}=fixture(g=>{g.restoreSave=()=>false;});g.player.carry.wood=8;assert.equal(g.loadout.move('sac','wood:0',4,2,1).ok,true);const before=g.loadout.snapshot(),raw=g.serialize();raw.loadout129.layouts[0].x=1;assert.equal(g.restoreSave(raw),false);assert.deepEqual(g.loadout.snapshot(),before);});

test('QA croisée : contrôle régional derrière inventaire inerte dès ouverture',()=>{const{g,doc,elements}=fixture();const dock=doc.createElement('section'),tray=doc.createElement('div'),b=doc.createElement('button');dock.id='fieldDock';dock.classList.add('field-dock');tray.id='fieldUtilityTray';elements.set(dock.id,dock);elements.set(tray.id,tray);tray.appendChild(b);dock.appendChild(tray);doc.body.appendChild(dock);g.loadoutUI.open();assert.ok(b.closest('[inert]'),'Le dock hors HUD doit être inerte pendant équipement');g.loadoutUI.close();assert.equal(g.ui.hud.inert,false);});

test('QA croisée : ouverture depuis commandement rend la modale et sa pause préalable',()=>{const{g}=fixture();const path=require.resolve('../src/command-ui.js');delete require.cache[path];require(path);g.showCommand(true,'workers');assert.equal(g.activeOverlay,g.ui.commandModal);assert.equal(g.paused,true);g.loadoutUI.open();assert.equal(g.activeOverlay,g.loadoutUI.overlay);g.loadoutUI.close();assert.equal(g.activeOverlay,g.ui.commandModal);assert.equal(g.paused,true);g.showCommand(false);assert.equal(g.paused,false);});

test('QA croisée : panneau stable pendant consultation sans changement du modèle',()=>{const{g}=fixture();g.player.carry.wood=9.25;g.loadoutUI.open();const before=g.loadoutUI.overlay.querySelectorAll('button');for(let i=0;i<500;i++)g.loadoutUI.refresh();const after=g.loadoutUI.overlay.querySelectorAll('button');assert.equal(after.length,before.length);for(let i=0;i<after.length;i++)assert.equal(after[i],before[i]);assert.equal(g.player.carry.wood,9.25);});

test('QA croisée : action dépôt répétable au clavier ne laisse pas de focus détaché',()=>{const{g,doc}=fixture();atHome(g);g.loadoutUI.open();const b=g.loadoutUI.overlay.querySelectorAll('button').find(b=>b.textContent==='+ 8');assert.ok(b);b.focus();b.click();assert.equal(g.player.carry.wood,8);assert.ok(g.loadoutUI.overlay.contains(doc.activeElement),'Le focus doit rester dans la modale après reconstruction');assert.ok(doc.body.contains(doc.activeElement),'Le contrôle ciblé doit toujours appartenir au document');});

test('QA croisée : nouvelle campagne depuis équipement ne conserve pas une pause orpheline',()=>{const{g}=fixture();g.paused=true;g.ui.pauseMenu.classList.remove('hidden');g.syncOverlayFocus();g.loadoutUI.open();g.startNew('standard','18294');assert.equal(g.loadoutUI.isOpen(),false);assert.equal(g.paused,false);assert.equal(g.activeOverlay,null);assert.equal(g.world.seed,18294);});

test('QA croisée : restauration réussie ferme ancien équipement sans réinjecter sa pause',()=>{const{g}=fixture();const raw=g.serialize();g.paused=true;g.ui.pauseMenu.classList.remove('hidden');g.syncOverlayFocus();g.loadoutUI.open();g.restoreSave(raw);assert.equal(g.loadoutUI.isOpen(),false);assert.equal(g.paused,false);assert.equal(g.activeOverlay,null);});

test('QA croisée : sauvegarder sac fermé ne génère pas la région pour lire les sacoches',()=>{const{g}=fixture();g.worldEvolution={...g.worldEvolution,overview(){throw Error('Le rangement ne doit pas consulter la géométrie régionale.');}};assert.doesNotThrow(()=>g.serialize());});

test('QA croisée : I depuis carte locale ouvre un seul équipement, Échap rend le terrain',()=>{const{g,dispatchDocument}=fixture();dispatchDocument('keydown',{code:'KeyM'});assert.equal(g.exploration125.overlayOpen(),true);dispatchDocument('keydown',{code:'KeyI'});assert.equal(g.exploration125.overlayOpen(),false);assert.equal(g.loadoutUI.isOpen(),true);assert.equal(g.activeOverlay,g.loadoutUI.overlay);g.loadoutUI.overlay.dispatch('keydown',{code:'Escape'});assert.equal(g.loadoutUI.isOpen(),false);assert.equal(g.paused,false);assert.equal(g.activeOverlay,null);assert.equal(g.input.pressed.has('KeyI'),false);});
