'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs');
const {standAt}=require('./helpers/physical-fixtures.cjs');
const C=require('../src/core.js'),N=require('../src/night-gear.js'),Save=require('../src/save.js');
function fresh(){const {game:g}=bootGame();N.install(g);g.startNew('standard','17117');standAt(g,g.player,g.core());g.resources.wood=g.resources.stone=g.resources.scrap=g.resources.fuel=400;return g;}
function step(g,seconds){for(let i=0;i<Math.ceil(seconds/.04);i++){g.update(.04);g.input.pressed.clear();}}
function craft(g,kind){assert.equal(g.nightGear.craft(kind).ok,true,kind);step(g,C.NightGearRules.craftSeconds);return g.nightGear.snapshot().devices.at(-1);}
function unlock(g){const t=g.essentials.targets().find(t=>t.family==='light'),d=g.serialize();d.frontier.seen=[...d.frontier.seen,t.poi];d.essentials.jobs[t.id]={stage:'delivered'};g.restoreSave(d);standAt(g,g.player,g.core());}
function outside(g){g.player.x=2200;g.player.y=2400;g.player.facing=0;}
test('nuits : huit équipements distincts, migration vide et aucune récompense au chargement',()=>{const g=fresh();assert.equal(Object.keys(C.NightGearRules.types).length,8);const raw=g.serialize();delete raw.nightGear;const before={...raw.resources};g.restoreSave(raw);assert.deepEqual(g.nightGear.snapshot(),N.initial());assert.deepEqual(g.resources,before);assert.deepEqual(Save.validate(raw).nightGear,N.initial());});
test('nuits : fabrication temporisée, paiement unique et annulation sans coût',()=>{const g=fresh(),before=g.resources.wood;assert.ok(g.nightGear.craft('torch').ok);step(g,1);assert.equal(g.nightGear.snapshot().devices.length,0);g.input.keys.add('KeyD');step(g,.04);g.input.keys.clear();assert.equal(g.nightGear.overview().task,null);assert.equal(g.resources.wood,before);standAt(g,g.player,g.core());const d=craft(g,'torch');assert.equal(d.location,'stock');assert.equal(g.resources.wood,before-4);assert.equal(g.resources.fuel,398);});
test('nuits : recettes industrielles raccordées aux modules essentiels, fabrication puis équipement',()=>{const g=fresh();assert.equal(g.nightGear.craft('chemlight').ok,false);unlock(g);for(const kind of ['flare','chemlight','worklight','beacon']){const d=craft(g,kind);assert.ok(g.nightGear.transfer(d.id,'equip').ok);}assert.equal(g.nightGear.beltCount(),4);});
test('nuits : allumage porté, une source maximum, pose/reprise et masques locaux',()=>{const g=fresh(),a=craft(g,'torch'),b=craft(g,'lantern');g.nightGear.transfer(a.id,'equip');g.nightGear.transfer(b.id,'equip');assert.ok(g.nightGear.ignite(a.id).ok);assert.equal(g.nightGear.ignite(b.id).ok,false);assert.ok(g.nightwatch.sources(false).some(s=>s.id==='gear-'+a.id));outside(g);assert.ok(g.nightGear.place(a.id).ok);assert.ok(g.nightGear.ignite(b.id).ok);assert.equal(g.nightGear.pickup(a.id).ok,false);g.nightGear.ignite(b.id);assert.ok(g.nightGear.pickup(a.id).ok);assert.equal(g.nightGear.snapshot().devices.find(d=>d.id===a.id).location,'belt');});
test('nuits : autonomie exacte à la reprise, pause sans usure et recharge payée',()=>{const g=fresh(),d=craft(g,'lantern');g.nightGear.transfer(d.id,'equip');g.nightGear.ignite(d.id);step(g,2);const left=g.nightGear.snapshot().devices[0].left;g.paused=true;step(g,3);assert.equal(g.nightGear.snapshot().devices[0].left,left);g.paused=false;assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.nightGear.snapshot().devices[0].left,left);g.nightGear.ignite(d.id);standAt(g,g.player,g.core());const fuel=g.resources.fuel;assert.ok(g.nightGear.refill(d.id).ok);assert.equal(g.resources.fuel,fuel-3);assert.equal(g.nightGear.snapshot().devices[0].left,360);assert.equal(g.nightGear.refill(d.id).ok,false);});
test('nuits : ceinture commune bloque kits et équipements au neuvième emplacement',()=>{const g=fresh();unlock(g);const raw=g.serialize();raw.essentials.belt.light=8;g.restoreSave(raw);standAt(g,g.player,g.core());const d=craft(g,'torch');assert.equal(g.nightGear.transfer(d.id,'equip').ok,false);g.essentials.transferKit('light','store');assert.ok(g.nightGear.transfer(d.id,'equip').ok);assert.equal(g.essentials.transferKit('light','equip').ok,false);const bad=g.serialize();bad.essentials.belt.light=8;assert.throws(()=>g.restoreSave(bad));});
test('nuits : foyer extérieur posé, extinction et ravitaillement avec le bois du sac',()=>{const g=fresh(),d=craft(g,'campfire');g.nightGear.transfer(d.id,'equip');assert.equal(g.nightGear.ignite(d.id).ok,false);outside(g);assert.ok(g.nightGear.place(d.id).ok);assert.ok(g.nightGear.ignite(d.id).ok);step(g,2);assert.equal(g.nightGear.pickup(d.id).ok,false);assert.ok(g.nightGear.ignite(d.id).ok);g.player.carry.wood=8;assert.ok(g.nightGear.refill(d.id).ok);assert.equal(g.player.carry.wood,0);assert.equal(g.nightGear.snapshot().devices[0].left,300);});
test('nuits : matériel portable suit le passage région et la lampe posée reste dans son domaine',()=>{const g=fresh(),d=craft(g,'lantern');g.nightGear.transfer(d.id,'equip');g.nightGear.ignite(d.id);g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());assert.equal(g.nightGear.lights('local').filter(l=>l.kind==='lantern').length,0);const light=g.nightGear.lights('region').find(l=>l.kind==='lantern');assert.ok(light);assert.ok(Math.abs(light.x-g.frontier.snapshot().x)<.001);assert.ok(g.nightGear.place(d.id).ok);const p=g.nightGear.snapshot().devices[0];g.save(false);g.load();assert.deepEqual(g.nightGear.snapshot().devices[0],p);});
test('nuits : objets invalides rejetés avant mutation et identifiants uniques',()=>{const g=fresh();craft(g,'torch');const before=g.serialize();for(const mutate of [d=>d.devices.push({...d.devices[0]}),d=>d.devices[0].left=1e8,d=>d.devices[0].kind='__proto__',d=>d.devices[0].on=true,d=>d.serial=1]){const raw=g.serialize();mutate(raw.nightGear);assert.throws(()=>g.restoreSave(raw));assert.deepEqual(g.nightGear.snapshot(),before.nightGear);assert.deepEqual(g.resources,before.resources);}});
test('nuits : pluie accélère flammes sans altérer chemlights étanches',()=>{const g=fresh();unlock(g);const a=craft(g,'torch'),b=craft(g,'chemlight');g.nightGear.transfer(a.id,'equip');g.nightGear.transfer(b.id,'equip');outside(g);g.nightGear.ignite(a.id);g.nightGear.place(a.id);g.nightGear.ignite(b.id);g.weather=1;g.nightGear.step(1);const devices=g.nightGear.snapshot().devices;assert.ok(devices[0].left<179.8);assert.equal(devices[1].left,359.9);});
test('nuits : les consommables expirent et les appareils réutilisables restent récupérables',()=>{const g=fresh();unlock(g);const a=craft(g,'chemlight'),b=craft(g,'lantern');const raw=g.serialize();for(const d of raw.nightGear.devices){d.location='placed';Object.assign(d,{domain:'local',x:2200+d.id*45,y:2400,z:0,inside:null,angle:0,left:.02,on:true,used:true});}g.restoreSave(raw);g.nightGear.step(.04);const all=g.nightGear.snapshot().devices;assert.equal(all.length,1);assert.equal(all[0].id,b.id);assert.equal(all[0].left,0);assert.equal(all[0].on,false);});
test('nuits : fabrication de fortune régionale prend et paie le sac',()=>{const g=fresh();g.player.x=4058;g.player.y=2048;g.frontier.enter();g.player.carry.wood=2;g.player.carry.fuel=1;assert.ok(g.nightGear.craft('branch').ok);step(g,5);assert.equal(g.nightGear.snapshot().devices[0].location,'belt');assert.equal(g.player.carry.wood,0);assert.equal(g.player.carry.fuel,0);});
test('nuits : les murs G4 occultent une source sans fermer sa porte',()=>{const g=fresh();g.wave=4;g.phase='assault';g.exploration125={generation:4,plan:{solids:[{kind:'station-wall',x:2390,y:2350,w:5,h:40},{kind:'station-wall',x:2390,y:2410,w:5,h:40}]}};const lamp={id:'test',x:2370,y:2400,r:200,angle:0,half:Math.PI};assert.equal(g.nightwatch.lit({x:2420,y:2400},[lamp]),true,'porte libre');assert.equal(g.nightwatch.lit({x:2420,y:2360},[lamp]),false,'mur mince opaque');});
test('nuits : une nouvelle partie vide le matériel avant sa première sauvegarde',()=>{const g=fresh();craft(g,'torch');g.startNew('standard','18118');assert.deepEqual(g.nightGear.snapshot(),N.initial());assert.ok(g.load());assert.deepEqual(g.nightGear.snapshot(),N.initial());});
test('nuits : improvisation permise pendant l’assaut, atelier indisponible et horde proche refusée',()=>{const g=fresh();g.worldEvolution.enableWorld4();g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());g.player.carry.wood=20;g.player.carry.fuel=8;g.player.carry.stone=4;g.phase='assault';g.phaseTime=999;assert.ok(g.nightGear.previewCraft('branch').ok);assert.ok(g.nightGear.previewCraft('torch').ok);assert.ok(g.nightGear.previewCraft('campfire').ok);assert.equal(g.nightGear.previewCraft('lantern').ok,false);const before=g.player.carry.wood;assert.ok(g.nightGear.craft('branch').ok);step(g,5);assert.equal(g.nightGear.snapshot().devices[0].kind,'branch');assert.equal(g.player.carry.wood,before-2);const raw=g.serialize(),p=raw.frontier;raw.phase='assault';raw.phaseTime=999;raw.worldEvolution.groups=[{id:'W0000',kind:'resting',count:80,lost:0,wound:0,x:p.x+14,y:p.y,a:0,seen:false}];raw.worldEvolution.serial=Math.max(1,raw.worldEvolution.serial);g.restoreSave(raw);const carry={...g.player.carry};assert.equal(g.nightGear.previewCraft('torch').ok,false);assert.equal(g.nightGear.craft('torch').ok,false);assert.deepEqual(g.player.carry,carry);});
