'use strict';const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),C=require('../src/core.js'),W=require('../src/frontier-world.js'),G=require('../src/frontier-geometry.js'),P=require('../src/frontier-places.js'),Routing=require('../src/frontier-routing.js'),Save=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs'),reference=require('./fixtures/frontier115-fingerprints.json');
const h=o=>crypto.createHash('sha256').update(JSON.stringify(o)).digest('hex'),copy=o=>JSON.parse(JSON.stringify(o));function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function enter(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}
function at(g,p,pos,z=0){const d=g.serialize();Object.assign(d.frontier,{x:pos.x,y:pos.y,z,inside:p.id,seen:[...new Set([...d.frontier.seen,p.id])]});for(let i=0;i<1+G.hash(d.worldSeed,p.id,'threat')%4;i++)d.frontier.enemies[p.id+':e'+i]=0;d.frontier.kills=Object.values(d.frontier.enemies).filter(n=>n===0).length;g.restoreSave(d);}
for(const ref of reference)test('monde hérité : empreintes 1.15 conservées avec végétation routière écartée, graine '+ref.seed,()=>{
 const w=W.create(ref.seed,1);assert.equal(w.pois.length,ref.pois);assert.equal(h(w.pois.map(({generation,outdoor,...p})=>p)),ref.poiHash);assert.equal(h(w.pois.flatMap(p=>p.levels.map(z=>w.plan(p,z)))),ref.plansHash);
 const originalChunks=[[16,16],[4,7],[17,16],[28,26]].map(([x,y])=>{
  const chunk=w.chunk(x,y),cleared=chunk.cleared||[];
  const onPavement=item=>{const margin=item.kind==='tree'?item.canopy+.8:item.r+.6;return w.roads.some(r=>G.nearest(item,r.a,r.b).d<r.width/2+margin)||w.pois.some(p=>G.nearest(item,p.drive.a,p.drive.b).d<p.drive.width/2+margin);};
  for(const item of cleared)assert.ok(onPavement(item),'only vegetation covering real pavement is cleared: '+item.id);
  for(const item of [...chunk.trees,...chunk.rocks])assert.equal(onPavement(item),false,'kept vegetation remains off carriageways: '+item.id);
  // Reconstitute the original generation order, including invisible tombstones.
  // This retains the old fingerprint and checks every ID, coordinate and amount;
  // the correction cannot silently alter payloads or delete off-road resources.
  const order=(a,b)=>Number(a.id.split('_').at(-1))-Number(b.id.split('_').at(-1));
  return{cx:chunk.cx,cy:chunk.cy,trees:[...chunk.trees,...cleared.filter(n=>n.kind==='tree')].sort(order),rocks:[...chunk.rocks,...cleared.filter(n=>n.kind==='rock')].sort(order)};
 });
 assert.equal(h(originalChunks),ref.chunksHash);
});
test('contenu : douze nouvelles conceptions avec identifiants de codex distincts',()=>{assert.equal(P.PRESETS.length,12);assert.equal(new Set(P.PRESETS.map(p=>p.codex)).size,12);assert.equal(G.PRESETS.length,62);for(const p of P.PRESETS)assert.ok(p.w>=20&&p.levels.length>=1);});
for(const seed of [17117,42,903145])test('contenu : toutes les nouvelles familles sont implantées sans chevauchement '+seed,()=>{const w=W.create(seed,2);for(const p of P.PRESETS)assert.ok(w.pois.some(q=>q.type===p.id));for(let i=0;i<w.pois.length;i++)for(let j=i+1;j<w.pois.length;j++)assert.equal(G.overlap(w.pois[i].reserve,w.pois[j].reserve),false);});
test('parcelles : les props de cour partagent collisions et contenants',()=>{const w=W.create(17117),p=w.pois.find(p=>p.type==='bakery');for(const o of p.outdoor){const q=G.global(p,o.x+o.w/2,o.y+o.h/2);assert.ok(w.blocked(q.x,q.y,.32));assert.ok(w.containers(q.x,q.y,3).some(b=>b.id===o.id));assert.equal(w.vehicleClear(q.x,q.y,p.a),false);}});
test('parcelles : les aménagements extérieurs ne se superposent ni aux voitures ni entre eux',()=>{const w=W.create(17117);for(const p of w.pois){const all=p.outdoor.map(o=>({...G.global(p,o.x+o.w/2,o.y+o.h/2),w:o.w,h:o.h,a:p.a}));for(let i=0;i<all.length;i++){for(const b of p.parking)assert.equal(G.obb(all[i],b),false,p.id);for(let j=i+1;j<all.length;j++)assert.equal(G.obb(all[i],all[j]),false,p.id);}}});
test('plans : chacune des douze implantations possède des espaces et du mobilier propres',()=>{const w=W.create(17117),signs=[];for(const d of P.PRESETS){const p=w.pois.find(p=>p.type===d.id),pl=w.plan(p,0);assert.ok(pl.objects.length>=6,d.id);assert.ok(pl.rooms.length>=3,d.id);signs.push(h(pl));}assert.equal(new Set(signs).size,12);});
test('migration : partie 1.15 conserve son monde, ses découvertes et ses prises',()=>{const{game:g}=fresh();let raw=g.serialize();raw.version=14;raw.frontier={...C.Frontier.initial(),version:1,active:true,x:4248,y:4142,inside:'P0000',anchor:{x:g.player.x,y:g.player.y},seen:['P0000']};delete raw.frontier.generation;delete raw.frontier.notes;delete raw.frontier.pin;const w=W.create(17117,1),o=w.plan(w.pois[0],0).objects[0];raw.frontier.taken[o.id]=2;const stocks=copy(raw.resources);g.restoreSave(raw);assert.equal(g.frontier.snapshot().generation,1);assert.equal(g.frontier.world().pois.length,211);assert.equal(g.frontier.snapshot().taken[o.id],2);assert.deepEqual(g.resources,stocks);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.frontier.snapshot().generation,1);});
test('nouvelle campagne : région enrichie sans transfert des notes précédentes',()=>{const{game:g}=fresh();enter(g);at(g,g.frontier.world().pois[0],{x:4248,y:4142});assert.ok(g.frontier.annotate('P0000','danger'));assert.ok(g.frontier.pin('P0000'));g.startNew('standard','42');const s=g.frontier.snapshot();assert.equal(s.generation,3);assert.equal(s.pin,null);assert.deepEqual(s.notes,{});assert.equal(s.seen.length,0);});
test('carnet : inconnu, statut faux et hors partie refusés sans ressource créée',()=>{const{game:g}=fresh(),before=copy(g.resources);assert.equal(g.frontier.annotate('P0000','danger'),false);assert.equal(g.frontier.pin('P0000'),false);enter(g);at(g,g.frontier.world().pois[0],{x:4248,y:4142});assert.equal(g.frontier.annotate('P0000','reward'),false);assert.deepEqual(g.resources,before);});
test('carnet : notes et repère persistent après quatre reprises',()=>{const{game:g}=fresh();enter(g);at(g,g.frontier.world().pois[0],{x:4248,y:4142});assert.ok(g.frontier.annotate('P0000','cleared'));assert.ok(g.frontier.pin('P0000'));for(let i=0;i<4;i++){assert.ok(g.save(false));assert.ok(g.load());}assert.equal(g.frontier.snapshot().notes.P0000,'cleared');assert.equal(g.frontier.snapshot().pin,'P0000');assert.ok(g.frontier.pin(null));});
test('carnet : import falsifié rejeté avant toute mutation',()=>{const{game:g}=fresh();const before=g.world;for(const change of [d=>d.frontier.pin='P0000',d=>d.frontier.notes.P0000='danger',d=>d.frontier.generation=99,d=>d.frontier.notes=[]]){const d=g.serialize();change(d);assert.throws(()=>g.restoreSave(d));assert.equal(g.world,before);}});
test('orientation : route continue sur graphe et coût carburant sans débit',()=>{const{game:g}=fresh();enter(g);const w=g.frontier.world(),p=w.pois.find(p=>p.type==='library');at(g,p,G.global(p,p.w/2,-2));g.frontier.pin(p.id);const money=copy(g.resources),f=g.frontier.snapshot(),r=g.frontier.guidance();assert.ok(r&&r.metres>=0&&r.path.length>=4);assert.ok(Math.abs(r.fuel-r.metres*.004)<1e-8);assert.deepEqual(g.resources,money);assert.deepEqual(g.frontier.snapshot(),f);});
test('orientation : itinéraire disponible pour les 223 parcelles et cache de graphe partagé',()=>{const w=W.create(17117),graph=Routing.graph(w);for(const p of w.pois){const r=Routing.route(w,{x:4096,y:4096},p);assert.ok(r&&Number.isFinite(r.metres),p.id);assert.ok(r.metres>=Math.hypot(4096-p.drive.b.x,4096-p.drive.b.y)-.1);}assert.equal(Routing.graph(w),graph);});
test('cour : prise partielle sauvegardée sans recharger le contenant',()=>{const{game:g}=fresh();enter(g);const p=g.frontier.world().pois.find(p=>p.type==='bakery'),o=p.outdoor[0];at(g,p,G.global(p,o.x+o.w/2,o.y-1));g.input.keys.add('KeyE');for(let i=0;i<60;i++)g.update(.04);g.input.keys.clear();const s=g.frontier.snapshot();assert.ok(s.taken[o.id]>0);const amount=s.taken[o.id],bag=copy(g.player.carry);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.frontier.snapshot().taken[o.id],amount);assert.deepEqual(g.player.carry,bag);});
