'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core.js'),D=C.PowerGrid,S=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function put(g,type,x=70,y=65,progress=1){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,progress);g.world.add(b);g.refreshMetrics(true);return b;}
function run(g,seconds){for(let i=0;i<Math.round(seconds/.04);i++)g.powerGrid.step(.04);}
function stable(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
const consumer=(id,need,partial=false,rank=1,light=false)=>({id,need,partial,rank,priority:2,light});
const battery=(extra={})=>({id:1,charge:0,capacity:900,chargeRate:6,output:8,mode:'auto',...extra});
const plan=(extra={})=>D.plan({generation:8,consumers:[],batteries:[battery()],phase:'calm',dt:.1,...extra});
test('électricité: trois réserves, trois âges, limites connues et total 69',()=>{assert.equal(Object.keys(D.BUILDINGS).length,3);assert.equal(Object.keys(C.BUILDINGS).length,71);assert.deepEqual(Object.values(D.BUILDINGS).map(b=>b.unlockTier),[2,5,8]);assert.equal(C.SAVE_VERSION,20);assert.equal(D.RULES.efficiency,.9)});
test('plan: une batterie vide reçoit seulement le surplus après rendement',()=>{const p=plan({consumers:[consumer(2,4)]});assert.equal(p.chargeInput,4);assert.ok(Math.abs(p.changes[0].stored-.36)<1e-9);assert.equal(p.batteryOutput,0)});
test('plan: le débit de charge limite le stockage malgré un grand surplus',()=>{const p=plan({generation:100});assert.equal(p.chargeInput,6);assert.ok(Math.abs(p.changes[0].charge-.54)<1e-9)});
test('plan: batterie pleine ne consomme pas le surplus',()=>{const p=plan({batteries:[battery({charge:900})]});assert.equal(p.chargeInput,0);assert.equal(p.changes[0].charge,900)});
test('plan: décharge seulement la puissance manquante',()=>{const p=plan({consumers:[consumer(2,12)],batteries:[battery({charge:20})]});assert.equal(p.batteryOutput,4);assert.equal(p.changes[0].charge,19.6);assert.equal(p.chargeInput,0)});
test('plan: une capacité élevée ne remplace pas le débit de sortie',()=>{const p=plan({generation:0,consumers:[consumer(2,12)],batteries:[battery({charge:900})]});assert.equal(p.allocation[0].powered,false);assert.equal(p.shortfall,12);assert.equal(p.batteryOutput,0);assert.equal(p.changes[0].charge,900)});
test('plan: pas de charge et décharge circulaires entre deux batteries',()=>{const p=plan({consumers:[consumer(4,12)],batteries:[battery({charge:5}),battery({id:2,charge:0})]});assert.equal(p.chargeInput,0);assert.equal(p.changes[1].charge,0);assert.equal(p.changes[0].charge,4.6)});
test('plan: une quantité infime ne finance pas une durée complète',()=>{const p=plan({generation:0,consumers:[consumer(2,8)],batteries:[battery({charge:.1})]});assert.equal(p.batteryOutput,0);assert.equal(p.changes[0].charge,.1)});
test('plan: une industrie peut recevoir le reliquat sans énergie négative',()=>{const p=plan({generation:0,consumers:[consumer(2,8,true)],batteries:[battery({charge:.1})]});assert.equal(p.allocation[0].share,.125);assert.equal(p.batteryOutput,1);assert.equal(p.changes[0].charge,0)});
test('plan: réserve de nuit ne se vide pas pendant le calme',()=>{const p=plan({consumers:[consumer(2,12)],batteries:[battery({charge:500,mode:'night'})]});assert.equal(p.batteryOutput,0);assert.equal(p.changes[0].charge,500);assert.equal(plan({phase:'warning',consumers:[consumer(2,12)],batteries:[battery({charge:500,mode:'night'})]}).batteryOutput,4)});
test('plan: isolation conserve la charge et refuse toute entrée',()=>{for(const generation of [0,50]){const p=plan({generation,consumers:[consumer(2,12)],batteries:[battery({charge:500,mode:'isolated'})]});assert.equal(p.changes[0].charge,500);assert.equal(p.chargeInput,0);assert.equal(p.batteryOutput,0)}});
test('plan: priorité lumière choisit réellement un projecteur avant une industrie',()=>{const consumers=[consumer(1,8,true,3),consumer(2,3,false,4,true)];const a=plan({consumers,batteries:[]}),b=plan({consumers,batteries:[],priority:'lights'});assert.equal(a.allocation.find(a=>a.id===2).powered,false);assert.equal(b.allocation.find(a=>a.id===2).powered,true);assert.equal(b.allocation.find(a=>a.id===1).share,5/8)});
test('plan: 2 000 configurations conservent l’énergie sans mutations d’entrée',()=>{let seed=77;const rand=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);for(let i=0;i<2000;i++){const args={generation:rand()*100,consumers:Array.from({length:7},(_,j)=>consumer(j+10,1+Math.floor(rand()*20),rand()>.5,Math.floor(rand()*4),rand()>.5)),batteries:Array.from({length:3},(_,j)=>battery({id:j+1,charge:rand()*900,mode:['auto','night','isolated'][Math.floor(rand()*3)]})),phase:rand()>.5?'calm':'assault',dt:.04},before=JSON.stringify(args),p=D.plan(args),old=args.batteries.reduce((n,b)=>n+b.charge,0),now=p.changes.reduce((n,b)=>n+b.charge,0);assert.ok(Math.abs(now-old-(p.chargeInput*.9-p.batteryOutput)*args.dt)<1e-7);assert.ok(p.batteryOutput<=24+1e-7);assert.ok(p.delivered<=p.generation+p.batteryOutput+1e-7);assert.equal(JSON.stringify(args),before);assert.ok(!(p.chargeInput>1e-7&&p.batteryOutput>1e-7))}});
test('plan: pas non fini, nul ou excessif refusé',()=>{for(const dt of [0,-1,NaN,Infinity,.3])assert.throws(()=>plan({dt}))});
test('construction: chantier de réserve ne contient aucune charge',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet',70,65,0);run(g,2);assert.equal(g.powerGrid.snapshot().batteries.length,0);b.work(b.def.buildTime);g.completeBuilding(b);assert.equal(g.powerGrid.charge(b.id),0)});
test('simulation: réserve réellement chargée par 10 s de surplus',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,10);assert.ok(Math.abs(g.powerGrid.charge(b.id)-54)<1e-7)});
test('simulation: refresh, ouverture et sérialisation ne chargent pas',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');const before=stable(g);for(let i=0;i<20;i++){g.powerGrid.overview();g.refreshMetrics();g.powerGrid.preview();g.serialize()}assert.equal(g.powerGrid.charge(b.id),0);assert.equal(stable(g),before)});
test('simulation: pause, menu et dt invalide n’avancent pas la réserve',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');g.togglePause(true);assert.equal(g.powerGrid.step(.04),false);g.togglePause(false);for(const dt of [0,-1,Infinity,.3])assert.equal(g.powerGrid.step(dt),false);g.returnToMenu();g.powerGrid.step(.04);assert.equal(g.powerGrid.charge(b.id),0)});
test('simulation: le déficit nocturne retire seulement l’appoint consommé',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,10);for(let i=0;i<4;i++)put(g,'searchlight',75+i*3,65);g.phase='assault';g.refreshMetrics(true);const before=g.powerGrid.charge(b.id);run(g,1);assert.ok(Math.abs(g.powerGrid.charge(b.id)-(before-4))<1e-7);assert.ok([...g.world.buildings.values()].filter(b=>b.type==='searchlight').every(b=>b.powered))});
test('simulation: réserve épuisée, circuit retrouve sa vraie pénurie',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,1);for(let i=0;i<4;i++)put(g,'searchlight',75+i*3,65);g.phase='assault';run(g,3);g.refreshMetrics(true);assert.ok(g.powerGrid.charge(b.id)>=0);assert.ok([...g.world.buildings.values()].filter(b=>b.type==='searchlight'&&!b.powered).length>0)});
test('circuit: couper une usine arrête courant, production et intrants',()=>{const{game:g}=fresh(),b=put(g,'marketHall');assert.ok(g.powerGrid.setCircuit(b.id,'off'));const before=copy(g.resources);g.population=0;g.economyTick(.25);assert.equal(g.powerUsed,0);assert.equal(g.resources.food,before.food);assert.equal(g.resources.fuel,before.fuel);assert.equal(b.powered,false)});
test('circuit: arrêt des services du logement sans expulsion ni rations gratuites',()=>{const{game:g}=fresh(),b=put(g,'rowHomes'),h=g.housing,pop=g.population;g.powerGrid.setCircuit(b.id,'off');assert.equal(g.housing,h);assert.equal(g.population,pop);const f=g.resources.food;g.economyTick(.25);assert.ok(g.resources.food<f)});
test('circuit: programme nocturne activé à l’alerte, éteint au calme',()=>{const{game:g}=fresh(),b=put(g,'streetlight');g.powerGrid.setCircuit(b.id,'night');assert.equal(b.powered,false);g.phase='warning';g.refreshMetrics(true);assert.equal(b.powered,true);g.phase='calm';g.refreshMetrics(true);assert.equal(b.powered,false)});
test('circuit: programme diurne arrête une industrie au crépuscule',()=>{const{game:g}=fresh(),b=put(g,'lumber');g.powerGrid.setCircuit(b.id,'day');assert.equal(b.powered,true);g.phase='warning';g.refreshMetrics(true);assert.equal(b.powered,false);assert.equal(b.powerShare,0)});
test('circuit: remise toujours allumé supprime l’exception sans consommer de stock',()=>{const{game:g}=fresh(),b=put(g,'streetlight');const stock=copy(g.resources);g.powerGrid.setCircuit(b.id,'off');g.powerGrid.setCircuit(b.id,'on');assert.equal(g.powerGrid.snapshot().circuits.length,0);assert.equal(b.powered,true);assert.deepEqual(g.resources,stock)});
test('incendie: une batterie raccordée en feu cesse de charger et décharger',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,1);b.siegeOffline=true;const before=g.powerGrid.charge(b.id);run(g,1);assert.equal(g.powerGrid.charge(b.id),before)});
test('perte: destruction enlève la charge, reconstruction commence vide',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,5);assert.ok(g.powerGrid.charge(b.id)>0);g.destroyBuilding(b);assert.equal(g.powerGrid.charge(b.id),0);const next=put(g,'batteryCabinet',b.gx,b.gy);assert.equal(g.powerGrid.charge(next.id),0)});
test('sauvegarde: cinq reprises conservent exactement l’énergie et les commandes',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet'),lamp=put(g,'streetlight',73,65);run(g,3);g.powerGrid.setCircuit(lamp.id,'night');g.powerGrid.setBattery(b.id,'auto');g.powerGrid.setPriority('lights');const before=g.powerGrid.snapshot();for(let i=0;i<5;i++){assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.powerGrid.snapshot(),before)}});
test('sauvegarde: anciens formats sans nouvelle charge ni commande imposée',()=>{const{game:g}=fresh(),d=g.serialize();for(let version=1;version<=10;version++){const old=copy(d);old.version=version;delete old.powerGrid;const next=S.validate(old);assert.equal(next.version,C.SAVE_VERSION);assert.deepEqual(next.powerGrid,D.empty());assert.deepEqual(next.resources,d.resources)}});
test('sauvegarde: surcharge, doublon, charge manquante et mauvaise référence refusés',()=>{const{game:g}=fresh();put(g,'batteryCabinet');const d=g.serialize(),world=g.world;for(const mutate of [x=>x.batteries[0].charge=901,x=>x.batteries.push({...x.batteries[0]}),x=>x.batteries[0].charge=-1,x=>x.batteries[0].id=99999,x=>x.batteries=[],x=>x.circuits=[{id:g.core().id,mode:'off'}]]){const bad=copy(d);mutate(bad.powerGrid);assert.throws(()=>g.restoreSave(bad));assert.equal(g.world,world)}});
test('sauvegarde: nouvelle campagne ne garde aucune batterie ou circuit',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,3);g.powerGrid.setBattery(b.id,'auto');g.startNew('standard','42');assert.deepEqual(g.powerGrid.snapshot(),D.empty());assert.equal(g.lastSaveStatus.ok,true)});
test('production: une remise sous tension tardive ne paie pas toute la période passée',()=>{const{game:g}=fresh(),b=put(g,'lumber');g.powerGrid.setCircuit(b.id,'off');for(let i=0;i<5;i++)g.powerGrid.step(.04,true);g.powerGrid.setCircuit(b.id,'on');g.powerGrid.step(.04,true);const wood=g.resources.wood;g.economyTick(.24);assert.ok(Math.abs(g.resources.wood-wood-b.def.production.wood*.04)<1e-7)});
test('production: couper au dernier instant conserve seulement le travail déjà alimenté',()=>{const{game:g}=fresh(),b=put(g,'lumber');g.powerGrid.step(.04,true);g.powerGrid.setCircuit(b.id,'off');for(let i=0;i<5;i++)g.powerGrid.step(.04,true);const wood=g.resources.wood;g.economyTick(.24);assert.ok(Math.abs(g.resources.wood-wood-b.def.production.wood*.04)<1e-7);const second=g.resources.wood;g.economyTick(.24);assert.equal(g.resources.wood,second)});
test('incident: un consommateur incendié ou perdu ne vide plus la réserve',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet'),p=put(g,'searchlight',75,65);run(g,1);p.siegeOffline=true;g.powerGrid.preview();assert.equal(g.powerUsed,0);assert.equal(p.powered,false);p.siegeOffline=false;p.territoryOffline=true;g.powerGrid.preview();assert.equal(g.powerUsed,0);assert.equal(p.powered,false)});
test('incendie: sauvegarde avec batterie embrasée valide puis aucune décharge',()=>{const{game:g}=fresh(),b=put(g,'batteryCabinet');run(g,1);const d=g.serialize();d.siege.fires.push({id:b.id,heat:35,age:0,spread:0,origin:'blast'});d.siege.stats.ignitions++;g.restoreSave(d);const q=g.powerGrid.charge(b.id);g.powerGrid.step(.04);assert.equal(g.powerGrid.charge(b.id),q);assert.equal(g.powerGrid.overview().batteries[0].offline,true)});
test('stabilité: pas de micro-recharges et clignotement sur un déficit persistant',()=>{let b=battery({charge:.1}),outputs=[];for(let i=0;i<300;i++){const p=plan({generation:8,consumers:[consumer(10,3),consumer(11,3),consumer(12,3),consumer(13,3)],batteries:[b],dt:.04});assert.equal(p.chargeInput,0);b={...b,charge:p.changes[0].charge};outputs.push(p.delivered);}assert.ok(outputs.slice(10).every(n=>n===6));assert.ok(b.charge>=0)});
