'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {boot127}=require('./helpers/expansions127.cjs');
const C=require('../src/core.js'),G=require('../src/frontier-geometry.js');
function fresh(){const {game:g}=boot127();g.startNew('standard','17117');g.phaseTime=999;return g;}
const lamp=()=>({id:1,kind:'lantern',location:'belt',left:300,on:false,used:true});
function equip(g){const raw=g.serialize();raw.nightGear={version:1,serial:2,devices:[lamp()]};g.restoreSave(raw);}
function localWall(g){const distance=C.NightGearRules.placeDistance*32;for(const wall of g.exploration125.plan.solids.filter(s=>s.kind==='station-wall')){
 const vertical=wall.w<wall.h,center={x:wall.x+wall.w/2,y:wall.y+wall.h/2},a={x:center.x-(vertical?distance/2:0),y:center.y-(vertical?0:distance/2)},b={x:center.x+(vertical?distance/2:0),y:center.y+(vertical?0:distance/2)};
 if(g.friendlyPositionClear({radius:9},a.x,a.y)&&g.friendlyPositionClear({radius:9},b.x,b.y))return{a,b,angle:vertical?0:Math.PI/2};
 }assert.fail('Deux côtés libres d’un vrai mur de station');}
function regionalWall(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const w=g.frontier.world(),d=C.NightGearRules.placeDistance;for(const poi of w.pois){for(const wall of w.plan(poi,0).walls){const vertical=wall.w<wall.h,center={x:wall.x+wall.w/2,y:wall.y+wall.h/2},a=G.global(poi,center.x-(vertical?d/2:0),center.y-(vertical?0:d/2)),b=G.global(poi,center.x+(vertical?d/2:0),center.y+(vertical?0:d/2));if(!w.blocked(a.x,a.y,.32,0,null)&&!w.blocked(b.x,b.y,.28,0,null)&&!w.line(a,b,0,null,null,.015)){const raw=g.serialize();Object.assign(raw.frontier,a,{a:Math.atan2(b.y-a.y,b.x-a.x),z:0,inside:null});g.restoreSave(raw);return{a,b,poi};}}}assert.fail('Deux côtés libres d’un vrai mur régional');}
test('QA 1.28 nuits : une lampe ne se pose pas à travers un mur G4',()=>{const g=fresh();equip(g);const {a,angle}=localWall(g);Object.assign(g.player,a,{facing:angle});const before=g.nightGear.snapshot();assert.equal(g.nightGear.place(1).ok,false);assert.deepEqual(g.nightGear.snapshot(),before);});
test('QA 1.28 nuits : une lampe ne se pose pas à travers un mur régional',()=>{const g=fresh();equip(g);regionalWall(g);const before=g.nightGear.snapshot();assert.equal(g.nightGear.place(1).ok,false);assert.deepEqual(g.nightGear.snapshot(),before);});
test('QA 1.28 nuits : récupération et chaleur respectent les murs G4',()=>{const g=fresh(),{a,b}=localWall(g),raw=g.serialize();Object.assign(raw.player,a);raw.nightGear={version:1,serial:3,devices:[{...lamp(),location:'placed',domain:'local',...b,z:0,inside:null,angle:0},{id:2,kind:'campfire',location:'placed',domain:'local',...b,z:0,inside:null,angle:0,left:200,on:true,used:true}]};g.restoreSave(raw);g.player.carry.food=4;g.player.carry.wood=1;assert.equal(g.nightGear.pickup(1).ok,false);assert.equal(g.survivalPack.preview('meal').ok,false);});
test('QA 1.28 nuits : une reprise à terre dépose les lampes avant la réanimation immédiate',()=>{const g=fresh();equip(g);const raw=g.serialize();Object.assign(raw.player,{x:2400,y:2450,health:0,dead:true,downTimer:.02});g.restoreSave(raw);g.update(.04);assert.equal(g.player.dead,false);const d=g.nightGear.snapshot().devices[0];assert.equal(d.location,'placed');assert.equal(d.domain,'local');assert.equal(d.x,2400);assert.equal(d.y,2450);assert.equal(g.save(false),true);});
test('QA 1.28 nuits : la ceinture tombe au lieu régional exact du décès',()=>{const g=fresh();equip(g);g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const p=g.frontier.snapshot();g.player.invulnerable=0;g.frontier.damage(1000);assert.equal(g.player.dead,true);g.update(.04);const d=g.nightGear.snapshot().devices[0];assert.equal(d.location,'placed');assert.equal(d.domain,'region');assert.equal(d.x,p.x);assert.equal(d.y,p.y);assert.equal(d.z,p.z);assert.equal(d.inside,p.inside);assert.equal(g.save(false),true);});
test('QA 1.28 nuits : le rechargement interrompt un assemblage sans coût',()=>{const g=fresh();g.player.x=2400;g.player.y=2450;g.player.carry.wood=4;g.player.carry.fuel=2;assert.ok(g.nightGear.craft('torch').ok);g.nightGear.step(.1);g.player.reload=1;g.nightGear.step(.1);assert.equal(g.nightGear.busy(),false);assert.equal(g.player.carry.wood,4);assert.equal(g.player.carry.fuel,2);assert.equal(g.nightGear.snapshot().devices.length,0);});

test('QA 1.28 nuits : pause et modale suspendent aussi le pas public des lampes',()=>{const g=fresh();equip(g);assert.ok(g.nightGear.ignite(1).ok);const before=g.nightGear.snapshot();g.paused=true;g.nightGear.step(.1);assert.deepEqual(g.nightGear.snapshot(),before);g.paused=false;g.activeOverlay={};g.nightGear.step(.1);assert.deepEqual(g.nightGear.snapshot(),before);g.activeOverlay=null;g.nightGear.step(.1);assert.equal(g.nightGear.snapshot().devices[0].left,299.9);});
test('QA 1.28 nuits : une torche abritée dans une station ne brûle pas sous la pluie',()=>{const g=fresh();const st=g.exploration125.plan.stations[0],raw=g.serialize();raw.nightGear={version:1,serial:3,devices:[{id:1,kind:'torch',location:'placed',domain:'local',x:st.x,y:st.y,z:0,inside:null,angle:0,left:180,on:true,used:true},{id:2,kind:'torch',location:'placed',domain:'local',x:2812,y:2300,z:0,inside:null,angle:0,left:180,on:true,used:true}]};g.restoreSave(raw);g.weather=1;g.nightGear.step(.1);const [indoor,outdoor]=g.nightGear.snapshot().devices;assert.equal(indoor.left,179.9);assert.equal(outdoor.left,179.74);});
test('QA 1.28 nuits : une vraie porte de station permet encore pose et récupération',()=>{const g=fresh();equip(g);let fixture=null;const distance=C.NightGearRules.placeDistance*32;for(const st of g.exploration125.plan.stations){const angle={north:Math.PI/2,south:-Math.PI/2,west:0,east:Math.PI}[st.facing],a={x:st.door.x-Math.cos(angle)*distance/2,y:st.door.y-Math.sin(angle)*distance/2},b={x:st.door.x+Math.cos(angle)*distance/2,y:st.door.y+Math.sin(angle)*distance/2};if(g.friendlyPositionClear(g.player,a.x,a.y)&&g.friendlyPositionClear({radius:9},b.x,b.y)&&g.nightGear.localLineClear(a,b))fixture={a,b,angle};}assert.ok(fixture);Object.assign(g.player,fixture.a,{facing:fixture.angle});assert.ok(g.nightGear.place(1).ok);const d=g.nightGear.snapshot().devices[0];assert.ok(Math.hypot(d.x-fixture.b.x,d.y-fixture.b.y)<1e-6);assert.ok(g.nightGear.pickup(1).ok);assert.equal(g.nightGear.snapshot().devices[0].location,'belt');});
test('QA 1.28 nuits : décès à l’étage conserve domaine, pièce et niveau du dépôt',()=>{const g=fresh();equip(g);g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const w=g.frontier.world(),poi=w.pois.find(p=>p.type==='duplex');let point=null;for(let y=1;y<poi.h-1&&!point;y+=.5)for(let x=1;x<poi.w-1&&!point;x+=.5){const q=G.global(poi,x,y);if(!w.blocked(q.x,q.y,.32,1,poi.id))point=q;}assert.ok(point);const raw=g.serialize();Object.assign(raw.frontier,point,{z:1,inside:poi.id,seen:[...new Set([...raw.frontier.seen,poi.id])]});g.restoreSave(raw);g.player.invulnerable=0;g.frontier.damage(1000);const d=g.nightGear.snapshot().devices[0];assert.equal(d.domain,'region');assert.equal(d.x,point.x);assert.equal(d.y,point.y);assert.equal(d.z,1);assert.equal(d.inside,poi.id);assert.equal(g.save(false),true);assert.equal(g.load(),true);assert.deepEqual(g.nightGear.snapshot().devices[0],d);});

test('QA 1.28 nuits : validation géométrique réutilisée, distinguée par génération et bornée à trois cartes',()=>{const N=require('../src/night-gear.js'),original=globalThis.DeadwallFrontierWorld,requests=[];const poi={id:'P0001',levels:[0,1],x:100,y:100,w:10,h:10,a:0},point=G.global(poi,5,5);globalThis.DeadwallFrontierWorld={...original,create:(seed,generation)=>{requests.push([seed,generation]);return{pois:[poi]};}};const raw={version:1,serial:2,devices:[{...lamp(),location:'placed',domain:'region',...point,z:1,inside:poi.id,angle:0}]};const check=(seed,generation=4)=>N.normalize(raw,{worldSeed:seed,frontier:{generation}});try{check(99971001);check(99971002);check(99971003);check(99971001);assert.equal(requests.length,3);check(99971004);check(99971002);assert.equal(requests.length,5,'la plus ancienne carte est évincée');check(99971002,3);assert.equal(requests.length,6,'changer de génération change de géométrie');assert.throws(()=>N.normalize({...raw,devices:[{...raw.devices[0],x:0}]},{worldSeed:99971002,frontier:{generation:3}}),/éclairage nocturne/);assert.equal(requests.length,6,'réutiliser la carte ne contourne pas la validation');}finally{globalThis.DeadwallFrontierWorld=original;}});
test('QA 1.28 nuits : une ancienne génération ne reçoit pas un toit G4 invisible',()=>{const g=fresh(),st=g.exploration125.plan.stations[0],raw=g.serialize();raw.nightGear={version:1,serial:2,devices:[{id:1,kind:'torch',location:'placed',domain:'local',x:st.x,y:st.y,z:0,inside:null,angle:0,left:180,on:true,used:true}]};g.restoreSave(raw);g.exploration125.generation=3;g.weather=1;g.nightGear.step(.1);assert.equal(g.nightGear.snapshot().devices[0].left,179.74);});
