'use strict';
const {standAt}=require('./helpers/physical-fixtures.cjs');
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),M=require('../src/recon.js'),A=require('../src/recon-art.js');
function fresh(){const env=bootGame();env.game.startNew('standard','17117');return env;}
function reveal(g,ids=[0,1,2,3,4]){const d=g.serialize();for(const i of ids)d.dayworks.sites[i].seen=true;g.restoreSave(d);return g.recon.points().filter(p=>p.kind==='site');}
function put(g,type,x,y,progress=1){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,progress);g.world.add(b);return b;}
function stable(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
test('recon: version de sauvegarde courante v11 et règles bornées',()=>{assert.equal(C.SAVE_VERSION,20);assert.equal(C.RECON_RULES.maxStops,4);assert.ok(C.RECON_RULES.maxExpanded<=16384)});
test('recon: 18 rendus nommés pour les 18 découvertes, sans doublon de style',()=>{assert.deepEqual(Object.keys(A.STYLES).sort(),C.Dayworks.SITES.map(s=>s.id).sort());assert.equal(new Set(Object.values(A.STYLES)).size,18)});
test('recon: points inconnus cachés, dépôt initial visible',()=>{const{game:g}=fresh();const ps=g.recon.points();assert.equal(ps.filter(p=>p.kind==='site').length,0);assert.equal(ps.filter(p=>p.kind==='call').length,0);assert.equal(ps.filter(p=>p.kind==='depot').length,1)});
test('recon: nouvelle découverte exposée après repérage, pas de coordonnées des inconnues',()=>{const{game:g}=fresh();reveal(g,[0]);assert.equal(g.recon.points().filter(p=>p.kind==='site').length,1);assert.ok(!g.recon.points().some(p=>p.ref===C.Dayworks.SITES[1].id))});
test('recon: réserve et relevé restent ceux du registre de campagne',()=>{const{game:g}=fresh();const d=g.serialize();Object.assign(d.dayworks.sites[0],{seen:true,survey:6,remaining:3});g.restoreSave(d);const s=g.recon.points().find(p=>p.kind==='site');assert.equal(s.remaining,3);assert.equal(s.survey,6);assert.equal(s.unlock,'dayGreenhouse')});
test('recon: retour au centre n’est ni un déplacement ni un dépôt',()=>{const{game:g}=fresh();g.player.carry.wood=7;const before=stable(g);assert.ok(g.recon.returnHome());assert.equal(stable(g),before);assert.equal(g.recon.overview().queue.length,1)});
test('recon: parcours de quatre lieux, doublons et cinquième refusés',()=>{const{game:g}=fresh();const ps=reveal(g);for(const p of ps.slice(0,4))assert.ok(g.recon.enqueue(p.id));assert.equal(g.recon.enqueue(ps[0].id),false);assert.equal(g.recon.enqueue(ps[4].id),false);assert.equal(g.recon.overview().queue.length,4)});
test('recon: ordre des étapes modifiable sans trier la campagne',()=>{const{game:g}=fresh();const ps=reveal(g,[0,1]);ps.forEach(p=>g.recon.enqueue(p.id));assert.ok(g.recon.move(ps[1].id,-1));assert.equal(g.recon.overview().queue[0].id,ps[1].id);assert.equal(g.recon.move(ps[1].id,-1),false);assert.equal(g.recon.move(ps[1].id,Infinity),false);assert.ok(g.recon.remove(ps[1].id));assert.equal(g.recon.overview().queue.length,1)});
test('recon: lieu épuisé visible mais pas ajouté comme nouvelle récolte',()=>{const{game:g}=fresh();const d=g.serialize();Object.assign(d.dayworks.sites[0],{seen:true,survey:6,remaining:0});g.restoreSave(d);const p=g.recon.points().find(p=>p.kind==='site');assert.equal(p.done,true);assert.equal(g.recon.enqueue(p.id),false);assert.ok(g.recon.choose(p.id))});
test('recon: inconnu, identifiant inventé et appel non repéré refusés',()=>{const{game:g}=fresh();for(const id of ['site:housing-1','call:aid','depot:999999',null,'__proto__']){assert.equal(g.recon.enqueue(id),false);assert.equal(g.recon.choose(id),false)}});
test('recon: lecture et calcul ne modifient ni stocks, ni RNG, ni compteurs',()=>{const{game:g}=fresh();const ps=reveal(g,[0]);g.recon.enqueue(ps[0].id);const before=stable(g);for(let i=0;i<10;i++)g.recon.overview(true);assert.equal(stable(g),before)});
test('recon: commandes refusées à terre ou hors partie',()=>{const{game:g}=fresh();const ps=reveal(g,[0]);g.player.dead=true;assert.equal(g.recon.enqueue(ps[0].id),false);assert.equal(g.recon.returnHome(),false);g.returnToMenu();assert.deepEqual(g.recon.points(),[])});
test('recon: pause du commandement permet de préparer, pause générale ne le permet pas',()=>{const{game:g}=fresh();const ps=reveal(g,[0]);g.togglePause(true);assert.equal(g.recon.enqueue(ps[0].id),false);g.togglePause(false);assert.ok(g.recon.enqueue(ps[0].id))});
test('recon: nouvelle campagne et reprise effacent seulement le parcours temporaire',()=>{const{game:g}=fresh();const ps=reveal(g,[0]);g.recon.enqueue(ps[0].id);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.recon.overview().queue.length,0);assert.equal(g.recon.points().filter(p=>p.kind==='site').length,1);g.recon.returnHome();g.startNew('standard','42');assert.equal(g.recon.overview().queue.length,0)});
test('recon: import invalide conserve la campagne et le parcours',()=>{const{game:g}=fresh();g.recon.returnHome();const before=g.recon.overview().queue.map(p=>p.id),w=g.world;assert.throws(()=>g.restoreSave({version:8}));assert.equal(w,g.world);assert.deepEqual(g.recon.overview().queue.map(p=>p.id),before)});
test('recon: entrepôts achevés seulement, retrait ne laisse pas de destination morte',()=>{const{game:g}=fresh();const b=put(g,'warehouse',70,65,0);assert.equal(g.recon.points().filter(p=>p.kind==='depot').length,1);b.progress=1;b.health=b.maxHealth;assert.ok(g.recon.enqueue('depot:'+b.id));g.world.remove(b);assert.ok(!g.recon.overview().queue.some(p=>p.ref===b.id))});
test('recon: un trajet direct a la longueur géométrique attendue',()=>{const{game:g}=fresh();const p={x:2200,y:2048},q={x:2230,y:2088,reach:54},r=M.routeBetween(g,p,q);assert.ok(r.ok);assert.equal(r.distance,50);assert.deepEqual(r.path[0],p)});
test('recon: coordonnées invalides ou hors monde refusées',()=>{const{game:g}=fresh();for(const p of [{x:NaN,y:2},{x:Infinity,y:8},{x:-1,y:10},{x:5000,y:1},null])assert.equal(M.routeBetween(g,p,{x:2050,y:2050}).ok,false)});
test('recon: enceinte fermée bloque le trajet, porte auto le rouvre aux alliés',()=>{
 const{game:g}=fresh();for(let y=59;y<=68;y++)for(let x=59;x<=68;x++)if(x===59||x===68||y===59||y===68){if(y===59&&(x===63||x===64))continue;put(g,'woodWall',x,y)}const gate=put(g,'gate',63,59);gate.gateMode='closed';g.world.navigationVersion++;
 standAt(g,g.player,g.core());const to={x:2048,y:1800,reach:54};assert.equal(M.routeBetween(g,g.player,to).ok,false);gate.gateMode='auto';g.world.navigationVersion++;const route=M.routeBetween(g,g.player,to);assert.ok(route.ok,route.reason);assert.ok(route.path.slice(1).every((p,i)=>M.segmentClear(g,route.path[i],p)));
});
test('recon: invalide le trajet après verrouillage d’une porte',()=>{const{game:g}=fresh();const b=put(g,'gate',63,57);g.player.x=b.x;g.player.y=b.bottom+30;g.recon.returnHome();const r=g.recon.route(true);assert.ok(r.ok);assert.ok(g.setGateMode('closed',b));g.recon.route(true);assert.equal(g.resources.wood,180)});
test('recon: rendu refuse un identifiant inconnu avant tout accès Canvas',()=>{assert.equal(A.draw({}, {id:'unknown',x:1,y:2}),false);assert.equal(A.draw({}, {id:'housing-1',x:Infinity,y:2}),false)});
