'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),P=require('../src/atlas-projection.js'),Routes=require('../src/return-routes.js');
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function snapshot(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
function put(g,type,x,y,progress=1){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,progress);g.world.add(b);return b;}
function ring(g){for(let x=56;x<=74;x++){put(g,'woodWall',x,56);put(g,'woodWall',x,74);}for(let y=57;y<74;y++){put(g,'woodWall',56,y);put(g,'woodWall',74,y);}g.fieldcraft.setup();}
function carFixture(){const{game:g}=fresh(),{standAt}=require('./helpers/physical-fixtures.cjs');put(g,'expeditionGarage',77,65);g.refreshMetrics(true);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const v=g.expeditions.car();v.x=g.player.x=4058;v.y=g.player.y=2048;v.fuel=20;v.driving=true;g.player.radius=22;assert.ok(g.frontier.enter());return{g,v};}
test('retour : quatre trajets géométriques au dépôt pour les deux gabarits',()=>{const{game:g}=fresh();for(const mode of ['foot','car']){const out=g.returnRoutes.verify(mode);assert.equal(out.gates.length,4);const search=Routes.createSearch(g,mode);for(const gate of out.gates){assert.equal(gate.status,'connected');assert.ok(gate.path.length>=2);for(let i=1;i<gate.path.length;i++)assert.ok(search.segment(gate.path[i-1],gate.path[i]));const last=gate.path.at(-1);assert.ok(g.fieldcraft.workAt({...last,radius:search.clear.radius},g.core(),70));}}});
test('retour : même projection métrique que D-17',()=>{const{game:g}=fresh(),r=g.returnRoutes.verify('car').gates[0];assert.equal(r.localMetres,r.localUnits/32);assert.equal(r.localFuel,r.localUnits*.003);assert.deepEqual(r.worldPath,r.path.map(p=>P.toRegion(p.x,p.y)));});
test('retour : calcul, sélection et lecture ne consomment rien',()=>{const{game:g}=fresh(),before=snapshot(g);g.returnRoutes.verify('foot');assert.ok(g.returnRoutes.select('east'));g.returnRoutes.budget();g.returnRoutes.overlay();assert.equal(snapshot(g),before);});
test('retour : un point central bouché peut avoir une approche décalée',()=>{const{game:g}=fresh();put(g,'woodWall',126,64);const e=g.returnRoutes.verify('foot').gates.find(q=>q.id==='east');assert.equal(e.central,'entry-blocked');assert.equal(e.status,'connected');assert.notEqual(e.offset,0);assert.ok(g.friendlyPositionClear({radius:13},e.entry.x,e.entry.y));});
test('retour : un vrai encerclement ne devient pas un trajet à travers un mur',()=>{const{game:g}=fresh();ring(g);const p=Routes.createSearch(g,'foot').find({x:4036,y:2048});assert.equal(p.path,null);assert.equal(p.status,'no-path');});
test('retour : une ouverture d’une cellule peut admettre le piéton et refuser le break',()=>{const{game:g}=fresh();ring(g);g.world.remove(g.world.atCell(74,64));const a=Routes.createSearch(g,'foot').find({x:4036,y:2048}),b=Routes.createSearch(g,'car').find({x:4036,y:2048});assert.ok(a.path);assert.equal(b.path,null);});
test('retour : une nouvelle emprise rend le tracé périmé et masqué',()=>{const{game:g}=fresh();g.returnRoutes.verify();g.returnRoutes.select('east');assert.ok(g.returnRoutes.overlay());put(g,'woodWall',95,64);assert.ok(g.returnRoutes.isStale());assert.equal(g.returnRoutes.overlay(),null);assert.equal(g.returnRoutes.budget(),null);assert.equal(g.returnRoutes.select('west'),false);g.returnRoutes.verify();assert.equal(g.returnRoutes.isStale(),false);});
test('retour : fermeture de porte prise en compte sans dépendre du compteur de navigation',()=>{const{game:g}=fresh();const door=put(g,Object.keys(C.BUILDINGS).find(k=>C.BUILDINGS[k].gate),91,63);door.gateMode='open';g.returnRoutes.verify();const nav=g.world.navigationVersion;door.gateMode='closed';assert.equal(g.world.navigationVersion,nav);assert.ok(g.returnRoutes.isStale());});
test('retour : chantier terminé, décor épuisé et déplacement invalident le diagnostic',()=>{const{game:g}=fresh(),b=put(g,'house',100,80,.5);g.returnRoutes.verify();b.progress=1;assert.ok(g.returnRoutes.isStale());g.returnRoutes.verify();const node=g.world.nodes.find(n=>!n.depleted);node.depleted=true;assert.ok(g.returnRoutes.isStale());g.returnRoutes.verify();b.gx+=3;assert.ok(g.returnRoutes.isStale());});
test('retour : les petites variations de santé ne modifient pas la géométrie',()=>{const{game:g}=fresh();g.returnRoutes.verify();g.core().health--;assert.equal(g.returnRoutes.isStale(),false);});
test('retour : débit local et régional distincts dans le budget automobile',()=>{const{g,v}=carFixture();g.returnRoutes.verify('car');g.returnRoutes.select('east');const b=g.returnRoutes.budget();assert.equal(b.localFuel,b.localMetres*32*.003);assert.equal(b.regionFuel,b.regionMetres*.004);assert.ok(Math.abs(b.required-(b.localFuel+b.regionFuel)*1.25-2)<1e-8);assert.equal(b.originKind,'vehicle');assert.equal(v.fuel,20);});
test('retour : voiture laissée en région, estimation depuis son emplacement',()=>{const{g,v}=carFixture();g.frontier.board();g.returnRoutes.verify('car');g.returnRoutes.select('east');const before=g.returnRoutes.budget(),d=g.serialize();d.frontier.x+=30;g.restoreSave(d);g.returnRoutes.verify('car');g.returnRoutes.select('east');const after=g.returnRoutes.budget();assert.deepEqual(after.position,before.position);assert.equal(after.regionMetres,before.regionMetres);});
test('retour : stockage et marges restent des valeurs lues, pas des cadeaux',()=>{const{g,v}=carFixture();const stock=g.resources.fuel;v.cargo.fuel=2;g.player.carry.fuel=1;g.fieldSupplies.reserve(4);g.returnRoutes.verify('car');g.returnRoutes.select('east');const b=g.returnRoutes.budget();assert.equal(b.available,23);assert.equal(b.reserve,4);assert.equal(g.resources.fuel,stock);});
test('retour : les résultats exposés sont des copies et les identifiants sont contrôlés',()=>{const{game:g}=fresh(),r=g.returnRoutes.verify();r.gates[0].path[0].x=NaN;assert.ok(Number.isFinite(g.returnRoutes.snapshot().gates[0].path[0].x));assert.equal(g.returnRoutes.select('non-existant'),false);assert.throws(()=>g.returnRoutes.verify('train'));});
test('retour : nouvelle partie et reprise annulent le diagnostic transitoire',()=>{const{game:g}=fresh();g.returnRoutes.verify();g.returnRoutes.select('east');assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.returnRoutes.snapshot().checked,false);g.returnRoutes.verify();g.startNew('standard','42');assert.equal(g.returnRoutes.snapshot().checked,false);assert.equal(g.serialize().version,20);assert.equal('returnRoutes' in g.serialize(),false);});
test('retour : les routes extérieures sont découpées autour de D-17 sans modifier le monde',()=>{const{game:g}=fresh(),world=g.frontier.world(),before=JSON.stringify(world.roads),outside=Routes.outsideWorld(world);assert.equal(JSON.stringify(world.roads),before);for(const r of outside.roads)for(let t=.05;t<1;t+=.05){const p={x:r.a.x+(r.b.x-r.a.x)*t,y:r.a.y+(r.b.y-r.a.y)*t};assert.ok(!(p.x>4032.01&&p.x<4159.99&&p.y>4032.01&&p.y<4159.99));}});
test('retour : une jonction opposée ne passe pas par le centre fictif',()=>{const{g}=carFixture();g.returnRoutes.verify('car');g.returnRoutes.select('west');const b=g.returnRoutes.budget();assert.equal(b.status,'connected');assert.ok(b.regionMetres>1000);for(let i=1;i<b.regionalPath.length;i++)for(let t=.1;t<1;t+=.1){const a=b.regionalPath[i-1],c=b.regionalPath[i],x=a.x+(c.x-a.x)*t,y=a.y+(c.y-a.y)*t;assert.ok(!(x>4032.1&&x<4159.9&&y>4032.1&&y<4159.9));}});
test('retour : le décalage de grille retrouve une porte de deux cellules réellement franchissable',()=>{const{game:g}=fresh();ring(g);g.world.remove(g.world.atCell(74,64));g.world.remove(g.world.atCell(74,65));const v=g.returnRoutes.verify('car');assert.ok(v.gates.some(q=>q.path));for(const gate of v.gates.filter(q=>q.path)){const search=Routes.createSearch(g,'car');for(let i=1;i<gate.path.length;i++)assert.ok(search.segment(gate.path[i-1],gate.path[i]));}});
test('retour : distinguer arrivée centrale bloquée et chemin intérieur non trouvé',()=>{const{game:g}=fresh();ring(g);put(g,'woodWall',126,64);const e=g.returnRoutes.verify('foot').gates.find(q=>q.id==='east');assert.equal(e.central,'entry-blocked');assert.equal(e.path,null);assert.equal(e.status,'no-path');});
