'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/core.js'),T=require('../src/tactics.js'),{bootGame}=require('./helpers/browser.cjs');
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function add(g,type,x,y){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,1);g.world.add(b);return b;}
function wallColumn(g){for(let y=61;y<=66;y++)add(g,'woodWall',66,y);g.refreshMetrics(true);}
function validArrival(g,actor,p){assert.ok(g.friendlyPositionClear(actor,p.x,p.y));assert.ok(Math.hypot(p.x-g.core().x,p.y-g.core().y)<180);assert.ok(![...g.world.buildings.values()].some(b=>T.blocksFriendly(b)&&T.overlapsBuilding(b,{...actor,...p})));}
test('arrivées : un point extérieur déjà libre est conservé',()=>{const{game:g}=fresh(),p={x:g.core().x+90,y:g.core().y};assert.deepEqual(g.coreArrivalPosition(g.player,p),p);});
test('réanimation : un mur adjacent renvoie vers un accès extérieur, jamais sous le centre',()=>{const{game:g}=fresh();wallColumn(g);g.player.dead=true;g.player.health=0;g.player.downTimer=.01;g.player.x=3000;g.player.y=3000;g.player.carry.wood=12;g.updatePlayer(.1);assert.equal(g.player.dead,false);assert.equal(g.player.health,g.player.maxHealth);assert.equal(g.player.carry.wood,6);validArrival(g,g.player,g.player);const x=g.player.x;g.input.keys.add('KeyA');g.updatePlayer(.04);assert.ok(g.player.x<x);});
test('accueil payé : un seul ouvrier, frais conservés et point libre près du centre',()=>{const{game:g}=fresh();wallColumn(g);g.activeCrisis={id:'injury',wave:g.wave,status:'pending',remaining:30,targetId:0,choice:null};const before={...g.resources},n=g.units.length;assert.ok(g.resolveCrisis('A'));assert.equal(g.units.length,n+1);const u=g.units.at(-1);validArrival(g,u,u);assert.equal(g.resources.food,before.food-12);assert.equal(g.resources.medicine,before.medicine-6);assert.ok(g.save(false));assert.ok(g.load());assert.ok(g.units.some(p=>p.id===u.id));});
test('accueil : le rayon entier ne reste pas partiellement sous le centre',()=>{const{game:g}=fresh(),p={x:g.core().x+70,y:g.core().y-25};const arrival=g.coreArrivalPosition(g.units[0],p);validArrival(g,g.units[0],arrival);assert.ok(Math.hypot(arrival.x-p.x,arrival.y-p.y)>0);});
test('arrivées : le coin d’un mur ne laisse pas passer un acteur trop large',()=>{const{game:g}=fresh(),b=add(g,'woodWall',66,64),p={x:b.left-5,y:b.top-5};const a=g.coreArrivalPosition(g.player,p);validArrival(g,g.player,a);assert.ok(!T.overlapsBuilding(b,{...g.player,...a}));});
test('arrivées : auto/ouvert restent accessibles, fermé impose un accès extérieur',()=>{for(const mode of ['auto','open','closed']){const{game:g}=fresh(),b=add(g,'gate',66,63);b.gateMode=mode;g.world.navigationVersion++;const p={x:b.x,y:b.y};const result=g.coreArrivalPosition(g.player,p);validArrival(g,g.player,result);if(mode==='closed')assert.notDeepEqual(result,p);else assert.deepEqual(result,p);}});
test('arrivées : coordonnées hors monde remplacées sans modification des réserves',()=>{const{game:g}=fresh();wallColumn(g);const money={...g.resources};for(const p of [{x:-100,y:2000},{x:5000,y:2050}])validArrival(g,g.player,g.coreArrivalPosition(g.player,p));assert.deepEqual(g.resources,money);});
