'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/core.js'),Save=require('../src/save.js');
const{bootGame}=require('./helpers/browser.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function put(g,type,x,y){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,1);g.world.add(b);g.refreshMetrics(true);return b;}
function fixture(){
 const e=bootGame(),g=e.game;g.startNew('standard','17117');put(g,'planningOffice',70,59);put(g,'warehouse',71,64);g.units=[g.units[0]];g.refreshMetrics(true);
 const d=g.serialize();
 // This artificial site needs a free endpoint: a current save must keep its
 // existing props, rather than repack the stone that overlapped the old point.
 Object.assign(d.dayworks.sites[1],{x:2448,y:2128,seen:true,survey:6});g.restoreSave(d);
 assert.deepEqual(g.fieldcraft.snapshot().nodes,d.fieldcraft.nodes,'La fixture conserve les positions physiques sauvegardées.');
 assert.ok(g.friendlyPositionClear(g.units[0],d.dayworks.sites[1].x,d.dayworks.sites[1].y),'Le lieu artificiel est accessible avec le rayon réel de l’ouvrier.');
 return{...e,id:d.dayworks.sites[1].id,u:g.units[0]};
}
const site=(g,id)=>g.dayworks.snapshot().sites.find(s=>s.id===id);
const step=(g,n)=>{for(let i=0;i<n&&!g.gameOver&&!g.paused;i++){g.update(.04);g.input.pressed.clear();}};
function until(g,condition,n=2200){for(let i=0;i<n;i++){if(condition())return i;step(g,1);}assert.ok(condition(),'condition non atteinte');return n;}
const stable=g=>{const d=g.serialize();delete d.timestamp;return JSON.stringify(d);};
test('récupération: format courant avec limites et bilan vide',()=>{assert.equal(C.SAVE_VERSION,20);assert.equal(C.Salvage.RULES.maxCrews,4);assert.equal(C.Salvage.RULES.cost.food,4);assert.deepEqual(C.Salvage.normalize(),C.Salvage.empty())});
test('récupération: démarrage neuf ne produit aucune erreur de sauvegarde',()=>{const{game:g}=bootGame(),old=console.error;let errors=[];try{console.error=(...x)=>errors.push(x);g.startNew();assert.equal(g.lastSaveStatus.ok,true);assert.equal(errors.length,0)}finally{console.error=old}});
test('récupération: état de campagne inchangé lors du devis et du tableau',()=>{const{game:g,id}=fixture(),before=stable(g);for(let i=0;i<20;i++){assert.ok(g.salvage.status(id).ok);g.salvage.overview();}assert.equal(stable(g),before)});
test('récupération: paiement unique, même ouvrier et population identique',()=>{const{game:g,id,u}=fixture(),before=g.resources.food,pop=g.population;assert.ok(g.salvage.assign(id).ok);assert.equal(g.resources.food,before-4);assert.equal(g.units.length,1);assert.equal(g.population,pop);assert.equal(g.salvage.snapshot().crews[0].id,u.id);assert.equal(g.lastSaveStatus.ok,true);assert.equal(g.salvage.assign(id).ok,false);assert.equal(g.resources.food,before-4)});
test('récupération: le relevé du commandant est obligatoire',()=>{const{game:g,id}=fixture(),d=g.serialize();d.dayworks.sites[1].survey=5;g.restoreSave(d);const before=g.resources.food;assert.equal(g.salvage.assign(id).ok,false);assert.equal(g.resources.food,before)});
test('récupération: bureau, entrepôt et quatre rations réellement requis',()=>{for(const blocked of ['planningOffice','warehouse','food']){const{game:g,id}=fixture();if(blocked==='food')g.resources.food=3;else{const b=[...g.world.buildings.values()].find(b=>b.type===blocked);g.world.remove(b)}const before=stable(g);assert.equal(g.salvage.assign(id).ok,false);assert.equal(stable(g),before)}});
test('récupération: un site inconnu, épuisé ou inexistant est refusé',()=>{const{game:g,id}=fixture();for(const key of ['unknown','__proto__',null,'housing-1'])assert.equal(g.salvage.assign(key).ok,false);const d=g.serialize();d.dayworks.sites[1].remaining=0;g.restoreSave(d);assert.equal(g.salvage.assign(id).ok,false)});
test('récupération: départ interdit la nuit, à terre et sous repli général',()=>{for(const mode of ['night','dead','retreat']){const{game:g,id}=fixture();if(mode==='night')g.phase='assault';else if(mode==='dead')g.player.dead=true;else g.workerOrder='retreat';assert.equal(g.salvage.assign(id).ok,false)}});
test('récupération: trajet réel, prélèvement local puis retour avec dix ressources',()=>{const{game:g,id,u}=fixture(),before=site(g,id).remaining,stock=g.resources.wood;g.salvage.assign(id);assert.equal(site(g,id).remaining,before);assert.equal(g.resources.wood,stock);until(g,()=>u.carry>0);assert.ok(Math.hypot(u.x-site(g,id).x,u.y-site(g,id).y)<=48);assert.equal(g.resources.wood,stock);until(g,()=>g.salvage.snapshot().stats.returned===1);assert.ok(Math.abs(site(g,id).remaining-(before-10))<1e-7);assert.ok(Math.abs(g.resources.wood-(stock+10))<1e-7);assert.equal(u.carry,0);assert.equal(g.salvage.snapshot().crews.length,0)});
test('récupération: le sac précédent est déposé avant de charger le nouveau lieu',()=>{const{game:g,id,u}=fixture();u.carry=3;u.carryType='stone';const before=g.resources.stone;g.salvage.assign(id);assert.equal(g.salvage.snapshot().crews[0].prepared,false);until(g,()=>g.salvage.snapshot().crews[0]?.prepared);assert.ok(Math.abs(g.resources.stone-before-3)<1e-7);assert.equal(u.carry,0);assert.equal(site(g,id).remaining,32)});
test('récupération: un ouvrier ne vide jamais une réserve à distance',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);const before=site(g,id).remaining;assert.equal(g.dayworks.recoverForWorker(u,id,.2),0);assert.equal(site(g,id).remaining,before)});
test('récupération: temps invalides, unité étrangère et autre site refusés',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);Object.assign(u,{x:site(g,id).x,y:site(g,id).y});for(const dt of [NaN,Infinity,-1,0,99])assert.equal(g.dayworks.recoverForWorker(u,id,dt),0);assert.equal(g.dayworks.recoverForWorker({...u},id,.1),0);assert.equal(g.dayworks.recoverForWorker(u,'housing-1',.1),0);assert.equal(site(g,id).remaining,32)});
test('récupération: reliquat inférieur au sac conservé exactement',()=>{const{game:g,id}=fixture(),d=g.serialize();d.dayworks.sites[1].remaining=2.25;g.restoreSave(d);const before=g.resources.wood;g.salvage.assign(id);until(g,()=>g.salvage.snapshot().stats.returned===1);assert.equal(site(g,id).remaining,0);assert.ok(Math.abs(g.resources.wood-before-2.25)<1e-7)});
test('récupération: chargement partagé avec le joueur, jamais sous zéro',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);Object.assign(u,{x:site(g,id).x,y:site(g,id).y});g.player.x=u.x;g.player.y=u.y;g.dayworks.setTool('survey');g.input.keys.add('KeyE');for(let i=0;i<200;i++){g.updateInteraction(.04);g.dayworks.recoverForWorker(u,id,.04)}g.input.keys.clear();const total=C.bagTotal(g.player.carry)+u.carry+site(g,id).remaining;assert.ok(Math.abs(total-32)<1e-7);assert.ok(site(g,id).remaining>=0)});
test('récupération: retour incomplet reste au dépôt saturé avec son sac',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=u.maxCarry-.001);g.resources.wood=g.storage;until(g,()=>g.workerCanWorkAt(u,g.core(),65));step(g,15);assert.ok(u.carry>9.99);assert.equal(g.salvage.snapshot().stats.returned,0);g.resources.wood-=3;step(g,2);assert.ok(Math.abs(u.carry-7)<1e-7);g.resources.wood-=20;until(g,()=>g.salvage.snapshot().stats.returned===1);assert.equal(u.carry,0)});
test('récupération: rappel manuel ramène la cargaison partielle sans remboursement',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=1);const load=u.carry,stock=g.resources.wood;assert.ok(g.salvage.recall(u.id));until(g,()=>g.salvage.snapshot().stats.returned===1);assert.ok(Math.abs(g.resources.wood-stock-load)<1e-7);assert.equal(g.salvage.snapshot().stats.dispatched,1)});
test('récupération: au crépuscule, la collecte s’arrête mais le retour continue',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=1);g.phaseTime=.01;step(g,1);assert.equal(g.phase,'warning');assert.equal(g.salvage.snapshot().crews[0].returning,true);const before=site(g,id).remaining;step(g,10);assert.equal(site(g,id).remaining,before)});
test('récupération: danger visible déclenche le repli avec le sac',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=1);g.spawnZombie('walker');const z=g.zombies.at(-1);z.x=u.x+25;z.y=u.y;g.rebuildBuckets();g.salvage.updateAssignedUnit(u,.04);assert.equal(g.salvage.snapshot().crews[0].returning,true);assert.ok(u.carry>0)});
test('récupération: dépôt détruit ou repli général rappelle les équipes',()=>{for(const mode of ['warehouse','retreat','planningOffice']){const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=1);if(mode==='retreat')g.workerOrder='retreat';else{const b=[...g.world.buildings.values()].find(b=>b.type===mode);g.destroyBuilding(b)}g.salvage.overview();assert.equal(g.salvage.snapshot().crews[0].returning,true)}});
test('récupération: mort fait perdre le sac sans reconstituer le lieu',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);until(g,()=>u.carry>=1);const before=site(g,id).remaining,wood=g.resources.wood;u.dead=true;u.health=0;const s=g.salvage.snapshot();assert.equal(s.stats.lost,1);assert.equal(s.crews.length,0);assert.equal(site(g,id).remaining,before);assert.equal(g.resources.wood,wood);assert.ok(g.save(false))});
test('récupération: ouvriers non détournés vers la voirie',()=>{const{game:g,id,u}=fixture();put(g,'roadDepot',74,59);g.salvage.assign(id);assert.equal(g.infrastructure.assign(u.id).ok,false);assert.equal(g.infrastructure.snapshot().crew.length,0)});
test('récupération: ouvriers non détournés vers les secours',()=>{const{game:g,id}=fixture();put(g,'workshop',70,70);put(g,'generator',76,65);put(g,'fireStation',76,70);g.salvage.assign(id);assert.equal(g.siege.assign().ok,false);assert.equal(g.siege.snapshot().crew.length,0)});
test('récupération: ouvrier déjà affecté à la voirie non assignable',()=>{const{game:g,id,u}=fixture();put(g,'roadDepot',74,59);assert.ok(g.infrastructure.assign(u.id).ok);assert.equal(g.salvage.assign(id).ok,false)});
test('sauvegarde: quatre reprises conservent équipe, sac et réserve du lieu',()=>{const{game:g,id}=fixture();g.salvage.assign(id);until(g,()=>g.units[0].carry>=2);const before=stable(g);for(let i=0;i<4;i++){assert.ok(g.save(false));assert.ok(g.load());assert.equal(stable(g),before)}until(g,()=>g.salvage.snapshot().stats.returned===1);assert.equal(g.salvage.snapshot().stats.dispatched,1)});
test('sauvegarde: ancien format 8 migre sans octroyer équipe ni matériau',()=>{const{game:g}=fixture(),d=g.serialize();d.version=8;delete d.salvage;const before=copy(d.resources),next=Save.validate(d);assert.equal(next.version,C.SAVE_VERSION);assert.deepEqual(next.salvage,C.Salvage.empty());assert.deepEqual(next.resources,before);g.restoreSave(d);assert.equal(g.salvage.snapshot().crews.length,0)});
test('sauvegarde: registre v9 obligatoire et erreurs avant mutation du monde',()=>{const{game:g,id}=fixture();g.salvage.assign(id);const d=g.serialize(),w=g.world,money=copy(g.resources);delete d.salvage;assert.throws(()=>g.restoreSave(d),/registre/);assert.equal(g.world,w);assert.deepEqual(g.resources,money)});
test('sauvegarde: identités, doublons et références étrangères refusés',()=>{const{game:g,id}=fixture();g.salvage.assign(id);const d=g.serialize();for(const mutate of [s=>s.crews.push({...s.crews[0]}),s=>s.crews[0].id=9999,s=>s.crews[0].site='unknown',s=>s.crews[0].prepared='true',s=>s.stats.returned=2]){const bad=copy(d);mutate(bad.salvage);assert.throws(()=>Save.validate(bad))}});
test('sauvegarde: affectation double aux secours ou à la voirie refusée',()=>{const{game:g,id,u}=fixture();g.salvage.assign(id);for(const system of ['siege','infrastructure']){const d=g.serialize();d[system].crew=system==='siege'?[{id:u.id,water:0,release:false}]:[{id:u.id,returning:false}];assert.throws(()=>Save.validate(d),/affecté/)}});
test('sauvegarde: nouvelle campagne ne conserve jamais la précédente équipe',()=>{const{game:g,id}=fixture();g.salvage.assign(id);g.startNew('standard','42');assert.deepEqual(g.salvage.snapshot(),C.Salvage.empty());assert.equal(g.lastSaveStatus.ok,true)});
for(const id of ['returnRelay','foodCourt','materialsCourt','entryBastion'])test('ensembles: '+id+' sans chevauchement, coût normal et empreintes exactes',()=>{const D=C.Dayworks,p=D.PLANS.find(p=>p.id===id),items=D.footprint(id,20,20),cells=new Set();for(const i of items){const d=C.BUILDINGS[i.type];for(let y=0;y<d.size[1];y++)for(let x=0;x<d.size[0];x++){const key=(i.gx+x)+':'+(i.gy+y);assert.ok(!cells.has(key));cells.add(key);assert.ok(i.gx+x<20+p.w&&i.gy+y<20+p.h)}}const q=D.quote(items,C.BUILDINGS,()=>({valid:true}),6,()=>true);assert.ok(q.ok);const cost={};for(const i of items)for(const [r,n]of Object.entries(C.BUILDINGS[i.type].cost))cost[r]=(cost[r]||0)+n;assert.deepEqual(q.cost,cost)});
test('ensembles: entrée historique intacte et quatre cours tardives distinctes',()=>{const p=C.Dayworks.footprint('entryBastion',0,0);assert.equal(p.filter(i=>i.type==='woodWall').length,19);assert.equal(p.filter(i=>i.type==='watchtower').length,2);assert.equal(p.filter(i=>i.type==='gate').length,1);assert.ok(!p.some(i=>i.gy===6&&i.gx===4));assert.deepEqual(C.Dayworks.PLANS.slice(0,11).map(p=>p.id),['courtyard','airlock','camp','returnRelay','foodCourt','materialsCourt','entryBastion','observationRelay','careCourt','spikedApproach','maintenanceRedoubt']);assert.deepEqual(C.Dayworks.PLANS.slice(11).map(p=>p.id),['forwardCare150','electricFoodCourt150','watchedBastion150','continuitySector150'])});
test('sauvegarde: formats 1 à 8 migrés sans rations, équipe ou ressources gratuites',()=>{const{game:g}=fixture();const raw=g.serialize();for(let version=1;version<=8;version++){const d=copy(raw);d.version=version;delete d.salvage;const r=Save.validate(d);assert.equal(r.version,C.SAVE_VERSION);assert.deepEqual(r.resources,raw.resources);assert.deepEqual(r.salvage,C.Salvage.empty());}});
test('sauvegarde: un sac de récupération surchargé ou d’un autre matériau est refusé',()=>{const{game:g,id}=fixture();g.salvage.assign(id);for(const [carry,carryType] of [[11,'wood'],[2,'ammo']]){const d=g.serialize();Object.assign(d.units[0],{carry,carryType});assert.throws(()=>Save.validate(d),/Sac de récupération/);}});
