'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),G=require('../src/frontier-geometry.js'),Save=require('../src/save.js');const copy=o=>JSON.parse(JSON.stringify(o));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function enter(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}
function step(g,n){for(let i=0;i<n;i++){g.update(.04);g.input.pressed.clear();}}
function prepareCache(g,empty=true){enter(g);const w=g.frontier.world(),p=w.pois.find(p=>p.type==='warehouse'),b=w.plan(p,0).objects.find(b=>b.kind==='shelf'),d=g.serialize(),q=G.global(p,b.x+b.w/2,b.y+b.h+1);Object.assign(d.frontier,{x:q.x,y:q.y,z:0,inside:p.id,seen:[p.id]});for(let i=0;i<1+G.hash(d.worldSeed,p.id,'threat')%4;i++){d.frontier.enemies[p.id+':e'+i]=0;delete d.frontier.tracks[p.id+':e'+i];}d.frontier.kills=Object.values(d.frontier.enemies).filter(h=>h===0).length;if(empty)d.frontier.taken[b.id]=b.amount;g.restoreSave(d);g.player.carry.wood=6;g.player.carry.scrap=4;return{p,b};}
function carFixture(){const e=fresh(),g=e.game,{standAt}=require('./helpers/physical-fixtures.cjs');const b=new(g.core().constructor)(g.nextId++,'expeditionGarage',77,65,0,1);g.world.add(b);g.refreshMetrics(true);g.fieldcraft.setup();standAt(g,g.player,g.core());g.resources.wood=g.resources.scrap=300;assert.ok(g.expeditions.buildCar().ok);const v=g.expeditions.car();g.player.x=v.x=4058;g.player.y=v.y=2048;v.driving=true;v.fuel=8;g.player.radius=22;assert.ok(g.frontier.enter());assert.ok(g.frontier.board());return{...e,v};}
test('relève : migration 1–16 sans cache ni ressource offerte',()=>{const{game:g}=fresh(),d=g.serialize();for(let version=1;version<=16;version++){const raw=copy(d);raw.version=version;delete raw.fieldSupplies;const out=Save.validate(raw);assert.equal(out.version,20);assert.deepEqual(out.resources,d.resources);assert.deepEqual(out.fieldSupplies.caches,[]);}});
test('soins : paiement après quatre secondes, quantité transportée uniquement',()=>{const{game:g}=fresh();enter(g);g.player.health=40;g.resources.medicine=80;assert.equal(g.fieldSupplies.begin('heal').ok,false);g.player.carry.medicine=2;assert.ok(g.fieldSupplies.begin('heal').ok);step(g,50);assert.equal(g.player.health,40);assert.equal(g.player.carry.medicine,2);step(g,50);assert.equal(g.player.health,75);assert.equal(g.player.carry.medicine,0);assert.equal(g.resources.medicine,80);});
test('soins : aucune dépense à pleine vie, aucun dépassement',()=>{const{game:g}=fresh();enter(g);g.player.carry.medicine=2;assert.equal(g.fieldSupplies.begin('heal').ok,false);g.player.health=95;assert.ok(g.fieldSupplies.begin('heal').ok);step(g,100);assert.equal(g.player.health,100);assert.equal(g.player.carry.medicine,0);});
test('soins : déplacement interrompt sans coût et sans restauration de vie',()=>{const{game:g}=fresh();enter(g);g.player.health=40;g.player.carry.medicine=2;g.fieldSupplies.begin('heal');step(g,20);g.input.keys.add('KeyD');step(g,1);g.input.keys.clear();step(g,100);assert.equal(g.player.health,40);assert.equal(g.player.carry.medicine,2);assert.equal(g.fieldSupplies.busy(),false);});
test('soins : dégâts et rechargement interrompent, pause ne fait pas progresser',()=>{const{game:g}=fresh();enter(g);g.player.health=60;g.player.carry.medicine=2;g.fieldSupplies.begin('heal');g.paused=true;step(g,200);assert.equal(g.fieldSupplies.overview().task.elapsed,0);g.paused=false;g.player.health=55;step(g,1);assert.equal(g.fieldSupplies.busy(),false);assert.equal(g.player.carry.medicine,2);g.fieldSupplies.begin('heal');g.input.keys.add('KeyR');step(g,1);g.input.keys.clear();assert.equal(g.fieldSupplies.busy(),false);});
test('soins : sauvegarder une action inachevée ne produit pas un soin au rechargement',()=>{const{game:g}=fresh();enter(g);g.player.health=40;g.player.carry.medicine=2;g.fieldSupplies.begin('heal');step(g,40);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.fieldSupplies.busy(),false);step(g,120);assert.equal(g.player.health,40);assert.equal(g.player.carry.medicine,2);});
test('relai : emplacement vidé obligatoire et coût réel à la fin du travail',()=>{const{game:g}=fresh(),{b}=prepareCache(g);const before=g.frontier.snapshot().taken[b.id];assert.ok(g.fieldSupplies.begin('cache',b.id).ok);step(g,124);assert.equal(g.fieldSupplies.snapshot().caches.length,0);assert.equal(g.player.carry.wood,6);step(g,1);assert.equal(g.fieldSupplies.snapshot().caches.length,1);assert.equal(g.player.carry.wood,0);assert.equal(g.player.carry.scrap,0);assert.equal(C.bagTotal(g.fieldSupplies.snapshot().caches[0].stock),0);assert.equal(g.frontier.snapshot().taken[b.id],before);});
test('relai : contenant plein et candidat invalide refusés sans effacer le butin',()=>{const{game:g}=fresh(),{b}=prepareCache(g,false);assert.equal(g.fieldSupplies.begin('cache',b.id).ok,false);assert.equal(g.fieldSupplies.begin('cache','P9999:0:0').ok,false);assert.equal(g.frontier.snapshot().taken[b.id],undefined);assert.equal(g.player.carry.wood,6);});
test('relai : dépôt et retrait conservent chaque ressource, capacité globale de 60',()=>{const{game:g}=fresh(),{b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);g.player.carry.wood=38;assert.equal(g.fieldSupplies.transfer(b.id,'wood','deposit','max').amount,38);g.player.carry.scrap=38;assert.equal(g.fieldSupplies.transfer(b.id,'scrap','deposit','max').amount,22);assert.equal(C.bagTotal(g.fieldSupplies.snapshot().caches[0].stock),60);assert.equal(g.player.carry.scrap,16);assert.equal(g.fieldSupplies.transfer(b.id,'wood','withdraw',5).amount,5);assert.equal(g.player.carry.wood,5);assert.equal(g.fieldSupplies.snapshot().caches[0].stock.wood,33);});
test('relai : reprises conservent le stock et le contenant original vidé',()=>{const{game:g}=fresh(),{b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);g.player.carry.food=8;g.fieldSupplies.transfer(b.id,'food','deposit','max');const f=copy(g.frontier.snapshot().taken),r=g.fieldSupplies.snapshot();for(let i=0;i<4;i++){assert.ok(g.save(false));assert.ok(g.load());}assert.deepEqual(g.fieldSupplies.snapshot(),r);assert.deepEqual(g.frontier.snapshot().taken,f);});
test('relai : retrait interdit à distance ou derrière une cloison',()=>{const{game:g}=fresh(),{p,b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);g.player.carry.food=8;g.fieldSupplies.transfer(b.id,'food','deposit',8);const d=g.serialize();d.frontier.x+=120;d.frontier.inside=null;g.restoreSave(d);assert.equal(g.fieldSupplies.transfer(b.id,'food','withdraw',1).ok,false);assert.equal(g.fieldSupplies.snapshot().caches[0].stock.food,8);});
test('relai : retrait d’un relais non vide refusé, aucun remboursement à vide',()=>{const{game:g}=fresh(),{b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);g.player.carry.food=2;g.fieldSupplies.transfer(b.id,'food','deposit',2);assert.equal(g.fieldSupplies.remove(b.id),false);g.fieldSupplies.transfer(b.id,'food','withdraw',2);assert.ok(g.fieldSupplies.remove(b.id));assert.equal(g.player.carry.wood,0);assert.equal(g.fieldSupplies.snapshot().caches.length,0);});
test('coffre : reprise de provisions et plafond du sac sans création',()=>{const{game:g,v}=carFixture();v.cargo.medicine=10;for(const k of C.RESOURCE_KEYS)g.player.carry[k]=0;g.player.carry.wood=g.player.carryCapacity-3;const total=v.cargo.medicine+g.player.carry.medicine;assert.equal(g.fieldSupplies.transfer('car','medicine','withdraw',5).amount,3);assert.equal(C.bagTotal(g.player.carry),g.player.carryCapacity);assert.equal(v.cargo.medicine+g.player.carry.medicine,total);});
test('dépôt : préparation réelle à D-17 et interdiction de retrait distant',()=>{const{game:g}=fresh(),{standAt}=require('./helpers/physical-fixtures.cjs');standAt(g,g.player,g.core());const before=g.resources.medicine;assert.equal(g.fieldSupplies.transfer('depot','medicine','withdraw',2).amount,2);assert.equal(g.resources.medicine,before-2);enter(g);assert.equal(g.fieldSupplies.transfer('depot','medicine','withdraw',2).ok,false);});
test('réparation : 50 points pour 12 ferrailles après six secondes, sans remplir le réservoir',()=>{const{game:g,v}=carFixture();v.health=230;g.player.carry.scrap=12;const fuel=v.fuel;assert.ok(g.fieldSupplies.begin('repair').ok);step(g,149);assert.equal(v.health,230);assert.equal(g.player.carry.scrap,12);step(g,1);assert.equal(v.health,280);assert.equal(g.player.carry.scrap,0);assert.equal(v.fuel,fuel);});
test('réparation : détruit ou nuit, aucun chantier et aucune résurrection',()=>{const{game:g,v}=carFixture();v.health=0;g.player.carry.scrap=12;assert.equal(g.fieldSupplies.begin('repair').ok,false);v.health=200;g.phase='warning';assert.equal(g.fieldSupplies.begin('repair').ok,false);assert.equal(g.player.carry.scrap,12);});
test('transfert : entrées invalides sans débit, dépôt saturé ne détruit pas le reliquat',()=>{const{game:g,v}=carFixture();v.cargo.food=80;g.player.carry.wood=10;for(const x of [-1,0,NaN,Infinity,'10'])assert.equal(g.fieldSupplies.transfer('car','wood','deposit',x).ok,false);assert.equal(g.fieldSupplies.transfer('car','__proto__','deposit',5).ok,false);assert.equal(g.fieldSupplies.transfer('car','wood','deposit',10).ok,false);assert.equal(v.cargo.food,80);assert.equal(g.player.carry.wood,10);});
test('retour : trajet aller + retour + marge, calcul sans mutation',()=>{const{game:g,v}=carFixture();const p=g.frontier.world().pois.find(p=>p.type==='library'),d=g.serialize();d.frontier.seen.push(p.id);g.restoreSave(d);g.frontier.pin(p.id);const before=g.serialize();delete before.timestamp;const r=g.fieldSupplies.routePlan();assert.ok(r&&r.metres>r.outwardMetres);assert.ok(Math.abs(r.required-r.fuel*1.25-2)<1e-6);const after=g.serialize();delete after.timestamp;assert.deepEqual(after,before);assert.ok(g.fieldSupplies.reserve(4));assert.equal(g.fieldSupplies.routePlan().reserve,4);assert.equal(g.fieldSupplies.reserve(-1),false);});
test('validation : doublons, surcapacité, contenant plein et faux type rejetés avant mutation',()=>{const{game:g}=fresh(),{b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);const world=g.world,d=g.serialize();for(const fn of [x=>x.fieldSupplies.caches.push(copy(x.fieldSupplies.caches[0])),x=>x.fieldSupplies.caches[0].stock.food=61,x=>x.fieldSupplies.caches[0].stock.food=NaN,x=>x.frontier.taken[b.id]=0,x=>x.fieldSupplies.caches[0].id='P9999:0:0',x=>x.fieldSupplies.reserve=9]){const q=copy(d);fn(q);assert.throws(()=>g.restoreSave(q));assert.equal(g.world,world);}});
test('nouvelle campagne : aucun relais, stock ou action hérité',()=>{const{game:g}=fresh(),{b}=prepareCache(g);g.fieldSupplies.begin('cache',b.id);step(g,125);g.startNew('standard','42');assert.deepEqual(g.fieldSupplies.snapshot(),C.FieldSupplies.initial());assert.equal(g.fieldSupplies.busy(),false);});
test('transaction : coût indisponible au dernier instant annule sans paiement partiel',()=>{const{game:g}=fresh();enter(g);g.player.health=40;g.player.carry.medicine=2;g.fieldSupplies.begin('heal');step(g,99);g.player.carry.medicine=1;step(g,1);assert.equal(g.player.health,40);assert.equal(g.player.carry.medicine,1);assert.equal(g.fieldSupplies.busy(),false);});
test('limites : maximum de seize relais et clés de ressource strictes',()=>{const L=C.FieldSupplies,d=L.initial();for(let i=0;i<16;i++)d.caches.push({id:'P'+String(i).padStart(4,'0')+':0:0',stock:L.emptyBag()});assert.equal(L.normalize(d).caches.length,16);d.caches.push({id:'P0016:0:0',stock:L.emptyBag()});assert.throws(()=>L.normalize(d));d.caches.pop();d.caches[0].stock.credits=5;assert.throws(()=>L.normalize(d));});
