'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs');
const C=require('../src/core.js'),S=require('../src/survival-pack.js');
function fresh(){const {game:g}=bootGame();require('../src/night-gear.js').install(g);require('../src/expansion-kit.js').install(g);S.install(g);g.startNew('standard','17117');g.player.x=2400;g.player.y=2480;g.player.facing=0;g.phaseTime=999;for(const k of C.RESOURCE_KEYS)g.player.carry[k]=k==='food'?25:k==='wood'?20:k==='scrap'?15:k==='fuel'?8:k==='medicine'?4:0;g.player.carryCapacity=100;return g;}
function step(g,n){for(let i=0;i<Math.ceil(n/.04);i++){g.survivalPack.step(.04);}}
function camp(g){let q=g.survivalPack.preview('camp');if(!q.ok&&q.reason.includes('sol')){for(let y=2250;y<3000&&!q.ok;y+=80)for(let x=2250;x<3000&&!q.ok;x+=80){g.player.x=x;g.player.y=y;q=g.survivalPack.preview('camp');}}assert.ok(q.ok,q.reason);assert.ok(g.survivalPack.begin('camp').ok);step(g,C.SurvivalPackRules.camp.seconds);assert.equal(g.survivalPack.snapshot().camps.length,1);return g.survivalPack.snapshot().camps[0];}
function withCampfire(g){let spot=null;for(let y=2250;y<3000&&!spot;y+=40)for(let x=2250;x<3000&&!spot;x+=40){const a={x,y},b={x:x+45,y};if(g.friendlyPositionClear(g.player,x,y)&&g.friendlyPositionClear({radius:9},b.x,b.y)&&g.nightGear.localLineClear(a,b))spot=a;}assert.ok(spot,'un vrai accès dégagé au foyer existe');Object.assign(g.player,spot);const d=g.serialize();d.nightGear={version:1,serial:2,devices:[{id:1,kind:'campfire',location:'placed',domain:'local',x:g.player.x+45,y:g.player.y,z:0,inside:null,angle:0,left:300,on:true,used:true}]};g.restoreSave(d);}
test('bivouac : migration vide, cinq systèmes et coût payé après travail réel',()=>{const g=fresh(),before={...g.player.carry};assert.deepEqual(g.survivalPack.snapshot(),S.initial());assert.equal(['camp','meal','dressing','cover','service'].filter(k=>C.SurvivalPackRules[k]).length,5);camp(g);assert.equal(g.player.carry.wood,before.wood-12);assert.equal(g.player.carry.scrap,before.scrap-6);assert.equal(g.survivalPack.snapshot().camps[0].left,600);});
test('bivouac : déplacement et interruption conservent toutes les ressources',()=>{const g=fresh();camp(g);g.player.health=60;const before={...g.player.carry};assert.ok(g.survivalPack.begin('rest').ok);step(g,2);g.player.x+=10;step(g,.04);assert.equal(g.survivalPack.busy(),false);assert.deepEqual(g.player.carry,before);assert.equal(g.player.health,60);assert.ok(g.survivalPack.begin('rest').ok);g.survivalPack.cancel();assert.deepEqual(g.player.carry,before);});
test('bivouac : pause et modale gèlent préparations et durées',()=>{const g=fresh();camp(g);g.player.health=60;assert.ok(g.survivalPack.begin('rest').ok);const before=g.survivalPack.snapshot();g.paused=true;step(g,30);assert.deepEqual(g.survivalPack.snapshot(),before);assert.equal(g.survivalPack.overview().task.progress,0);g.paused=false;g.activeOverlay={};step(g,30);assert.deepEqual(g.survivalPack.snapshot(),before);g.activeOverlay=null;step(g,12);assert.equal(g.player.health,76);});
test('bivouac : menaces, portée et décès refusent ou annulent la relève',()=>{const g=fresh();camp(g);g.player.health=60;const old=g.nearbyZombies;g.nearbyZombies=()=>[{x:g.player.x+30,y:g.player.y,health:60,dead:false}];assert.equal(g.survivalPack.preview('rest').ok,false);g.nearbyZombies=old;assert.ok(g.survivalPack.begin('rest').ok);const food=g.player.carry.food;g.player.health-=2;step(g,.04);assert.equal(g.survivalPack.busy(),false);assert.equal(g.player.carry.food,food);g.player.x+=500;assert.equal(g.survivalPack.preview('rest').ok,false);g.player.dead=true;assert.equal(g.survivalPack.preview('dressing').ok,false);});
test('bivouac : repas exige un vrai foyer accessible et dure seulement deux minutes',()=>{const g=fresh();assert.equal(g.survivalPack.preview('meal').ok,false);withCampfire(g);const food=g.player.carry.food;assert.ok(g.survivalPack.begin('meal').ok);step(g,8);assert.equal(g.player.carry.food,food-4);assert.equal(g.survivalPack.snapshot().meal.left,120);assert.equal(g.survivalPack.begin('meal').ok,false);step(g,120.1);assert.deepEqual(g.survivalPack.snapshot().meal,{left:0,budget:0});});
test('bivouac : pansement progressif payé, plafonné et rompu par les dégâts',()=>{const g=fresh();g.player.health=50;const medicine=g.player.carry.medicine;assert.ok(g.survivalPack.begin('dressing').ok);step(g,5);assert.equal(g.player.health,50);assert.equal(g.player.carry.medicine,medicine-2);step(g,5);assert.ok(Math.abs(g.player.health-53)<1e-6);const d=g.serialize();g.restoreSave(d);assert.deepEqual(g.survivalPack.snapshot().dressing,d.expansions127.modules.survival.dressing);g.player.health-=1;step(g,.04);assert.deepEqual(g.survivalPack.snapshot().dressing,{left:0,remaining:0});});
test('bivouac : bâche protège seulement les flammes à proximité dans le même domaine',()=>{const g=fresh();const c=camp(g);assert.ok(g.survivalPack.begin('cover').ok);step(g,7);assert.equal(g.survivalPack.rainProtection({...c,location:'placed'},c),.9);assert.equal(g.survivalPack.rainProtection({...c,x:c.x+400,location:'placed'},c),0);assert.equal(g.survivalPack.rainProtection({...c,domain:'region',location:'placed'},c),0);step(g,300.1);assert.equal(g.survivalPack.rainProtection({...c,location:'placed'},c),0);});
test('bivouac : lanterne entretenue sur place, paiement unique sans dépasser le réservoir',()=>{const g=fresh();camp(g);const d=g.serialize();d.nightGear={version:1,serial:2,devices:[{id:1,kind:'lantern',location:'belt',left:300,on:false,used:true}]};g.restoreSave(d);const fuel=g.player.carry.fuel,scrap=g.player.carry.scrap;assert.ok(g.survivalPack.begin('service').ok);step(g,8);assert.equal(g.nightGear.snapshot().devices[0].left,360);assert.equal(g.player.carry.fuel,fuel-4);assert.equal(g.player.carry.scrap,scrap-2);assert.equal(g.survivalPack.begin('service').ok,false);});
test('bivouac : sauvegarde reprend les durées et annule le travail non terminé',()=>{const g=fresh();camp(g);g.player.health=50;assert.ok(g.survivalPack.begin('rest').ok);step(g,1);const before=g.survivalPack.snapshot(),bag={...g.player.carry};g.restoreSave(g.serialize());assert.deepEqual(g.survivalPack.snapshot(),before);assert.equal(g.survivalPack.busy(),false);assert.deepEqual(g.player.carry,bag);g.startNew('standard','17118');assert.deepEqual(g.survivalPack.snapshot(),S.initial());});
test('bivouac : état malformé, durée inférieure à zéro et doublons rejetés',()=>{const s=S.initial();assert.throws(()=>S.normalize({...s,meal:{left:-1,budget:0}}));assert.throws(()=>S.normalize({...s,dressing:{left:0,remaining:18}}));const a={id:1,domain:'local',x:2000,y:2200,z:0,inside:null,left:600,cover:0};assert.throws(()=>S.normalize({...s,serial:2,camps:[a,a]}));assert.throws(()=>S.normalize({...s,serial:2,camps:[{...a,x:5000}]}));});

test('bivouac : économie d’endurance appliquée à une course réelle, sans bonus à l’arrêt',()=>{const control=fresh(),boost=fresh();withCampfire(boost);assert.ok(boost.survivalPack.begin('meal').ok);step(boost,8);let spot=null;for(let y=1900;y<2900&&!spot;y+=24)for(let x=1900;x<2900&&!spot;x+=24)if([0,24,48,72,96,120,144,168].every(dx=>control.friendlyPositionClear(control.player,x+dx,y)))spot={x,y};assert.ok(spot);for(const g of[control,boost]){g.player.x=spot.x;g.player.y=spot.y;g.player.stamina=80;g.input.keys.add('KeyD');g.input.keys.add('ShiftLeft');}const a=control.player.x,b=boost.player.x;for(let i=0;i<20;i++){control.update(.04);boost.update(.04);}assert.ok(control.player.x>a);assert.ok(boost.player.x>b);assert.ok(boost.player.stamina>control.player.stamina+1);const budget=boost.survivalPack.snapshot().meal.budget;boost.input.keys.clear();boost.update(.04);assert.equal(boost.survivalPack.snapshot().meal.budget,budget);});
test('bivouac : activité régionale paie le sac et ne se déplace pas avec le joueur',()=>{const g=fresh();g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const q=g.survivalPack.preview('camp');assert.ok(q.ok,q.reason);assert.ok(g.survivalPack.begin('camp').ok);step(g,7);const c=g.survivalPack.snapshot().camps[0];assert.equal(c.domain,'region');assert.equal(c.z,0);const raw=g.serialize();g.restoreSave(raw);assert.deepEqual(g.survivalPack.snapshot().camps[0],c);g.player.health=70;assert.ok(g.survivalPack.begin('rest').ok);step(g,12);assert.equal(g.player.health,86);});
test('bivouac : les fournitures disparues pendant le travail annulent sans dette',()=>{const g=fresh();g.player.health=60;assert.ok(g.survivalPack.begin('dressing').ok);step(g,2);g.player.carry.medicine=0;step(g,4);assert.equal(g.survivalPack.busy(),false);assert.equal(g.player.carry.medicine,0);assert.equal(g.survivalPack.snapshot().dressing.remaining,0);});
test('bivouac : limite des quatre haltes, démontage sans remboursement et expiration',()=>{const g=fresh(),raw=g.serialize();raw.expansions127.modules.survival={...S.initial(),serial:5,camps:[1,2,3,4].map(id=>({id,domain:'local',x:g.player.x+id*400,y:g.player.y,z:0,inside:null,left:.08,cover:0}))};g.restoreSave(raw);assert.equal(g.survivalPack.preview('camp').ok,false);step(g,.12);assert.equal(g.survivalPack.snapshot().camps.length,0);camp(g);const bag={...g.player.carry};assert.ok(g.survivalPack.dismantle().ok);assert.deepEqual(g.player.carry,bag);assert.equal(g.survivalPack.snapshot().camps.length,0);});
test('bivouac : bâche raccordée à l’usure réelle des flammes sous la pluie',()=>{const g=fresh(),c=camp(g);assert.ok(g.survivalPack.begin('cover').ok);step(g,7);const raw=g.serialize();raw.nightGear={version:1,serial:3,devices:[{id:1,kind:'torch',location:'placed',domain:'local',x:c.x,y:c.y,z:0,inside:null,angle:0,left:180,on:true,used:true},{id:2,kind:'torch',location:'placed',domain:'local',x:c.x+500,y:c.y,z:0,inside:null,angle:0,left:180,on:true,used:true}]};g.restoreSave(raw);g.weather=1;g.nightGear.step(.1);const [covered,exposed]=g.nightGear.snapshot().devices;assert.ok(covered.left>exposed.left);assert.ok(Math.abs(covered.left-(180-.116))<1e-6);assert.ok(Math.abs(exposed.left-(180-.26))<1e-6);});
test('bivouac : API d’entretien refuse le remplissage hors transaction autorisée',()=>{const g=fresh(),raw=g.serialize();raw.nightGear={version:1,serial:2,devices:[{id:1,kind:'lantern',location:'belt',left:100,on:false,used:true}]};g.restoreSave(raw);assert.equal(g.survivalPack.authorizeService(1,240),false);assert.equal(g.nightGear.serviceLantern(1,240),false);assert.equal(g.nightGear.snapshot().devices[0].left,100);});

test('bivouac : rendu local au pied de profondeur du décor, jamais dans la surcouche du héros',()=>{const g=fresh(),c=camp(g),view={left:0,top:0,right:4096,bottom:4096},entries=g.depthEntries(view),item=entries.find(e=>e.entity.__survivalCamp?.id===c.id);assert.ok(item);assert.equal(item.kind,1);assert.equal(item.depth,c.y+C.SurvivalPackRules.campRadius*32);assert.ok(entries.every((e,i)=>!i||e.depth>=entries[i-1].depth));assert.doesNotThrow(()=>g.render());});

test('bivouac : changer le regard pendant le vrai update ne déplace ni n’annule le chantier',()=>{const {game:g}=require('./helpers/expansions127.cjs').boot127();g.startNew('standard','17117');g.phaseTime=999;g.player.x=2812;g.player.y=2300;g.player.facing=0;Object.assign(g.player.carry,{wood:16,scrap:9,fuel:1});const q=g.survivalPack.preview('camp');assert.ok(q.ok,q.reason);const target={x:q.target.x,y:q.target.y};assert.ok(g.survivalPack.begin('camp').ok);g.input.mouseX=0;g.input.mouseY=0;for(let i=0;i<180;i++){g.update(.04);g.input.pressed.clear();}const built=g.survivalPack.snapshot().camps;assert.equal(built.length,1);assert.equal(built[0].x,target.x);assert.equal(built[0].y,target.y);assert.equal(g.player.carry.wood,4);});
