'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto'),C=require('../src/core.js'),G=require('../src/frontier-geometry.js'),W=require('../src/frontier-world.js'),P=require('../src/frontier-specialists.js'),Q=require('../src/frontier-survey.js'),Save=require('../src/save.js'),{bootGame}=require('./helpers/browser.cjs'),refs=require('./fixtures/frontier116-fingerprints.json');
const hash=v=>crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex'),copy=v=>JSON.parse(JSON.stringify(v));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function enter(g){g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());}
function step(g,n){for(let i=0;i<n;i++){g.update(.04);g.input.pressed.clear();}}
function at(g,p,q,z=0){const d=g.serialize();Object.assign(d.frontier,{inside:p.id,z,x:q.x,y:q.y,seen:[...new Set([...d.frontier.seen,p.id])]});g.restoreSave(d);}
for(const ref of refs)test('1.16 conservée : parcelles, plans et végétation hors chaussées '+ref.seed,()=>{
 const w=W.create(ref.seed,2);assert.equal(w.pois.length,ref.pois);assert.equal(hash(w.pois),ref.poiHash);assert.equal(hash(w.pois.flatMap(p=>p.levels.map(z=>w.plan(p,z)))),ref.plansHash);
 const chunks=[[16,16],[4,7],[17,16],[28,26]].map(([x,y])=>{
  const chunk=w.chunk(x,y),cleared=chunk.cleared||[],onPavement=item=>{const margin=item.kind==='tree'?item.canopy+.8:item.r+.6;return w.roads.some(r=>G.nearest(item,r.a,r.b).d<r.width/2+margin)||w.pois.some(p=>G.nearest(item,p.drive.a,p.drive.b).d<p.drive.width/2+margin);};
  for(const item of cleared)assert.ok(onPavement(item),'only pavement vegetation may be cleared: '+item.id);
  for(const item of [...chunk.trees,...chunk.rocks])assert.equal(onPavement(item),false,'kept vegetation remains off pavement: '+item.id);
  // Keep the unchanged 1.16 fingerprint: every original payload survives either
  // as visible vegetation or as an invisible, save-validating tombstone.
  const order=(a,b)=>Number(a.id.split('_').at(-1))-Number(b.id.split('_').at(-1));
  return{cx:chunk.cx,cy:chunk.cy,trees:[...chunk.trees,...cleared.filter(n=>n.kind==='tree')].sort(order),rocks:[...chunk.rocks,...cleared.filter(n=>n.kind==='rock')].sort(order)};
 });
 assert.equal(hash(chunks),ref.chunksHash);
});
test('spécialistes : huit programmes distincts, 42 types au total',()=>{assert.equal(P.PRESETS.length,8);assert.equal(G.PRESETS.length,62);assert.equal(new Set(P.PRESETS.map(p=>p.codex)).size,8);const w=W.create(17117);for(const d of P.PRESETS){const p=w.pois.find(p=>p.type===d.id);assert.ok(p,d.id);const pl=w.plan(p,0);assert.ok(pl.rooms.length>=4,d.id);assert.ok(pl.objects.length>=5,d.id);}});
test('générations : anciennes versions sans nouveaux lieux',()=>{assert.equal(new Set(W.create(17117,1).pois.map(p=>p.type)).size,22);assert.equal(new Set(W.create(17117,2).pois.map(p=>p.type)).size,34);assert.equal(new Set(W.create(17117,3).pois.map(p=>p.type)).size,42);});
test('géométrie : les huit nouveaux plans ne superposent pas le mobilier',()=>{const w=W.create(17117);for(const d of P.PRESETS){const p=w.pois.find(p=>p.type===d.id);for(const z of p.levels){const pl=w.plan(p,z);for(const o of pl.objects){const a={l:o.x,r:o.x+o.w,t:o.y,b:o.y+o.h};for(const b of pl.walls)assert.equal(G.overlap(a,{l:b.x,r:b.x+b.w,t:b.y,b:b.y+b.h}),false,o.id);for(const b of pl.objects)if(o.id<b.id)assert.equal(G.overlap(a,{l:b.x,r:b.x+b.w,t:b.y,b:b.y+b.h}),false,o.id);}}}});
test('prudence : rythme réduit et aucune ressource facturée',()=>{const{game:g}=fresh();enter(g);const money=copy(g.resources),x=g.frontier.snapshot().x;assert.ok(g.frontier.quiet(true));assert.deepEqual(g.resources,money);g.input.keys.add('KeyD');step(g,50);g.input.keys.clear();assert.ok(Math.abs(g.frontier.snapshot().x-x-3.3)<.001);assert.equal(g.frontier.overview().sound.kind,'Pas prudents');assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.frontier.snapshot().quiet,true);});
test('prudence : maintien de course ne supprime pas le pas discret',()=>{const{game:g}=fresh();enter(g);g.frontier.quiet(true);const x=g.frontier.snapshot().x;g.input.keys.add('KeyD');g.input.keys.add('ShiftLeft');step(g,25);assert.ok(Math.abs(g.frontier.snapshot().x-x-1.65)<.001);});
test('cible : distance calculée au bord du véhicule, pas au centre',()=>{const b={id:'P0000:car:0',kind:'car',x:5,y:5,w:4.6,h:1.85,a:0,amount:10,resource:'scrap'},p={x:8.5,y:5,z:0,inside:null},q=Q.edge(p,b);assert.ok(Math.abs(q.x-7.3)<.001);const fake={containers:()=>[b],line:()=>true};const targets=Q.targets(fake,p,{});assert.equal(targets.length,1);assert.ok(Math.abs(targets[0].distance-1.2)<.001);});
test('cible : un mur écarte le contenant et une caisse vide reste identifiable',()=>{const b={id:'P0000:0:0',kind:'crate',x:5,y:5,w:1.2,h:.8,a:0,amount:10,resource:'wood'},p={x:6.6,y:5,z:0};assert.equal(Q.targets({containers:()=>[b],line:()=>false},p,{}).length,0);const a=Q.targets({containers:()=>[b],line:()=>true},p,{[b.id]:10});assert.equal(a[0].left,0);assert.equal(a[0].label,'Caisse');});
test('bruit : même étage seulement, rayon atténué derrière un obstacle',()=>{const T=C.FrontierTacticsRules,p={x:10,y:10,z:0,inside:null},near={id:'P0000:e0',x:15,y:10,z:0},far={id:'P0001:e0',x:25,y:10,z:0},upper={id:'P0002:e0',x:10,y:10,z:1};Q.hear({line:()=>false},[near,far,upper],p,20,T);assert.equal(near.mode,'investigate');assert.equal(far.mode,undefined);assert.equal(upper.mode,undefined);assert.equal(near.gx,10);});
test('bruit : les coups de feu sont plus audibles que la marche',()=>{const r=C.FrontierTacticsRules;assert.ok(r.quietNoise<r.walkNoise);assert.ok(r.walkNoise<r.runNoise);assert.ok(r.runNoise<r.shotNoise.pistol);});
test('poursuite : un infecté inspecte un bruit en contournant le mur',()=>{const T=C.FrontierTacticsRules,wall={x:5,y:2,w:.3,h:6},blocked=(x,y)=>x<.4||y<.4||x>19.6||y>19.6||G.circleRect(x,y,.3,wall);const world={blocked,line(a,b,z,p,ignore,r=.015){const n=Math.ceil(Math.hypot(a.x-b.x,a.y-b.y)/.1);for(let i=1;i<=n;i++)if(G.circleRect(a.x+(b.x-a.x)*i/n,a.y+(b.y-a.y)*i/n,r,wall))return false;return true;}};
const e={id:'P0000:e0',poi:'P0000',x:3,y:5,z:0,a:Math.PI,hp:65,cool:0},p={x:8,y:5,z:0,inside:null,quiet:true};Q.hear(world,[e],p,42,T);for(let i=0;i<320;i++){Q.step(world,e,p,.04,T,{left:2},blocked);assert.equal(blocked(e.x,e.y),false);}assert.ok(e.x>5.3,JSON.stringify(e));});
test('vision : pas de détection à travers le mur, même de très près',()=>{const e={x:1,y:1,z:0,a:0,poi:'P0000'},p={x:2,y:1,z:0,quiet:false};Q.step({line:()=>false},e,p,.04,C.FrontierTacticsRules,{left:0},()=>false);assert.equal(e.mode,'idle');});
test('rencontre : position et intention de l’infecté sont conservées à la reprise',()=>{const{game:g}=fresh();enter(g);const w=g.frontier.world(),p=w.pois[0];at(g,p,G.global(p,p.w/2,2));step(g,1);const e=g.frontier.overview().enemies.find(e=>e.poi===p.id);assert.ok(e);e.x=p.x;e.y=p.y;e.a=Math.PI;assert.ok(g.frontier.shoot());const id=e.id;assert.equal(e.mode,'investigate');const before=g.frontier.snapshot().tracks[id];assert.ok(before);assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.frontier.snapshot().tracks[id],before);step(g,1);const after=g.frontier.overview().enemies.find(e=>e.id===id);assert.ok(after&&after.ttl>0);assert.notEqual(after.mode,'idle');});
test('validation : une poursuite étrangère au lieu est refusée avant mutation',()=>{const{game:g}=fresh();enter(g);const before=g.world;for(const change of [d=>d.frontier.quiet=1,d=>d.frontier.tracks={'P9999:e0':{x:1,y:1,z:0,a:0,gx:1,gy:1,ttl:5,cool:0,mode:'investigate'}},d=>d.frontier.generation=9]){const data=g.serialize();change(data);assert.throws(()=>g.restoreSave(data));assert.equal(g.world,before);}});
test('migration : la 1.16 conserve la génération 2, sans posture ni poursuite gratuite',()=>{const{game:g}=fresh();const raw=g.serialize();raw.version=15;raw.frontier.generation=2;delete raw.frontier.quiet;delete raw.frontier.tracks;const old=copy(raw.resources);g.restoreSave(raw);assert.equal(g.frontier.snapshot().generation,2);assert.equal(g.frontier.world().pois.length,223);assert.equal(g.frontier.snapshot().quiet,false);assert.deepEqual(g.frontier.snapshot().tracks,{});assert.deepEqual(g.resources,old);assert.equal(g.serialize().version,20);});
test('inspection : afficher un lieu ne fait pas progresser sa poursuite',()=>{const{game:g}=fresh();enter(g);const before=g.frontier.snapshot();for(let i=0;i<20;i++)g.frontier.overview();assert.deepEqual(g.frontier.snapshot(),before);});
test('nouvelle campagne : aucun bruit ni posture prudente hérités',()=>{const{game:g}=fresh();enter(g);g.frontier.quiet(true);g.frontier.shoot();g.startNew('standard','42');const d=g.frontier.snapshot();assert.equal(d.quiet,false);assert.deepEqual(d.tracks,{});assert.equal(d.generation,3);assert.equal(g.frontier.overview().sound.radius,0);});
test('prudence : être au volant ne réduit pas la distance de visibilité',()=>{const e={x:10,y:10,z:0,a:0,poi:'P0000',mode:'idle',ttl:0,cool:0},p={x:25,y:10,z:0,quiet:true,car:{driving:true}};Q.step({line:()=>true},e,p,.04,C.FrontierTacticsRules,{left:0},()=>false);assert.equal(e.mode,'pursuit');});
