'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),C=require('../src/core.js');
const Night=require('../src/night-gear.js'),Survival=require('../src/survival-pack.js'),Essential=require('../src/essential-state.js'),W=require('../src/frontier-world.js');
const full=generation=>({worldSeed:17117,frontier:{generation,seen:[],taken:{}},essentials:{jobs:{},belt:{}}});
const point={domain:'region',x:16000,y:12000,z:0,inside:null};
function lamp(p=point){return{version:1,serial:2,devices:[{id:1,kind:'torch',location:'placed',left:180,on:false,used:false,...p,angle:0}]};}
function camp(p=point){return{...Survival.initial(),serial:2,camps:[{id:1,...p,left:600,cover:0}]};}
function gear(p=point){return{...Essential.initial(),serial:2,effects:[{id:1,kind:'light',left:60,pulse:0,...p}]};}
test('domaines 1.31 : éclairage, bivouac et appareils admettent 24 km seulement pour G5',()=>{for(const[module,raw]of [[Night,lamp()],[Survival,camp()],[Essential,gear()]]){assert.equal(module.normalize(raw,full(5)).version,1);assert.equal(module.normalize(raw).version,1);for(const generation of [1,2,3,4])assert.throws(()=>module.normalize(raw,full(generation)));}});
test('domaines 1.31 : limites maximales strictes, axes séparés et monde local toujours 4096',()=>{for(const[module,make]of [[Night,lamp],[Survival,camp],[Essential,gear]]){for(const p of [{...point,x:W.sizeForGeneration(5)+.01},{...point,y:W.sizeForGeneration(5)+.01},{...point,x:-.01},{...point,domain:'local',x:4097,y:2000}])assert.throws(()=>module.normalize(make(p),full(5)));assert.equal(module.normalize(make({...point,x:8000,y:8000}),full(4)).version,1);}});
test('domaines 1.31 : bivouac réellement posable au-delà du vieux bord puis repris sans déplacement',()=>{const {game:g}=require('./helpers/expansions127.cjs').boot127();require('../src/world-pack131.js').install(g);g.startNew('standard','17117');require('./helpers/legacy-region135.cjs').pinLegacyRegion(g,5);g.phase='calm';g.phaseTime=9999;g.player.x=4058;g.player.y=2048;assert.ok(g.frontier.enter());const world=g.frontier.world();assert.equal(world.generation,5);let prepared=false;for(let x=12000;x<12400&&!prepared;x+=16){for(let y=12000;y<12400&&!prepared;y+=16){if(world.blocked(x,y,.32,0,null)||world.blocked(x+1.7,y,1.1,0,null))continue;const raw=g.serialize();Object.assign(raw.frontier,{x,y,z:0,inside:null,a:0});g.restoreSave(raw);Object.assign(g.player.carry,{wood:12,scrap:6});prepared=g.survivalPack.preview('camp').ok;}}assert.ok(prepared,'sol extérieur libre et réellement accessible');assert.ok(g.survivalPack.begin('camp').ok);for(let i=0;i<175;i++)g.survivalPack.step(.04);const actual=g.survivalPack.snapshot().camps[0];assert.ok(actual.x>8192);const raw=g.serialize();raw.nightGear=lamp({...point,x:actual.x,y:actual.y});assert.doesNotThrow(()=>g.restoreSave(raw));assert.deepEqual(g.survivalPack.snapshot().camps[0],actual);assert.equal(g.nightGear.snapshot().devices[0].x,actual.x);const before=g.world,old=structuredClone(raw);old.frontier.generation=4;assert.throws(()=>g.restoreSave(old));assert.equal(g.world,before);});
