'use strict';
const {legacyAge}=require('./helpers/legacy-city.cjs');
const {standAt}=require('./helpers/physical-fixtures.cjs');
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {bootGame}=require('./helpers/browser.cjs'),C=require('../src/core.js'),Save=require('../src/save.js'),N=require('../src/nightwatch.js');
const clone=x=>JSON.parse(JSON.stringify(x));
function fresh(){const e=bootGame();e.game.startNew('standard','17117');return e;}
function put(g,type,x=70,y=65,progress=1){const b=new(g.core().constructor)(g.nextId++,type,x,y,0,progress);g.world.add(b);g.refreshMetrics(true);return b;}
function dark(g){g.wave=4;g.phase='assault';g.player.x=3300;g.player.y=3300;g.camera.x=g.player.x;g.camera.y=g.player.y;g.refreshMetrics(true);g.nightwatch.invalidate();}
function stable(g){const d=g.serialize();delete d.timestamp;return JSON.stringify(d);}
test('âges: onze seuils ordonnés, premiers scores conservés',()=>{assert.deepEqual(C.CITY_TIERS.slice(0,7).map(t=>t.requiredScore),[0,10,24,48,85,135,210]);assert.deepEqual(C.CITY_TIERS.slice(7).map(t=>t.requiredScore),[420,750,1200,1850]);assert.equal(C.CITY_TIERS.length,11);assert.equal(C.cityTier(1850).name,'MÉGAVILLE III')});
test('âges: vingt-six nouveaux bâtiments avec coûts et dépendances accessibles',()=>{const defs=Object.values(C.Urban.BUILDINGS);assert.equal(defs.length,26);assert.equal(Object.keys(C.BUILDINGS).length,71+Object.keys(C.CityContent150.BUILDINGS).length);for(const d of defs){assert.ok(d.buildTime>0&&d.health>0);assert.ok(d.unlockTier>=0&&d.unlockTier<11);for(const [key,n]of Object.entries(d.cost)){assert.ok(C.RESOURCE_KEYS.includes(key));assert.ok(n>0&&Number.isFinite(n))}if(d.requires){assert.ok(C.BUILDINGS[d.requires]);assert.ok(C.BUILDINGS[d.requires].unlockTier<=d.unlockTier)}}});
test('catalogue: bâtiments des âges futurs absents du DOM, non grisés',()=>{const{game:g}=fresh();for(const category of ['colony','industry','defense']){g.currentCategory=category;g.refreshBuildMenu(true);assert.ok([...g.ui.buildList.children].every(b=>C.BUILDINGS[b.dataset.buildId].unlockTier<=g.tier.id))}});
test('catalogue: lampe de secours visible au refuge, projecteur caché',()=>{const{game:g}=fresh();g.currentCategory='defense';g.refreshBuildMenu(true);const ids=g.ui.buildList.children.map(b=>b.dataset.buildId);assert.ok(ids.includes('beacon'));assert.ok(!ids.includes('searchlight'))});
test('progression: seuls les bâtiments achevés débloquent un âge',()=>{const{game:g}=fresh();put(g,'house',70,65,0);assert.equal(g.tier.id,0);const b=[...g.world.buildings.values()].find(b=>b.type==='house');b.progress=1;g.refreshMetrics(true);assert.equal(g.tier.id,1)});
test('progression: âge atteint conservé après perte, jamais de ressources ou logements conservés',()=>{const{game:g}=fresh(),b=put(g,'house'),money=clone(g.resources);assert.equal(g.tier.id,1);g.world.remove(b);g.refreshMetrics(true);assert.equal(g.tier.id,1);assert.equal(g.housing,6);assert.equal(g.cityScore,8);assert.deepEqual(g.resources,money)});
test('progression: le palier ne supprime ni coûts ni bâtiment prérequis',()=>{const{game:g}=fresh();legacyAge(g,210);g.refreshMetrics(true);const before=clone(g.resources);assert.equal(g.placeOne('residentialTower',72,66),false);assert.deepEqual(g.resources,before)});
test('progression: seuil historique importé, mémorisé dans la sauvegarde et reset de nouvelle campagne',()=>{const{game:g}=fresh(),stocks=clone(g.resources);legacyAge(g,750);assert.equal(g.tier.id,8);assert.deepEqual(g.resources,stocks);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.tier.id,8);assert.deepEqual(g.resources,stocks);g.startNew('standard','42');assert.equal(g.tier.id,0);assert.equal(g.urban.overview().peakScore,8)});
test('économie: grand entrepôt augmente la capacité sans livrer de ressources',()=>{const{game:g}=fresh(),before=clone(g.resources);const b=put(g,'centralStore');assert.equal(g.storage,2300);assert.deepEqual(g.resources,before);assert.equal(g.world.nearestStorage(b.x,b.y).id,b.id)});
test('économie: un récupérateur ordinaire dépose dans le nouveau stockage',()=>{const{game:g}=fresh(),b=put(g,'logisticsHub'),u=g.units[0];standAt(g,u,b);u.carry=8;u.carryType='wood';const before=g.resources.wood;g.depositWorker(u,b,.04);assert.equal(g.resources.wood,before+8);assert.equal(u.carry,0)});
test('économie: solaire uniquement au calme, sans batterie nocturne',()=>{const{game:g}=fresh();put(g,'solarCourt');assert.equal(g.powerGenerated,26);g.phase='warning';g.refreshMetrics(true);assert.equal(g.powerGenerated,8);g.phase='assault';g.refreshMetrics(true);assert.equal(g.powerGenerated,8);g.phase='calm';g.refreshMetrics(true);assert.equal(g.powerGenerated,26)});
test('économie: centrale consomme son carburant et cesse de produire à zéro',()=>{const{game:g}=fresh();put(g,'powerPlant');assert.equal(g.powerGenerated,98);const fuel=g.resources.fuel;g.economyTick(1);assert.ok(Math.abs(g.resources.fuel-fuel+.065)<1e-7);g.resources.fuel=0;g.refreshMetrics(true);assert.equal(g.powerGenerated,8)});
test('économie: usine alimentaire plafonnée sans gaspiller ses intrants',()=>{const{game:g}=fresh();put(g,'marketHall');g.resources.food=g.storage;const fuel=g.resources.fuel;g.population=0;g.economyTick(1);assert.equal(g.resources.food,g.storage);assert.equal(g.resources.fuel,fuel)});
test('santé: hôpital exige présence, courant et médicaments, sans résurrection',()=>{const{game:g}=fresh(),b=put(g,'hospital');standAt(g,g.player,b);g.player.health=50;const meds=g.resources.medicine;g.updateBuildings(.1);assert.ok(g.player.health>50);assert.ok(g.resources.medicine<meds);g.resources.medicine=0;const h=g.player.health;g.updateBuildings(.1);assert.equal(g.player.health,h);g.player.dead=true;g.resources.medicine=10;g.updateBuildings(.1);assert.equal(g.player.dead,true)});
test('incendies: nouvelles centrales et bâtiments urbains participent au système',()=>{const{game:g}=fresh(),b=put(g,'powerPlant');g.damageBuilding(b,b.maxHealth*.6);g.update(.04);assert.ok(g.siege.snapshot().fires.some(f=>f.id===b.id));g.refreshMetrics(true);assert.equal(g.powerGenerated,8)});
test('nuits: premières trois normales, puis 4/7/10, sans RNG',()=>{assert.deepEqual(Array.from({length:13},(_,i)=>i+1).filter(N.scheduled),[4,7,10,13]);assert.equal(N.scheduled(Infinity),false);assert.equal(N.scheduled(4.5),false)});
test('nuits: forecast au jour, obscurité seulement à l’assaut/sécurisation',()=>{const{game:g}=fresh();g.wave=4;assert.ok(g.nightwatch.forecast());assert.equal(g.nightwatch.isBlackout(),false);g.phase='warning';assert.equal(g.nightwatch.isBlackout(),false);g.phase='assault';assert.ok(g.nightwatch.isBlackout());g.phase='aftermath';assert.ok(g.nightwatch.isBlackout())});
test('nuits: aucun halo personnel gratuit, torche allumée directionnelle',()=>{const{game:g}=fresh();dark(g);assert.equal(g.nightwatch.lit({x:3420,y:3300}),false);g.player.facing=0;assert.ok(g.urban.flashlight(true));assert.ok(g.nightwatch.lit({x:3400,y:3300}));assert.equal(g.nightwatch.lit({x:3200,y:3300}),false)});
test('nuits: lampe achevée et alimentée nécessaire',()=>{const{game:g}=fresh();dark(g);const b=put(g,'streetlight',100,100,0),p={x:b.x+100,y:b.y};assert.equal(g.nightwatch.lit(p),false);b.progress=1;g.refreshMetrics(true);assert.ok(g.nightwatch.lit(p));b.powered=false;g.nightwatch.invalidate();assert.equal(g.nightwatch.lit(p),false)});
test('nuits: porte verrouillée coupe le faisceau, ouverte le laisse passer',()=>{const{game:g}=fresh();dark(g);const l=put(g,'searchlight',100,100),b=put(g,'gate',104,100);b.rotation=1;const old=g.world.cells(b);g.world.rewrite(b,old);l.rotation=0;g.refreshMetrics(true);const p={x:l.x+220,y:l.y};b.gateMode='closed';g.nightwatch.invalidate();assert.equal(g.nightwatch.lit(p),false);b.gateMode='open';g.world.navigationVersion++;g.nightwatch.invalidate();assert.ok(g.nightwatch.lit(p))});
test('nuits: rotation du projecteur sauvegardée sans coût ni nouvelle emprise',()=>{const{game:g}=fresh(),b=put(g,'searchlight'),before=clone(g.resources),cells=g.world.cells(b);assert.ok(g.urban.direction(b.id,2));assert.deepEqual(g.world.cells(b),cells);assert.deepEqual(g.resources,before);assert.ok(g.save(false));assert.ok(g.load());assert.equal(g.world.buildings.get(b.id).rotation,2)});
test('nuits: ciblage automatique exclut les infectés hors lumière',()=>{const{game:g}=fresh();dark(g);g.spawnZombie('walker');const z=g.zombies[0];z.x=3410;z.y=3300;g.rebuildBuckets();assert.equal(g.nightwatch.target(g.player.x,g.player.y,400),null);g.urban.flashlight(true);g.player.facing=0;assert.equal(g.nightwatch.target(g.player.x,g.player.y,400),z)});
test('nuits: pas de nouvelles unités ni modification de vagues par inspection',()=>{const{game:g}=fresh();dark(g);g.phase='warning';g.prepareWave();const before=stable(g);for(let i=0;i<20;i++){g.nightwatch.forecast();g.nightwatch.sources();g.urban.overview();}assert.equal(stable(g),before)});
test('sauvegarde: v9 migrée pendant un assaut n’impose pas soudain le noir',()=>{const{game:g}=fresh();g.wave=4;g.phase='warning';g.prepareWave();g.phase='assault';g.startAssault();const d=g.serialize();d.version=9;delete d.urban;g.restoreSave(d);assert.equal(g.nightwatch.isBlackout(),false);assert.equal(g.urban.snapshot().skipNightWave,4);g.wave=7;assert.ok(g.nightwatch.isBlackout())});
test('sauvegarde: les anciens formats migrent sans torche activée ni ressources',()=>{const{game:g}=fresh(),d=g.serialize();for(let version=1;version<=9;version++){const raw=clone(d);raw.version=version;delete raw.urban;const next=Save.validate(raw);assert.equal(next.version,C.SAVE_VERSION);assert.equal(next.urban.flashlight,false);assert.deepEqual(next.resources,d.resources);assert.equal(next.urban.peakScore,8)}});
test('sauvegarde: données urbaines invalides refusées avant mutation',()=>{const{game:g}=fresh(),d=g.serialize(),w=g.world;for(const change of [u=>u.peakScore=-1,u=>u.peakScore=NaN,u=>u.skipNightWave=999,u=>u.flashlight=1,u=>u.peakScore=0]){const raw=clone(d);change(raw.urban);assert.throws(()=>g.restoreSave(raw));assert.equal(g.world,w)}});
test('sauvegarde: registre v10 obligatoire, précédentes clés conservées',()=>{const{game:g}=fresh(),d=g.serialize();delete d.urban;assert.throws(()=>Save.validate(d));assert.ok(C.LEGACY_SAVE_KEYS.includes('deadwall-save-v9'));assert.equal(C.SAVE_VERSION,20)});
test('nuits: la limite graphique des lumières n’éteint pas les défenses hors caméra',()=>{const{game:g}=fresh();dark(g);g.camera.x=g.camera.y=900;
 for(let i=0;i<90;i++){const b=put(g,'beacon',20+i%15*2,20+Math.floor(i/15)*2);b.powered=true;}
 const far=put(g,'streetlight',100,100);for(const b of g.world.buildings.values())b.powered=true;g.nightwatch.invalidate();assert.equal(g.nightwatch.sources().length,85);assert.ok(g.nightwatch.sources(false).length>85);assert.ok(g.nightwatch.lit({x:far.x+60,y:far.y}));
});
