'use strict';const test=require('node:test'),assert=require('node:assert/strict'),{boot127}=require('./helpers/expansions127.cjs'),C=require('../src/core.js'),W=require('../src/frontier-world.js'),G=require('../src/frontier-geometry.js'),Pack=require('../src/world-pack131.js');
const seed=17117,copy=x=>JSON.parse(JSON.stringify(x));let regional;
const w=()=>regional||(regional=W.create(seed,5));
function boot(){const {game:g}=boot127();Pack.install(g);g.startNew('standard',String(seed));require('./helpers/legacy-region135.cjs').pinLegacyRegion(g,5);return g;}
function visit(g,p,cleared=true){const d=g.serialize(),f=d.frontier,q=G.global(p,p.w/2,-2);Object.assign(f,{active:true,x:q.x,y:q.y,z:0,inside:null,anchor:{x:g.player.x,y:g.player.y},car:null});if(!f.seen.includes(p.id))f.seen.push(p.id);if(cleared)for(let i=0;i<g.frontier.world().threatCount(p);i++)f.enemies[p.id+':e'+i]=0;f.kills=Object.values(f.enemies).filter(x=>x===0).length;g.restoreSave(d);g.input.keys.clear();g.input.pressed.clear();g.player.carry=C.makeBag({wood:16,scrap:16,food:8,medicine:4});}
function work(g,kind,id){const before=g.worldOps131.preview(kind,id);assert.equal(before.ok,true,before.reason);assert.equal(g.worldOps131.begin(kind,id).ok,true);for(let i=0;i<Math.ceil(before.seconds/.1)+2;i++)g.worldOps131.step(.1);assert.equal(g.worldOps131.busy(),false);}
test('G5 : neuf fois la surface, noyau G4 et parcelles historiques exactement conservés',()=>{const old=W.create(seed,4),next=w();assert.equal(next.size,24576);assert.equal(old.size,8192);assert.equal(next.size**2/old.size**2,9);assert.deepEqual(next.pois.slice(0,old.pois.length),old.pois);assert.deepEqual(next.roads.slice(0,old.roads.length),old.roads);assert.equal(next.sectors.length,512);assert.ok(next.pois.length>1600);assert.equal(next.cacheSize(),0);assert.equal(next.planCacheSize(),0);});
test('G5 : quatre coins lointains physiques, génération à demande, LRU et reconstruction déterministe',()=>{const next=w(),saved=copy(next.chunk(95,95));assert.ok(saved.trees.length);for(let n=0;n<96;n++)next.chunk(n,90);assert.ok(next.cacheSize()<=25);assert.deepEqual(next.chunk(95,95),saved);for(const p of next.pois.slice(-100))next.plan(p,0);assert.ok(next.planCacheSize()<=48);assert.equal(next.blocked(24577,12000),true);assert.equal(next.vehicleClear(25000,12000,0),false);assert.ok(next.around(22000,22000,60).some(c=>c.trees.length));const before=next.cacheSize();assert.ok(next.prefetch(22000,10000,1)<=1);assert.ok(next.cacheSize()<=25);assert.ok(before<=25);});
test('G5 : réseau lointain joint aux routes historiques, parcelles hors routes et autres parcelles',()=>{const next=w(),outer=next.pois.filter(p=>p.generation===5);for(const p of outer){assert.ok(p.x>8192||p.y>8192);assert.ok(next.nearestRoad(p.drive.a).d<.001);for(const road of next.roads){assert.equal(G.segmentRect(G.local(p,road.a.x,road.a.y),G.local(p,road.b.x,road.b.y),{x:0,y:0,w:p.w,h:p.h}),false,p.id+' coupe '+road.id);}}for(let i=0;i<outer.length;i++)for(let j=i+1;j<outer.length;j++)assert.equal(G.overlap(outer[i].reserve,outer[j].reserve),false);assert.ok(next.roads.some(r=>r.a.x===8160&&r.a.y===4170&&r.b.x>8192));});
test('G5 : index de routes exact contre oracle exhaustif et faible travail de génération détaillée',()=>{const next=w();for(let i=0;i<120;i++){const p={x:G.hash(seed,i,'x')%24576,y:G.hash(seed,i,'y')%24576},actual=next.nearestRoad(p),expected=Math.min(...next.roads.map(r=>G.nearest(p,r.a,r.b).d));assert.ok(Math.abs(actual.d-expected)<1e-9);}const before=next.streamStats().nearestChecks;next.chunk(88,89);assert.ok(next.streamStats().nearestChecks-before<100000,'index should avoid 2648 roads × 1100 trees');});
test('G5 : occupations explicites, aucun humain hostile inventé, alliés sans infectés résidents',()=>{const next=w();assert.ok(next.pois.some(p=>p.occupation==='allied'));assert.ok(next.pois.some(p=>p.occupation==='infected'));for(const p of next.pois.filter(p=>p.generation===5)){assert.notEqual(p.occupation,'hostile');assert.equal(next.threatCount(p)>0,p.occupation==='infected');}assert.ok(next.pois.some(p=>p.frontier131?.reserve));});
test('G5 : nouvelle campagne et reprise éloignée conservent position, étage et prélèvements',()=>{const g=boot(),p=g.frontier.world().pois.find(p=>p.generation===5&&p.x>18000&&p.levels.includes(1));assert.equal(g.frontier.position().generation,5);visit(g,p);const d=g.serialize(),f=d.frontier,q=G.global(p,p.w/2,p.h/2);Object.assign(f,{x:q.x,y:q.y,z:1,inside:p.id});const obj=g.frontier.world().plan(p,1).objects[0];f.taken[obj.id]=Math.min(2,obj.amount);g.restoreSave(d);const saved=g.serialize();g.restoreSave(saved);assert.equal(g.frontier.position().x,q.x);assert.equal(g.frontier.position().z,1);assert.equal(g.frontier.snapshot().taken[obj.id],f.taken[obj.id]);const broken=copy(saved);broken.frontier.generation=4;assert.throws(()=>g.restoreSave(broken));assert.equal(g.frontier.position().generation,5);});
test('G5 : relais financé, conservation des transferts et soins débités sur place',()=>{const g=boot(),p=g.frontier.world().pois.find(p=>p.occupation==='allied');visit(g,p);const before=copy(g.player.carry);work(g,'relay',p.id);assert.equal(g.player.carry.wood,before.wood-8);assert.equal(g.player.carry.scrap,before.scrap-4);const bag=C.bagTotal(g.player.carry);assert.equal(g.worldOps131.transfer(p.id,'store').ok,true);assert.equal(C.bagTotal(g.player.carry),0);assert.equal(C.bagTotal(g.worldOps131.snapshot().relays[p.id]),bag);g.player.health=60;work(g,'rest',p.id);assert.equal(g.player.health,76);assert.equal(C.bagTotal(g.worldOps131.snapshot().relays[p.id]),bag-3);g.restoreSave(g.serialize());assert.equal(g.worldOps131.transfer(p.id,'take').ok,true);assert.equal(C.bagTotal(g.player.carry),bag-3);assert.equal(g.worldOps131.preview('relay',p.id).ok,false);});
test('G5 : site infesté exige tous ses occupants, certification durable ouvre relais',()=>{const g=boot(),p=g.frontier.world().pois.find(p=>p.occupation==='infected');visit(g,p,false);assert.equal(g.worldOps131.preview('secure',p.id).ok,false);assert.equal(g.worldOps131.preview('relay',p.id).ok,false);visit(g,p,true);work(g,'secure',p.id);assert.ok(g.worldOps131.snapshot().secured.includes(p.id));work(g,'relay',p.id);assert.ok(g.worldOps131.snapshot().relays[p.id]);const bad=g.serialize();delete bad.frontier.enemies[p.id+':e0'];bad.frontier.kills--;assert.throws(()=>g.restoreSave(bad));assert.ok(g.worldOps131.snapshot().relays[p.id]);});
test('G5 : réserve physique finie, scellé persistant et prélèvement refusé si faux registre',()=>{const g=boot(),p=g.frontier.world().pois.find(p=>p.frontier131?.reserve);visit(g,p);const crate=p.outdoor.find(o=>o.id===p.frontier131.reserve),before=copy(crate);assert.equal(g.worldOps131.opened(p.id),false);const invalid=g.serialize();invalid.frontier.taken[crate.id]=1;assert.throws(()=>g.restoreSave(invalid));work(g,'reserve',p.id);assert.equal(g.worldOps131.opened(p.id),true);const saved=g.serialize();saved.frontier.taken[crate.id]=crate.amount;g.restoreSave(saved);assert.equal(g.frontier.snapshot().taken[crate.id],crate.amount);for(let n=0;n<40;n++)g.frontier.world().chunk(40+n,70);assert.deepEqual(g.frontier.world().pois.find(q=>q.id===p.id).outdoor.find(o=>o.id===crate.id),before);assert.equal(g.worldOps131.preview('reserve',p.id).ok,false);});
test('G5 : relevé sectoriel révèle lieux GPS, pause et mouvement interrompent sans payer',()=>{const g=boot(),p=g.frontier.world().pois.find(p=>p.generation===5);visit(g,p);const before=copy(g.player.carry);assert.equal(g.worldOps131.begin('survey',p.id).ok,true);g.paused=true;for(let i=0;i<80;i++)g.worldOps131.step(.1);assert.deepEqual(g.player.carry,before);assert.equal(g.worldOps131.overview().task.progress,0);g.paused=false;g.input.keys.add('ArrowRight');g.worldOps131.step(.1);g.input.keys.clear();assert.equal(g.worldOps131.busy(),false);assert.deepEqual(g.player.carry,before);work(g,'survey',p.id);assert.ok(g.worldOps131.snapshot().surveyed.includes(p.sector));const sector=g.frontier.world().sectors.find(s=>s.id===p.sector);for(const id of sector.sites)assert.ok(g.frontier.snapshot().seen.includes(id));assert.equal(g.worldOps131.preview('survey',p.id).ok,false);});
test('G5 : migration volontaire G4 préserve campagnes explorées et retourne un refus hors dépôt',()=>{const g=boot(),d=g.serialize();d.frontier.generation=4;g.restoreSave(d);g.player.x=100;g.player.y=100;assert.equal(g.worldOps131.expand().ok,false);const core=g.core();g.player.x=core.x;g.player.y=core.y+64;const old=g.frontier.world(),p=old.pois[0],data=g.serialize();data.frontier.seen=[p.id];g.restoreSave(data);const supplies=copy(g.resources),nodes=copy(g.serialize().nodes);assert.equal(g.worldOps131.expand().ok,true);assert.deepEqual(g.resources,supplies);assert.deepEqual(g.serialize().nodes,nodes);assert.ok(g.frontier.snapshot().seen.includes(p.id));assert.equal(g.frontier.position().generation,5);});
test('G5 : caméra et atlas acceptent les secteurs lointains sans écraser la précision locale',()=>{const P=require('../src/atlas-projection.js'),cam=P.camera(1000,800);cam.regionSize(24576);cam.fit(23000,23000,420);assert.equal(cam.x,23000);assert.equal(cam.y,23000);assert.ok(cam.scale>1);cam.fit(12288,12288,24576);assert.ok(cam.bounds().right>=24576);assert.ok(cam.bounds().bottom>=24576);cam.fit(4096,4096,190);assert.ok(cam.scale>4);});
