'use strict';
/* Synthetic Node/DOM logic benchmark. This never reports browser FPS. */
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync}=require('node:child_process'),{performance}=require('node:perf_hooks');
const root=path.resolve(__dirname,'..'),args=process.argv.slice(2);
const option=(key,fallback)=>{const i=args.indexOf(key);return i<0?fallback:args[i+1];};
const summarize=samples=>{const sorted=[...samples].sort((a,b)=>a-b);return{samples:samples.length,meanMs:samples.reduce((a,b)=>a+b,0)/samples.length,p50Ms:sorted[Math.floor((sorted.length-1)*.5)],p95Ms:sorted[Math.floor((sorted.length-1)*.95)],maxMs:sorted.at(-1)};};
function deterministic(seed){let value=seed>>>0;return()=>{value=(Math.imul(1664525,value)+1013904223)>>>0;return value/4294967296;};}
function boot(project,expanded){
 Math.random=deterministic(127031);let env;
 if(expanded)env=require(path.join(project,'tests/helpers/expansions127.cjs')).boot127();
 else{env=require(path.join(project,'tests/helpers/browser.cjs')).bootGame();const g=env.game,proto=Object.getPrototypeOf(document.createElement('div'));if(!proto.append)proto.append=function(...nodes){nodes.forEach(n=>this.appendChild(n));};if(!proto.insertBefore)proto.insertBefore=function(n,s){const i=this.children.indexOf(s);this.children.splice(i<0?this.children.length:i,0,n);n.parentNode=this;};require(path.join(project,'src/night-gear.js')).install(g);require(path.join(project,'src/exploration-125.js')).install(g,document);require(path.join(project,'src/actor-presentation.js')).install(g);}
 env.game.startNew('standard','17117');env.game.random=new globalThis.DeadwallCore.Random(17117);return env.game;
}
function counts(g){const s=g.expansions?.snapshot().modules;return{zombies:g.zombies.length,corpses:g.corpses.length,particles:g.particles.length,projectiles:g.projectiles.length,nodes:g.world.nodes.length,buildings:g.world.buildings.size,...s?{surveys:s.exploration.surveys.length,caches:s.exploration.caches.length,markers:s.exploration.markers.length,cargo:s.exploration.cargo.length,camps:s.survival.camps.length,fittings:s.fortification.fittings.length,debris:s.fortification.debris.length,companionPositions:Object.keys(s.companions.positions).length,campaignHistory:s.campaign.history.length,campaignSites:Object.values(s.campaign.usedSites).reduce((a,b)=>a+b.length,0)}:{}};}
function fixture(g){
 const C=globalThis.DeadwallCore,raw=g.serialize(),s=raw.expansions127.modules;let serial=1;const nodeList=g.world.nodes.filter(n=>!n.depleted).slice(0,80);
 s.exploration.surveys=nodeList.map(n=>({nodeId:n.id,type:n.type,x:n.x,y:n.y}));
 s.exploration.caches=Array.from({length:C.ExplorePackRules.maxCaches},(_,i)=>({id:serial++,x:2500+i*64,y:2300,stock:{...C.makeBag(),wood:12,food:12}}));
 s.exploration.markers=Array.from({length:C.ExplorePackRules.maxMarkers},(_,i)=>({id:serial++,x:500+i*120,y:1800}));
 s.exploration.cargo=nodeList.slice(0,C.ExplorePackRules.maxCargo).map(n=>({id:serial++,nodeId:n.id,type:n.type,amount:12,stage:'ground',x:n.x,y:n.y}));s.exploration.serial=serial;
 s.survival.camps=Array.from({length:C.SurvivalPackRules.maxCamps},(_,i)=>({id:i+1,domain:'local',x:2500+i*120,y:2450,z:0,inside:null,left:600,cover:300}));s.survival.serial=5;s.survival.meal={left:120,budget:60};
 g.restoreSave(raw);require(path.join(root,'tests/helpers/physical-fixtures.cjs')).standAt(g,g.player,g.core());
 const defense=g.campaignPack.previewStart('defense');if(defense.ok)g.campaignPack.start('defense');
 return{description:'Valid, synthetic maximum exploration containers and four timed camps; finite resources injected only as benchmark fixtures. Campaign defense started through its paid API.',counts:counts(g)};
}
function runBenchmark(){
 const project=path.resolve(option('--project',root)),expanded=args.includes('--expanded'),scene=option('--scene','calm'),g=boot(project,expanded),C=globalThis.DeadwallCore;
 g.phaseTime=9999;g.exploration125.wildNext=1e8;
 if(scene==='pressure'){g.wave=1000;g.phase='warning';g.prepareWave();g.phase='assault';g.startAssault();g.spawnTimer=-1000;g.update(.04);assert.equal(g.zombies.length,C.PERFORMANCE_LIMITS.zombies);}
 for(let i=0;i<100;i++)g.update(.04);
 global.gc?.();const memoryStart=process.memoryUsage(),samples=[],max=counts(g);
 for(let i=0;i<600;i++){const t=performance.now();g.update(.04);samples.push(performance.now()-t);if(i%100===0)for(const[k,v]of Object.entries(counts(g)))max[k]=Math.max(max[k]||0,v);}
 const modules=[];if(expanded){g.ui.commandModal=document.getElementById('commandModal');g.activeOverlay=g.ui.commandModal;g.paused=true;for(const d of g.expansions.entries()){for(let i=0;i<10;i++){d.overview();d.actions();}const sample=[];for(let i=0;i<150;i++){const t=performance.now();d.overview();d.actions();sample.push(performance.now()-t);}modules.push({id:d.id,...summarize(sample)});}g.activeOverlay=null;g.paused=false;}
 const bytes=Buffer.byteLength(JSON.stringify(g.serialize()));global.gc?.();return{kind:'timing',version:require(path.join(project,'package.json')).version,variant:expanded?'1.27-all-packs':'1.26-preserved-base',scene,seed:17117,stepSeconds:.04,warmupUpdates:100,measuredUpdates:600,update:summarize(samples),hubModuleModels:modules,saveBytes:bytes,memory:{before:memoryStart,after:process.memoryUsage()},maxCounts:max,endCounts:counts(g),elapsed:g.elapsed};
}
function runEndurance(){
 const g=boot(root,true),C=globalThis.DeadwallCore,setup=fixture(g),max=counts(g),checkpoints=[],startMemory=process.memoryUsage();let safetyKills=0,checks=0;const samples=[],slowUpdates=[],start=performance.now();
 for(let i=0;i<15000;i++){
  // Explicit synthetic assistance keeps the run alive; not an actual player/balance test.
  for(const z of g.zombies)if(!z.dead&&(Math.hypot(z.x-g.core().x,z.y-g.core().y)<550||g.units.some(u=>!u.dead&&Math.hypot(z.x-u.x,z.y-u.y)<160))){g.killZombie(z,false);safetyKills++;}
  g.player.invulnerable=Math.max(g.player.invulnerable,.08);const beforeElapsed=g.elapsed,phase=g.phase,t=performance.now();g.update(.04);const ms=performance.now()-t;samples.push(ms);if(slowUpdates.length<10||ms>slowUpdates.at(-1).ms){slowUpdates.push({step:i+1,elapsed:beforeElapsed,ms,phase,afterCheckpoint:i%1875===0&&i>0});slowUpdates.sort((a,b)=>b.ms-a.ms);slowUpdates.length=Math.min(10,slowUpdates.length);}
  if((i+1)%25===0){const n=counts(g);for(const[k,v]of Object.entries(n)){assert.ok(Number.isFinite(v));max[k]=Math.max(max[k]||0,v);}assert.ok(n.zombies<=C.PERFORMANCE_LIMITS.zombies);assert.ok(n.corpses<=C.PERFORMANCE_LIMITS.corpses);assert.ok(n.particles<=C.PERFORMANCE_LIMITS.particles);for(const[k,limit]of Object.entries({surveys:C.ExplorePackRules.maxSurveys,caches:C.ExplorePackRules.maxCaches,markers:C.ExplorePackRules.maxMarkers,cargo:C.ExplorePackRules.maxCargo,camps:C.SurvivalPackRules.maxCamps,fittings:C.FortificationPackRules.maxFittings,debris:C.FortificationPackRules.maxDebris,companionPositions:4,campaignHistory:C.CampaignPackRules.history})){assert.ok(n[k]<=limit,k+' beyond bounded registry');}for(const value of Object.values(g.resources))assert.ok(Number.isFinite(value)&&value>=0&&value<=g.storage+.000001);assert.ok(!g.gameOver);checks++;}
  if((i+1)%1875===0){const state=g.expansions.snapshot(),before=counts(g),bytes=Buffer.byteLength(JSON.stringify(g.serialize()));assert.ok(g.save(false));assert.ok(g.load());assert.deepEqual(g.expansions.snapshot(),state);checkpoints.push({elapsed:g.elapsed,counts:before,saveBytes:bytes,heapUsed:process.memoryUsage().heapUsed});}
 }
 assert.ok(Math.abs(g.elapsed-600)<.00001);const result={kind:'endurance',version:require('../package.json').version,seed:17117,simulatedSeconds:600,updates:15000,stepSeconds:.04,fixture:setup,checks,saveReloadCheckpoints:checkpoints.length,safetyKills,bot:'Approaching zombies removed within 550 world units of core or 160 of allied units; player receives renewed short invulnerability.',wallMs:performance.now()-start,slowUpdates,update:summarize(samples),maxCounts:max,endCounts:counts(g),checkpoints,memory:{before:startMemory,after:process.memoryUsage()},boundedGrowthPassed:true};return result;
}
if(args.includes('--child')){process.stdout.write(JSON.stringify(args.includes('--endurance')?runEndurance():runBenchmark()));}
else{
 const baseline=path.resolve(option('--baseline-root',path.join(root,'..','DEADWALL_1.23_MONDE_VIVANT'))),runs=[],rounds=Number(option('--rounds','3'));if(!fs.existsSync(path.join(baseline,'package.json')))throw Error('Provide the preserved 1.26 project with --baseline-root PATH.');
 for(let round=0;round<rounds;round++)for(const scene of ['calm','pressure'])for(const expanded of round%2?[true,false]:[false,true]){const a=['--expose-gc',__filename,'--child','--project',expanded?root:baseline,'--scene',scene,...expanded?['--expanded']:[]],r=spawnSync(process.execPath,a,{encoding:'utf8',maxBuffer:16*1024*1024});if(r.status!==0)throw Error(r.stderr||r.stdout);runs.push({round:round+1,...JSON.parse(r.stdout)});process.stderr.write('Round '+(round+1)+' '+scene+' '+(expanded?'1.27':'1.26')+' complete\n');}
 const endurance=spawnSync(process.execPath,['--expose-gc',__filename,'--child','--endurance'],{encoding:'utf8',maxBuffer:16*1024*1024});if(endurance.status!==0)throw Error(endurance.stderr||endurance.stdout);
 const data={generatedAt:new Date().toISOString(),protocol:'Node logic + fake DOM; no browser, layout, GPU or raster timing. Separate fresh child per variant/scene/round, seeded fixture RNG, .04 s active simulation steps, no flaky timing assertions.',environment:{node:process.version,platform:process.platform,arch:process.arch,cpu:os.cpus()[0]?.model,logicalCpus:os.cpus().length,totalMemoryBytes:os.totalmem(),rss:process.memoryUsage().rss},baselineVersion:require(path.join(baseline,'package.json')).version,runs,endurance:JSON.parse(endurance.stdout)};
 const dir=path.join(root,'reports/1.27.0');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'PERFORMANCE.json'),JSON.stringify(data,null,2)+'\n');
 const f=n=>n.toFixed(3),rows=[];for(const scene of ['calm','pressure'])for(const variant of ['1.26-preserved-base','1.27-all-packs']){const r=runs.filter(r=>r.scene===scene&&r.variant===variant);rows.push('| '+scene+' | '+variant+' | '+f(r.reduce((s,x)=>s+x.update.meanMs,0)/r.length)+' | '+f(r.reduce((s,x)=>s+x.update.p50Ms,0)/r.length)+' | '+f(r.reduce((s,x)=>s+x.update.p95Ms,0)/r.length)+' | '+f(Math.max(...r.map(x=>x.update.maxMs)))+' | '+Math.max(...r.map(x=>x.saveBytes))+' |');}
 const s=data.endurance;let text='# Performance et endurance 1.27\n\n'+data.protocol+'\n\nEnvironnement : '+data.environment.cpu+' ; '+data.environment.logicalCpus+' CPU logiques ; Node '+process.version+' ; '+process.platform+'/'+process.arch+'. L’hôte est partagé : la durée maximale inclut les pauses de collecte mémoire et la concurrence des autres tâches.\n\nCommande : `node scripts/benchmark127.cjs --baseline-root <projet-1.26> --rounds 3`. Chaque round utilise 100 mises à jour de chauffe puis 600 mesures de 0,04 s. Ordre des versions alterné selon les rounds. Les nombres de temps ci-dessous sont les moyennes des statistiques par round ; le maximum est le pire échantillon.\n\n| Scène | Version | Moyenne update ms | p50 ms | p95 ms | Maximum ms | Sauvegarde octets max |\n|---|---|---:|---:|---:|---:|---:|\n'+rows.join('\n')+'\n\nLa base 1.26 est le projet conservé, avec éclairage, monde D-17 et présentation des acteurs installés. La 1.27 ajoute les cinq packs et leur registre. La scène pression démarre à la vague technique 1000, plafonnée à 720 infectés simultanés ; ce n’est pas une estimation d’équilibrage de cette vague. Aucune image n’est rendue pendant la mesure. `update()` inclut les rafraîchissements périodiques du DOM de test ; il exclut le coût réel de mise en page/CSS.\n\n## Modèles du panneau Opérations\n\nLes aperçus/actions des cinq modules sont mesurés uniquement dans le contexte modal du commandement (état pause/overlay reproduit, sans chronométrer le DOM du panneau), 150 appels par module après 10 appels de chauffe. Ils ne sont pas exécutés à chaque image du benchmark.\n\n| Module | Moyenne ms | p95 moyen ms | Maximum ms |\n|---|---:|---:|---:|\n';
 for(const id of ['exploration','survival','fortification','companions','campaign']){const r=runs.flatMap(r=>r.hubModuleModels||[]).filter(x=>x.id===id);text+='| '+id+' | '+f(r.reduce((a,x)=>a+x.meanMs,0)/r.length)+' | '+f(r.reduce((a,x)=>a+x.p95Ms,0)/r.length)+' | '+f(Math.max(...r.map(x=>x.maxMs)))+' |\n';}
 text+='\n## Endurance additionnelle des extensions\n\n'+s.updates+' mises à jour de 0,04 s : **10 minutes simulées**, '+s.checks+' contrôles, '+s.saveReloadCheckpoints+' sauvegardes réellement rechargées. '+s.safetyKills+' infectés éliminés par un bot explicitement artificiel pour empêcher la fin de partie. Les mouvements, vagues, économie, expirations et sauvegardes restent ceux du moteur.\n\nFixture synthétique validée avant simulation : 80 relevés, 8 caches remplies, 24 piquets, 8 ballots au sol et 4 camps temporisés, plus une opération de défense engagée via son API payante. Ces ressources et poses sont des données de charge du test ; elles ne sont pas offertes dans une nouvelle partie.\n\nLes tableaux sont contrôlés contre les limites de core.js. Aucun dépassement observé. Les caches/piquets/ballots persistent ; les camps et effets expirent. Les maxima et tous les checkpoints figurent dans PERFORMANCE.json. Les empreintes mémoire sont publiées comme observations du processus : elles ne prouvent pas l’absence de fuite dans un navigateur.\n\nDurée de calcul endurance : '+f(s.wallMs/1000)+' s ; update moyen '+f(s.update.meanMs)+' ms, p95 '+f(s.update.p95Ms)+' ms ; maximum '+f(s.update.maxMs)+' ms. Les dix mises à jour les plus lentes sont publiées avec leur position dans la simulation, notamment juste après reprise.\n\nAucun seuil de temps fragile n’est un critère de test. Ces chiffres mesurent le coût CPU de la simulation sur cet hôte, **pas les FPS, la fluidité du navigateur, le GPU, le tactile ou l’équilibrage d’une partie sans assistance**.\n';fs.writeFileSync(path.join(dir,'PERFORMANCE.md'),text);process.stdout.write(JSON.stringify({report:'reports/1.27.0/PERFORMANCE.json',runs:runs.length,enduranceChecks:s.checks,enduranceWallMs:s.wallMs})+'\n');
}
