/* Dedicated armory panel, with the simulation paused and explicit field-work handoff. */
(function(root){'use strict';
function install(g,doc=root.document){if(!g.arsenal134||!doc||g.arsenalUI134)return false;const C=root.DeadwallCore,D=C.Arsenal134Rules.catalog;let opened=false,openedWorld=null,previousPause=false,returnFocus=null,category='all',tab='carried';const inert=new Map();
const el=(tag,text,cls)=>{const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;},button=(label,fn,key)=>{const b=el('button',label);b.type='button';b.dataset.action=key||label;b.addEventListener('click',fn);return b;};
const overlay=el('section',undefined,'arsenal134-overlay hidden');overlay.id='arsenal134';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.setAttribute('aria-labelledby','arsenal134Title');overlay.inert=true;
const shell=el('div',undefined,'arsenal134-shell'),head=el('header',undefined,'arsenal134-header'),heading=el('div');const title=el('h1','L’ARMURERIE');title.id='arsenal134Title';heading.append(el('small','D-17 / QUARTIER-MAÎTRE'),title);const closeButton=button('FERMER · ÉCHAP',()=>close(),'close');head.append(heading,closeButton);shell.append(head);
const status=el('p',undefined,'arsenal134-status');status.setAttribute('role','status');shell.append(status);const tabs=el('nav',undefined,'arsenal134-tabs');tabs.setAttribute('aria-label','Sections de l’armurerie');for(const[id,name]of [['carried','Harnais'],['locker','Râtelier'],['catalog','Atelier'],['posts','Postes déployés']])tabs.append(button(name,()=>{tab=id;refresh();},'tab:'+id));shell.append(tabs);
const filters=el('nav',undefined,'arsenal134-filters');filters.setAttribute('aria-label','Familles d’équipement');for(const[id,name]of [['all','Tout'],['firearm','Armes à feu'],['melee','Mêlée'],['improvised','Fortune'],['tool','Outils'],['deployed','Défenses']])filters.append(button(name,()=>{category=id;refresh();},'filter:'+id));shell.append(filters);const grid=el('div',undefined,'arsenal134-grid');shell.append(grid);overlay.append(shell);doc.body.append(overlay);
function icon(d){if(root.DeadwallAssets136)return root.DeadwallAssets136.icon(doc,d.id,{category:d.category,className:'arsenal134-icon'});const box=el('span',undefined,'arsenal134-icon');box.setAttribute('aria-hidden','true');const svg=doc.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 120 64');const path=doc.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d.category==='firearm'?'M14 22h67v9H50l-8 21H30l5-20H14zm67 2h25v5H81M17 23l-9 14h19':d.category==='deployed'?'M16 48l34-25 34 25M50 23v34M36 15h38v15H36zM74 19h34v6H74':d.id==='knife'||d.id==='machete'?'M17 48l20-18 11 11-22 17zM35 30L90 6 68 37 48 43z':'M21 53L76 11l8 9-56 41zM60 10l17-7 26 22-9 15-30-18z');path.setAttribute('fill','none');path.setAttribute('stroke','currentColor');path.setAttribute('stroke-width','4');path.setAttribute('stroke-linejoin','round');svg.append(path);box.append(svg);return box;}
function act(fn,field=false){const r=fn();if(r?.ok&&field){close(true);return;}status.textContent=r?.reason||g.arsenal134.view().message;refresh();}
function stat(host,label,value){const n=el('div');n.append(el('small',label),el('strong',value));host.append(n);}
function card(d,i,post,v){const node=el('article',undefined,'arsenal134-card');node.append(icon(d),el('small',({firearm:'ARME À FEU',melee:'MÊLÉE',improvised:'FORTUNE',tool:'OUTIL',deployed:'POSTE DÉFENSIF'})[d.category]),el('h2',d.name));const stats=el('div',undefined,'arsenal134-stats');stat(stats,'IMPACT',d.damage+(d.pellets>1?' × '+d.pellets:''));stat(stats,'PORTÉE',d.range.toFixed(1)+' m');stat(stats,'CADENCE',d.fireRate.toFixed(2)+'/s');stat(stats,'MASSE',d.kg.toFixed(1)+' kg');stat(stats,d.category==='firearm'?'RECHARGE':'EFFORT',d.category==='firearm'?d.reload+' s':d.stamina?d.stamina+' endurance':'Autonome');stat(stats,'USURE',d.wear+' / action');node.append(stats);
if(i){const state=el('div',undefined,'arsenal134-condition');state.append(el('span','État '+Math.ceil(i.condition)+' %'+(d.magazine?' · '+i.rounds+' / '+d.magazine+' chargées':'')));const meter=el('progress');meter.max=100;meter.value=i.condition;meter.setAttribute('aria-label','État de '+d.name);state.append(meter);node.append(state);}
node.append(el('p',d.description));const controls=el('div',undefined,'arsenal134-controls');
if(tab==='catalog'){const q=d.craft||g.arsenal134.preview('craft',d.id);node.append(el('p',C.resourceText(d.cost)+' · palier '+d.tier+' · '+(d.requires?C.BUILDINGS[d.requires].name+' physique requis':'Dépôt de D-17'),'arsenal134-cost'));const detail=el('small',q.ok?'Paiement après '+q.seconds+' s de travail. Objet prêt au râtelier ; retrait au dépôt, sans nouveau paiement.':q.reason,'arsenal134-reason');detail.id='arsenal134Recipe-'+d.id;const b=button('ASSEMBLER · '+(q.seconds||'—')+' s',()=>act(()=>g.arsenal134.begin('craft',d.id),true),'craft:'+d.id);b.disabled=!q.ok;b.setAttribute('aria-describedby',detail.id);controls.append(b);node.append(detail);}
else if(tab==='posts'){node.append(el('p',Math.ceil(post.health)+' / '+d.health+' intégrité'));for(const[k,name]of [['ammo','RAVITAILLER'],['repair','RÉPARER'],['pickup','REPRENDRE'],['clear','DÉBLAYER L’ÉPAVE']]){const b=button(name,()=>act(()=>g.arsenal134.servicePost(i.uid,k)),'post:'+i.uid+':'+k);b.disabled=!post.near||(k==='clear'?post.health>0:post.health<=0)||k==='ammo'&&!d.ammoPerReload;controls.append(b);}}
else{if(tab==='carried'){if(d.category==='deployed')controls.append(button('DÉPLOYER DEVANT SOI',()=>{close(true);const r=g.arsenal134.deploy(i.uid);if(!r.ok){g.notify(r.reason,'danger');}},'deploy:'+i.uid));else{const b=button(v.equipped===i.uid?'EN MAIN':'ÉQUIPER',()=>act(()=>g.arsenal134.equip(i.uid)),'equip:'+i.uid);b.setAttribute('aria-pressed',String(v.equipped===i.uid));controls.append(b);}}const move=button(tab==='carried'?'RANGER AU DÉPÔT':'PRENDRE',()=>act(()=>g.arsenal134.transfer(i.uid,tab==='carried'?'locker':'carried')),'move:'+i.uid);move.disabled=!v.atHome;controls.append(move);const q=g.arsenal134.preview('repair',d.id),repair=button('RÉPARER',()=>act(()=>g.arsenal134.begin('repair',d.id,i.uid),true),'repair:'+i.uid);repair.disabled=!q.ok||i.condition>=100;controls.append(repair);if(i.condition<100&&q.cost)node.append(el('small','Réparation : '+C.resourceText(q.cost)));}
node.append(controls);return node;}
function refresh(){if(!opened)return;const old=doc.activeElement?.dataset?.action,scroll=grid.scrollTop,v=g.arsenal134.view();status.textContent=v.weight.toFixed(1)+' / '+v.capacity+' kg au harnais · '+(v.atHome?'Dépôt accessible':'Retrait au râtelier : rejoignez le dépôt')+(v.message?' · '+v.message:'');for(const b of tabs.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.action==='tab:'+tab));for(const b of filters.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b.dataset.action==='filter:'+category));grid.replaceChildren();const items=tab==='catalog'?v.catalog.map(d=>({d})):tab==='posts'?v.posts.map(p=>({d:D[p.item.id],i:p.item,post:p})):v[tab].map(i=>({d:D[i.id],i}));let count=0;for(const{d,i,post}of items)if(category==='all'||category===d.category){grid.append(card(d,i,post,v));count++;}if(!count)grid.append(el('p','Aucun équipement dans cette section. L’atelier permet de préparer du matériel au dépôt.','arsenal134-empty'));grid.scrollTop=scroll;if(old){const b=[...overlay.querySelectorAll('button')].find(b=>b.dataset.action===old&&!b.disabled);(b||closeButton).focus({preventScroll:true});}}
function cleanup(){opened=false;openedWorld=null;overlay.classList.add('hidden');overlay.inert=true;for(const[n,value]of inert)n.inert=value;inert.clear();g.releaseInputs();}
const sync=g.syncOverlayFocus.bind(g);g.syncOverlayFocus=(...a)=>{
 // An accepted campaign replacement must reach its own introduction or death
 // screen. A rejected operation keeps the same world and this modal intact.
 if(opened&&(g.world!==openedWorld||g.state!=='playing'||g.gameOver||g.player.dead)){cleanup();returnFocus=null;}
 if(!opened)return sync(...a);for(const n of [...doc.body.children,g.ui.hud,g.ui.commandModal,g.ui.pauseMenu])if(n&&n!==overlay){if(!inert.has(n))inert.set(n,n.inert);n.inert=true;}overlay.inert=false;g.activeOverlay=overlay;g.releaseInputs();if(!overlay.contains(doc.activeElement))closeButton.focus({preventScroll:true});};
function open(){if(opened)return true;if(g.state!=='playing'||g.player.dead||g.gameOver)return false;if(g.activeOverlay===g.ui.commandModal)g.showCommand(false);if(g.activeOverlay&&g.activeOverlay!==g.ui.pauseMenu)return false;returnFocus=doc.activeElement;previousPause=g.paused;openedWorld=g.world;opened=true;g.paused=true;g.releaseInputs();g.cancelPlacement?.();overlay.classList.remove('hidden');g.syncOverlayFocus();refresh();closeButton.focus({preventScroll:true});return true;}
function close(resume=false){if(!opened)return false;cleanup();if(g.state==='playing'&&!g.gameOver){g.paused=resume?false:previousPause;if(resume)g.ui.pauseMenu.classList.add('hidden');}g.syncOverlayFocus();if(returnFocus&&!returnFocus.closest?.('[inert], .hidden'))returnFocus.focus({preventScroll:true});returnFocus=null;return true;}
const escape=g.onEscape.bind(g);g.onEscape=(...a)=>opened?close():escape(...a);
overlay.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();e.stopPropagation();close();}else if(e.code==='Tab')g.trapOverlayFocus(e);});
const suspend=g.suspendForFocusLoss.bind(g);g.suspendForFocusLoss=(...a)=>{if(opened){previousPause=true;g.ui.pauseMenu.classList.remove('hidden');}const r=suspend(...a);if(opened)g.syncOverlayFocus();return r;};
g.arsenalUI134=Object.freeze({open,close,refresh,isOpen:()=>opened,element:overlay});g.art?.ready?.then(()=>{if(opened)refresh();});return true;}
const api={install};root.DeadwallArsenalUI134=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;else if(root.DEADWALL&&root.document)install(root.DEADWALL);
})(globalThis);
