/* Interactive survey map. Gestures only alter its viewport, never campaign state. */
(function(root){'use strict';const P=root.DeadwallAtlasProjection,R=root.DeadwallAtlasRender;
function attach(g,canvas,host){if(canvas.atlas)return canvas.atlas;const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;},write=(e,t)=>{if(e.textContent!==String(t))e.textContent=String(t);},cam=P.camera(canvas.width,canvas.height),layers={terrain:true,roads:true,city:true,places:true,labels:true,gates:true,relays:true,units:true,routes:true,travelled:false,intelligence:true,tours:true,biomes:false};let lastView=null,selected=null,drag=null,pointers=new Map(),pinch=null,measureMode=false,measures=[],hits=0;
const frame=make('div',undefined,'atlas-frame');canvas.before(frame);frame.append(canvas);canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Atlas interactif. Glisser pour déplacer, molette ou deux doigts pour zoomer, cliquer pour inspecter. Clavier : flèches, plus, moins, 1 région, 2 D-17, 3 joueur.');
const tools=make('div',undefined,'atlas-tools'),btn=(name,id,fn)=>{const b=make('button',name);b.id=id;b.type='button';b.addEventListener('click',()=>{fn();draw();});return b;};
tools.append(btn('D-17','atlasHome',()=>city()),btn('MESURER','atlasMeasure',()=>{measureMode=!measureMode;measures=[];document.getElementById('atlasMeasure').setAttribute('aria-pressed',String(measureMode));}),btn('AGRANDIR','atlasExpand',()=>{host.classList.toggle('atlas-expanded');document.getElementById('atlasExpand').setAttribute('aria-pressed',String(host.classList.contains('atlas-expanded')));resize();}));frame.before(tools);
const layerPanel=make('details',undefined,'atlas-layers');layerPanel.append(make('summary','Calques de la carte'));const names={terrain:'Sols et végétation',biomes:'Noms des biomes',roads:'Routes',city:'Cité D-17',places:'Lieux repérés',labels:'Noms',gates:'Jonctions',relays:'Relais',units:'Alliés et caméra',routes:'Itinéraire',travelled:'Secteurs parcourus',intelligence:'Indices du bureau',tours:'Tournée'};for(const[k,name]of Object.entries(names)){const lab=make('label'),input=make('input');input.type='checkbox';input.checked=layers[k];input.dataset.layer=k;input.id='atlasLayer-'+k;input.addEventListener('change',()=>{layers[k]=input.checked;draw();});lab.append(input,document.createTextNode(name));layerPanel.append(lab);}tools.append(layerPanel);
const provenance=make('p',undefined,'atlas-provenance');provenance.id='atlasWorld';tools.after(provenance);
const readout=make('p','Glisser pour parcourir • molette / deux doigts pour zoomer','atlas-readout');readout.id='atlasCoordinates';frame.after(readout);
const inspector=make('section',undefined,'atlas-inspector');inspector.id='atlasInspector';const title=make('h3','D-17 — carte de la cité'),body=make('p'),pinButton=btn('CHOISIR COMME REPÈRE','atlasPin',()=>{if(selected?.kind==='poi')g.frontier.pin(selected.id);}),back=btn('VUE D’ENSEMBLE','atlasReset',()=>fit());inspector.append(title,body,pinButton,back);readout.after(inspector);pinButton.hidden=true;
const overview=make('details',undefined,'atlas-city-card');overview.id='atlasCityCard';overview.append(make('summary','D-17 : emprise et jonctions'));const metric=make('p'),gateRows=make('div',undefined,'atlas-gates');overview.append(metric,gateRows);inspector.after(overview);const gateElements={};for(const gate of P.gates){const button=btn(gate.name,'atlasGate-'+gate.id,()=>{const current=P.gatesFor(g).find(q=>q.id===gate.id);cam.regionSize(view().world.size);cam.fit(current.x,current.y,70);selected={kind:'gate',id:gate.id};});const s=make('span');gateRows.append(button,s);gateElements[gate.id]=s;}
function view(){return lastView||g.frontier.overview();}
function resize(){const box=canvas.getBoundingClientRect();if(box.width<20)return;const aspect=host.classList.contains('atlas-expanded')?1.2:window.innerWidth<650? .92:1.48,width=Math.max(280,Math.min(1400,Math.round(box.width))),height=Math.round(width/aspect),dpr=Math.min(2,window.devicePixelRatio||1);if(canvas.width!==Math.round(width*dpr)||canvas.height!==Math.round(height*dpr)){canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);}canvas.style.height=height+'px';cam.resize(width,height);}
function localPoint(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*cam.width/r.width,y:(e.clientY-r.top)*cam.height/r.height};}
function fit(){const size=view().world.size||P.RULES.regionSize;cam.regionSize(size);cam.fit(size/2,size/2,size);selected=null;}
function city(){const h=P.home(g);cam.regionSize(view().world.size);cam.fit(h.x,h.y,P.RULES.citySpan);selected={kind:'home',id:'D17'};}
function locate(){const current=g.frontier.overview();if(!lastView||current.world!==lastView.world){selected=null;measures=[];}lastView=current;cam.regionSize(lastView.world.size);const p=P.playerPosition(g,lastView);cam.fit(p.x,p.y,lastView.active?420:P.RULES.citySpan);draw();}
function focusPOI(id){const p=view().world.pois.find(p=>p.id===id);if(!p||!view().seen.includes(id))return false;cam.fit(p.x,p.y,Math.max(180,p.w*2,p.h*2));selected={kind:'poi',id};draw();return true;}
function inspect(q){const w=cam.world(q.x,q.y),v=view(),m=P.model(g),radius=8/cam.scale;if(measureMode){if(measures.length===2)measures=[];measures.push(w);draw();return;}
selected=null;if(layers.city){const b=m.buildings.filter(b=>w.x>=b.x&&w.x<=b.x+b.w&&w.y>=b.y&&w.y<=b.y+b.h).sort((a,b)=>a.w*a.h-b.w*b.h)[0];if(b)selected={kind:'building',id:b.id};}
if(!selected&&layers.gates){const gate=m.gates.find(p=>Math.hypot(w.x-p.x,w.y-p.y)<radius);if(gate&&cam.scale>.35)selected={kind:'gate',id:gate.id};}
if(!selected&&layers.city&&w.x>=m.bounds.x&&w.x<=m.bounds.x+m.bounds.w&&w.y>=m.bounds.y&&w.y<=m.bounds.y+m.bounds.h)selected={kind:'home',id:'D17'};
if(!selected&&layers.places){const G=root.DeadwallFrontierGeometry;const p=v.world.pois.filter(p=>v.seen.includes(p.id)).find(p=>{const l=G.local(p,w.x,w.y);return l.x>=-radius&&l.y>=-radius&&l.x<=p.w+radius&&l.y<=p.h+radius});if(p)selected={kind:'poi',id:p.id};}if(!selected&&v.world.biomeAt&&w.x>=0&&w.y>=0&&w.x<=v.world.size&&w.y<=v.world.size)selected={kind:'terrain',x:w.x,y:w.y};hits++;draw();}
function biomeText(world,x,y){const b=world.biomeAt?.(x,y);if(!b)return '';const other=root.DeadwallBiomes135?.BY?.[b.secondary],transition=other&&other.id!==b.id&&b.blend>=.2?' · transition vers '+other.name:'';return b.name+(b.habitat?.name?' · '+b.habitat.name:'')+transition;}

function info(v,m){pinButton.hidden=true;const empty=()=>{write(title,'Atlas de D-17');write(body,'Sélectionnez un bâtiment de la cité, une jonction ou un lieu déjà repéré. Les empreintes suivent l’échelle du monde ; les icônes restent lisibles à distance.');};if(!selected){empty();return;}
if(selected.kind==='home'){write(title,'D-17 — cité réelle');write(body,'128 × 128 m dans le repère régional. '+m.buildings.length+' structures présentes, '+m.buildings.filter(b=>!b.complete).length+' chantiers. Projection : 32 unités locales = 1 m ; une cellule locale = 1 m. La carte ne redimensionne ni ne déplace votre ville.');}
else if(selected.kind==='building'){const b=m.buildings.find(b=>b.id===selected.id);if(!b){write(title,'Structure disparue');write(body,'Ce bâtiment a été détruit ou retiré. La carte ne conserve pas une copie fictive.');return;}write(title,b.name);write(body,(b.complete?'Achevé':'Chantier '+Math.round(b.progress*100)+' %')+' · emprise '+b.w+' × '+b.h+' m · intégrité '+Math.ceil(b.health)+' / '+Math.ceil(b.maxHealth)+' · grille '+b.source.gx+', '+b.source.gy+(b.type.toLowerCase().includes('gate')?' · porte '+b.gateMode:'')+(b.source.def.powerUse?' · '+(b.powered?'alimenté':'sans courant'):'')+'. Inspection seule : gérer ce bâtiment depuis D-17.');}
else if(selected.kind==='gate'){const gate=m.gates.find(p=>p.id===selected.id);write(title,'Jonction '+gate.name);write(body,'Point de retour local : '+gate.localX+', '+gate.localY+' unités. À pied : '+(gate.foot?'position libre':'obstruée')+' ; break : '+(gate.car?'position libre':'obstruée')+'. Contrôle local du point central, pas garantie de tout l’itinéraire. La traversée reste physique.');}
else if(selected.kind==='terrain'){const b=v.world.biomeAt?.(selected.x,selected.y);if(!b){empty();return;}write(title,biomeText(v.world,selected.x,selected.y));write(body,(selected.x/1000).toFixed(3)+' / '+(selected.y/1000).toFixed(3)+' km · sol '+({grass:'herbe',underbrush:'sous-bois',mud:'boue',gravel:'gravier'}[b.surface]||b.surface)+'. Les noms suivent les mêmes champs écologiques que le terrain. Petit décor passable ; arbres et rochers ont leurs emprises physiques. Aucun stock ni trajet sûr n’est garanti.');}
else if(selected.kind==='poi'){const p=v.world.pois.find(p=>p.id===selected.id);if(!p||!v.seen.includes(p.id)){empty();return;}write(title,p.name);write(body,p.w+' × '+p.h+' m · '+p.levels.length+' niveau(x) · '+(p.x/1000).toFixed(3)+', '+(p.y/1000).toFixed(3)+' km'+(biomeText(v.world,p.x,p.y)?' · '+biomeText(v.world,p.x,p.y):'')+'. Repéré dans la campagne. Les notes du carnet ne certifient ni la sécurité ni l’épuisement du lieu.');pinButton.hidden=false;pinButton.disabled=!g.canIssueCommand();}}
function draw(v){const changed=v&&(!lastView||v.world!==lastView.world);if(v)lastView=v;if(changed){fit();measures=[];selected=null;}if(!lastView)return;cam.regionSize(lastView.world.size);resize();const h=P.home(g),size=lastView.world.size;write(provenance,'Graine '+lastView.world.seed+' · carte G'+lastView.world.generation+' · '+(size/1000).toFixed(3)+' × '+(size/1000).toFixed(3)+' km · D-17 : '+(h.x/1000).toFixed(3)+' / '+(h.y/1000).toFixed(3)+' km. Région : vue complète ; D-17 : zoom du refuge.');if(measures.length!==2)write(readout,'Centre : '+(cam.x/1000).toFixed(3)+' / '+(cam.y/1000).toFixed(3)+' km'+(biomeText(lastView.world,cam.x,cam.y)?' · '+biomeText(lastView.world,cam.x,cam.y):'')+' · Nord en haut.');const c=canvas.getContext('2d'),dpr=canvas.width/cam.width;c.setTransform(dpr,0,0,dpr,0,0);const result=R.render(c,g,lastView,cam,layers,selected);if(measures.length){c.strokeStyle='#f4d798';c.lineWidth=2;c.setLineDash([4,3]);c.beginPath();measures.forEach((p,i)=>{const s=cam.screen(p.x,p.y);i?c.lineTo(s.x,s.y):c.moveTo(s.x,s.y)});c.stroke();c.setLineDash([]);for(const p of measures){const s=cam.screen(p.x,p.y);c.fillStyle='#f8ddab';c.beginPath();c.arc(s.x,s.y,4,0,Math.PI*2);c.fill();}if(measures.length===2)write(readout,'Mesure à vol d’oiseau : '+Math.hypot(measures[1].x-measures[0].x,measures[1].y-measures[0].y).toFixed(1)+' m. Aucune vérification d’itinéraire.');}
write(metric,'D-17 : '+result.model.buildings.length+' structures · '+g.population+' personnes / '+g.housing+' logements · '+(g.tier?.name||'Refuge')+'. La cité est toujours celle de votre campagne.');for(const gate of result.model.gates)write(gateElements[gate.id],(gate.foot?'Piéton libre':'Piéton bloqué')+' · '+(gate.car?'Break libre':'Break bloqué'));info(lastView,result.model);canvas.dataset.zoom=cam.zoom.toFixed(3);canvas.dataset.scale=cam.scale.toFixed(6);canvas.dataset.homePixels=(128*cam.scale).toFixed(3);canvas.dataset.buildings=String(result.model.buildings.length);}
canvas.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();const p=localPoint(e);cam.zoomAt(Math.exp(-Math.max(-200,Math.min(200,e.deltaY))*.004),p.x,p.y);draw();},{passive:false});
canvas.addEventListener('pointerdown',e=>{if(e.button!==0&&e.pointerType!=='touch')return;e.preventDefault();canvas.focus({preventScroll:true});const p=localPoint(e);pointers.set(e.pointerId,p);canvas.setPointerCapture?.(e.pointerId);drag={id:e.pointerId,start:p,last:p,moved:false};if(pointers.size===2){const a=[...pointers.values()];pinch={distance:Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y),mid:{x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}};drag.moved=true;}});
canvas.addEventListener('pointermove',e=>{const p=localPoint(e);if(pointers.has(e.pointerId))pointers.set(e.pointerId,p);if(pointers.size===2&&pinch){e.preventDefault();const a=[...pointers.values()],distance=Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y),mid={x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};cam.pan(mid.x-pinch.mid.x,mid.y-pinch.mid.y);if(pinch.distance>5)cam.zoomAt(distance/pinch.distance,mid.x,mid.y);pinch={distance,mid};if(drag)drag.moved=true;draw();return;}if(drag&&pointers.has(e.pointerId)){if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>4)drag.moved=true;if(drag.moved){cam.pan(p.x-drag.last.x,p.y-drag.last.y);draw();}drag.last=p;}if(measures.length!==2){const q=cam.world(p.x,p.y),h=P.home(g);write(readout,q.x>=0&&q.y>=0&&q.x<=view().world.size&&q.y<=view().world.size? 'Coordonnées : '+(q.x/1000).toFixed(3)+' / '+(q.y/1000).toFixed(3)+' km · '+(q.x>=h.minX&&q.x<=h.maxX&&q.y>=h.minY&&q.y<=h.maxY?'D-17 — grille '+P.toLocal(q.x,q.y,g).x.toFixed(0)+', '+P.toLocal(q.x,q.y,g).y.toFixed(0)+' unités':'Nord en haut')+(biomeText(view().world,q.x,q.y)?' · '+biomeText(view().world,q.x,q.y):''):'Hors de la région');}});
function release(e){const wasPinch=!!pinch,p=localPoint(e);pointers.delete(e.pointerId);if(pointers.size<2)pinch=null;if(drag?.id===e.pointerId){const click=!drag.moved&&!wasPinch&&e.type!=='pointercancel';drag=null;if(click)inspect(p);}if(pointers.size===0){drag=null;pinch=null;}try{canvas.releasePointerCapture?.(e.pointerId)}catch{}}
canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('lostpointercapture',()=>{if(!pointers.size){drag=null;pinch=null;}});
canvas.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','1','2','3','Home','Escape'].includes(e.key)){e.preventDefault();e.stopPropagation();if(e.key==='ArrowLeft')cam.pan(70,0);if(e.key==='ArrowRight')cam.pan(-70,0);if(e.key==='ArrowUp')cam.pan(0,70);if(e.key==='ArrowDown')cam.pan(0,-70);if(e.key==='+'||e.key==='=')cam.zoomAt(1.5);if(e.key==='-')cam.zoomAt(1/1.5);if(e.key==='Home'||e.key==='1')fit();if(e.key==='2')city();if(e.key==='3')locate();if(e.key==='Escape'){measureMode=false;measures=[];selected=null;document.getElementById('atlasMeasure').setAttribute('aria-pressed','false');}draw();}});
const observer=typeof ResizeObserver!=='undefined'?new ResizeObserver(()=>{if(lastView&&canvas.getBoundingClientRect().width>20)draw();}):null;observer?.observe(frame);
const api=Object.freeze({draw,fit,city,locate,focusPOI,zoom:factor=>{cam.zoomAt(factor);draw();},pan:(dx,dy)=>{cam.pan(dx,dy);draw();},screen:(x,y)=>cam.screen(x,y),position:()=>cam.snapshot(),focusPoint:(x,y,span=220)=>{cam.fit(x,y,span);selected=null;draw();},selected:()=>selected?{...selected}:null,layers:()=>({...layers}),measure:()=>measures.map(p=>({...p})),bounds:()=>cam.bounds()});canvas.atlas=api;return api;
}
root.DeadwallAtlasView={attach};})(globalThis);
