/* Physical opening reinforcements. Geometry is derived from existing walls; materials remain in the carried bag until work completes. */
(function(root){
'use strict';
const C=root.DeadwallCore||(typeof require==='function'?require('./core.js'):null);
const G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null);
const rules=()=>C.BarricadeRules134,clone=x=>JSON.parse(JSON.stringify(x));
const live=e=>!!e&&!e.dead&&(e.health??e.hp)>0;
const scale=t=>t.domain==='local'?32:1;
const round=n=>Number(n.toFixed(4));
function initial(){return{version:1,records:[]};}
function target(id,domain,kind,name,x,y,width,angle=0,z=0,inside=null){return{id,domain,kind,name,x,y,width,angle,z,inside};}
function localTargets(plan){
 if(!plan)return[];const out=[];
 for(const s of plan.stations||[]){const d=s.door;out.push(target('local:'+s.id+':door','local','door',(s.archetypeLabel||'Station')+' · porte',d.x,d.y,d.width,s.horizontal?0:Math.PI/2));
  for(const [i,w]of(s.windows||[]).entries())out.push(target('local:'+s.id+':window:'+(w.id??i),'local','window',(s.archetypeLabel||'Station')+' · fenêtre brisée',w.x,w.y,w.width,w.horizontal===false?Math.PI/2:0));}
 for(const y of plan.backyards||[]){const d=y.gate;out.push(target('local:'+y.id+':gate','local','gate','Cour résidentielle · portail',d.x,d.y,d.width,d.vertical?Math.PI/2:0));}
 return out;
}
function regionTargets(world,p,z=0){
 if(!p||!p.levels.includes(z))return[];const plan=world.plan(p,z),out=[],seen=new Set();
 // Pair collinear wall bands. Their real missing span, not a decorative door sprite, is the aperture.
 for(const vertical of[false,true]){
  const groups=new Map();for(const b of plan.walls){if(vertical?b.w>.5||b.h<.25:b.h>.5||b.w<.25)continue;const key=round(vertical?b.x:b.y)+':'+round(vertical?b.w:b.h);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(b);}
  for(const bands of groups.values()){bands.sort((a,b)=>vertical?a.y-b.y:a.x-b.x);let prior=bands[0];for(let i=1;i<bands.length;i++){const b=bands[i],lo=vertical?prior.y+prior.h:prior.x+prior.w,hi=vertical?b.y:b.x,gap=hi-lo,axis=vertical?b.x+b.w/2:b.y+b.h/2;
   if(gap>=.7&&gap<=4.5){const a=vertical?Math.PI/2:0,lx=vertical?axis:(lo+hi)/2,ly=vertical?(lo+hi)/2:axis,rect=vertical?{x:axis-.15,y:lo,w:.3,h:gap}:{x:lo,y:axis-.15,w:gap,h:.3};
    if(![...plan.objects,...plan.stairs].some(o=>G.overlap({l:rect.x,r:rect.x+rect.w,t:rect.y,b:rect.y+rect.h},{l:o.x,r:o.x+o.w,t:o.y,b:o.y+o.h},.03))){const pos=G.global(p,lx,ly),id='region:'+p.id+':'+z+':'+(vertical?'v':'h')+':'+round(axis)+':'+round(lo)+':'+round(hi);if(!seen.has(id)){seen.add(id);const exterior=lx<.4||ly<.4||lx>p.w-.4||ly>p.h-.4;out.push(target(id,'region',exterior?'door':'opening',p.name+' · '+(exterior?'porte extérieure':'passage intérieur'),pos.x,pos.y,gap,p.a+a,z,p.id));}}}
   if((vertical?b.y+b.h:b.x+b.w)>(vertical?prior.y+prior.h:prior.x+prior.w))prior=b;
  }}
 }
 return out;
}
function localPoint(t,p){const dx=p.x-t.x,dy=p.y-t.y,c=Math.cos(t.angle),s=Math.sin(t.angle);return{x:dx*c+dy*s,y:-dx*s+dy*c};}
function hitCircle(t,x,y,r){const q=localPoint(t,{x,y}),h=rules().thickness*scale(t)/2;return G.circleRect(q.x,q.y,r,{x:-t.width/2,y:-h,w:t.width,h:h*2});}
function hitLine(t,a,b,pad=0){const h=rules().thickness*scale(t)/2;return G.segmentRect(localPoint(t,a),localPoint(t,b),{x:-t.width/2-pad,y:-h-pad,w:t.width+pad*2,h:h*2+pad*2});}
function resolveFrom(world,plan,id){if(id.startsWith('local:'))return localTargets(plan).find(t=>t.id===id)||null;const parts=id.split(':'),p=world?.pois.find(p=>p.id===parts[1]);return p?regionTargets(world,p,Number(parts[2])).find(t=>t.id===id)||null:null;}
const validationCache=new Map();
function validationGeometry(full){const key=full.worldSeed+':'+(full.frontier?.generation??3)+':'+(full.exploration125?.layoutRevision??1);let ctx=validationCache.get(key);if(!ctx){const W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),E=root.DeadwallExploration125||(typeof require==='function'?require('./exploration-125.js'):null);ctx={world:null,plan:E.createFeaturePlan(full.worldSeed,C.WORLD_SIZE,full.exploration125?.layoutRevision??1),create:()=>W.create(full.worldSeed,full.frontier?.generation??3)};validationCache.set(key,ctx);if(validationCache.size>3)validationCache.delete(validationCache.keys().next().value);}return ctx;}
function normalize(raw,full){
 if(raw===undefined)return initial();const bad=()=>{throw Error('Barricades : registre ou ouverture incohérente.');};
 if(!raw||Array.isArray(raw)||raw.version!==1||Object.keys(raw).some(k=>!['version','records'].includes(k))||!Array.isArray(raw.records)||raw.records.length>rules().maxRecords)bad();
 const ids=new Set(),ctx=full&&raw.records.length?validationGeometry(full):null;
 const records=raw.records.map(r=>{if(!r||Array.isArray(r)||Object.keys(r).some(k=>!['target','type','hp'].includes(k))||typeof r.target!=='string'||r.target.length>180||!Object.hasOwn(rules().types,r.type)||!Number.isFinite(r.hp)||r.hp<=0||r.hp>rules().types[r.type].health||ids.has(r.target)||!/^local:|^region:/.test(r.target))bad();ids.add(r.target);if(ctx){if(r.target.startsWith('local:')&&full.exploration125?.generation!==4&&full.frontier?.generation<4)bad();if(r.target.startsWith('region:')&&!ctx.world)ctx.world=ctx.create();if(!resolveFrom(ctx.world,ctx.plan,r.target))bad();}return{target:r.target,type:r.type,hp:r.hp};});
 return{version:1,records};
}
function install(g){
 if(g.barricades134)return g.barricades134;if(!g.expansions)throw Error('Registre des opérations absent.');
 let attackClock=0,attackAfter=new Map();
 let state=initial(),job=null,selected=null,message='',resolved=[],bins=new Map(),worldBound=null,regionBound=null,geometryKey='',targetCache=new Map();
 const wrap=(name,fn)=>{const old=g[name]?.bind(g);if(old)g[name]=(...a)=>fn(old,...a);};
 const oldLOS=g.hostileLineClear.bind(g);
 const running=()=>g.state==='playing'&&!g.paused&&!g.activeOverlay&&!g.gameOver;
 const position=()=>{const p=g.frontier?.position?.();return p?.active?{...p,domain:'region'}:{domain:'local',x:g.player.x,y:g.player.y,z:0,inside:null};};
 const same=(t,p)=>t.domain===p.domain&&t.z===p.z&&(p.z===0||t.inside===p.inside);
 const record=id=>state.records.find(r=>r.target===id);
 function resolve(id){if(id.startsWith('local:')&&g.exploration125?.generation!==4)return null;if(targetCache.has(id))return targetCache.get(id);const t=resolveFrom(id.startsWith('region:')?g.frontier.world():null,g.exploration125?.plan,id);targetCache.set(id,t);return t;}
 function rebuild(){resolved=state.records.map(r=>({r,t:resolve(r.target)})).filter(v=>v.t);bins=new Map();for(const pair of resolved){const t=pair.t,s=scale(t),range=t.width/2+rules().thickness*s,size=s*8;for(let y=Math.floor((t.y-range)/size);y<=Math.floor((t.y+range)/size);y++)for(let x=Math.floor((t.x-range)/size);x<=Math.floor((t.x+range)/size);x++){const key=t.domain+':'+t.z+':'+x+':'+y;if(!bins.has(key))bins.set(key,[]);bins.get(key).push(pair);}}if(g.world){g.world.navigationVersion++;g.world.flowDirty=true;}g.flowTimer=0;}
 function query(domain,z,x,y,r=0){const size=(domain==='local'?32:1)*8,set=new Set();for(let gy=Math.floor((y-r)/size);gy<=Math.floor((y+r)/size);gy++)for(let gx=Math.floor((x-r)/size);gx<=Math.floor((x+r)/size);gx++)for(const pair of bins.get(domain+':'+z+':'+gx+':'+gy)||[])set.add(pair);return[...set];}
 function collision(domain,x,y,r=0,z=0,inside=null,ignore=null){return query(domain,z,x,y,r).some(({r:row,t})=>row.hp>0&&t.id!==ignore&&(z===0||t.inside===inside)&&hitCircle(t,x,y,r));}
 function lineClear(domain,a,b,z=0,inside=null,ignore=null,pad=0){return !query(domain,z,(a.x+b.x)/2,(a.y+b.y)/2,Math.hypot(b.x-a.x,b.y-a.y)/2+pad).some(({r,t})=>r.hp>0&&t.id!==ignore&&(z===0||t.inside===inside)&&hitLine(t,a,b,pad));}
 function firstObstruction(a,b,pad=0){let hit=null;for(const {t}of query('local',0,(a.x+b.x)/2,(a.y+b.y)/2,Math.hypot(b.x-a.x,b.y-a.y)/2+pad)){const u=localPoint(t,a),v=localPoint(t,b),h=rules().thickness*32/2;let lo=0,hi=1,valid=true;for(const [origin,delta,min,max]of[[u.x,v.x-u.x,-t.width/2-pad,t.width/2+pad],[u.y,v.y-u.y,-h-pad,h+pad]]){if(Math.abs(delta)<1e-10){if(origin<min||origin>max){valid=false;break;}}else{const q=(min-origin)/delta,r=(max-origin)/delta;lo=Math.max(lo,Math.min(q,r));hi=Math.min(hi,Math.max(q,r));if(lo>hi){valid=false;break;}}}if(valid&&(!hit||lo<hit.fraction))hit={fraction:lo,x:a.x+(b.x-a.x)*lo,y:a.y+(b.y-a.y)*lo,barricade:t.id,target:t};}return hit;}
 function hitProjectile(domain,x,y,amount,z=0,inside=null){const pair=query(domain,z,x,y,.02*scale({domain})).find(({t})=>(z===0||t.inside===inside)&&hitCircle(t,x,y,.015*scale(t)));return pair?damage(pair.t.id,amount):false;}
 function bind(){
  const key=g.world?.seed+':'+g.exploration125?.layoutRevision+':'+g.frontier?.position?.().generation;if(key!==geometryKey){geometryKey=key;targetCache.clear();rebuild();}
  if(g.world&&worldBound!==g.world){worldBound=g.world;const solid=g.world.solidForFriendly.bind(g.world),cost=g.world.movementCost.bind(g.world);g.world.solidForFriendly=(x,y)=>solid(x,y)||collision('local',x,y,1);g.world.movementCost=(...a)=>{const v=cost(...a),x=a[0]*C.TILE+C.TILE/2,y=a[1]*C.TILE+C.TILE/2;return collision('local',x,y,C.TILE*.55)?Math.max(v,400):v;};}
  const lost=resolved.filter(({t})=>t.domain==='region'&&g.worldEvolution?.structureDestroyed?.(t.inside)).map(({r})=>r.target);if(lost.length){state.records=state.records.filter(r=>!lost.includes(r.target));if(job&&lost.includes(job.id))cancel('Le support de la barricade est détruit.');rebuild();}
  // Do not materialize the distant world just to open the local operations panel.
  if(g.frontier?.active?.()||state.records.some(r=>r.target.startsWith('region:'))){const w=g.frontier.world();if(regionBound!==w){regionBound=w;const blocked=w.blocked.bind(w),line=w.line.bind(w),vehicle=w.vehicleClear.bind(w);w.blocked=(x,y,r=.32,z=0,inside=null,ignore=null)=>blocked(x,y,r,z,inside,ignore)||collision('region',x,y,r,z,inside,ignore);w.line=(a,b,z=0,inside=null,ignore=null,r=.05)=>line(a,b,z,inside,ignore,r)&&lineClear('region',a,b,z,inside,ignore,r);w.vehicleClear=(x,y,a,ww=4.8,h=2.03)=>vehicle(x,y,a,ww,h)&&!query('region',0,x,y,Math.hypot(ww,h)/2).some(({t})=>G.obb({x,y,a,w:ww,h},{x:t.x,y:t.y,a:t.angle,w:t.width,h:rules().thickness}));}}
 }
 function nearby(radius=5){bind();const p=position();let ts;if(p.domain==='local')ts=g.exploration125?.generation===4?localTargets(g.exploration125?.plan):[];else{const w=g.frontier.world();ts=w.nearPOI(p.x,p.y,radius+8).filter(v=>!g.worldEvolution?.structureDestroyed?.(v.id)&&(p.z===0||v.id===p.inside)).flatMap(v=>regionTargets(w,v,p.z));}return ts.filter(t=>same(t,p)&&Math.hypot(t.x-p.x,t.y-p.y)<=radius*scale(t)+t.width/2).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y));}
 function current(){const ts=nearby();return ts.find(t=>t.id===selected)||ts[0]||null;}
 function pointOnFace(t,p=position()){const q=localPoint(t,p),s=scale(t),x=Math.max(-t.width/2+.04*s,Math.min(t.width/2-.04*s,q.x)),y=(q.y<0?-1:1)*(rules().thickness/2+.07)*s,c=Math.cos(t.angle),sn=Math.sin(t.angle);return{x:t.x+x*c-y*sn,y:t.y+x*sn+y*c};}
 function reachable(t){const p=position();if(!t||!same(t,p))return false;const q=pointOnFace(t,p);if(Math.hypot(p.x-q.x,p.y-q.y)>rules().reach*scale(t))return false;return t.domain==='local'?oldLOS(p,q,false)&&lineClear('local',p,q,0,null,t.id):g.frontier.world().line(p,q,p.z,p.inside,t.id,.025);}
 function actors(p){return p.domain==='local'?[g.player,...g.units,...g.zombies,g.expeditions?.entity?.(),...(g.territories?.truckEntities?.()||[])].filter(live).filter(e=>e!==g.player||!g.player.regionAbsent):[...g.frontier.contacts(),...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[]),...(g.worldEvolution?.overview?.().companions||[]).filter(c=>Number.isFinite(c.x)&&Number.isFinite(c.y)&&!c.riding).map(c=>({...c,hp:c.health||1,radius:.32})),...(live(g.player)?[{...position(),hp:g.player.health,radius:.32}]:[])].filter(live).filter(e=>(e.z||0)===p.z);}
 function occupied(t){if(actors(t).some(e=>hitCircle(t,e.x,e.y,(e.radius||.32*scale(t))+.04*scale(t))))return true;if(t.domain==='local')return false;const car=g.frontier.position().car;if(!car||t.z!==0)return false;const profile=g.worldEvolution?.vehicleProfile?.()||{w:4.8,h:2.03},s=scale(t);return G.obb({x:car.x,y:car.y,a:car.a||0,w:profile.w*s,h:profile.h*s},{x:t.x,y:t.y,a:t.angle,w:t.width,h:rules().thickness*s});}
 function safe(t){const p=position(),enemies=t.domain==='local'?g.zombies:[...g.frontier.contacts(),...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[])];return !enemies.some(e=>live(e)&&(e.z||0)===p.z&&Math.hypot(e.x-p.x,e.y-p.y)<rules().safeRadius*scale(t));}
 function able(){return g.expansions.canAct()&&!g.expeditions?.driving?.()&&!g.frontier?.position?.().car?.driving&&!g.interventions134?.busy?.()&&g.player.reload<=0&&!g.selectedBuild&&!g.fieldcraft?.context?.().mounted;}
 const fail=reason=>{message=reason;return{ok:false,reason};};
 function eligibility(kind,id,type,continuing=false){const t=id?resolve(id):current(),r=t&&record(t.id);if(!able())return{ok:false,reason:'Rejoignez une ouverture à pied, hors poste de tir, rechargement ou placement, le sac accessible.'};if(!continuing&&(job||g.expansions.busy('barricades134')))return{ok:false,reason:'Terminez ou annulez le travail en cours.'};if(!t||t.domain==='region'&&g.worldEvolution?.structureDestroyed?.(t.inside)||!reachable(t))return{ok:false,reason:'Approchez d’une porte, fenêtre brisée ou ouverture accessible.'};if(kind!=='dismantle'&&!safe(t))return{ok:false,reason:'Écartez les infectés avant de travailler.'};
  if(kind==='build'){const d=rules().types[type];if(!d)return{ok:false,reason:'Matériau inconnu.'};if(r)return{ok:false,reason:'Démontez la barricade existante avant de changer de matériau.'};if(state.records.length>=rules().maxRecords)return{ok:false,reason:'Limite de barricades atteinte ; démontez un ancien poste.'};if(occupied(t))return{ok:false,reason:'Dégagez l’ouverture : une personne ou un véhicule occupe le passage.'};if(!C.canAfford(g.player.carry,d.cost))return{ok:false,reason:'À porter dans le sac : '+C.resourceText(d.cost)+'.'};return{ok:true,t,r,cost:d.cost,seconds:d.seconds};}
  if(!r)return{ok:false,reason:'Aucune barricade sur cette ouverture.'};if(kind==='repair'){if(r.hp>=rules().types[r.type].health)return{ok:false,reason:'Cette barricade est intacte.'};if(!C.canAfford(g.player.carry,rules().repairCost))return{ok:false,reason:'À porter dans le sac : '+C.resourceText(rules().repairCost)+'.'};return{ok:true,t,r,cost:rules().repairCost,seconds:rules().repairSeconds};}if(kind==='dismantle')return{ok:true,t,r,cost:{},seconds:rules().dismantleSeconds};return{ok:false,reason:'Action inconnue.'};
 }
 function begin(kind,id,type){bind();const q=eligibility(kind,id,type);if(!q.ok)return fail(q.reason);job={kind,id:q.t.id,type,elapsed:0,seconds:q.seconds/(g.arsenal134?.toolFactor?.(kind==='dismantle'?'dismantle':'barricade')||1),start:position(),health:g.player.health};message=kind==='dismantle'?'Démontage en cours. Accessible des deux côtés, sans outil.':'Travail en cours : restez sur place.';g.releaseInputs?.();return{ok:true};}
 function cancel(reason='Travail interrompu. Aucun matériau n’a été dépensé.'){if(!job)return false;job=null;message=reason;return true;}
 function interruptForLoot(){return job&&g.input.keys?.has('KeyE')?cancel('Travail interrompu : fouille demandée. Aucun matériau n’a été dépensé.'):false;}
 function damage(id,amount){const r=record(id);if(!r||!Number.isFinite(amount)||amount<=0)return false;r.hp=Math.max(0,r.hp-amount);if(r.hp===0){state.records=state.records.filter(v=>v!==r);rebuild();if(job?.id===id)cancel('La barricade a cédé.');g.notify?.('Barricade rompue : l’ouverture est libre.','danger');}return true;}
 function finish(t,q){
  if(t.kind==='build'){C.spend(g.player.carry,q.cost);state.records.push({target:t.id,type:t.type,hp:rules().types[t.type].health});message='Ouverture barricadée. Les deux faces bloquent les pas et les tirs.';}
  else if(t.kind==='repair'){C.spend(g.player.carry,q.cost);q.r.hp=Math.min(rules().types[q.r.type].health,q.r.hp+rules().repairHP);message='Réparation terminée.';}
  else{const d=rules().types[q.r.type],ratio=q.r.hp/d.health;let room=Math.max(0,g.player.carryCapacity-C.bagTotal(g.player.carry));for(const [k,v]of Object.entries(d.cost)){const n=Math.min(room,Math.floor(v*rules().refundFactor*ratio));g.player.carry[k]=(g.player.carry[k]||0)+n;room-=n;}state.records=state.records.filter(v=>v!==q.r);message='Passage dégagé. Matériaux usés récupérés dans la limite du sac.';}
  g.arsenal134?.wearTool?.(t.kind==='dismantle'?'dismantle':'barricade',t.seconds);job=null;rebuild();g.audio.build?.();g.save(false);
 }
 function step(dt){if(!running()||!Number.isFinite(dt)||dt<=0||dt>rules().maxStep)return;bind();if(interruptForLoot())return;if(job){const p=position(),t=job,q=eligibility(t.kind,t.id,t.type,true);if(!live(g.player)||!same(t.start,p)||Math.hypot(t.start.x-p.x,t.start.y-p.y)>.35*scale(p)||g.player.health<t.health||g.input.mouseDown||g.input.touchFire||g.player.reload>0||g.selectedBuild||!q.ok||g.expansions.busy('barricades134')){cancel(q.reason||'Travail interrompu : déplacement ou danger.');return;}job.elapsed+=dt;g.player.action='build';if(p.domain==='region')g.frontier.signalWork?.();if(job.elapsed>=job.seconds)finish(t,q);}}
 function pressure(domain,dt){if(!running()||!resolved.length||!Number.isFinite(dt)||dt<=0||dt>rules().maxStep)return;const p=position();if(domain==='region'&&p.domain!=='region')return;if(domain==='region'){attackClock+=dt;for(const [id,until]of attackAfter)if(until<attackClock-10)attackAfter.delete(id);}const enemies=domain==='local'?g.zombies:[...g.frontier.contacts(),...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[])];for(const e of enemies){if(!live(e))continue;const z=domain==='local'?0:(e.z||0),s=domain==='local'?32:1,candidates=query(domain,z,e.x,e.y,rules().pressureReach*s+(e.radius||.32*s)).filter(({t})=>hitCircle(t,e.x,e.y,rules().pressureReach*s+(e.radius||.32*s)));if(!candidates.length)continue;const pair=candidates.sort((a,b)=>Math.hypot(a.t.x-e.x,a.t.y-e.y)-Math.hypot(b.t.x-e.x,b.t.y-e.y))[0],face=pointOnFace(pair.t,e);const clear=domain==='local'?oldLOS(e,face,false):g.frontier.world().line(e,face,z,e.poi||p.inside,pair.t.id,.01);if(!clear)continue;if(domain==='local'){if(e.attackCooldown>0)continue;const def=C.ENEMIES[e.kind];if(!def)continue;e.attackCooldown=1/def.attackRate;damage(pair.t.id,def.damage*(def.structureDamage||1)*g.difficulty.enemyDamage);}else{if(e.cool>0||(attackAfter.get(e.id)||0)>attackClock)continue;e.cool=rules().regionAttackSeconds;if(e.group?.contacts?.[e.index])e.group.contacts[e.index].cool=e.cool;attackAfter.set(e.id,attackClock+rules().regionAttackSeconds);damage(pair.t.id,rules().regionDamage*g.difficulty.enemyDamage);}}}
 function draw(ctx,t,r){
  const s=scale(t),th=rules().thickness*s,elevation=.5*s,c=Math.cos(t.angle),sn=Math.sin(t.angle),corners=[[-t.width/2,-th/2],[t.width/2,-th/2],[t.width/2,th/2],[-t.width/2,th/2]].map(([x,y])=>({x:x*c-y*sn,y:x*sn+y*c}));
  ctx.save();ctx.translate(t.x,t.y);ctx.fillStyle='rgba(0,0,0,.3)';ctx.beginPath();corners.forEach((p,i)=>i?ctx.lineTo(p.x+.08*s,p.y+.15*s):ctx.moveTo(p.x+.08*s,p.y+.15*s));ctx.closePath();ctx.fill();
  // Ground geometry rotates; height always rises toward screen north.
  const sides=corners.map((p,i)=>({a:p,b:corners[(i+1)%4]})).sort((a,b)=>(a.a.y+a.b.y)-(b.a.y+b.b.y));
  for(const {a,b}of sides){ctx.fillStyle=r.type==='sheet'?'#56615b':'#6b5239';ctx.strokeStyle=r.type==='sheet'?'#929d91':'#b1946a';ctx.lineWidth=.035*s;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.lineTo(b.x,b.y-elevation);ctx.lineTo(a.x,a.y-elevation);ctx.closePath();ctx.fill();ctx.stroke();if(Math.hypot(a.x-b.x,a.y-b.y)>th*2){for(let f=.2;f<1;f+=.25){ctx.beginPath();ctx.moveTo(a.x,a.y-elevation*f);ctx.lineTo(b.x,b.y-elevation*f);ctx.stroke();}if(r.type==='braced'){ctx.strokeStyle='#afb2a0';ctx.lineWidth=.09*s;ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y-elevation);ctx.stroke();}}}
  ctx.fillStyle=r.type==='sheet'?'#9aa59a':'#b49464';ctx.beginPath();corners.forEach((p,i)=>i?ctx.lineTo(p.x,p.y-elevation):ctx.moveTo(p.x,p.y-elevation));ctx.closePath();ctx.fill();
  if(r.hp<rules().types[r.type].health){const width=Math.max(.8*s,Math.abs(c)*t.width+Math.abs(sn)*th),bottom=Math.abs(sn)*t.width/2+Math.abs(c)*th/2;ctx.fillStyle='#211f19';ctx.fillRect(-width/2,bottom+.13*s,width,.075*s);ctx.fillStyle='#c49d56';ctx.fillRect(-width/2,bottom+.13*s,width*r.hp/rules().types[r.type].health,.075*s);}ctx.restore();
 }
 function depthEntries(domain,v,view){return resolved.filter(({t})=>t.domain===domain&&(domain==='local'||t.z===v.z&&(v.z===0||t.inside===v.inside))).filter(({t})=>!view||t.x+t.width/2>=(view.left??view.l)&&t.x-t.width/2<=(view.right??view.r)&&t.y+t.width/2>=(view.top??view.t)&&t.y-t.width/2<=(view.bottom??view.b)).map(({t,r},i)=>({kind:domain==='local'?5:'barricade',id:domain==='local'?134000+i:t.id,depth:t.y+Math.abs(Math.sin(t.angle))*t.width/2+Math.abs(Math.cos(t.angle))*rules().thickness*scale(t)/2,draw:c=>draw(c,t,r)}));}
 function overview(){const t=current(),r=t&&record(t.id);return{task:job?{kind:job.kind,progress:Math.min(1,job.elapsed/job.seconds)}:null,summary:message||'Renforcez les ouvertures réelles avec les matériaux de votre sac. Une barricade ferme le passage aux survivants, aux infectés et aux tirs. Démontable depuis les deux côtés.',rows:[{label:'Ouverture',value:t?t.name:'Approchez d’une porte, fenêtre brisée ou portail'},{label:'Matériau',value:r?rules().types[r.type].name:'Passage libre'},{label:'Intégrité',value:r?Math.ceil(r.hp)+' / '+rules().types[r.type].health:'—'},{label:'Travail',value:job?Math.ceil(job.seconds-job.elapsed)+' s restantes':'Aucun'},{label:'Posées',value:state.records.length+' / '+rules().maxRecords}]};}
 function actions(){const t=current(),rows=[];for(const [type,d]of Object.entries(rules().types)){const q=eligibility('build',t?.id,type);rows.push({id:'build-'+type,label:d.name+' · '+d.health+' PV',description:C.resourceText(d.cost)+' dans le sac · '+d.seconds+' s sur place.',disabled:!q.ok,reason:q.reason,run:()=>begin('build',t?.id,type),close:true});}for(const [kind,label]of[['repair','Réparer · +'+rules().repairHP+' PV'],['dismantle','Démonter depuis cette face']]){const q=eligibility(kind,t?.id);rows.push({id:kind,label,description:kind==='repair'?C.resourceText(rules().repairCost)+' dans le sac · '+rules().repairSeconds+' s':'Sans outil · '+rules().dismantleSeconds+' s · récupération partielle selon intégrité et sac.',disabled:!q.ok,reason:q.reason,run:()=>begin(kind,t?.id),close:true});}const ts=nearby();if(ts.length>1)rows.push({id:'next',label:'Autre ouverture proche',run:()=>{selected=ts[(ts.findIndex(v=>v.id===t?.id)+1)%ts.length].id;return{ok:true};}});if(job)rows.push({id:'cancel',label:'Interrompre le travail',run:()=>({ok:cancel()})});return rows;}
 wrap('friendlyPositionClear',(old,e,x,y)=>old(e,x,y)&&!collision('local',x,y,(e.radius||10)*.78));
 wrap('hostilePositionClear',(old,e,x,y)=>old(e,x,y)&&!collision('local',x,y,e.radius||10));
 wrap('hostileLineClear',(old,a,b,...rest)=>old(a,b,...rest)&&lineClear('local',a,b));
 wrap('hasLineOfSight',(old,a,b,...rest)=>old(a,b,...rest)&&lineClear('local',a,b));
 wrap('updateZombies',(old,dt)=>{const before=resolved.some(v=>v.t.domain==='local')?new Map(g.zombies.filter(live).map(z=>[z,{x:z.x,y:z.y}])):null;const result=old(dt);if(before)for(const [z,p]of before)if(!z.dead&&!lineClear('local',p,z,0,null,null,z.radius||10)){z.x=p.x;z.y=p.y;}pressure('local',dt);return result;});

 wrap('depthEntries',(old,v)=>[...old(v),...depthEntries('local',v,v)].sort((a,b)=>a.depth-b.depth));
 wrap('update',(old,dt)=>{bind();if(job&&(!live(g.player)||g.gameOver))cancel();
  // E hands the existing job back to ordinary interaction before it checks busy.
  if(job&&live(g.player)&&running()&&Number.isFinite(dt)&&dt>0&&dt<=rules().maxStep)interruptForLoot();
  const result=old(dt);if(job&&(!live(g.player)||g.gameOver))cancel();step(dt);pressure('region',dt);return result;});
 const api={version:'1.34.0',snapshot:()=>clone(state),targets:nearby,resolve,select:id=>{const t=nearby().find(t=>t.id===id);if(!t)return false;selected=id;return true;},current,overview,actions,eligibility,begin,cancel,busy:()=>!!job,damage,collision,lineClear,firstObstruction,hitProjectile,depthEntries,step,pressure,bind,get job(){return job?clone(job):null;}};g.barricades134=api;
 g.expansions.register({id:'barricades134',title:'Barricades & ouvertures',overview,actions,busy:api.busy,validate:normalize,snapshot:api.snapshot,restore:raw=>{state=normalize(raw);job=null;selected=null;attackAfter.clear();attackClock=0;targetCache.clear();rebuild();bind();},reset:()=>{state=initial();job=null;selected=null;message='';attackAfter.clear();attackClock=0;targetCache.clear();rebuild();}});
 bind();return api;
}
const api={initial,normalize,localTargets,regionTargets,hitCircle,hitLine,install};root.DeadwallBarricades134=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root.DEADWALL&&root.DEADWALL.expansions)install(root.DEADWALL);
})(typeof globalThis!=='undefined'?globalThis:this);
