/* The existing operations modal owns focus, pause and controls; this only adds a physical opening inspection. */
(function(root){
'use strict';
function install(g,doc){if(!g?.barricades134||!g.expansionUI||!doc||g.barricadesUI134)return false;const detail=doc.getElementById('expansionDetail');if(!detail)return false;
 const panel=doc.createElement('figure');panel.className='barricade-inspect134';panel.hidden=true;
 panel.innerHTML='<svg viewBox="0 0 280 138" role="img" aria-label="Ouverture et renforts, vue de face"><path class="frame" d="M28 126V16h224v110M51 126V39h178v87"/><path class="aperture" d="M51 40h178v86H51z"/><g class="boards"><path d="m53 59 173-12 2 15L54 76zM53 94l173-9 2 15-174 11z"/><path class="brace" d="m75 117 8 6 110-77-8-6zM77 40l-8 7 124 77 9-8z"/></g><g class="sheet"><path d="M55 44h170v76H55z"/><path d="M69 46v72m22-72v72m22-72v72m22-72v72m22-72v72m22-72v72m22-72v72"/></g><path class="ground" d="M15 128h250"/></svg>';
 const caption=doc.createElement('figcaption'),title=doc.createElement('strong'),hint=doc.createElement('span'),meter=doc.createElement('progress');meter.max=1;meter.setAttribute('aria-label','Intégrité de la barricade');caption.append(title,hint,meter);panel.appendChild(caption);detail.prepend(panel);
 function refresh(){const active=detail.getAttribute('aria-labelledby')==='expansionTab-barricades134'&&g.expansionUI.isOpen();panel.hidden=!active;if(!active)return;const t=g.barricades134.current(),r=t&&g.barricades134.snapshot().records.find(r=>r.target===t.id),d=r&&root.DeadwallCore.BarricadeRules134.types[r.type];panel.dataset.material=r?.type||'open';title.textContent=t?({window:'Fenêtre brisée',gate:'Portail de cour',door:'Porte',opening:'Passage intérieur'}[t.kind]||'Ouverture'):'Inspection des ouvertures';hint.textContent=t?(t.width/(t.domain==='local'?32:1)).toFixed(2)+' m · '+(r?d.name+' · bloque aussi vos tirs':'passage libre'):'Approchez d’une porte, d’une fenêtre brisée ou d’un portail.';meter.hidden=!r;meter.value=r?r.hp/d.health:0;}
 detail.parentNode?.addEventListener('click',refresh);const old=g.updateUI.bind(g);g.updateUI=(...a)=>{const out=old(...a);refresh();return out;};g.barricadesUI134=Object.freeze({refresh,panel});return true;
}
const api={install};root.DeadwallBarricadesUI134=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;else{const mount=()=>install(root.DEADWALL,root.document);if(root.document?.readyState==='loading')root.document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();}
})(typeof globalThis!=='undefined'?globalThis:this);
