(function(root){'use strict';const D=root.DeadwallEssentialContent||(typeof require==='function'?require('./essential-content.js'):null);let R;const keys=['light','aid','brace','decoy'];function configure(r){R=r;}const bag=()=>Object.fromEntries(keys.map(k=>[k,0]));function initial(){return{version:1,jobs:{},stock:bag(),belt:bag(),effects:[],serial:1};}
function normalize(raw,data){if(raw===undefined)return initial();if(!raw||raw.version!==1||!raw.jobs||typeof raw.jobs!=='object'||Array.isArray(raw.jobs)||Object.keys(raw.jobs).length>12)throw Error('Registre de services invalide.');const s=initial(),num=(n,a,b,i=false)=>{if(!Number.isFinite(n)||n<a||n>b||i&&!Number.isInteger(n))throw Error('Valeur de service invalide.');return n;};let player=0,car=0;
const W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),regionSize=W.sizeForGeneration(data?.frontier?.generation??5);
function point(p){if(!p||!['local','region'].includes(p.domain))throw Error('Position absente.');const q={domain:p.domain,x:num(p.x,0,p.domain==='region'?regionSize:4096),y:num(p.y,0,p.domain==='region'?regionSize:4096),z:num(p.z,-1,2,true),inside:p.inside??null};if(q.inside!==null&&!/^P\d{4}$/.test(q.inside)||q.domain==='local'&&q.z!==0)throw Error('Niveau invalide.');return q;}
for(const[id,j]of Object.entries(raw.jobs)){if(!Object.hasOwn(D.byId,id)||!j||!['surveyed','player','car','ground','delivered'].includes(j.stage))throw Error('Mission inconnue.');const o={stage:j.stage};if(j.stage==='player')player++;if(j.stage==='car'){car++;o.carId=num(j.carId,1,2147483646,true);}if(j.stage==='ground')o.point=point(j.point);s.jobs[id]=o;}if(player>1||car>1)throw Error('Porte-module surchargé.');
for(const name of ['stock','belt']){const b=raw[name];if(!b||typeof b!=='object'||Array.isArray(b)||Object.keys(b).length!==4||Object.keys(b).some(k=>!keys.includes(k)))throw Error('Kits invalides.');for(const k of keys)s[name][k]=num(b[k],0,name==='stock'?R.stockMax:R.beltMax,true);}if(Object.values(s.belt).reduce((a,b)=>a+b,0)>R.beltMax)throw Error('Ceinture pleine.');
if(!Array.isArray(raw.effects)||raw.effects.length>R.maxEffects)throw Error('Trop de dispositifs.');s.serial=num(raw.serial,1,1e9,true);const seen=new Set();for(const e of raw.effects){if(!e||!['light','decoy'].includes(e.kind))throw Error('Dispositif invalide.');const id=num(e.id,1,s.serial-1,true),p=point(e);if(seen.has(id)||e.kind==='decoy'&&p.domain!=='region')throw Error('Dispositif dupliqué ou hors région.');seen.add(id);s.effects.push({...p,id,kind:e.kind,left:num(e.left,0,R.kits[e.kind].duration),pulse:num(e.pulse,0,1)});}return s;}
function targets(w){const P=root.DeadwallAtlasProjection||(typeof require==='function'?require('./atlas-projection.js'):null),anchor=P.home(w),G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),used=new Set(),out=[];for(const j of D.jobs){let found;for(const type of j.types){const pool=w.pois.filter(p=>p.type===type&&!used.has(p.id)).sort((a,b)=>Math.hypot(a.x-anchor.x,a.y-anchor.y)-Math.hypot(b.x-anchor.x,b.y-anchor.y)||a.id.localeCompare(b.id));for(const p of pool){const o=j.kinds.map(k=>w.plan(p,0).objects.find(o=>o.kind===k)).find(Boolean)||w.plan(p,0).objects[0];if(o){found={...j,poi:p.id,place:p.name,z:0,objectId:o.id,object:o,...G.global(p,o.x+o.w/2,o.y+o.h/2)};break;}}if(found)break;}if(found){used.add(found.poi);out.push(found);}}return out;}
const cache=new Map();function validate(raw,data){const s=normalize(raw,data);if(!Object.keys(s.jobs).length&&!s.effects.length&&!keys.some(k=>s.belt[k]||s.stock[k]))return s;const W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),key=data.worldSeed+':'+data.frontier.generation;let w=cache.get(key);if(!w){w=W.create(data.worldSeed,data.frontier.generation);cache.set(key,w);if(cache.size>3)cache.delete(cache.keys().next().value);}const ts=targets(w);for(const[id,j]of Object.entries(s.jobs)){const t=ts.find(t=>t.id===id);if(!t||!data.frontier.seen.includes(t.poi))throw Error('Mission non découverte.');if(j.stage==='car'&&j.carId!==data.expeditions?.vehicle?.id)throw Error('Colis dans un véhicule étranger.');}
const points=[...s.effects,...Object.values(s.jobs).filter(j=>j.stage==='ground').map(j=>j.point)];for(const e of points)if(e.domain==='region'&&e.z!==0){const p=w.pois.find(p=>p.id===e.inside);if(!p||!p.levels.includes(e.z))throw Error('Objet sans étage.');const G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),q=G.local(p,e.x,e.y);if(q.x<0||q.y<0||q.x>p.w||q.y>p.h)throw Error('Objet hors bâtiment.');}
for(const k of keys)if((s.stock[k]||s.belt[k]||s.effects.some(e=>e.kind===k))&&!D.jobs.some(j=>j.family===k&&s.jobs[j.id]?.stage==='delivered'))throw Error('Recette non récupérée.');return s;}
const api={configure,get RULES(){return R;},keys,initial,normalize,validate,targets,content:D};root.DeadwallEssentialState=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(globalThis);
