/* Technical recoveries connect a physical place, return cargo, and night preparations. */
(function(root){'use strict';function install(g){if(g.essentials)return;const C=root.DeadwallCore,S=C.Essentials,R=S.RULES,G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),Survey=root.DeadwallFrontierSurvey||(typeof require==='function'?require('./frontier-survey.js'):null);let state=S.initial(),home=g.world,pending=null,world=null,sites=[],task=null,message='';const wrap=(n,fn)=>{const old=g[n].bind(g);g[n]=(...a)=>fn(old,...a);};
function ensure(){if(home!==g.world){home=g.world;state=S.normalize(pending||undefined);pending=null;world=null;sites=[];task=null;message='';}return state;}
function view(){ensure();return g.frontier.overview();}function targets(){const w=g.frontier.world();if(w!==world){world=w;sites=S.targets(w);}return sites;}
const can=()=>g.state==='playing'&&!g.gameOver&&!g.player.dead&&g.player.health>0&&g.canIssueCommand();const fail=t=>{message=t;return{ok:false,reason:t};};const pack=where=>Object.entries(state.jobs).find(([,s])=>s.stage===where);const unlocked=k=>S.content.jobs.some(j=>j.family===k&&state.jobs[j.id]?.stage==='delivered');
const atHome=()=>!g.frontier.active()&&g.core()&&g.workerCanWorkAt(g.player,g.core(),100);const carNear=()=>g.frontier.active()?g.frontier.vehiclePresent():g.expeditions.overview().nearCar;
function handlingReason(){if(!can())return 'Le commandant doit être disponible.';if(g.expeditions.driving()||g.frontier.position().car?.driving)return 'Descendez du véhicule avant de manipuler le matériel.';if(g.player.reload>0)return 'Terminez la recharge avant de manipuler le matériel.';if(g.fieldcraft?.context?.().mounted)return 'Libérez le poste manuel avant de manipuler le matériel.';if(task||g.fieldSupplies?.busy()||g.expansions?.busy('essentials'))return 'Terminez le travail en cours avant de manipuler le matériel.';return '';}
const otherLoad=()=>g.explorationPack?.carrying?.()||g.campaignPack?.carrying?.();
function position(){const f=g.frontier.position();return f.active?{domain:'region',x:f.x,y:f.y,z:f.z,inside:f.inside}:{domain:'local',x:g.player.x,y:g.player.y,z:0,inside:null};}
function safe(f){return ![...f.enemies,...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[])].some(e=>e.hp>0&&e.z===f.z&&(e.z===0||e.poi===f.inside)&&Math.hypot(e.x-f.x,e.y-f.y)<R.danger&&g.frontier.visibleEnemy(e));}
function reachable(id){if(!g.frontier.active())return false;const f=view(),t=targets().find(t=>t.id===id);return !!t&&f.active&&!f.car?.driving&&f.z===t.z&&f.seen.includes(t.poi)&&Survey.targets(f.world,f,f.taken,C.Frontier.RULES.lootReach).some(o=>o.id===t.objectId);}
function available(kind,id){const reason=handlingReason();if(reason)return fail(reason);if(g.phase!=='calm')return fail('Cette intervention se prépare pendant le jour.');if(kind==='craft'){if(!S.keys.includes(id)||!unlocked(id))return fail('Rapportez le premier module de cette spécialité.');if(!atHome()||g.expeditions.driving())return fail('Rejoignez le dépôt à pied.');if(state.stock[id]>=R.stockMax)return fail('Réserve de kits pleine.');const cost=R.kits[id].cost;if(!C.canAfford(g.resources,cost))return fail('Matériaux insuffisants au dépôt.');return{ok:true,cost,seconds:R.craftSeconds};}
if(!reachable(id)||g.player.reload>0||!safe(view()))return fail('Approchez le matériel au bon niveau, hors de portée des infectés.');const t=targets().find(t=>t.id===id),stage=state.jobs[id]?.stage;if(kind==='inspect'){if(stage)return fail('Relevé déjà effectué.');return{ok:true,cost:{},seconds:R.inspectSeconds};}if(kind!=='recover'||stage!=='surveyed')return fail('Examinez ce matériel avant de le déposer.');if(pack('player')||otherLoad())return fail('Le porte-module du commandant est occupé.');const cost=R.workCost[t.family];if(!C.canAfford(g.player.carry,cost))return fail('Outils consommables requis dans le sac.');return{ok:true,cost,seconds:R.workSeconds[t.family]};}
function preview(kind,id){ensure();const before=message,q=available(kind,id);message=before;return q;}
function begin(kind,id){ensure();const q=available(kind,id);if(!q.ok)return q;task={kind,id,...q,elapsed:0,position:position(),health:g.player.health,pulse:0};message=kind==='inspect'?'Relevé en cours…':kind==='recover'?'Dépose du module…':'Assemblage au dépôt…';g.releaseInputs();if(g.activeOverlay===g.ui.commandModal)g.showCommand(false);return{ok:true};}
function cancel(){if(!task)return false;task=null;message='Intervention interrompue. Aucun matériau dépensé.';return true;}
function tickTask(dt){if(!task)return;const t=task,p=position(),busy=task;task=null;const q=available(t.kind,t.id);task=busy;if(!q.ok||p.domain!==t.position.domain||p.z!==t.position.z||Math.hypot(p.x-t.position.x,p.y-t.position.y)>.06||g.player.health<t.health){cancel();return;}t.elapsed+=dt;t.pulse-=dt;if(t.kind==='recover'&&t.pulse<=0){g.frontier.signalWork();t.pulse=1;}if(t.elapsed+1e-7<t.seconds)return;C.spend(t.kind==='craft'?g.resources:g.player.carry,q.cost);if(t.kind==='inspect')state.jobs[t.id]={stage:'surveyed'};if(t.kind==='recover')state.jobs[t.id]={stage:'player'};if(t.kind==='craft')state.stock[t.id]++;message=t.kind==='recover'?'Module arrimé au dos. Rejoignez D-17.':t.kind==='inspect'?'Relevé conservé dans le carnet.':'Kit préparé dans la réserve du dépôt.';task=null;g.audio.ui?.();g.save(false);}
function movePack(direction){ensure();const reason=handlingReason();if(reason)return fail(reason);if(!carNear())return fail('Rejoignez le break et descendez.');const from=direction==='load'?'player':direction==='take'?'car':null,to=from==='player'?'car':'player';if(!from||!pack(from)||pack(to)||to==='player'&&otherLoad())return fail('Porte-module indisponible.');const [id]=pack(from);state.jobs[id]=to==='car'?{stage:to,carId:g.expeditions.car().id}:{stage:to};g.save(false);return{ok:true};}
function deliver(){ensure();const reason=handlingReason();if(reason)return fail(reason);if(!atHome())return fail('Livraison au dépôt de D-17 uniquement.');const candidate=pack('player')||(carNear()?pack('car'):null);if(!candidate)return fail('Aucun module à livrer.');const[id]=candidate,k=S.content.byId[id].family;if(state.stock[k]+R.reward>R.stockMax)return fail('Utilisez d’abord les kits en réserve.');state.jobs[id]={stage:'delivered'};state.stock[k]+=R.reward;message='Module livré : procédé disponible et deux kits de ce lot préparés.';g.save(false);return{ok:true};}
function transferKit(k,direction){ensure();const reason=handlingReason();if(reason)return fail(reason);if(!atHome()||!S.keys.includes(k))return fail('Équipez les kits au dépôt.');const from=direction==='equip'?'stock':direction==='store'?'belt':null,to=from==='stock'?'belt':'stock';if(!from||state[from][k]<1)return fail('Aucun kit disponible.');if(to==='belt'&&Object.values(state.belt).reduce((a,b)=>a+b,0)>=R.beltMax||to==='stock'&&state.stock[k]>=R.stockMax)return fail('Rangement plein.');state[from][k]--;state[to][k]++;g.save(false);return{ok:true};}
function grounded(p,reference){const point={...p};if(point.domain==='local'){for(let i=0;i<24;i++){const x=point.x+Math.cos(i)*((i%3)*16),y=point.y+Math.sin(i)*((i%3)*16);if(g.friendlyPositionClear({radius:13},x,y))return{...point,x,y};}}else{const w=g.frontier.world();for(let i=0;i<36;i++){const x=point.x+Math.cos(i)*((i%6)*.6),y=point.y+Math.sin(i)*((i%6)*.6);if(!w.blocked(x,y,.32,point.z,point.inside))return{...point,x,y};}}return point;}
function dropOnDeath(point=position()){ensure();const held=pack('player'),working=!!task;if(held)state.jobs[held[0]]={stage:'ground',point:grounded(point)};cancel();return !!held||working;}
function takeGround(id){ensure();const reason=handlingReason();if(reason)return fail(reason);const j=state.jobs[id];if(pack('player')||otherLoad()||j?.stage!=='ground')return fail('Colis indisponible.');const p=position(),t=j.point,range=p.domain==='local'?70:2.2;if(p.domain!==t.domain||p.z!==t.z||Math.hypot(p.x-t.x,p.y-t.y)>range)return fail('Approchez du colis.');const f=p.domain==='region'?view():null;if(p.domain==='region'&&(!safe(f)||!f.world.line(p,t,p.z,p.inside,null,.015))||p.domain==='local'&&!(g.nightGear?.localLineClear?g.nightGear.localLineClear(p,t):g.hostileLineClear(p,t,false)))return fail('Accès au colis obstrué.');state.jobs[id]={stage:'player'};g.save(false);return{ok:true};}
function aidTargets(p,d){return(p.domain==='local'?[g.player,...g.units]:[g.player]).filter(u=>!u.dead&&(p.domain!=='local'||!u.regionAbsent)&&u.health>0&&u.health<u.maxHealth&&Math.hypot(u.x-g.player.x,u.y-g.player.y)<=d.radius&&(p.domain!=='local'||u===g.player||(g.nightGear?.localLineClear?g.nightGear.localLineClear(g.player,u):g.hostileLineClear(g.player,u,false)))).sort((a,b)=>a.health/a.maxHealth-b.health/b.maxHealth);}
function braceTarget(d){return[...g.world.buildings.values()].filter(b=>!b.dead&&b.health>0&&b.completed&&b.def.wall&&b.health<b.maxHealth&&g.workerCanWorkAt(g.player,b,d.reach)).sort((a,b)=>Math.hypot(a.x-g.player.x,a.y-g.player.y)-Math.hypot(b.x-g.player.x,b.y-g.player.y))[0];}
function previewUse(k){ensure();const reason=handlingReason();if(reason)return{ok:false,reason};if(!S.keys.includes(k)||state.belt[k]<1)return{ok:false,reason:'Kit porté requis.'};const p=position(),d=R.kits[k];if(k==='aid'&&!aidTargets(p,d).length)return{ok:false,reason:'Personne à soigner à portée.'};if(k==='brace'){if(p.domain!=='local')return{ok:false,reason:'Cet étai est destiné aux défenses de D-17.'};if(!braceTarget(d))return{ok:false,reason:'Rejoignez un mur ou une porte endommagés.'};}if(k==='decoy'&&p.domain!=='region')return{ok:false,reason:'Diversion disponible dans la région, pas sur la horde de D-17.'};if((k==='light'||k==='decoy')&&(state.effects.length>=R.maxEffects||state.serial>=1e9))return{ok:false,reason:'Trop de dispositifs actifs.'};return{ok:true};}
function use(k){ensure();const q=previewUse(k);if(!q.ok)return fail(q.reason);const p=position(),d=R.kits[k];let actual=0;
if(k==='aid'){let budget=d.totalHeal;for(const u of aidTargets(p,d)){const n=Math.min(d.heal,u.maxHealth-u.health,budget);u.health+=n;actual+=n;budget-=n;if(!budget)break;}if(!actual)return fail('Personne à soigner à portée.');}
else if(k==='brace'){const b=braceTarget(d);actual=Math.min(d.repair,b.maxHealth-b.health);b.health+=actual;}
else{if(k==='decoy'&&p.domain!=='region')return fail('Diversion disponible dans la région, pas sur la horde de D-17.');if(state.effects.length>=R.maxEffects||state.serial>=1e9)return fail('Trop de dispositifs actifs.');state.effects.push({...p,id:state.serial++,kind:k,left:d.duration,pulse:0});}
state.belt[k]--;message=d.name+' utilisé'+(actual?' : '+actual.toFixed(0)+' points restaurés.':'.');g.audio.ui?.();g.nightwatch?.invalidate();g.save(false);return{ok:true,amount:actual};}
function lights(domain){ensure();return state.effects.filter(e=>e.kind==='light'&&e.domain===domain&&e.left>0).map(e=>({...e,r:R.kits.light.radius*(domain==='local'?32:1)}));}
function status(){ensure();return{belt:{...state.belt},carrying:pack('player')?.[0]||null,handlingReason:handlingReason(),task:task?{kind:task.kind,id:task.id,progress:task.elapsed/task.seconds}:null};}
function overview(){ensure();const f=view(),all=targets(),known=all.filter(t=>f.seen.includes(t.poi));return{...S.normalize(state),message,handlingReason:handlingReason(),known:known.map(t=>({...t,stage:state.jobs[t.id]?.stage||'available',near:reachable(t.id)})),families:S.keys.map(k=>({id:k,...R.kits[k],unlocked:unlocked(k)})),carrying:pack('player')?.[0]||null,carryingVehicle:pack('car')?.[0]||null,atHome:!!atHome(),nearCar:!!carNear(),task:task?{kind:task.kind,id:task.id,progress:task.elapsed/task.seconds}:null,ground:Object.entries(state.jobs).filter(([,j])=>j.stage==='ground').map(([id,j])=>({id,title:S.content.byId[id].title,...j.point}))};}
function observe(dt){const f=g.frontier.position();for(const e of state.effects){e.left=Math.max(0,e.left-dt);e.pulse=Math.max(0,e.pulse-dt);if(e.kind==='decoy'&&e.domain==='region'&&f.active&&e.z===f.z&&(e.z===0||e.inside===f.inside)&&e.pulse<=0){g.frontier.signalAt(e,R.kits.decoy.radius);e.pulse=1;}}const n=state.effects.length;state.effects=state.effects.filter(e=>e.left>1e-7);if(n!==state.effects.length)g.nightwatch.invalidate();}
function takeBeltForDeath(){ensure();if(!g.player.dead&&g.player.health>0)return Object.fromEntries(Object.keys(state.belt).map(k=>[k,0]));const belt={...state.belt};for(const k of Object.keys(state.belt))state.belt[k]=0;cancel();return belt;}
function recoverBelt(belt){ensure();const moved=Object.fromEntries(Object.keys(state.belt).map(k=>[k,0]));if(!can()||!belt||Object.keys(belt).length!==4||Object.keys(belt).some(k=>!Object.hasOwn(state.belt,k)||!Number.isInteger(belt[k])||belt[k]<0||belt[k]>R.beltMax))return moved;let room=Math.max(0,R.beltMax-Object.values(state.belt).reduce((a,b)=>a+b,0)-(g.nightGear?.beltCount()||0));for(const k of Object.keys(state.belt)){const n=unlocked(k)?Math.min(room,belt[k]):0;state.belt[k]+=n;moved[k]=n;room-=n;}return moved;}
g.essentials=Object.freeze({takeBeltForDeath,recoverBelt,begin,preview,previewUse,cancel,movePack,deliver,transferKit,takeGround,use,overview,status,dropOnDeath,lights,busy:()=>!!task,carrying:()=>{ensure();return !!pack('player');},snapshot:()=>{ensure();return S.normalize(state);},targets});
const interrupts=['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyZ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyF','KeyE','KeyR','PageUp','PageDown'];
wrap('update',(old,dt)=>{ensure();const running=g.state==='playing'&&!g.paused&&!g.activeOverlay&&!g.gameOver,prev=running?position():null,pc=running?g.frontier.position().car:null,lc=running?g.expeditions.car():null;
if(running&&(g.player.dead||g.player.health<=0))dropOnDeath(prev);
if(running&&task&&(interrupts.some(k=>g.input.keys.has(k)||g.input.pressed.has(k))||g.input.mouseDown||g.input.touchFire))cancel();const r=old(dt);if(running&&!g.gameOver&&Number.isFinite(dt)&&dt>0){const n=Math.min(.1,dt);if(g.player.dead||g.player.health<=0)dropOnDeath(prev);const held=pack('car');if(held&&(!g.expeditions.car()||g.expeditions.car().health<=0||g.expeditions.car().id!==held[1].carId)){state.jobs[held[0]]={stage:'ground',point:grounded(pc?{domain:'region',x:pc.x,y:pc.y,z:0,inside:null}:{domain:'local',x:lc?.x||g.player.x,y:lc?.y||g.player.y,z:0,inside:null})};}observe(n);tickTask(n);}return r;});
wrap('serialize',(old,...a)=>{ensure();return{...old(...a),essentials:S.normalize(state)};});
wrap('restoreSave',(old,raw)=>{const record=S.validate(raw?.version>=19&&raw.version<=C.SAVE_VERSION?raw.essentials:undefined,raw);pending=record;try{const r=old(raw);ensure();return r;}catch(e){pending=null;throw e;}});
wrap('startNew',(old,...a)=>{const before=g.world,r=old(...a);if(g.world!==before){pending=null;ensure();state=S.initial();task=null;}return r;});wrap('returnToMenu',(old,...a)=>{cancel();return old(...a);});wrap('depthEntries',(old,view)=>{const entries=old(view);if(g.frontier.active()&&!view?.homeProjection)return entries;for(const item of root.DeadwallEssentialArt?.depthEntries?.(g,'local',null,view)||[])entries.push({kind:1,id:-122000,depth:item.depth,order:entries.length,entity:{id:-122000,x:item.x,y:item.y,__essentialDraw:item.draw}});entries.sort((a,b)=>a.depth-b.depth||a.kind-b.kind||a.id-b.id||a.order-b.order);return entries;});
wrap('drawBuilding',(old,ctx,b,...a)=>b.__essentialDraw?b.__essentialDraw(ctx):old(ctx,b,...a));
wrap('drawPlayer',(old,ctx,...a)=>{const r=old(ctx,...a);if(!g.frontier.active()&&!g.player.dead&&!g.expeditions.driving())root.DeadwallEssentialArt?.carried(ctx,g,g.player.x,g.player.y,32);return r;});return g.essentials;}
const api={install};root.DeadwallEssentialOps=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(globalThis);
