(function(root){'use strict';const rows=[
['light-grid','La lampe du dernier quart','light',['generatorRoom','garage','warehouse'],['machine','workbench','shelf'],'Émile, électricien','Le coffret est resté sur le plan de travail. Le groupe est arrêté ; le ballast portable peut encore servir.','Conditionner le ballast.','Une lampe donne le temps de réparer le réseau ; elle ne le remplace pas.'],
['light-exit','Les sorties balisées','light',['school','library','townhall'],['desk','wardrobe','shelf'],'Mina, responsable des locaux','Les occupants sont partis avec les plans. Les balises attendent près des outils. Une sortie indiquée ne signifie pas que la rue est sûre.','Déposer les balises.','Garder un chemin lisible derrière la dernière porte.'],
['light-stores','La réserve des ampoules','light',['hardware','market','mall'],['shelf','crate','desk'],'Louis, magasinier','Les lampes de poche ont disparu. Les lourds boîtiers restent. Il faut les trier avant le transport.','Trier les boîtiers.','Les projecteurs consommeront toujours de l’énergie.'],
['aid-clean','Le plateau propre','aid',['dental','clinic'],['medical','sterilizer','shelf','desk'],'Nora, soignante','Le personnel séparait le matériel utilisé du matériel préparé. La fiche ne promet aucun remède contre la contamination.','Conditionner les plateaux.','La relève a besoin de matériel propre et de médicaments réels.'],
['aid-shift','La relève des soigneurs','aid',['veterinary','clinic','hotel'],['medical','wardrobe','desk'],'Ada, assistante','Les cages sont vides. Les propriétaires sont partis avant la fermeture. Les boîtes du personnel sont restées.','Trier le nécessaire.','Récupérer du matériel ne signifie pas avoir retrouvé les disparus.'],
['aid-shelter','Le casier des nuits longues','aid',['bunker','firestation','hotel'],['wardrobe','crate','shelf'],'Samir, veilleur','La liste mentionne couvertures et tours de garde. Sa dernière ligne : vérifier les personnes avant le registre.','Déposer le casier.','Ceux qui tiennent la porte ont aussi besoin de soins.'],
['brace-timber','Les bastaings secs','brace',['sawmill','warehouse'],['logs','workbench','crate'],'Jeanne, cheffe de chantier','Les bois humides sont écartés. Les ferrures et les cales sont conservées sous couverture.','Assembler la valise de ferrures.','Un étai donne du temps ; il ne change pas la résistance maximale.'],
['brace-joinery','Le gabarit de réparation','brace',['joinery','hardware','house'],['workbench','clamps','shelf','desk'],'Paul, menuisier','Les dimensions de la porte ont été reprises plusieurs fois. Le gabarit permettait de réparer sans démonter toute la fermeture.','Récupérer les attaches.','Préparer les outils avant la nuit.'],
['brace-freight','L’atelier du quai','brace',['freight','warehouse','garage'],['workbench','shelf','crate'],'Rosa, manutentionnaire','Les sangles déchirées sont au sol. Les tendeurs intacts sont rangés à part.','Déposer les tendeurs.','Chaque réparation demande des matériaux.'],
['decoy-alarm','La sirène muette','decoy',['firestation','garage'],['machine','workbench','desk'],'Luc, mécanicien','La sirène a été débranchée pour éloigner les infectés. Le petit boîtier autonome reste utilisable.','Récupérer le boîtier.','Un bruit détourne une recherche, pas forcément un poursuivant.'],
['decoy-post','Le dernier appel','decoy',['postoffice','townhall','school'],['desk','shelf','crate'],'Iris, agente du tri','Le standard est coupé. Le boîtier d’annonce n’a pas besoin de la ligne. Son carton interdit les essais près des dortoirs.','Déposer le module.','Une diversion brève n’est pas une protection.'],
['decoy-road','La ligne des poids lourds','decoy',['garage','fuel','warehouse'],['machine','workbench','fuel','shelf'],'Malik, dépanneur','Un avertisseur démontable permettait de signaler un véhicule sans démarrer le moteur.','Isoler l’avertisseur.','Le tester au mauvais endroit attire le problème vers soi.']
];const jobs=rows.map(([id,title,family,types,kinds,author,note,work,epilogue])=>({id,title,family,types,kinds,author,note,work,epilogue}));const api={jobs,byId:Object.fromEntries(jobs.map(j=>[j.id,j]))};root.DeadwallEssentialContent=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;})(globalThis);
