/* Physical daytime expeditions in the DEADWALL game. */
(function(root){'use strict';const C=typeof module!=='undefined'&&module.exports?require('./core.js'):root.DeadwallCore,E=C.Expeditions,R=E.RULES;
 const live=e=>e&&!e.dead&&e.health>0,dist=(a,b)=>a&&b?Math.hypot(a.x-b.x,a.y-b.y):Infinity;
 function install(g){if(g.expeditions)return g.expeditions;
  // UI reconciliation may already replace the live radius during restore. Derive
  // the foot body from the player factory without allocating an entity ID.
  const normalRadius=g.makePlayer(0).radius;let state=E.initial(),world=g.world,pending=null,notice='',speed=0,phase=g.phase;
  const wrap=(n,fn)=>{const old=g[n].bind(g);g[n]=(...a)=>fn(old,...a);};
  const profile=()=>g.worldEvolution?.vehicleProfile()||{name:'Break',speed:R.speed/32,fuel:R.fuelPerUnit*32,tank:R.tank,cargo:R.cargo,w:4.6,h:1.85,health:R.carHealth,cost:R.buildCar};const vehicleRadius=(p=profile())=>Math.max(12,Number((Math.max(p.w,p.h)*(22/4.6)).toFixed(6)));
  function ensure(){if(world!==g.world){world=g.world;state=E.normalize(pending||undefined);pending=null;speed=0;phase=g.phase;notice='';const placement=world.placement.bind(world);world.placement=(def,x,y,rotation=0,ignore=0)=>{const q=placement(def,x,y,rotation,ignore),v=state.vehicle;if(!q.valid||!live(v)||v.regionAway)return q;const w=def.size[rotation%2?1:0]*32,h=def.size[rotation%2?0:1]*32,r=vehicleRadius();return v.x+r>x*32&&v.x-r<x*32+w&&v.y+r>y*32&&v.y-r<y*32+h?{valid:false,reason:'Véhicule à déplacer'}:q;};}return state;}
  function reconcile(){ensure();const a=state.analyst;if(a){const u=g.units.find(u=>u.id===a.id),p=g.world.buildings.get(a.post);if(!live(u))state.analyst=null;else if(!live(p)||!p.completed||g.phase!=='calm'||g.workerOrder==='retreat')a.returning=true;}
   if(state.vehicle?.driving){g.player.radius=vehicleRadius();g.player.x=state.vehicle.x;g.player.y=state.vehicle.y;}
   for(const s of state.sites)if(E.BY_ID[s.id].intel<=state.intel)s.known=true;
  }
  const materialReady=()=>g.player.reload<=0&&!state.vehicle?.driving&&!g.expansions?.busy();
  const command=()=>g.canIssueCommand()&&!g.player.regionAbsent&&live(g.player),running=()=>g.state==='playing'&&!g.gameOver&&!g.paused&&!g.activeOverlay;
  const operational=t=>[...g.world.buildings.values()].filter(b=>live(b)&&b.completed&&b.type===t);
  const home=p=>g.core()&&dist(p,g.core())<=R.homeRange&&g.hostileLineClear(p,g.core());
  const nearCar=()=>live(state.vehicle)&&!state.vehicle.regionAway&&dist(g.player,state.vehicle)<=70&&g.hostileLineClear(g.player,state.vehicle);
  const safe=p=>!g.zombies.some(z=>live(z)&&dist(z,p)<R.danger&&g.hostileLineClear(z,p));
  const report=(text,ok=true)=>{notice=text;return{ok,reason:text};};
  function save(text){if(text)g.notify(text);g.save(false);return report(text||'Ordre enregistré.');}
  function isAssigned(id){ensure();return state.analyst?.id===id;}
  function busy(id){const t=g.territories.snapshot();return isAssigned(id)||t.withdrawing.includes(id)||Object.values(t.sectors).some(s=>s.workerId===id)||g.siege.isAssigned(id)||g.infrastructure.isAssigned(id)||g.citadel.isEscort(id)||g.salvage.isAssigned(id);}
  function assign(){reconcile();const post=operational('expeditionOffice').find(b=>b.powered&&!b.siegeOffline&&!b.territoryOffline),u=g.units.find(u=>live(u)&&u.kind==='worker'&&!busy(u.id));if(!command()||g.phase!=='calm'||g.workerOrder==='retreat'||!post||!post.powered||state.analyst||!u||!C.canAfford(g.resources,R.analystCost))return report('Bureau alimenté, calme, ouvrier libre et deux rations requis.',false);
   C.spend(g.resources,R.analystCost);state.analyst={id:u.id,post:post.id,progress:0,returning:false};u.state=u.carry>0?'return':'move';u.navigation=null;u.targetNode=u.targetBuilding=-1;return save('Ouvrier #'+u.id+' affecté au renseignement. Il rejoint son bureau.');}
  function recall(){ensure();if(!command()||!state.analyst)return false;state.analyst.returning=true;g.save(false);return true;}
  function updateAssignedUnit(u,dt){reconcile();const a=state.analyst;if(!a||a.id!==u.id)return false;if(!running()||!Number.isFinite(dt)||dt<=0)return true;dt=Math.min(dt,R.maxStep);const post=g.world.buildings.get(a.post),core=g.core();if(!core)return true;if(!safe(u)||post&&!safe(post))a.returning=true;
   if(a.returning||u.carry>0){u.state='return';if(u.carry>0){g.depositWorker(u,core,dt);return true;}if(!g.workerCanWorkAt(u,core,70)){g.moveWorkerToJob(u,core,dt,'exp-intel-home');return true;}state.analyst=null;u.state='idle';u.think=0;return true;}
   if(!g.workerCanWorkAt(u,post,90)){u.state='move';g.moveWorkerToJob(u,post,dt,'exp-intel:'+a.post);return true;}u.state='idle';if(g.fieldAtlas?.researchStep(u,post,dt))return true;if(!post.powered||post.siegeOffline||post.territoryOffline||state.intel>=R.maxIntel||g.resources.food<R.researchFood)return true;
   a.progress=Math.min(R.researchSeconds,a.progress+dt);if(a.progress>=R.researchSeconds){g.resources.food-=R.researchFood;state.intel++;a.progress=0;reconcile();g.notify('Renseignement établi : '+state.intel+' dossier(s) exploitable(s).');}return true;
  }
  function carClear(x,y,p=profile()){const rr=vehicleRadius(p);if(g.fieldcraft)return g.friendlyPositionClear({radius:rr/0.9},x,y);if(x<rr+4||y<rr+4||x>C.WORLD_SIZE-rr-4||y>C.WORLD_SIZE-rr-4)return false;for(let i=0;i<8;i++)if(g.world.solidForFriendly(x+Math.cos(i*Math.PI/4)*rr,y+Math.sin(i*Math.PI/4)*rr))return false;return !g.world.solidForFriendly(x,y);}
  function buildCar(){reconcile();const vp=g.worldEvolution?.overview().fleet.selectedProfile||profile(),cost=vp.cost||R.buildCar;if(!command()||g.phase!=='calm'||!home(g.player)||!operational('expeditionGarage').length||live(state.vehicle)||!C.canAfford(g.resources,cost))return report('Garage disponible, présence au centre et coût du véhicule sélectionné requis.',false);
   const core=g.core();let point=null;for(let radius=70;radius<=135&&!point;radius+=20)for(let i=0;i<12;i++){const x=core.x+Math.cos(i*Math.PI/6)*radius,y=core.y+Math.sin(i*Math.PI/6)*radius;if(carClear(x,y,vp)&&!g.units.some(u=>live(u)&&dist(u,{x,y})<Math.max(40,vehicleRadius(vp)+(u.radius||12)))){point={x,y};break;}}
   if(!point)return report('Libérez une aire accessible près du centre.',false);C.spend(g.resources,cost);g.worldEvolution?.activateSelected();state.vehicle={id:g.nextId++,...point,health:vp.health,fuel:0,angle:0,driving:false,cargo:C.makeBag()};state.stats.built++;state.active=null;return save(vp.name+' mis en service. Réservoir et coffre vides.');}
  function board(){reconcile();const v=state.vehicle;if(!command()||!nearCar()||!safe(g.player)&&!v.driving)return report('Rejoignez le break et écartez les menaces immédiates.',false);
   if(v.driving){let point=null;for(let i=0;i<16;i++){const p={x:v.x+Math.cos(i*Math.PI/8)*(vehicleRadius()+normalRadius+8),y:v.y+Math.sin(i*Math.PI/8)*(vehicleRadius()+normalRadius+8)};if(g.friendlyPositionClear({radius:normalRadius},p.x,p.y)&&(g.nightGear?.localLineClear(v,p)??g.hostileLineClear(v,p,false))&&p.x>normalRadius+4&&p.y>normalRadius+4&&p.x<C.WORLD_SIZE-normalRadius-4&&p.y<C.WORLD_SIZE-normalRadius-4){point=p;break;}}
    if(!point)return report('Sortie obstruée : déplacez le véhicule.',false);v.driving=false;g.player.radius=normalRadius;Object.assign(g.player,point);speed=0;return save('À pied. Le break reste à son emplacement.');}
   g.cancelPlacement();g.player.reload=0;g.input.mouseDown=false;g.input.touchFire=false;v.driving=true;g.player.x=v.x;g.player.y=v.y;g.player.radius=vehicleRadius();speed=0;return save('Au volant : déplacements habituels. F pour descendre.');}
  function refuel(){ensure();if(!materialReady())return report('Descendez du véhicule et terminez le rechargement ou l’intervention avant de manipuler le matériel.',false);const v=state.vehicle,p=profile();if(!command()||!nearCar()||p.tank<=0||v.fuel>=p.tank)return report('Break proche et place dans le réservoir requis.',false);let need=p.tank-v.fuel,n=Math.min(need,g.player.carry.fuel);g.player.carry.fuel-=n;v.fuel+=n;need-=n;let c=Math.min(need,v.cargo.fuel);v.cargo.fuel-=c;v.fuel+=c;need-=c;n+=c;if(need>0&&home(v)&&home(g.player)){c=Math.min(need,g.resources.fuel);g.resources.fuel-=c;v.fuel+=c;n+=c;}if(n<=0)return report('Aucun carburant porté. Revenez avec un bidon ou près du dépôt.',false);return save(n.toFixed(1)+' carburant transféré au réservoir.');}
  function transfer(){ensure();if(!materialReady())return report('Descendez du véhicule et terminez le rechargement ou l’intervention avant de manipuler le matériel.',false);const v=state.vehicle,p=profile();if(!command()||!nearCar())return report('Rejoignez le véhicule pour ouvrir le coffre.',false);let room=p.cargo-C.bagTotal(v.cargo),n=0;for(const k of C.RESOURCE_KEYS){const move=Math.min(room,g.player.carry[k]);v.cargo[k]+=move;g.player.carry[k]-=move;room-=move;n+=move;}return n>0?save(n.toFixed(1)+' ressources chargées dans le coffre.'):report('Sac vide ou coffre plein. Aucun matériau perdu.',false);}
  function unload(){ensure();if(!materialReady())return report('Descendez du véhicule et terminez le rechargement ou l’intervention avant de manipuler le matériel.',false);const v=state.vehicle;if(!command()||!nearCar()||!home(v)||!home(g.player))return report('Revenez avec le break près du centre pour décharger.',false);let n=0;for(const k of C.RESOURCE_KEYS){const move=Math.min(v.cargo[k],Math.max(0,g.storage-g.resources[k]));g.resources[k]+=move;v.cargo[k]-=move;n+=move;}g.depositedResources+=n;state.stats.delivered+=n;
   if(C.bagTotal(v.cargo)<=.000001&&state.active){state.active=null;state.stats.returned++;return save('Expédition rentrée. '+n.toFixed(1)+' ressources livrées.');}return save(n.toFixed(1)+' ressources livrées ; le reliquat reste dans le coffre.');}
  function buyFuel(){ensure();if(!command()||g.phase!=='calm'||!home(g.player)||!operational('expeditionOffice').length)return report('Le troc est disponible au centre, le jour, après construction du bureau.',false);if(state.trade.wave!==g.wave)state.trade={wave:g.wave,remaining:R.tradeStock};const amount=Math.min(R.tradeBatch,state.trade.remaining,g.storage-g.resources.fuel);if(amount<=0||g.resources.scrap<amount*R.tradePrice)return report('Stock du négociant épuisé, réserve pleine ou ferraille insuffisante.',false);g.resources.scrap-=amount*R.tradePrice;g.resources.fuel+=amount;state.trade.remaining-=amount;return save(amount.toFixed(1)+' carburant acheté par troc contre '+(amount*R.tradePrice).toFixed(1)+' ferrailles.');}
  function repair(){ensure();if(!materialReady())return report('Descendez du véhicule et terminez le rechargement ou l’intervention avant de manipuler le matériel.',false);const v=state.vehicle,p=profile();if(!command()||!nearCar()||!home(v)||!operational('expeditionGarage').length||v.health>=p.health||!C.canAfford(g.resources,R.repairCost))return report('Réparation au garage : 15 ferrailles, véhicule vivant au centre.',false);C.spend(g.resources,R.repairCost);v.health=Math.min(p.health,v.health+R.repairHealth);return save('Réparation effectuée, réservoir et coffre inchangés.');}
  function select(id){reconcile();const s=state.sites.find(s=>s.id===id),v=state.vehicle;if(!command()||g.phase!=='calm'||g.phaseTime<R.dayMin||!s?.known||C.bagTotal(s.stock)<=0||!live(v))return report('Destination connue, réserves restantes et véhicule opérationnel requis pendant le jour.',false);
   if(!state.active){if(!home(g.player)||!home(v)||v.fuel<2||!operational('expeditionOffice').length||g.resources.food<R.departureFood)return report('Départ au centre : bureau achevé, 3 rations et au moins 2 carburants dans le réservoir.',false);g.resources.food-=R.departureFood;state.stats.departed++;}
   state.active={id,wave:g.wave};return save('Destination : '+E.BY_ID[id].name+'. Sur place, descendez et maintenez ACTION pour fouiller.');}
  function abandon(confirm=false){ensure();if(!command()||!state.active)return report('Aucune sortie active.',false);if(!confirm)return report('Confirmez la fin de la sortie. Les rations restent dépensées ; le break et son coffre restent sur le terrain.',false);state.active=null;return save('Sortie interrompue. Le véhicule et sa cargaison ne sont pas téléportés.');}
  function work(dt){ensure();const s=state.sites.find(s=>s.id===state.active?.id),d=s&&E.BY_ID[s.id];if(!running()||!s||!live(g.player)||state.vehicle?.driving||g.phase!=='calm'||!Number.isFinite(dt)||dt<=0||(g.fieldcraft?!g.fieldcraft.workAt(g.player,{...d,renderSize:86,fixture:true},R.range):dist(g.player,d)>R.range)||!g.hostileLineClear(g.player,d))return false;
   if(g.selectedBuild||g.rallyPlacement)return false;
   if(!safe(g.player)){g.interactionText='Expédition interrompue : infectés à proximité.';return true;}g.interactionText=s.reported?'Fouiller '+d.name+' — carburant en priorité':'Relever '+d.name+' — '+Math.floor(s.progress)+' / '+d.seconds+' s';if(!g.input.keys.has('KeyE'))return true;dt=Math.min(dt,R.maxStep);
   if(!s.reported){s.progress=Math.min(d.seconds,s.progress+dt);if(s.progress>=d.seconds){s.reported=true;state.stats.reports++;state.intel=Math.min(R.maxIntel,state.intel+R.clueIntel);reconcile();g.notify('Renseignement récupéré. De nouvelles expéditions peuvent être identifiées.');}return true;}
   const key=['fuel',...C.RESOURCE_KEYS.filter(k=>k!=='fuel')].find(k=>s.stock[k]>.000001),room=Math.max(0,g.player.carryCapacity-C.bagTotal(g.player.carry));if(!key){g.interactionText='Lieu épuisé. Revenez au véhicule.';return true;}if(room<=0){g.interactionText='Sac plein : chargez le coffre ou remplissez le réservoir.';return true;}const n=Math.min(room,s.stock[key],R.lootRate*dt);s.stock[key]-=n;g.player.carry[key]+=n;return true;
  }
  function damage(amount){ensure();const v=state.vehicle;if(!live(v)||!Number.isFinite(amount)||amount<=0)return;v.health=Math.max(0,v.health-amount);if(v.health===0){const wasDriving=v.driving;v.driving=false;v.cargo=C.makeBag();v.fuel=0;state.active=null;state.stats.lost++;g.player.radius=normalRadius;speed=0;g.notify('Break détruit : coffre et carburant perdus.','danger');if(wasDriving){g.player.invulnerable=1;g.player.health=Math.max(1,g.player.health-30);}}
  }
  function drive(dt){reconcile();const v=state.vehicle;if(!v?.driving)return false;if(!running()||!Number.isFinite(dt)||dt<=0)return true;dt=Math.min(dt,R.maxStep);const keys=g.input.keys,up=keys.has('KeyW')||keys.has('KeyZ')||keys.has('ArrowUp'),down=keys.has('KeyS')||keys.has('ArrowDown'),left=keys.has('KeyA')||keys.has('KeyQ')||keys.has('ArrowLeft'),right=keys.has('KeyD')||keys.has('ArrowRight');let dx=+right-+left,dy=+down-+up,n=Math.hypot(dx,dy);
   g.player.shootCooldown=Math.max(0,g.player.shootCooldown-dt);g.player.invulnerable=Math.max(0,g.player.invulnerable-dt);g.player.reload=0;g.player.vx=g.player.vy=0;
   const vp=profile(),fuelRate=vp.fuel>0?R.fuelPerUnit*(vp.fuel/.004):0;if(!n||(fuelRate>0&&v.fuel<=.000001)){speed=0;g.interactionText=fuelRate>0&&v.fuel<=.000001?'Réservoir vide. Descendez et cherchez du carburant.':'Au guidon/volant — F pour descendre.';return true;}dx/=n;dy/=n;const baseRegional=C.WorldEvolution?.RULES?.vehicles?.break?.speed||18,localTop=R.speed*(vp.speed/baseRegional);speed=Math.min(localTop,speed+R.acceleration*dt);v.angle=Math.atan2(dy,dx);const boost=g.infrastructure?.speed(v.x,v.y,vp.w>6?'truck':'car')||1,total=fuelRate>0?Math.min(speed*dt*boost,(g.travel131?.fuelDistance(v.fuel,fuelRate*C.Frontier.RULES.metreUnits,v.id)??v.fuel/(fuelRate*C.Frontier.RULES.metreUnits))*C.Frontier.RULES.metreUnits):speed*dt*boost,steps=Math.max(1,Math.ceil(total/4));let travelled=0;
   for(let i=0;i<steps;i++){const old={x:v.x,y:v.y},move=total/steps;if(carClear(v.x+dx*move,v.y))v.x+=dx*move;if(carClear(v.x,v.y+dy*move))v.y+=dy*move;travelled+=dist(old,v);}const metres=travelled/C.Frontier.RULES.metreUnits,fuel=g.travel131?.fuelCost(metres,fuelRate*C.Frontier.RULES.metreUnits,v.id)??travelled*fuelRate;v.fuel=Math.max(0,v.fuel-fuel);g.travel131?.consumeDistance(metres,v.id);state.stats.distance+=travelled;state.stats.fuelUsed+=fuel;g.player.x=v.x;g.player.y=v.y;g.player.facing=v.angle;g.player.vx=dx*speed;g.player.vy=dy*speed;g.interactionText=(vp.tank?'Carburant '+v.fuel.toFixed(1)+' / '+vp.tank:'Propulsion humaine')+' · F pour descendre';return true;
  }
  function tick(dt){reconcile();if(!running()||!Number.isFinite(dt)||dt<=0)return;if(g.phase==='calm'){for(const s of state.sites)if(!s.known&&dist(g.player,E.BY_ID[s.id])<115&&g.hostileLineClear(g.player,E.BY_ID[s.id])){s.known=true;g.notify('Nouvelle expédition repérée : '+E.BY_ID[s.id].name);}}
   if(phase==='calm'&&g.phase!=='calm'&&state.active)g.notify('Crépuscule : fouilles suspendues. Rentrez avec le carburant restant.','danger');phase=g.phase;
   const v=state.vehicle;if(live(v)&&!v.driving&&!v.regionAway){const attackers=g.zombies.filter(z=>live(z)&&dist(z,v)<45&&g.hostileLineClear(z,v)).length;if(attackers)damage(Math.min(4,attackers)*3*Math.min(dt,.25));}
   if(v?.driving&&g.player.dead){v.driving=false;g.player.radius=normalRadius;speed=0;}
  }
  function overview(){reconcile();const v=state.vehicle;return{sites:state.sites.filter(s=>s.known).map(s=>({...s,...E.BY_ID[s.id],distance:dist(g.player,E.BY_ID[s.id]),minimumFuel:(()=>{const units=dist(v||g.player,E.BY_ID[s.id])+dist(E.BY_ID[s.id],g.core()),ratio=profile().fuel/(C.WorldEvolution?.RULES.vehicles.break.fuel??C.Frontier.RULES.fuelPerMetre),rate=R.fuelPerUnit*ratio;return g.travel131?.fuelCost(units/C.Frontier.RULES.metreUnits,rate*C.Frontier.RULES.metreUnits,v?.id??null)??units*rate;})()})),intel:state.intel,analyst:state.analyst?{...state.analyst}:null,vehicle:v?{...v,cargo:{...v.cargo}}:null,active:state.active?{...state.active}:null,tradeRemaining:state.trade.wave===g.wave?state.trade.remaining:R.tradeStock,stats:{...state.stats},notice,nearCar:nearCar(),atHome:home(g.player),day:g.phase==='calm'};}
  const api={overview,snapshot:()=>{reconcile();return E.normalize(state);},isAssigned,updateAssignedUnit,assign,recall,buildCar,board,refuel,transfer,unload,buyFuel,repair,select,abandon,work,drive,damage,carClear,entity:()=>{ensure();return live(state.vehicle)&&!state.vehicle.regionAway?{...state.vehicle,radius:vehicleRadius()}:null;},driving:()=>{ensure();return Boolean(state.vehicle?.driving);},car:()=>{ensure();return state.vehicle;}};g.expeditions=Object.freeze(api);
  wrap('serialize',(old,...a)=>({...old(...a),expeditions:api.snapshot()}));
  wrap('restoreSave',(old,input)=>{const data=root.DeadwallSave.validate(input),before=g.world;pending=data.expeditions;try{return old(data);}finally{if(g.world!==before){ensure();reconcile();if(state.vehicle?.driving){g.player.radius=vehicleRadius();g.player.x=state.vehicle.x;g.player.y=state.vehicle.y;}}pending=null;}});
  wrap('startNew',(old,...a)=>{pending=null;const r=old(...a);ensure();reconcile();return r;});
  wrap('update',(old,dt)=>{reconcile();const r=old(dt);tick(dt);return r;});
  wrap('updatePlayer',(old,dt)=>{if(drive(dt))return;return old(dt);});
  wrap('updateInteraction',(old,dt)=>{if(work(dt))return;return old(dt);});
  for(const n of ['shootPlayer','startReload','melee','placeOne'])wrap(n,(old,...a)=>{if(api.driving())return false;return old(...a);});
  wrap('damagePlayer',(old,amount)=>{if(api.driving()){damage(amount);return;}return old(amount);});
  wrap('drawPlayer',(old,...a)=>{if(!api.driving())return old(...a);});
  wrap('setGateMode',(old,mode,b=g.selectedBuilding)=>{const v=api.entity();if(v&&b&&mode!=='open'&&root.DeadwallTactics.overlapsBuilding(b,v))return false;return old(mode,b);});
  wrap('completeBuilding',(old,b)=>{const v=api.entity();if(v&&b?.def.wall&&root.DeadwallTactics.overlapsBuilding(b,v)){const p=Math.min(b.progress,.999);b.health=Math.max(.001,b.health-(b.progress-p)*b.maxHealth*.88);b.progress=p;b.completionBlocked=true;return false;}return old(b);});
  wrap('handlePressed',(old,...a)=>{if(g.input.pressed.has('KeyF'))board();return old(...a);});
  wrap('renderMinimap',(old,...a)=>{const r=old(...a),v=state.vehicle;if(v&&!v.regionAway){const c=g.mctx;c.fillStyle=live(v)?'#dec781':'#736f65';c.fillRect(v.x*g.minimap.width/C.WORLD_SIZE-3,v.y*g.minimap.height/C.WORLD_SIZE-2,6,4);}return r;});
  return g.expeditions;
 }
 const api={install};root.DeadwallExpeditions=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
