/* The expedition desk lives in the existing map, with an actual drivable vehicle. */
(function(root){'use strict';const g=root.DEADWALL,C=root.DeadwallCore,R=C.Expeditions.RULES;if(!g.expeditions)return;
 function mount(){if(g.expeditionsUI)return;const get=id=>document.getElementById(id),host=get('reconPanel');if(!host)return;
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;},txt=(n,s)=>{if(n.textContent!==String(s))n.textContent=String(s)};
  const button=(text,id,fn)=>{const n=el('button',text);n.type='button';n.id=id;n.addEventListener('click',()=>{if(n.disabled)return;const r=fn();if(r?.reason)txt(message,r.reason);refresh(true)});return n;};
  let selected='station',key='',last=-Infinity,confirm=false;
  const panel=el('section',undefined,'exp13');panel.id='expeditionPanel';host.append(panel);panel.append(el('small','EXPÉDITIONS / RENSEIGNEMENT & MOBILITÉ'),el('h2','Partir avec un plan. Revenir avec du carburant.'),el('p','Douze haltes supplémentaires dans D-17, découvertes par les renseignements ou la reconnaissance. Vous conduisez et fouillez sur la carte existante : aucun voyage instantané, aucun chargement à distance.'));
  const summary=el('p','','exp13-summary'),message=el('p','','exp13-message');message.id='expMessage';message.setAttribute('role','status');panel.append(summary,message);
  const grid=el('div',undefined,'exp13-layout'),map=el('canvas'),detail=el('article',undefined,'exp13-detail');map.id='expMap';map.width=600;map.height=450;map.setAttribute('role','img');map.setAttribute('aria-label','Destinations connues de D-17. La liste fournit les mêmes destinations au clavier.');grid.append(map,detail);panel.append(grid);
  const name=el('h3'),desc=el('p'),stock=el('p'),estimate=el('p','','exp13-note');detail.append(name,desc,stock,estimate);
  const start=button('PRÉPARER / CHOISIR CETTE DESTINATION','expSelect',()=>{const r=g.expeditions.select(selected);if(r.ok){g.showCommand(false);g.canvas.focus();}return r;});detail.append(start,el('p','Première préparation au centre : 3 rations. Réservoir séparé de 24 ; coffre de 80. Les réserves restent finies après une reprise. À pied sur place, maintenez ACTION / E. Le carburant est prélevé en premier.','exp13-note'));
  const select=el('select');select.id='expSiteList';select.setAttribute('aria-label','Choisir une expédition connue');select.addEventListener('change',()=>{selected=select.value;refresh(true)});panel.append(select);
  const staff=el('div',undefined,'exp13-staff'),stafftext=el('p'),staffButtons=el('div',undefined,'exp13-actions');staffButtons.append(button('AFFECTER UN OUVRIER AU RENSEIGNEMENT','expAssign',()=>g.expeditions.assign()),button('RAPPELER L’ANALYSTE','expRecall',()=>g.expeditions.recall()));staff.append(el('h3','Personnel attitré'),stafftext,staffButtons,el('p','Un ouvrier réel rejoint le bureau alimenté. Deux rations au détachement ; ensuite 45 secondes actives et deux rations par renseignement. La nuit et le repli général déclenchent son retour physique.','exp13-note'));panel.append(staff);
  const carsection=el('article',undefined,'exp13-car'),carstatus=el('p'),actions=el('div',undefined,'exp13-actions');carsection.append(el('h3','Véhicule d’expédition'),carstatus,actions);
  const btns={build:button('CONSTRUIRE LE VÉHICULE SÉLECTIONNÉ','expBuildCar',()=>g.expeditions.buildCar()),board:button('MONTER / DESCENDRE [F]','expBoard',()=>g.expeditions.board()),fuel:button('REMPLIR LE RÉSERVOIR','expRefuel',()=>g.expeditions.refuel()),cargo:button('SAC → COFFRE','expCargo',()=>g.expeditions.transfer()),unload:button('LIVRER AU CENTRE','expUnload',()=>g.expeditions.unload()),repair:button('RÉPARER : 15 FERRAILLES','expRepair',()=>g.expeditions.repair())};actions.append(...Object.values(btns));carsection.append(el('p','Véhicule : 40 bois + 90 ferrailles, réservoir vide. Conduite avec les directions habituelles ; pas de tir depuis la voiture. La consommation dépend de la distance parcourue, pas du temps au menu. En panne, descendez chercher un bidon. Détruit, le coffre et le carburant sont perdus.','exp13-note'));panel.append(carsection);
  const trade=el('article',undefined,'exp13-trade'),tradetext=el('p'),buy=button('TROC : 5 CARBURANTS CONTRE 20 FERRAILLES','expBuyFuel',()=>g.expeditions.buyFuel());trade.append(el('h3','Le négociant au centre'),tradetext,buy,el('p','Échange local en journée, bureau achevé. Au maximum 30 carburants par journée. Le carburant acheté entre au dépôt, pas directement dans le réservoir. Aucun argent réel.','exp13-note'));panel.append(trade);
  const abort=button('INTERROMPRE LA SORTIE','expAbort',()=>{if(!confirm){confirm=true;abort.textContent='CONFIRMER L’INTERRUPTION';return{reason:'Confirmez : les rations restent dépensées et le break reste sur le terrain.'};}confirm=false;abort.textContent='INTERROMPRE LA SORTIE';return g.expeditions.abandon(true)});panel.append(abort);
  const open=()=>{g.recon.open();refresh(true);panel.scrollIntoView({block:'start'});};const openBtn=button('EXPÉDITIONS & VOITURE','expOpen',open);get('citySystemsDock')?.querySelector('div')?.append(openBtn);
  const hud=el('div',undefined,'exp13-hud'),hudtext=el('small'),quick=button('VOITURE [F]','expVehicleButton',()=>g.expeditions.board());hud.id='expHUD';hud.append(hudtext,quick);get('hud')?.append(hud);
  function draw(v){const c=map.getContext('2d'),sx=600/C.WORLD_SIZE,sy=450/C.WORLD_SIZE;c.fillStyle='#14231a';c.fillRect(0,0,600,450);c.strokeStyle='#344d37';for(let i=0;i<9;i++){c.beginPath();c.moveTo(i*75,0);c.lineTo(i*75,450);c.moveTo(0,i*56.25);c.lineTo(600,i*56.25);c.stroke();}c.strokeStyle='#807957';c.lineWidth=3;c.beginPath();c.moveTo(0,225);c.lineTo(600,225);c.moveTo(300,0);c.lineTo(300,450);c.stroke();
   for(const b of g.world.buildings.values())if(!b.dead){c.fillStyle=b.type==='core'?'#eee0aa':'#668a65';c.fillRect(b.left*sx,b.top*sy,Math.max(2,b.w*32*sx),Math.max(2,b.h*32*sy));}
   const target=v.sites.find(s=>s.id===v.active?.id);if(target&&v.vehicle){c.strokeStyle='#cab583';c.setLineDash([5,5]);c.beginPath();c.moveTo(v.vehicle.x*sx,v.vehicle.y*sy);c.lineTo(target.x*sx,target.y*sy);c.stroke();c.setLineDash([]);}
   for(const s of v.sites){const x=s.x*sx,y=s.y*sy;c.fillStyle=s.id===selected?'#ecd699':C.bagTotal(s.stock)<=0?'#566d55':'#95b69b';c.beginPath();c.arc(x,y,s.id===selected?7:5,0,Math.PI*2);c.fill();c.font='10px sans-serif';c.textAlign=x>470?'right':x<130?'left':'center';c.fillStyle='#d9d6b9';c.fillText(s.id.toUpperCase(),x,y-12);}
   if(v.vehicle){c.fillStyle=v.vehicle.health>0?'#e6bd79':'#786f5e';c.fillRect(v.vehicle.x*sx-5,v.vehicle.y*sy-3,10,6);}c.fillStyle='#e9ebc7';c.beginPath();c.arc(g.player.x*sx,g.player.y*sy,3,0,Math.PI*2);c.fill();}
  function refresh(force=false){if(!force&&performance.now()-last<300)return;last=performance.now();const v=g.expeditions.overview(),car=v.vehicle,alive=car?.health>0,can=g.canIssueCommand();hud.classList.toggle('hidden',!car||g.state!=='playing'||g.gameOver);quick.disabled=!can||!v.nearCar;txt(quick,car?.driving?'DESCENDRE [F]':'MONTER [F]');txt(hudtext,car?'ESSENCE '+car.fuel.toFixed(1)+' / 24 · COFFRE '+C.bagTotal(car.cargo).toFixed(0)+' / 80':'');
   if(host.classList.contains('hidden'))return;txt(summary,v.sites.length+' / 12 expéditions connues · '+v.intel+' renseignements · '+(v.day?'Jour : '+C.formatTime(g.phaseTime):'Départs et fouilles suspendus : retour possible'));if(!v.sites.some(s=>s.id===selected))selected=v.sites[0]?.id;const k=v.sites.map(s=>s.id).join(',');if(k!==key){key=k;select.replaceChildren();for(const s of v.sites){const o=el('option',s.name);o.value=s.id;select.append(o);}}select.value=selected;const s=v.sites.find(s=>s.id===selected);
   txt(name,s?.name||'Aucune destination');txt(desc,s?.text||'');txt(stock,s?'Réserves restantes : '+C.resourceText(s.stock)+' · '+(s.reported?'renseignements récupérés':s.progress.toFixed(1)+' / '+s.seconds+' s de relevé'):'');txt(estimate,s?'Distance à vol d’oiseau : '+Math.round(s.distance)+' unités. Minimum géométrique vers ce lieu puis le centre : '+s.minimumFuel.toFixed(1)+' carburants. Les détours coûtent davantage ; aucun chemin sûr n’est garanti.':'');
   start.disabled=!can||!v.day||!alive||!s||C.bagTotal(s.stock)<=0;txt(stafftext,v.analyst?'Ouvrier #'+v.analyst.id+' · '+(v.analyst.returning?'retour au centre':v.analyst.progress.toFixed(1)+' / 45 s de recherche active'):'Aucun analyste détaché. Les relevés d’expédition apportent aussi des renseignements.');get('expAssign').disabled=!can||!v.day||!!v.analyst;get('expRecall').disabled=!can||!v.analyst||v.analyst.returning;
   txt(carstatus,car?'État '+Math.ceil(car.health)+' / 320 · Réservoir '+car.fuel.toFixed(1)+' / 24 · Coffre '+C.bagTotal(car.cargo).toFixed(1)+' / 80 · '+(car.driving?'au volant':'stationné'):'Aucun véhicule. Construisez un garage puis remettez un break en service.');btns.build.disabled=!can||alive||!v.day;btns.board.disabled=btns.fuel.disabled=btns.cargo.disabled=!can||!v.nearCar;btns.unload.disabled=btns.repair.disabled=!can||!v.nearCar||!v.atHome;buy.disabled=!can||!v.day||!v.atHome;txt(tradetext,v.tradeRemaining.toFixed(1)+' carburants disponibles aujourd’hui.');abort.disabled=!can||!v.active;draw(v);
  }
  map.addEventListener('click',e=>{const r=map.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*C.WORLD_SIZE,y=(e.clientY-r.top)/r.height*C.WORLD_SIZE,s=g.expeditions.overview().sites.map(s=>({s,d:Math.hypot(x-s.x,y-s.y)})).sort((a,b)=>a.d-b.d)[0];if(s&&s.d<150){selected=s.s.id;refresh(true)}});
  const old=g.updateUI.bind(g);g.updateUI=(...a)=>{const r=old(...a);refresh();return r;};const recon=g.reconUI;g.reconUI=Object.freeze({...recon,open:()=>{const r=recon.open();refresh(true);return r;}});get('reconTab')?.addEventListener('click',()=>refresh(true));
  for(const n of ['startNew','restoreSave']){const old=g[n].bind(g);g[n]=(...a)=>{const r=old(...a);key='';confirm=false;selected='station';abort.textContent='INTERROMPRE LA SORTIE';txt(message,'');refresh(true);return r;};}
  g.expeditionsUI=Object.freeze({open,refresh});refresh(true);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(globalThis);
