/* Regional reconnaissance shares the existing analyst, without free resources. */
(function(root){'use strict';
function install(g){if(g.fieldAtlas)return;const C=root.DeadwallCore,A=C.FieldAtlas,R=A.RULES,P=root.DeadwallAtlasProjection||(typeof require==='function'?require('./atlas-projection.js'):null);let state=A.initial(),owner=g.world,pending=null,message='',timer=0,knownCells=new Set(),memo=null;
const wrap=(name,fn)=>{const old=g[name].bind(g);g[name]=(...args)=>fn(old,...args);};
function ensure(){if(owner!==g.world){owner=g.world;state=A.normalize(pending||undefined);pending=null;knownCells=new Set(state.cells);timer=0;memo=null;message='';}return state;}
const can=()=>g.state==='playing'&&!g.gameOver&&!g.player.dead&&g.player.health>0&&g.canIssueCommand();
const fstate=()=>g.frontier.snapshot();const fail=t=>{message=t;return{ok:false,reason:t};};
function analyst(){const a=g.expeditions.snapshot().analyst,u=a&&g.units.find(u=>u.id===a.id),post=a&&g.world.buildings.get(a.post);return a&&u&&!u.dead&&u.health>0&&post&&!post.dead&&post.health>0?{...a,u,post}:null;}
function pool(town){const anchor=P.home(g),f=fstate(),seen=new Set([...f.seen,...state.reports.map(r=>r.id)]);return g.frontier.world().pois.filter(p=>A.district(p,g.frontier.world()).id===town&&!seen.has(p.id)).sort((a,b)=>Math.hypot(a.x-anchor.x,a.y-anchor.y)-Math.hypot(b.x-anchor.x,b.y-anchor.y)||a.id.localeCompare(b.id));}
function commission(town){ensure();if(!can()||g.phase!=='calm')return fail('Une recherche régionale se prépare pendant le jour.');if(state.job)return fail('Un dossier est déjà en cours.');const a=analyst();if(!a||a.returning||!a.post.completed||!a.post.powered||a.post.siegeOffline||a.post.territoryOffline)return fail('Affectez un analyste au bureau d’expédition alimenté.');const targets=pool(town).slice(0,R.batch);if(!targets.length)return fail('Aucune archive inédite à recouper dans ce secteur.');if(state.reports.length+targets.length>R.maxReports)return fail('Le carnet est plein.');if(!C.canAfford(g.resources,R.researchCost))return fail('Cinq rations sont nécessaires au dossier.');C.spend(g.resources,R.researchCost);state.job={town,progress:0,targets:targets.map(p=>p.id)};message='Dossier préparé. Le travail commence quand l’analyste atteint son bureau.';g.save(false);return{ok:true};}
function cancel(){ensure();if(!can()||!state.job)return false;state.job=null;message='Dossier abandonné. Les rations de préparation ne sont pas remboursées.';g.save(false);return true;}
function researchStep(u,post,dt){ensure();if(!state.job)return false;const a=analyst();if(!a||a.id!==u?.id||a.post.id!==post?.id||a.returning||g.state!=='playing'||g.paused||g.gameOver||g.activeOverlay||g.phase!=='calm'||!post.completed||!post.powered||post.siegeOffline||post.territoryOffline||g.workerOrder==='retreat'||!Number.isFinite(dt)||dt<=0||!g.workerCanWorkAt(u,post,90)||g.zombies.some(z=>!z.dead&&z.health>0&&Math.hypot(z.x-u.x,z.y-u.y)<C.Expeditions.RULES.danger&&g.hostileLineClear(z,u)))return true;
state.job.progress+=Math.min(.25,dt);if(state.job.progress+1e-8<R.researchSeconds)return true;const job=state.job,seen=new Set(fstate().seen);state.job=null;let n=0;for(const id of job.targets)if(!seen.has(id)&&!state.reports.some(r=>r.id===id)){state.reports.push({id,town:job.town,at:g.elapsed});n++;}memo=null;message=n+' lieu(x) signalé(s). Leur présence et leurs réserves restent à vérifier sur place.';g.notify(message);g.save(false);return true;}
function permitted(id){return fstate().seen.includes(id)||state.reports.some(r=>r.id===id);}
function add(id){ensure();if(!can()||!permitted(id)||state.tour.stops.includes(id)||state.tour.stops.length>=R.maxStops)return false;state.tour.stops.push(id);memo=null;message='Étape ajoutée à la tournée.';g.save(false);return true;}
function remove(id){ensure();if(!can())return false;const i=state.tour.stops.indexOf(id);if(i<0)return false;state.tour.stops.splice(i,1);if(i<state.tour.index)state.tour.index--;state.tour.index=Math.min(state.tour.index,state.tour.stops.length);if(state.tour.index>=state.tour.stops.length)state.tour.active=false;memo=null;g.save(false);return true;}
function reorder(id,delta){ensure();const i=state.tour.stops.indexOf(id),j=i+delta;if(!can()||state.tour.active||![-1,1].includes(delta)||i<0||j<0||j>=state.tour.stops.length)return false;[state.tour.stops[i],state.tour.stops[j]]=[state.tour.stops[j],state.tour.stops[i]];state.tour.index=0;memo=null;g.save(false);return true;}
function configure(mode,gate){ensure();if(!can()||!['foot','car'].includes(mode)||!P.gates.some(g=>g.id===gate))return false;state.tour.mode=mode;state.tour.gate=gate;memo=null;g.save(false);return true;}
function start(){ensure();if(!can()||!state.tour.stops.length)return false;state.tour.active=true;if(state.tour.index>=state.tour.stops.length)state.tour.index=0;memo=null;g.save(false);return true;}
function stop(){ensure();if(!can())return false;state.tour.active=false;memo=null;g.save(false);return true;}
function next(){ensure();if(!can()||!state.tour.active)return false;state.tour.index++;if(state.tour.index>=state.tour.stops.length){state.tour.active=false;message='Tournée terminée. Contrôlez les chemins du retour avant de rentrer.';}memo=null;g.save(false);return true;}
function point(id,f){const p=g.frontier.world().pois.find(p=>p.id===id);if(!p)return null;if(f.seen.includes(id)){const biome=C.BiomeRules135?.defs.find(d=>d.id===p.biome);return{id,name:p.name,x:p.x,y:p.y,confirmed:true,category:A.category(p.type),drive:p.drive,...(biome?{biome:biome.id,biomeName:biome.name,surface:biome.surface}:{})};}const r=state.reports.find(r=>r.id===id);if(!r)return null;const h=A.hint(p);return{id,name:'Indice '+id.slice(1)+' · '+h.category,...h,confirmed:false,drive:{a:{x:h.x,y:h.y},b:{x:h.x,y:h.y}}};}
function departure(f){const tour=state.tour,car=g.expeditions.car(),regionalCar=!!f.car&&f.car.id===car?.id,vehicleUsable=tour.mode==='car'&&!!car&&car.health>0&&(!f.active||regionalCar),gate=P.gatesFor(g).find(p=>p.id===tour.gate),origin=f.active?(vehicleUsable&&regionalCar?{x:f.car.x,y:f.car.y}:{x:f.x,y:f.y}):{x:gate.x,y:gate.y};return{car,vehicleUsable,gate,origin,originKind:f.active?(vehicleUsable&&regionalCar?'véhicule':'commandant'):'jonction de départ'};}
function biomeChoices(){ensure();const w=g.frontier.world();if(w.generation<6)return[];const seen=new Set(g.frontier.discoveries()),planned=new Set(state.tour.stops),counts=new Map();for(const p of w.pois)if(seen.has(p.id)){const count=counts.get(p.biome)||{known:0,available:0};count.known++;if(!planned.has(p.id))count.available++;counts.set(p.biome,count);}return C.BiomeRules135.defs.filter(d=>counts.has(d.id)).map(d=>({id:d.id,name:d.name,...counts.get(d.id)}));}
function prepareBiome(id){ensure();if(!can())return fail('Le commandant doit pouvoir préparer son carnet.');if(state.tour.active)return fail('Mettez la tournée en pause avant de compléter ses étapes.');const w=g.frontier.world(),choice=biomeChoices().find(d=>d.id===id);if(!choice?.available)return fail('Aucun lieu confirmé inédit dans ce biome.');const room=R.maxStops-state.tour.stops.length;if(room<=0)return fail('Les six places de la tournée sont déjà occupées.');
 const f=fstate(),{origin}=departure(f),Return=root.DeadwallReturnRoutes||(typeof require==='function'?require('./return-routes.js'):null),Router=root.DeadwallFrontierRouting||(typeof require==='function'?require('./frontier-routing.js'):null),outside=Return.outsideWorld(w),seen=new Set(f.seen),planned=new Set(state.tour.stops),candidates=w.pois.filter(p=>seen.has(p.id)&&p.biome===id&&!planned.has(p.id));let from=origin,metres=0;const last=state.tour.stops.at(-1);if(last&&state.tour.index<state.tour.stops.length){const target=point(last,f);if(target)from=target.drive.b;}const added=[];
 while(added.length<room&&candidates.length){let best=null;for(let i=0;i<candidates.length;i++){const p=candidates[i],route=Router.route(outside,from,p);if(route&&(!best||route.metres<best.route.metres||route.metres===best.route.metres&&p.id.localeCompare(best.p.id)<0))best={i,p,route};}if(!best)break;candidates.splice(best.i,1);added.push(best.p.id);metres+=best.route.metres;from=best.route.path.at(-1);}
 if(!added.length)return fail('Aucune liaison routière calculable vers ces lieux.');state.tour.stops.push(...added);memo=null;message=added.length+' étape(s) de '+choice.name+' ajoutée(s), par distance routière. Contrôlez les accès et les réserves sur place.';g.save(false);return{ok:true,added,biome:id,metres};}
function planning(){ensure();const f=fstate(),tour=state.tour,{car,vehicleUsable:v,gate,origin,originKind}=departure(f);const key=[g.world.seed,f.generation,tour.stops.join(','),tour.index,tour.active,tour.mode,tour.gate,origin.x.toFixed(2),origin.y.toFixed(2),originKind,f.seen.join(',')].join('|');let route=memo?.key===key?memo.value:null;
if(!route){const w=g.frontier.world(),Return=root.DeadwallReturnRoutes||(typeof require==='function'?require('./return-routes.js'):null),Router=root.DeadwallFrontierRouting||(typeof require==='function'?require('./frontier-routing.js'):null),outside=Return.outsideWorld(w),stops=tour.stops.slice(tour.index).map(id=>point(id,f)).filter(Boolean),legs=[];let from=origin,metres=0,failed=false;for(const p of stops){const r=Router.route(outside,from,p);if(!r){failed=true;break;}legs.push({...r,target:p});metres+=r.metres;from=r.path.at(-1);}const back=stops.length&&!failed?Router.route(outside,from,{drive:{a:gate,b:gate}}):null;route={legs,metres,back,loopMetres:metres+(back?.metres||0),failed:failed||!!stops.length&&!back,originKind,gate:gate.name};memo={key,value:route};}
const rate=tour.mode==='car'?(g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre):0,cost=metres=>g.travel131?.fuelCost(metres,rate,car?.id??null)??metres*rate,reserve=rate>0?g.fieldSupplies.snapshot().reserve:0,fuel=cost(route.loopMetres),withDetour=cost(route.loopMetres*C.FieldSupplies.RULES.detourFactor),available=v?car.fuel+car.cargo.fuel+g.player.carry.fuel:0;return{...route,mode:tour.mode,active:tour.active,required:withDetour+reserve,available,fuel,reserve,margin:withDetour-fuel,vehicleUsable:!!v,excludesLocal:true};}
function guidance(){ensure();if(!state.tour.active||!fstate().active)return null;const plan=planning(),leg=plan.legs[0],rate=plan.mode==='car'?(g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre):0;return leg?{...leg,name:leg.target.name,id:leg.target.id,tour:true,confirmed:leg.target.confirmed,fuel:g.travel131?.fuelCost(leg.metres,rate,g.expeditions.car()?.id??null)??leg.metres*rate}:null;}
// The map needs pins and tour markers, not every analyst district candidate list.
function mapView(){ensure();const f=fstate(),activeId=state.tour.active?state.tour.stops[state.tour.index]:null;return{arrived:!!activeId&&f.active&&f.z===0&&f.inside===activeId&&!f.car?.driving,reports:state.reports.map(r=>({...r,...point(r.id,f)})),steps:state.tour.stops.map((id,i)=>({...point(id,f),index:i,current:i===state.tour.index&&state.tour.active,past:i<state.tour.index}))};}
function overview(){ensure();const w=g.frontier.world(),a=analyst();return{...A.normalize(state),...mapView(),message,analyst:a?{id:a.id,returning:a.returning,atDesk:g.workerCanWorkAt(a.u,a.post,90),powered:!!a.post.powered}:null,districts:w.towns.map(t=>({id:t.id,name:t.name,available:pool(t.id).length>0}))};}
g.fieldAtlas=Object.freeze({commission,cancel,researchStep,add,remove,reorder,configure,start,stop,next,guidance,planning,biomeChoices,prepareBiome,mapView,overview,snapshot:()=>{ensure();return A.normalize(state);},travelled:()=>{ensure();return new Set(knownCells);}});
wrap('update',(old,dt)=>{ensure();const running=g.state==='playing'&&!g.paused&&!g.activeOverlay&&!g.gameOver&&!g.player.dead,r=old(dt);if(running&&Number.isFinite(dt)&&dt>0){timer-=Math.min(.25,dt);if(timer<=0){timer=R.recordSeconds;const f=fstate();if(f.active&&f.z===0&&!g.player.dead){const cell=A.cell(f.x,f.y);if(cell>=0&&cell<R.maxCells&&!knownCells.has(cell)){knownCells.add(cell);state.cells.push(cell);}}}}return r;});
wrap('serialize',(old,...a)=>{ensure();return{...old(...a),fieldAtlas:A.normalize(state)};});
wrap('restoreSave',(old,raw)=>{const record=A.validate(raw?.version>=18&&raw.version<=C.SAVE_VERSION?raw.fieldAtlas:undefined,raw);pending=record;try{const r=old(raw);ensure();return r;}catch(e){pending=null;throw e;}});
wrap('startNew',(old,...a)=>{const before=g.world,r=old(...a);if(g.world!==before){pending=null;ensure();state=A.initial();knownCells.clear();memo=null;}return r;});return g.fieldAtlas;}
const api={install};root.DeadwallFieldAtlas=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
