/* 1.18 supply management extends the existing map dossier. */
(function(root){'use strict';const g=root.DEADWALL,C=root.DeadwallCore;if(!g?.fieldSupplies)return;
function mount(){if(g.fieldSuppliesUI)return;const get=id=>document.getElementById(id),host=get('frontierDossier');if(!host)return;const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;},write=(e,t)=>{if(e.textContent!==String(t))e.textContent=t;};const button=(text,id,fn)=>{const b=make('button',text);b.id=id;b.type='button';b.addEventListener('click',()=>{if(!b.disabled){fn();refresh(true);}});return b;};
const panel=make('details',undefined,'supplies-panel');panel.id='fieldSupplyPanel';const summary=make('summary','Sac, coffre & relais'),intro=make('p','Répartissez les provisions sur place. Les transferts exigent un accès libre au bon étage. Les matériaux des soins et travaux doivent être dans le sac.'),status=make('p',undefined,'supplies-status'),head=make('div',undefined,'supplies-controls'),select=make('select'),amount=make('select');select.id='supplyEndpoint';select.setAttribute('aria-label','Réserve à utiliser');amount.id='supplyQuantity';amount.setAttribute('aria-label','Quantité à transférer');for(const[v,t]of [['1','1 unité'],['5','5 unités'],['max','Maximum']]){const o=make('option',t);o.value=v;amount.append(o);}amount.value='5';head.append(select,amount);
const table=make('table',undefined,'supplies-table'),thead=make('thead'),tr=make('tr');for(const t of ['Ressource','Sac','Réserve','Déposer','Reprendre'])tr.append(make('th',t));thead.append(tr);table.append(thead);const body=make('tbody');table.append(body);const rows={};for(const key of C.RESOURCE_KEYS){const row=make('tr'),bag=make('td'),end=make('td'),deposit=button('→','supplyDeposit-'+key,()=>move(key,'deposit')),withdraw=button('←','supplyWithdraw-'+key,()=>move(key,'withdraw'));deposit.setAttribute('aria-label','Déposer : '+C.RESOURCE_META[key].label);withdraw.setAttribute('aria-label','Reprendre : '+C.RESOURCE_META[key].label);const a=make('td'),b=make('td');a.append(deposit);b.append(withdraw);row.append(make('th',C.RESOURCE_META[key].label),bag,end,a,b);body.append(row);rows[key]={bag,end,deposit,withdraw};}
function move(key,direction){g.fieldSupplies.transfer(select.value,key,direction,amount.value==='max'?'max':Number(amount.value));}
const total=make('p',undefined,'supplies-note'),work=make('div',undefined,'supplies-work'),heal=button('Pansement · 2 médicaments · 4 s','supplyHeal',()=>g.fieldSupplies.begin('heal')),repair=button('Réparer le break · 12 ferrailles · 6 s','supplyRepair',()=>g.fieldSupplies.begin('repair')),cache=button('Aménager · 6 bois + 4 ferrailles · 5 s','supplyCreate',()=>g.fieldSupplies.begin('cache',g.frontier.overview().focus?.id)),hint=make('p',undefined,'supplies-note'),cancel=button('INTERROMPRE','supplyCancel',()=>g.fieldSupplies.cancel());work.append(heal,repair,cache,cancel);
const reserve=make('input'),label=make('label','Marge fixe de carburant : ');reserve.id='supplyReserve';reserve.type='number';reserve.min='0';reserve.max='8';reserve.step='.5';reserve.value='2';label.htmlFor=reserve.id;label.append(reserve);const route=make('p',undefined,'supplies-route'),cacheList=make('div',undefined,'supplies-cache-list');route.id='supplyRoute';panel.append(summary,intro,head,table,total,status,make('h3','Sur place'),work,hint,make('h3','Prévoir le retour'),label,route,make('h3','Relais aménagés'),cacheList,make('p','Un relais réutilise une caisse, une armoire ou un rayonnage entièrement vidé. Capacité : 60 ressources au total. Aucun stock offert. Une action interrompue ne dépense rien ; son progrès n’est pas repris après chargement.','supplies-note'));host.append(panel);
status.setAttribute('role','status');status.setAttribute('aria-live','polite');
let last=0,endsKey='',cacheKey='';function open(){g.frontierUI.open();panel.open=true;refresh(true);panel.scrollIntoView({block:'start'});}
const oldCargo=get('frontierCargo');if(oldCargo)oldCargo.replaceWith(button('SAC & RELAIS','frontierCargo',open));get('touchCommandDrawer')?.querySelector('.touch-command-grid')?.append(button('SAC & RELAIS','supplyTouchOpen',()=>{get('touchCommandDrawer').open=false;open();}));
const progressWrap=make('div',undefined,'supplies-progress hidden'),progressText=make('span'),progress=make('progress');progress.max=1;progress.id='supplyProgress';progress.setAttribute('aria-label','Action de terrain en cours');progressWrap.append(progressText,progress);get('frontierHud')?.insertBefore(progressWrap,get('frontierHud')?.lastChild||null);
select.addEventListener('change',()=>refresh(true));amount.addEventListener('change',()=>refresh(true));reserve.addEventListener('change',()=>{g.fieldSupplies.reserve(Number(reserve.value));refresh(true);});panel.addEventListener('toggle',()=>{if(panel.open)refresh(true);});
function refresh(force=false){if(!force&&performance.now()-last<350)return;last=performance.now();const active=g.frontier.active(),cargo=get('frontierCargo');if(cargo)cargo.disabled=!active||g.player.dead;const visible=panel.open&&!get('reconPanel').classList.contains('hidden');if(!active&&!visible){progressWrap.classList.add('hidden');return;}const quantity=amount.value==='max'?'max':Number(amount.value),v=g.fieldSupplies.overview(visible?select.value:undefined,quantity);progressWrap.classList.toggle('hidden',!v.task);if(v.task){progress.value=v.task.progress;write(progressText,(v.task.kind==='heal'?'Pansement':v.task.kind==='repair'?'Réparation':'Aménagement')+' · '+Math.round(v.task.progress*100)+' % · bouger pour annuler');}if(!visible)return;
const ek=v.endpoints.map(e=>e.id+':'+e.available).join('|');if(ek!==endsKey){endsKey=ek;select.replaceChildren();for(const end of v.endpoints){const o=make('option',end.name+(end.available?'':' · hors accès'));o.value=end.id;select.append(o);}}select.value=v.transfers.endpoint;const e=v.endpoints.find(e=>e.id===select.value),stock=e?.id==='car'?v.car:e?.id==='depot'?g.resources:e?.stock;for(const k of C.RESOURCE_KEYS){write(rows[k].bag,v.bag[k].toFixed(1));write(rows[k].end,stock?stock[k].toFixed(1):'—');for(const direction of ['deposit','withdraw']){const q=v.transfers.rows[k][direction],b=rows[k][direction];b.disabled=!q.ok;b.title=q.reason;b.setAttribute('aria-description',q.reason);}}
write(total,'Sac '+C.bagTotal(v.bag).toFixed(1)+' / '+g.player.carryCapacity+(stock?' · Réserve '+C.bagTotal(stock).toFixed(1)+(e.id==='depot'?' (capacité par ressource)':e.id==='car'?' / '+(g.worldEvolution?.vehicleProfile().cargo||80):' / 60'):' · Réserve indisponible'));write(status,v.transfers.reason||v.message||'G conserve le dépôt rapide du sac dans le coffre.');for(const[k,b,id]of [['heal',heal,null],['repair',repair,null],['cache',cache,v.focus?.id]]){const q=g.fieldSupplies.preview(k,id);b.disabled=!q.ok||!!v.task;b.title=q.ok?'Paiement après achèvement.':q.reason;}cancel.disabled=!v.task;write(hint,v.focus?'Cible : '+v.focus.label+' · '+v.focus.left.toFixed(1)+' restant. '+(g.fieldSupplies.hasCache(v.focus.id)?'Relais déjà aménagé.':cache.title):'Approchez un contenant puis utilisez T pour choisir la cible.');if(document.activeElement!==reserve)reserve.value=v.reserve;
const rp=g.fieldSupplies.routePlan();write(route,rp?(rp.target?'Aller vers '+rp.target+' puis retour':'Retour seul')+' par la jonction '+rp.gate+' : '+(rp.metres/1000).toFixed(2)+' km. Carburant estimé '+rp.fuel.toFixed(1)+' + 25 % de détour + '+rp.reserve.toFixed(1)+' de marge = '+rp.required.toFixed(1)+'. Emporté avec le véhicule : '+rp.available.toFixed(1)+(rp.vehicle?(rp.shortfall>.01?' — réserve insuffisante.':' — budget indicatif couvert.'):' — aucun véhicule utilisable.')+(rp.localSegmentVerified?' Région '+(rp.regionalMetres/1000).toFixed(2)+' km · portions dans D-17 '+(rp.localMetres/1000).toFixed(3)+' km. '+rp.note+' Ces passages peuvent changer après une construction ou un dégât ; aucun pilotage automatique.':' Les raccordements peuvent être bloqués ; ce calcul ne conduit pas le véhicule.'):'Aucun trajet calculable.');
const ck=JSON.stringify(v.caches);if(ck!==cacheKey){cacheKey=ck;cacheList.replaceChildren();if(!v.caches.length)cacheList.append(make('p','Aucun relais aménagé.'));for(const c of v.caches){const end=v.endpoints.find(e=>e.id===c.id),card=make('article');card.append(make('strong',end?.name||c.id),make('span',C.bagTotal(c.stock).toFixed(1)+' / 60'),button('REPÈRE','supplyPin-'+c.id,()=>g.frontier.pin(c.id.split(':')[0])),button('RETIRER À VIDE','supplyRemove-'+c.id,()=>g.fieldSupplies.remove(c.id)));cacheList.append(card);}}}
const update=g.updateUI.bind(g);g.updateUI=(...a)=>{const r=update(...a);refresh();return r;};const ui=g.frontierUI;g.frontierUI=Object.freeze({...ui,refresh:(...a)=>{ui.refresh(...a);refresh(...a);}});g.fieldSuppliesUI=Object.freeze({open,refresh});refresh(true);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();})(globalThis);
