/* Physical expedition logistics: transactional transfers and interruptible field work. */
(function(root){'use strict';
function install(g){if(g.fieldSupplies)return g.fieldSupplies;const C=root.DeadwallCore,L=C.FieldSupplies,R=L.RULES,P=root.DeadwallAtlasProjection||(typeof require==='function'?require('./atlas-projection.js'):null),Survey=root.DeadwallFrontierSurvey||(typeof require==='function'?require('./frontier-survey.js'):null);let state=L.initial(),home=g.world,pending=null,task=null,message='',routeMemo=null;
const wrap=(name,fn)=>{const old=g[name].bind(g);g[name]=(...a)=>fn(old,...a);};
function ensure(){if(home!==g.world){home=g.world;state=L.normalize(pending||undefined);pending=null;task=null;message='';routeMemo=null;}return state;}
const can=()=>!g.expansions?.busy('fieldSupplies')&&!g.essentials?.busy()&&g.state==='playing'&&!g.gameOver&&!g.player.dead&&g.player.health>0&&g.canIssueCommand();
function fail(text){message=text;return{ok:false,reason:text};}
function current(){ensure();return g.frontier.overview();}
function safe(f){return ![...f.enemies,...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[])].some(e=>e.hp>0&&e.z===f.z&&(e.z===0||e.poi===f.inside)&&Math.hypot(e.x-f.x,e.y-f.y)<R.safeRadius&&g.frontier.visibleEnemy(e));}
function accessible(f,id){if(!f.active||f.car?.driving)return false;return Survey.targets(f.world,f,f.taken,C.Frontier.RULES.lootReach).some(b=>b.id===id);}
function stockEnd(f,endpoint){if(endpoint==='depot'){if(f.active||!g.workerCanWorkAt(g.player,g.core(),125))return null;return{bag:g.resources,capacity:g.storage,individual:true};}
if(!f.active||!safe(f)||f.car?.driving)return null;if(endpoint==='car'){if(!g.frontier.vehiclePresent())return null;const car=g.expeditions.car();return car&&car.health>0?{bag:car.cargo,capacity:g.worldEvolution?.vehicleProfile().cargo||C.Expeditions.RULES.cargo,individual:false}:null;}
const cache=state.caches.find(c=>c.id===endpoint);return cache&&accessible(f,cache.id)?{bag:cache.stock,capacity:R.cacheCapacity,individual:false}:null;}
const transferAccessReason='Rejoignez le dépôt, le coffre ou le relais sur le bon niveau, par un accès libre.';
function transferHandlingReason(){if(g.fieldcraft?.context?.().mounted)return'Quittez le poste de tir avant de manipuler les réserves.';return!can()||task||g.player.reload>0?'Terminez le rechargement ou annulez l’action de terrain.':'';}
function transferQuote(endpoint,key,direction,amount,context){
 ensure();const reason=context?context.handling:transferHandlingReason();if(reason)return{ok:false,reason};
 if(!C.RESOURCE_KEYS.includes(key)||!['deposit','withdraw'].includes(direction)||!(amount==='max'||Number.isFinite(amount)&&amount>0&&amount<=1e6))return{ok:false,reason:'Transfert invalide.'};
 const end=context?context.end:stockEnd(current(),endpoint);if(!end)return{ok:false,reason:transferAccessReason};
 const source=direction==='deposit'?g.player.carry:end.bag,target=direction==='deposit'?end.bag:g.player.carry,room=direction==='deposit'?(end.individual?Math.max(0,end.capacity-target[key]):Math.max(0,end.capacity-C.bagTotal(target))):Math.max(0,g.player.carryCapacity-C.bagTotal(target));
 const n=Math.min(amount==='max'?1e6:amount,source[key],room);if(n<=1e-7)return{ok:false,reason:source[key]<=1e-7?'Aucune ressource disponible.':'Destination pleine.'};
 return{ok:true,amount:n,reason:direction==='deposit'?'Transférer depuis le sac':'Reprendre dans le sac',source,target};
}
const publicTransferQuote=q=>q.ok?{ok:true,amount:q.amount,reason:q.reason}:{ok:false,reason:q.reason};
function previewTransfer(endpoint,key,direction,amount='max'){return publicTransferQuote(transferQuote(endpoint,key,direction,amount));}
function transfer(endpoint,key,direction,amount){const q=transferQuote(endpoint,key,direction,amount);if(!q.ok)return fail(q.reason);const{source,target}=q,n=q.amount;source[key]-=n;target[key]+=n;if(Math.abs(source[key])<1e-8)source[key]=0;if(endpoint==='depot'&&direction==='deposit'){g.depositedResources+=n;g.chronicles131?.recordDeposit(n);}message=n.toFixed(1)+' '+C.RESOURCE_META[key].label+' transférés.';g.save(false);return{ok:true,amount:n};}
function check(kind,id=null){ensure();if(!can())return fail('Le commandant doit être disponible.');const f=current();if(!f.active||f.car?.driving)return fail('Descendez du véhicule dans la région.');if(g.player.reload>0)return fail('Attendez la fin du rechargement.');if(!safe(f))return fail('Un infecté trop proche empêche cette opération.');let cost,time;
if(kind==='heal'){if(g.player.health>=g.player.maxHealth-.001)return fail('Aucun soin nécessaire.');cost=R.healCost;time=R.healTime;}
else if(kind==='repair'){const v=g.expeditions.car();if(g.phase!=='calm')return fail('La réparation attendra le jour.');if(!g.frontier.vehiclePresent()||!v||v.health<=0)return fail('Rejoignez le véhicule intact, moteur arrêté.');if(v.health>=(g.worldEvolution?.vehicleProfile()?.health||C.Expeditions.RULES.carHealth)-.001)return fail('Le véhicule ne nécessite pas de réparation.');cost=R.repairCost;time=R.repairTime;}
else if(kind==='cache'){if(g.phase!=='calm')return fail('L’aménagement attendra le jour.');if(state.caches.length>=R.maxCaches)return fail('La limite de relais est atteinte.');if(state.caches.some(c=>c.id===id))return fail('Ce contenant est déjà un relais.');const b=typeof id==='string'?L.resolve(f.world,id):null;if(!b||!R.cacheKinds.includes(b.kind)||!f.seen.includes(b.poi)||!accessible(f,id))return fail('Choisissez une caisse, une armoire ou un rayonnage accessible.');if((f.taken[id]||0)<b.amount-1e-7)return fail('Videz d’abord ce contenant.');cost=R.cacheCost;time=R.cacheTime;}
else return fail('Opération inconnue.');if(Object.entries(cost).some(([k,n])=>g.player.carry[k]+1e-7<n))return fail('Matériaux nécessaires dans le sac, pas dans le dépôt distant.');return{ok:true,cost,time,position:{x:f.x,y:f.y,z:f.z,inside:f.inside},carId:f.car?.id||null};}
function begin(kind,id=null){if(task)return fail('Une action est déjà en cours.');const q=check(kind,id);if(!q.ok)return q;task={kind,id,...q,elapsed:0,health:g.player.health,carHealth:g.expeditions.car()?.health??0,pulse:0};message=kind==='heal'?'Pansement en cours…':kind==='repair'?'Réparation de terrain…':'Aménagement du relais…';g.releaseInputs();if(g.activeOverlay===g.ui.commandModal)g.showCommand(false);return{ok:true};}
function cancel(reason='Action interrompue ; aucune ressource dépensée.'){if(!task)return false;task=null;message=reason;return true;}
function tick(dt){if(!task)return;const f=current(),t=task;if(!f.active||g.player.dead||g.gameOver||Math.hypot(f.x-t.position.x,f.y-t.position.y)>.06||f.z!==t.position.z||f.inside!==t.position.inside||g.player.health<t.health-.00001||g.expeditions.car()?.health<t.carHealth-.00001){cancel();return;}const q=check(t.kind,t.id);if(!q.ok){cancel(q.reason+' Aucune ressource dépensée.');return;}
t.elapsed+=dt;t.pulse-=dt;if(t.kind!=='heal'&&t.pulse<=0){g.frontier.signalWork?.();t.pulse=.8;}if(t.elapsed+1e-8<t.time)return;
for(const[k,n]of Object.entries(q.cost))g.player.carry[k]=Math.max(0,g.player.carry[k]-n);if(t.kind==='heal')g.player.health=Math.min(g.player.maxHealth,g.player.health+R.healAmount);if(t.kind==='repair'){const v=g.expeditions.car();v.health=Math.min((g.worldEvolution?.vehicleProfile()?.health||C.Expeditions.RULES.carHealth),v.health+R.repairAmount);}if(t.kind==='cache')state.caches.push({id:t.id,stock:L.emptyBag()});message=t.kind==='heal'?'Pansement terminé.':t.kind==='repair'?'Réparation terminée.':'Relais aménagé, stock initial vide.';task=null;g.save(false);}
function remove(id){ensure();if(!can()||task)return false;const f=current(),index=state.caches.findIndex(c=>c.id===id);if(index<0||!accessible(f,id)||!safe(f)||C.bagTotal(state.caches[index].stock)>1e-7)return false;state.caches.splice(index,1);message='Relais retiré ; le contenant reste vide. Aucun remboursement.';g.save(false);return true;}
function reserve(n){ensure();if(!can()||!Number.isFinite(n)||n<0||n>8)return false;state.reserve=n;routeMemo=null;g.save(false);return true;}
function routePlan(){ensure();const f=current();if(f.generation>=7)return routePlan141(f);const origin=f.active?{x:f.x,y:f.y}:P.toRegion(g.player.x,g.player.y,g),key=[f.world.seed,f.generation,origin.x.toFixed(1),origin.y.toFixed(1),f.pin,state.reserve].join(':');let result;if(routeMemo?.key===key)result=routeMemo.value;else{const Routing=root.DeadwallFrontierRouting||(typeof require==='function'?require('./frontier-routing.js'):null),target=f.pin?f.world.pois.find(p=>p.id===f.pin):null,outward=target?Routing.route(f.world,origin,target):null,start=outward?outward.path[outward.path.length-1]:origin,gates=P.gatesFor(g);const options=gates.map(p=>{const route=Routing.route(f.world,start,{drive:{a:p,b:p}});return route?{...route,gate:p.name}:null;}).filter(Boolean).sort((a,b)=>a.metres-b.metres);if(!options.length)return null;const back=options[0],distance=(outward?.metres||0)+back.metres;result={target:target?.name||null,gate:back.gate,outwardMetres:outward?.metres||0,returnMetres:back.metres,metres:distance,path:back.path};routeMemo={key,value:result};}
const v=g.expeditions.car(),rate=g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre,cost=metres=>g.travel131?.fuelCost(metres,rate,v?.id??null)??metres*rate,fuel=cost(result.metres),withDetour=cost(result.metres*R.detourFactor),reserve=rate>0?state.reserve:0,required=withDetour+reserve,available=v&&v.health>0?v.fuel+(f.car||!f.active?v.cargo.fuel:0)+g.player.carry.fuel:0;return{...result,fuel,margin:withDetour-fuel,reserve,required,available,vehicle:!!v&&v.health>0,shortfall:Math.max(0,required-available)};}
// G7 treats D-17 and the regional terrain as distinct physical domains.
// The shared local search checks departure/return; regional roads cannot cross
// the local enclosure and use their own fuel rate.
function routePlan141(f){
 const Routing=root.DeadwallFrontierRouting||(typeof require==='function'?require('./frontier-routing.js'):null),Return=root.DeadwallReturnRoutes||(typeof require==='function'?require('./return-routes.js'):null),v=g.expeditions.car(),vehicle=!!v&&v.health>0&&(!f.active||!!f.car),mode=vehicle?'car':'foot',local=!f.active&&!f.car,origin=local?vehicle?{x:v.x,y:v.y}:{x:g.player.x,y:g.player.y}:f.car?{x:f.car.x,y:f.car.y}:{x:f.x,y:f.y};
 if(f.active&&f.z!==0)return null;
 const key=['G7',f.world.seed,f.generation,origin.x,origin.y,f.pin,state.reserve,mode,v?.id||0,g.worldEvolution?.vehicleProfile()?.w,g.worldEvolution?.vehicleProfile()?.h,Return.signature(g)].join(':');let result;
 if(routeMemo?.key===key)result=routeMemo.value;else{
  const target=f.pin?f.world.pois.find(p=>p.id===f.pin):null,departures=local?Return.departures(g,mode,origin):[{region:origin,localMetres:0,localPath:[]}],returnSearch=Return.adaptiveSearch(g,mode),arrivals=[];
  for(const gate of P.gatesFor(g))for(const offset of C.ReturnRouteRules.gateOffsets){const ew=gate.id==='east'||gate.id==='west',entry={x:gate.localX+(ew?0:offset),y:gate.localY+(ew?offset:0)},back=returnSearch.find(entry);if(!back.path)continue;arrivals.push({...gate,region:{x:gate.x+(ew?0:offset/32),y:gate.y+(ew?offset/32:0)},localMetres:back.metres,localPath:back.path});break;}
  const options=[];
  for(const departure of departures){const outward=target?Routing.route(f.world,departure.region,target):null;if(target&&!outward)continue;const start=outward?outward.path.at(-1):departure.region;
   for(const arrival of arrivals){const back=Routing.route(f.world,start,{drive:{a:arrival.region,b:arrival.region}});if(!back)continue;const regionalMetres=(outward?.metres||0)+back.metres,localMetres=departure.localMetres+arrival.localMetres;options.push({target:target?.name||null,gate:arrival.name,outwardMetres:outward?.metres||0,returnMetres:back.metres,regionalMetres,localMetres,departureLocalMetres:departure.localMetres,returnLocalMetres:arrival.localMetres,metres:regionalMetres+localMetres,path:back.path,outwardPath:outward?.path||[],departureLocalPath:departure.localPath,returnLocalPath:arrival.localPath,localSegmentVerified:true,note:'Trajet régional contournant D-17 ; départ et retour locaux vérifiés dans les obstacles courants.'});}
  }
  options.sort((a,b)=>a.metres-b.metres);if(!options.length)return null;result=options[0];routeMemo={key,value:result};
 }
 const rate=vehicle?(g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre):0,localRate=C.Expeditions.RULES.fuelPerUnit*32*(rate/(C.WorldEvolution.RULES.vehicles.break.fuel||C.Frontier.RULES.fuelPerMetre)),cost=(metres,r)=>g.travel131?.fuelCost(metres,r,v?.id??null)??metres*r;
 const budget=factor=>{const a=result.departureLocalMetres*factor,b=result.regionalMetres*factor,c=result.returnLocalMetres*factor;return cost(a,localRate)+(cost(a+b,rate)-cost(a,rate))+(cost(a+b+c,localRate)-cost(a+b,localRate));},fuel=budget(1),withDetour=budget(R.detourFactor),reserve=rate>0?state.reserve:0,required=withDetour+reserve,available=vehicle?v.fuel+(f.car||!f.active?v.cargo.fuel:0)+g.player.carry.fuel:0;
 return{...result,...Object.fromEntries(['path','outwardPath','departureLocalPath','returnLocalPath'].map(key=>[key,result[key].map(p=>({...p}))])),fuel,margin:withDetour-fuel,reserve,required,available,vehicle,shortfall:Math.max(0,required-available)};
}
function preview(kind,id=null){const before=message,q=check(kind,id);message=before;return q;}
function overview(endpoint,amount='max'){const f=current(),ends=[{id:'car',name:'Coffre · '+(g.worldEvolution?.vehicleProfile()?.name||'Véhicule'),available:!!stockEnd(f,'car')},{id:'depot',name:'Dépôt de D-17',available:!!stockEnd(f,'depot')},...state.caches.map(c=>{const b=L.resolve(f.world,c.id);return{id:c.id,name:'Relais · '+(b?.place||c.id)+' · '+(b?.room||'réserve')+(b?.z?' · niveau '+b.z:''),available:!!stockEnd(f,c.id),stock:{...c.stock}};})];let transfers;
 if(endpoint!==undefined){const selected=ends.some(e=>e.id===endpoint)?endpoint:ends.find(e=>e.available)?.id||'car',context={handling:transferHandlingReason(),end:stockEnd(f,selected)};
  // One physical context serves the table; a click always obtains a fresh quote.
  transfers={endpoint:selected,reason:context.handling||(!context.end?transferAccessReason:''),rows:Object.fromEntries(C.RESOURCE_KEYS.map(key=>[key,Object.fromEntries(['deposit','withdraw'].map(direction=>[direction,publicTransferQuote(transferQuote(selected,key,direction,amount,context))]))]))};
 }
 return{...L.normalize(state),endpoints:ends,bag:{...g.player.carry},car:g.expeditions.car()?{...g.expeditions.car().cargo}:null,message,focus:f.focus,...(transfers?{transfers}:{}),task:task?{kind:task.kind,elapsed:task.elapsed,time:task.time,x:task.position.x,y:task.position.y,progress:task.elapsed/task.time}:null};}
const stopKeys=['KeyW','KeyA','KeyS','KeyD','KeyQ','KeyZ','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyF','KeyE','KeyR','PageUp','PageDown','Digit1','Digit2','Digit3'];
g.fieldSupplies=Object.freeze({transfer,previewTransfer,begin,cancel,remove,reserve,routePlan,overview,preview,snapshot:()=>{ensure();return L.normalize(state);},busy:()=>!!task,hasCache:id=>{ensure();return state.caches.some(c=>c.id===id);},cacheSummary:id=>{ensure();const c=state.caches.find(c=>c.id===id);return c?{amount:C.bagTotal(c.stock),capacity:R.cacheCapacity}:null;}});
wrap('update',(old,dt)=>{ensure();const running=g.state==='playing'&&!g.paused&&!g.gameOver;if(running&&task&&(stopKeys.some(k=>g.input.keys.has(k)||g.input.pressed.has(k))||g.input.mouseDown||g.input.touchFire))cancel();const r=old(dt);if(running&&task)tick(Math.max(0,Math.min(dt,.1)));return r;});
wrap('serialize',(old,...a)=>{ensure();return{...old(...a),fieldSupplies:L.normalize(state)};});
wrap('restoreSave',(old,raw)=>{const record=L.validate(raw?.version>=17&&raw.version<=C.SAVE_VERSION?raw.fieldSupplies:undefined,raw);pending=record;try{const r=old(raw);ensure();return r;}catch(e){pending=null;throw e;}});
wrap('startNew',(old,...a)=>{const before=g.world,r=old(...a);if(g.world!==before){pending=null;ensure();state=L.initial();task=null;message='';}return r;});wrap('returnToMenu',(old,...a)=>{cancel();return old(...a);});
return g.fieldSupplies;}
const api={install};root.DeadwallFrontierCare=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
