/* The regional record is independent of renderer and of the home simulation. */
(function(root){'use strict';const W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),cache=new Map();
const MAX_TAKEN=120000;
function initial(){return{version:2,generation:3,quiet:false,tracks:{},notes:{},pin:null,active:false,x:4162,y:4096,z:0,inside:null,a:0,anchor:null,car:null,seen:[],taken:{},enemies:{},distance:0,shots:0,kills:0};}
function normalize(raw){if(raw===undefined)return initial();if(!raw||typeof raw!=='object'||Array.isArray(raw)||![1,2].includes(raw.version))throw Error('Registre régional invalide.');const s=initial();s.generation=raw.version===1?1:raw.generation;if(![1,2,3,4,5,6,7].includes(s.generation))throw Error('Génération inconnue');if(raw.quiet!==undefined&&typeof raw.quiet!=='boolean')throw Error('Marche prudente invalide');s.quiet=raw.quiet??false;const size=W.sizeForGeneration(s.generation),num=(v,lo,hi,int=false)=>{if(!Number.isFinite(v)||v<lo||v>hi||int&&!Number.isInteger(v))throw Error('Valeur régionale invalide.');return v;};
if(typeof raw.active!=='boolean')throw Error('État régional invalide.');s.active=raw.active;s.x=num(raw.x,.32,size-.32);s.y=num(raw.y,.32,size-.32);s.z=num(raw.z,-1,2,true);s.a=num(raw.a,-1e5,1e5);s.inside=raw.inside===null?null:raw.inside;if(s.inside!==null&&(typeof s.inside!=='string'||!/^P\d{4}$/.test(s.inside)))throw Error('Lieu absent.');
if(raw.anchor!==null){if(!raw.anchor)throw Error('Ancre absente');s.anchor={x:num(raw.anchor.x,0,4096),y:num(raw.anchor.y,0,4096)};}if(s.active&&!s.anchor)throw Error('Sortie sans point de retour.');if(!s.active&&s.z!==0)throw Error('Étage hors région.');
if(raw.car!==null){const c=raw.car;if(!c||typeof c.driving!=='boolean')throw Error('État de voiture invalide.');s.car={id:num(c.id,1,2147483646,true),x:num(c.x,3,size-3),y:num(c.y,3,size-3),a:num(c.a,-1e5,1e5),driving:c.driving};if(c.driving&&(!s.active||s.z!==0||Math.hypot(c.x-s.x,c.y-s.y)>.001))throw Error('Conducteur et voiture désynchronisés.');}
if(!Array.isArray(raw.seen)||raw.seen.length>5000)throw Error('Trop de découvertes.');s.seen=[...new Set(raw.seen)];if(s.seen.some(id=>typeof id!=='string'||!/^P\d{4}$/.test(id)))throw Error('Identifiant de découverte invalide.');
if(raw.version===2){if(!raw.notes||typeof raw.notes!=='object'||Array.isArray(raw.notes)||Object.keys(raw.notes).length>5000)throw Error('Carnet invalide');for(const[id,n]of Object.entries(raw.notes)){if(!/^P\d{4}$/.test(id)||!['todo','visited','cleared','danger'].includes(n))throw Error('Note invalide');s.notes[id]=n;}if(raw.pin!==null&&(typeof raw.pin!=='string'||!/^P\d{4}$/.test(raw.pin)))throw Error('Repère invalide');s.pin=raw.pin;}
for(const [name,max,re]of [['taken',MAX_TAKEN,/^(P\d{4}:(-?\d+:\d+|car:\d+|out:\d+)|[TR]\d+_\d+_\d+)$/],['enemies',15000,/^P\d{4}:e\d+$/]]){const input=raw[name];if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length>max)throw Error('Registre régional trop grand.');for(const[id,v]of Object.entries(input)){if(!re.test(id))throw Error('Identifiant régional invalide.');s[name][id]=num(v,0,name==='taken'?1000:80);}}
if(raw.tracks!==undefined){if(!raw.tracks||typeof raw.tracks!=='object'||Array.isArray(raw.tracks)||Object.keys(raw.tracks).length>15000)throw Error('Suivi régional invalide');for(const[id,b]of Object.entries(raw.tracks)){if(!/^P\d{4}:e\d+$/.test(id)||!b||!['idle','investigate','pursuit','search'].includes(b.mode))throw Error('Poursuite invalide');s.tracks[id]={x:num(b.x,.32,size-.32),y:num(b.y,.32,size-.32),z:num(b.z,-1,2,true),a:num(b.a,-1e5,1e5),mode:b.mode,ttl:num(b.ttl,0,16),gx:num(b.gx,.32,size-.32),gy:num(b.gy,.32,size-.32),cool:num(b.cool,0,2)};}}
s.distance=num(raw.distance||0,0,1e9);s.shots=num(raw.shots||0,0,1e9,true);s.kills=num(raw.kills||0,0,1e8,true);return s;}
function validate(state,data){const s=normalize(state);if(!s.active&&!s.car&&!s.seen.length&&!Object.keys(s.taken).length&&!Object.keys(s.enemies).length&&!Object.keys(s.notes).length&&s.pin===null&&!Object.keys(s.tracks).length)return s;
let w=cache.get(data.worldSeed+':'+s.generation);if(!w){w=W.create(data.worldSeed,s.generation);cache.set(data.worldSeed+':'+s.generation,w);if(cache.size>3)cache.delete(cache.keys().next().value);}const by=new Map(w.pois.map(p=>[p.id,p]));if(Object.keys(s.notes).some(id=>!s.seen.includes(id))||s.pin!==null&&!s.seen.includes(s.pin))throw Error('Repère sur lieu non découvert');if(s.seen.some(id=>!by.has(id)))throw Error('Lieu absent de cette graine.');if(s.inside!==null&&!by.has(s.inside))throw Error('Intérieur absent de cette graine.');if(s.z!==0&&(!by.get(s.inside)?.levels.includes(s.z)))throw Error('Étage non construit.');
if(s.z!==0){const p=by.get(s.inside),q=G.local(p,s.x,s.y);if(q.x<0||q.y<0||q.x>p.w||q.y>p.h)throw Error('Position hors étage.');
 // Earlier stair transitions retained approach coordinates even when another
 // floor had a wall there. Recover only that narrow, identifiable old landing.
 const pad=w.plan(p,s.z).stairs[0],radius=W.RULES.footRadius;
 if(pad&&(data.worldEvolution?.structures?.[p.id]??1)>.001&&w.blocked(s.x,s.y,radius,s.z,p.id)){
  const center=G.global(p,pad.x+pad.w/2,pad.y+pad.h/2);
  if(Math.hypot(s.x-center.x,s.y-center.y)<=1.8&&!w.blocked(center.x,center.y,radius,s.z,p.id)){s.x=center.x;s.y=center.y;}
 }
}
for(const[id,amount]of Object.entries(s.taken)){let obj;if(id[0]==='P'){const [key,z,n]=id.split(':'),p=by.get(key);if(!p)throw Error('Contenant dans un lieu absent.');obj=z==='out'?(p.outdoor||[]).find(q=>q.id===id):z==='car'?p.parking.find(q=>q.id===id):p.levels.includes(Number(z))?w.plan(p,Number(z)).objects.find(q=>q.id===id):null;}else{const match=/^([TR])(\d+)_(\d+)_(\d+)$/.exec(id);const c=w.chunk(Number(match[2]),Number(match[3]));obj=[...c.trees,...c.rocks,...(c.cleared||[])].find(q=>q.id===id);}if(!obj||amount>obj.amount+.000001)throw Error('Prélèvement supérieur au contenant.');}
for(const id of new Set([...Object.keys(s.enemies),...Object.keys(s.tracks)])){const [p,e]=id.split(':');if(!by.has(p)||Number(e.slice(1))>=w.threatCount(by.get(p)))throw Error('Menace régionale inexistante.');if(s.generation>=6&&s.enemies[id]!==undefined){const site=by.get(p),B=root.DeadwallBiomes135||(typeof require==='function'?require('./biomes135.js'):null);if(s.enemies[id]>B.enemyProfile(w.seed,site.x,site.y,id,{generation:s.generation}).health)throw Error('Intégrité de contact incompatible avec son profil.');}}
for(const[id,b]of Object.entries(s.tracks)){const p=by.get(id.split(':')[0]),index=Number(id.split(':e')[1]),expected=p.levels[G.hash(p.id,index)%p.levels.length];if(b.z!==expected||s.enemies[id]===0)throw Error('Poursuite hors niveau');if(b.z!==0){const q=G.local(p,b.x,b.y),t=G.local(p,b.gx,b.gy);if(q.x<.3||q.y<.3||q.x>p.w-.3||q.y>p.h-.3||t.x<.3||t.y<.3||t.x>p.w-.3||t.y>p.h-.3)throw Error('Poursuite hors bâtiment');}}
if(s.kills!==Object.values(s.enemies).filter(h=>h===0).length)throw Error('Compteur régional contradictoire.');
if(s.car&&data.expeditions?.vehicle?.id!==s.car.id)throw Error('Voiture étrangère à la campagne.');if(s.active&&Math.hypot(data.player.x-s.anchor.x,data.player.y-s.anchor.y)>.01)throw Error('Position locale modifiée en sortie.');return s;}
const api={MAX_TAKEN,initial,normalize,validate};root.DeadwallFrontierState=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
