/* Reachable object selection and hearing/last-known-position AI. No hidden loot creation. */
(function(root){'use strict';const G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null);
const names={car:'Véhicule abandonné',tree:'Arbre',rock:'Roche',crate:'Caisse',shelf:'Rayonnage',medical:'Armoire de soins',fridge:'Réfrigérateur',fuel:'Bidon',desk:'Bureau',bed:'Lit',sofa:'Canapé',table:'Table',wardrobe:'Armoire',workbench:'Établi',logs:'Bois empilé',rubble:'Débris',machine:'Machine arrêtée',counter:'Comptoir',oven:'Four arrêté',washer:'Lave-linge',kennel:'Chenil vide',plantTray:'Table de plants',tirePile:'Pneus',hoseRack:'Râtelier',bench:'Banc',sink:'Évier',pump:'Pompe',dentalChair:'Fauteuil dentaire',sterilizer:'Stérilisateur arrêté',steelTable:'Table inox',dishRack:'Râtelier de plonge',timberRack:'Stock de planches',sawBench:'Banc de découpe arrêté',clampRack:'Râtelier de serre-joints',palletStack:'Palettes',generator:'Groupe arrêté',electricalRack:'Baie électrique'};
function edge(origin,b){if(b.r){const dx=origin.x-b.x,dy=origin.y-b.y,d=Math.hypot(dx,dy)||1;return{x:b.x+dx/d*b.r,y:b.y+dy/d*b.r};}const p={x:b.x,y:b.y,w:b.w,h:b.h,a:b.worldAngle??b.a??0},q=G.local(p,origin.x,origin.y);return G.global(p,Math.max(0,Math.min(p.w,q.x)),Math.max(0,Math.min(p.h,q.y)));}
function targets(world,state,taken,reach=1.6){return world.containers(state.x,state.y,3,state.z,state.inside).map(b=>{const point=edge(state,b);return{...b,point,distance:Math.hypot(point.x-state.x,point.y-state.y),left:Math.max(0,b.amount-(taken[b.id]||0)),label:b.label||names[b.kind]||'Contenant'};}).filter(b=>b.distance<=reach&&world.line(state,b.point,state.z,state.inside,b.id,.025)).sort((a,b)=>a.distance-b.distance||a.id.localeCompare(b.id));}
function record(e){return{x:e.x,y:e.y,z:e.z,a:e.a,mode:e.mode||'idle',ttl:e.ttl||0,gx:e.gx??e.x,gy:e.gy??e.y,cool:e.cool||0};}
function hear(world,enemies,state,radius,rules){for(const e of enemies){if(e.z!==state.z||state.z!==0&&e.poi!==state.inside)continue;const d=Math.hypot(e.x-state.x,e.y-state.y),open=world.line(e,state,e.z,e.z?e.poi:null,null,.015);if(d>radius*(open?1:rules.muffled))continue;e.mode='investigate';e.ttl=rules.memory;e.gx=state.x;e.gy=state.y;e.path=null;e.repath=0;}}
function path(world,e,goal,rules,blocked){const step=rules.pathCell,margin=rules.pathMargin;if(Math.hypot(goal.x-e.x,goal.y-e.y)>65)return null;const left=Math.floor((Math.min(e.x,goal.x)-margin)/step),top=Math.floor((Math.min(e.y,goal.y)-margin)/step),width=Math.ceil(Math.abs(e.x-goal.x)/step+margin*2/step)+3,height=Math.ceil(Math.abs(e.y-goal.y)/step+margin*2/step)+3;if(width*height>22000)return null;
const point=i=>({x:(left+i%width)*step+step/2,y:(top+Math.floor(i/width))*step+step/2}),index=(x,y)=>(Math.floor(y/step)-top)*width+Math.floor(x/step)-left,cache=new Map(),free=i=>{if(i<0||i>=width*height)return false;if(!cache.has(i)){const p=point(i);cache.set(i,!blocked(p.x,p.y));}return cache.get(i);};
function closest(p){const cell=index(p.x,p.y),q=[];for(let y=-1;y<=1;y++)for(let x=-1;x<=1;x++){const i=cell+y*width+x;if(free(i)){const v=point(i);if(world.line(p,v,e.z,e.z?e.poi:null,null,rules.enemyRadius))q.push({i,d:Math.hypot(v.x-p.x,v.y-p.y)});}}q.sort((a,b)=>a.d-b.d);return q[0]?.i;}
const start=closest(e),finish=closest(goal);if(start===undefined||finish===undefined)return null;const Core=root.DeadwallCore||(typeof require==='function'?require('./core.js'):null),heap=new Core.MinHeap(),cost=new Map([[start,0]]),parent=new Map(),heur=i=>Math.abs(i%width-finish%width)+Math.abs(Math.floor(i/width)-Math.floor(finish/width));heap.push(start,heur(start));let checked=0;
while(heap.size&&checked++<rules.pathNodes){const node=heap.pop(),i=node.index;if(node.priority!==cost.get(i)+heur(i))continue;if(i===finish){const route=[point(i)];let k=i;while(k!==start){k=parent.get(k);route.push(point(k));}return route.reverse();}for(const delta of [-1,1,-width,width]){const j=i+delta;if(j<0||j>=width*height||Math.abs(i%width-j%width)>1||!free(j))continue;const next=(cost.get(i)||0)+1;if(next>=(cost.get(j)??Infinity))continue;if(!world.line(point(i),point(j),e.z,e.z?e.poi:null,null,rules.enemyRadius))continue;cost.set(j,next);parent.set(j,i);heap.push(j,next+heur(j));}}
return null;}
function step(world,e,state,dt,rules,budget,blocked){e.mode=e.mode||'idle';e.ttl=Math.max(0,(e.ttl||0)-dt);e.repath=Math.max(0,(e.repath||0)-dt);e.cool=Math.max(0,(e.cool||0)-dt);const dx=state.x-e.x,dy=state.y-e.y,d=Math.hypot(dx,dy),angle=Math.atan2(dy,dx),diff=Math.abs(Math.atan2(Math.sin(angle-e.a),Math.cos(angle-e.a))),range=state.quiet&&!state.car?.driving?rules.quietVision:rules.vision;
const sees=d<rules.nearVision||d<range&&(diff<rules.visionHalfAngle||e.mode==='pursuit');if(sees&&world.line(e,state,e.z,e.z?e.poi:null,null,.015)){e.mode='pursuit';e.ttl=rules.memory;e.gx=state.x;e.gy=state.y;}
if(e.ttl<=0){e.mode='idle';e.path=null;return;}if(!Number.isFinite(e.gx+e.gy))return;const goal={x:e.gx,y:e.gy},dist=Math.hypot(goal.x-e.x,goal.y-e.y);if(dist<.65){if(e.mode!=='pursuit'){e.mode='search';e.ttl=Math.min(e.ttl,rules.search);}return;}
let target=goal;if(!world.line(e,goal,e.z,e.z?e.poi:null,null,rules.enemyRadius)){if(!e.path&&e.repath===0&&budget.left>0){budget.left--;e.path=path(world,e,goal,rules,blocked);e.repath=rules.pathCooldown;}if(!e.path?.length)return;while(e.path.length&&Math.hypot(e.path[0].x-e.x,e.path[0].y-e.y)<.18)e.path.shift();if(!e.path.length){e.path=null;return;}target=e.path[0];}else e.path=null;
const vx=target.x-e.x,vy=target.y-e.y,len=Math.hypot(vx,vy);if(len<.01)return;const amount=Math.min(len,rules.enemySpeed*dt),parts=Math.max(1,Math.ceil(amount/.1)),before={x:e.x,y:e.y};e.a=Math.atan2(vy,vx);for(let i=0;i<parts;i++){const x=e.x+vx/len*amount/parts,y=e.y+vy/len*amount/parts;if(!blocked(x,e.y))e.x=x;if(!blocked(e.x,y))e.y=y;}if(Math.hypot(e.x-before.x,e.y-before.y)<.002)e.path=null;
}
const api={names,edge,targets,record,hear,path,step};root.DeadwallFrontierSurvey=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
