/* A field workbench stays in the world: time and threats continue during a puzzle. */
(function(root,factory){'use strict';const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else{root.DeadwallInterventionsUI134=api;const mount=()=>api.install(root.DEADWALL,root.document);if(root.document?.readyState==='loading')root.document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();}})(globalThis,function(){
'use strict';function install(g,doc=globalThis.document){if(g?.interventionsUI134)return g.interventionsUI134;if(!g?.interventions134||!doc?.body)return null;const el=(tag,text,cls)=>{const n=doc.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.classList.add(...cls.split(' '));return n;},add=(p,...ns)=>{for(const n of ns)p.appendChild(n);return p;},button=(id,text,fn)=>{const b=el('button',text);b.id=id;b.type='button';b.addEventListener('click',()=>{if(!b.disabled)fn();});return b;},wrap=(n,fn)=>{if(typeof g[n]!=='function')return;const old=g[n].bind(g);g[n]=(...a)=>fn(old,...a);};
const launch=button('interventions134Button','INTERVENTIONS',()=>open()),dock=el('section',undefined,'interventions134 hidden');dock.id='interventions134Dock';dock.inert=true;dock.setAttribute('aria-labelledby','interventions134Title');dock.setAttribute('role','region');const head=el('header'),title=el('h2','ÉTABLI DE TERRAIN');title.id='interventions134Title';const closeButton=button('interventions134Close','FERMER · ÉCHAP',()=>close(true));const heading=el('div',undefined,'interventions134-heading'),illustration=el('img',undefined,'interventions134-illustration hidden');illustration.alt='';illustration.setAttribute('aria-hidden','true');illustration.decoding='async';add(head,add(heading,illustration,el('small','D-17 / SERVICE DE CAMPAGNE'),title),closeButton);
const warning=el('p','Le temps continue. Une menace proche interrompt le travail.','interventions134-warning'),content=el('div',undefined,'interventions134-content'),status=el('p',undefined,'interventions134-status');status.setAttribute('role','status');status.setAttribute('aria-live','polite');const help=el('details'),hint=el('p','Crochetage : ← / → pour déplacer le crochet ; Entrée pour libérer une goupille lorsque la résistance devient souple. Groupe : alignez le cadran sur le repère de chaque module. Tableau : recopiez le diagnostic avec les quatre interrupteurs. Les matériaux du sac sont consommés au début de chaque tentative. Échap annule. Aucun réglage ne décrit une installation électrique réelle.');add(help,el('summary','MANUEL DE TERRAIN'),hint);add(dock,head,warning,content,status,help);doc.body.appendChild(dock);(doc.getElementById('fieldUtilityTray')||g.ui.hud).appendChild(launch);launch.classList.add('interventions134-launch');let opened=false,signature='',returnFocus=null,last=0;
function firstAction(){return [...content.querySelectorAll('button')].find(b=>!b.disabled)||closeButton;}
function open(){if(!g.player||g.player.dead||g.gameOver||g.paused||g.state!=='playing'||g.activeOverlay)return false;if(opened){refresh(true);return true;}returnFocus=doc.activeElement;opened=true;signature='';dock.classList.remove('hidden');dock.inert=false;g.releaseInputs();refresh(true);firstAction().focus({preventScroll:true});return true;}
function availableFocus(node){
 if(!node||!doc.body.contains(node)||node.disabled||node.hidden||node.closest?.('[inert], .hidden')||!node.getClientRects?.().length)return false;
 for(let parent=node.parentNode;parent;parent=parent.parentNode){
  if(parent.hidden)return false;
  if(parent.tagName==='DETAILS'&&!parent.open){const summary=[...parent.children].find(n=>n.tagName==='SUMMARY');if(!summary?.contains(node))return false;}
 }
 return true;
}
function close(cancel=false){
 if(cancel&&g.interventions134.busy())g.interventions134.cancel();if(!opened)return false;
 const ownedFocus=dock.contains(doc.activeElement);opened=false;dock.classList.add('hidden');dock.inert=true;g.releaseInputs();
 // This is a nonmodal workbench: an interruption must not reclaim focus the
 // player already moved elsewhere, or return it inside a now-closed drawer.
 if(ownedFocus&&g.state==='playing'&&!g.activeOverlay&&!g.paused)(availableFocus(returnFocus)?returnFocus:g.canvas).focus?.({preventScroll:true});
 returnFocus=null;return true;
}
function perform(fn){fn();refresh(true);}
function refresh(force=false){const now=globalThis.performance?.now?.()||0;if(!force&&now-last<160)return;last=now;const visible=g.state==='playing'&&!g.gameOver&&!g.player.dead&&!g.activeOverlay;launch.classList.toggle('hidden',!visible);launch.disabled=!visible||g.paused;if(opened&&(!visible||g.paused)){if(g.interventions134.busy())g.interventions134.cancel('Intervention interrompue : pause ou fenêtre de commandement ouverte.');close();return;}if(!opened)return;const v=g.interventions134.view(),s=v.session,artKey={lock:'art136LockChest',generator:'art136Generator',panel:'art136ElectricalPanel'}[s?.type],picture=globalThis.DeadwallAssets136?.ASSETS?.[artKey];heading.dataset.illustrated=String(!!picture);illustration.classList.toggle('hidden',!picture);if(picture&&illustration.getAttribute('src')!==picture.url)illustration.setAttribute('src',picture.url);status.textContent=v.message;const key=JSON.stringify(v);if(key===signature)return;signature=key;const focused=doc.activeElement,focus=focused?.id,hadContentFocus=content.contains(focused);content.replaceChildren();title.textContent=s?s.label.toUpperCase():'INTERVENTIONS À PORTÉE';
if(!s){const list=el('div',undefined,'interventions134-targets');const actions=g.interventions134.actions();if(!actions.length)add(list,el('p','Approchez un coffre verrouillé, un groupe électrogène ou le tableau situé près de l’entrée d’un local technique.'),el('p','Dans D-17, les groupes endommagés se réparent au contact.'));for(const a of actions){const row=el('article'),b=button('interventions134Action-'+a.id,a.label,()=>perform(a.run));b.disabled=!!a.disabled;add(row,b,el('small',a.reason||''));list.appendChild(row);}content.appendChild(list);}
else{const progress=el('div',undefined,'interventions134-progress');add(progress,el('strong',s.type==='panel'?'DISTRIBUTION':(s.type==='lock'?'GOUPILLE ':'MODULE ')+(s.step+1)+' / '+s.steps),el('span','ERREURS '+s.errors+' / '+s.maxErrors));content.appendChild(progress);if(s.type==='panel'){const circuits=el('div',undefined,'interventions134-circuits'),names=['Éclairage','Auxiliaires','Atelier','Réserve'];for(let i=0;i<4;i++){const b=button('interventions134Switch-'+i,names[i]+' · '+(s.switches[i]?'ACTIF':'COUPÉ'),()=>perform(()=>g.interventions134.act('toggle',i)));b.setAttribute('aria-pressed',String(s.switches[i]));add(circuits,add(el('div'),el('small','DIAGNOSTIC : '+(s.desired[i]?'ACTIF':'COUPÉ')),b));}content.appendChild(circuits);}else{const dial=el('div',undefined,'interventions134-dial');dial.setAttribute('aria-label','Position '+(s.dial+1)+' sur '+s.notches);for(let i=0;i<s.notches;i++){const mark=el('span',String(i+1));mark.classList.toggle('selected',i===s.dial);dial.appendChild(mark);}add(content,el('p',s.type==='lock'?'RÉSISTANCE : '+s.feedback.toUpperCase():'REPÈRE DU MODULE : '+(s.target+1),'interventions134-diagnostic'),dial,add(el('div',undefined,'interventions134-controls'),button('interventions134Left','← AJUSTER',()=>perform(()=>g.interventions134.act('adjust',-1))),button('interventions134Right','AJUSTER →',()=>perform(()=>g.interventions134.act('adjust',1)))));}const confirm=button('interventions134Confirm',s.type==='lock'?'LIBÉRER LA GOUPILLE':s.type==='panel'?'TESTER LA DISTRIBUTION':'VALIDER LE MODULE',()=>perform(()=>g.interventions134.act('confirm')));confirm.classList.add('interventions134-confirm');content.appendChild(confirm);}
if(hadContentFocus){const replacement=focus&&doc.getElementById(focus);(replacement&&content.contains(replacement)&&!replacement.disabled?replacement:firstAction()).focus?.({preventScroll:true});}}
dock.addEventListener('keydown',e=>{if(!opened)return;if(e.code==='Escape'){e.preventDefault();e.stopPropagation();close(true);return;}if(g.interventions134.busy()&&['ArrowLeft','ArrowRight','Enter'].includes(e.code)&&!e.target?.closest?.('summary,input,select,textarea,[contenteditable]')&&!(e.code==='Enter'&&e.target?.closest?.('button,a[href],[role="button"]'))){e.preventDefault();e.stopPropagation();perform(()=>g.interventions134.act(e.code==='Enter'?'confirm':'adjust',e.code==='ArrowLeft'?-1:1));}else e.stopPropagation();});dock.addEventListener('pointerdown',e=>e.stopPropagation());
wrap('onEscape',(old,...a)=>opened?close(true):old(...a));wrap('updateUI',(old,...a)=>{const result=old(...a);refresh();return result;});wrap('returnToMenu',(old,...a)=>{close(true);return old(...a);});wrap('suspendForFocusLoss',(old,...a)=>{close(true);return old(...a);});wrap('showCommand',(old,show,...a)=>{if(show)close(true);return old(show,...a);});wrap('togglePause',(old,...a)=>{if(opened)close(true);return old(...a);});
// Modal entry can stop updateUI altogether; reconcile before the first paused frame.
wrap('syncOverlayFocus',(old,...a)=>{const result=old(...a);refresh(true);return result;});
const api={open,close,refresh,isOpen:()=>opened,element:dock};g.interventionsUI134=Object.freeze(api);refresh(true);return api;}
return{install};});
