/* Physical field interventions. Puzzles are abstract gameplay, never wiring instructions. */
(function(root){
'use strict';
const C=root.DeadwallCore||(typeof require==='function'?require('./core.js'):null),G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),Survey=root.DeadwallFrontierSurvey||(typeof require==='function'?require('./frontier-survey.js'):null);
const rules=()=>C.InterventionRules134,copy=v=>JSON.parse(JSON.stringify(v)),worlds=new Map();
const initial=()=>({version:1,unlocked:[],attempts:{},plants:{},panels:[]});
function objectIn(w,id){const [key,level]=id.split(':'),p=w.pois.find(p=>p.id===key);if(!p)return null;let o,z=0;if(level==='car')o=p.parking.find(o=>o.id===id);else if(level==='out')o=(p.outdoor||[]).find(o=>o.id===id);else {z=Number(level);if(!p.levels.includes(z))return null;o=w.plan(p,z).objects.find(o=>o.id===id);}if(!o)return null;return{...o,...(level==='car'?{}:G.global(p,o.x+o.w/2,o.y+o.h/2)),worldAngle:level==='car'?o.a:p.a,poi:p.id,z};}
function validate(raw,full){if(raw===undefined)return initial();const R=rules(),bad=()=>{throw Error('Registre des interventions invalide.');},exact=(o,keys)=>{if(!o||typeof o!=='object'||Array.isArray(o)||Object.keys(o).length!==keys.length||Object.keys(o).some(k=>!keys.includes(k)))bad();};exact(raw,['version','unlocked','attempts','plants','panels']);if(raw.version!==1)bad();const s=initial(),valid=id=>typeof id==='string'&&/^P\d{4}:(?:(?:-?\d+|out|car):\d+|panel:-?\d+)$/.test(id);for(const k of ['unlocked','panels']){if(!Array.isArray(raw[k])||raw[k].length>R.maxRecords||new Set(raw[k]).size!==raw[k].length)bad();s[k]=raw[k].map(id=>{if(!valid(id)||(k==='panels')!==id.includes(':panel:'))bad();return id;});}for(const k of ['attempts','plants']){if(!raw[k]||typeof raw[k]!=='object'||Array.isArray(raw[k])||Object.keys(raw[k]).length>R.maxRecords)bad();for(const[id,v]of Object.entries(raw[k])){if(!valid(id)&&!(k==='attempts'&&/^local:\d+$/.test(id)))bad();if(k==='attempts'){if(!Number.isSafeInteger(v)||v<1||v>1e6)bad();s.attempts[id]=v;}else{exact(v,['condition','fuel','on']);if(!Number.isFinite(v.condition)||v.condition<0||v.condition>100||!Number.isFinite(v.fuel)||v.fuel<0||v.fuel>R.generator.tank||typeof v.on!=='boolean'||v.on&&(v.condition<=0||v.fuel<=0))bad();s.plants[id]={...v};}}}
if(full){const ids=[...s.unlocked,...s.panels,...Object.keys(s.plants),...Object.keys(s.attempts)];if(ids.some(id=>!id.startsWith('local:'))){const key=full.worldSeed+':'+full.frontier?.generation;if(!worlds.has(key)){worlds.set(key,W.create(full.worldSeed,full.frontier?.generation||3));if(worlds.size>3)worlds.delete(worlds.keys().next().value);}const w=worlds.get(key),seen=new Set(full.frontier?.seen||[]);for(const id of ids){if(id.startsWith('local:'))continue;const p=w.pois.find(p=>p.id===id.split(':')[0]);if(!p||!seen.has(p.id))bad();if(id.includes(':panel:')){if(!p.levels.includes(Number(id.split(':')[2]))||!p.levels.some(z=>w.plan(p,z).objects.some(o=>o.kind==='generator')))bad();}else{const o=objectIn(w,id);if(!o||s.plants[id]&&o.kind!=='generator'||s.unlocked.includes(id)&&(!['car','medical','wardrobe','crate','electricalRack'].includes(o.kind)||o.sealed131))bad();}}}}return s;}
function install(g){if(g.interventions134)return g.interventions134;if(!g.expansions)return null;const R=rules();if(!R)throw Error('InterventionRules134 requis.');let state=initial(),session=null,message='',authorized=null,cachedWorld=null,objectCache=new Map(),poweredSites=new Set(),connectedPanels=new Set();const wrap=(name,fn)=>{if(typeof g[name]!=='function')return;const old=g[name].bind(g);g[name]=(...a)=>fn(old,...a);},world=()=>g.frontier.world(),pos=()=>{const f=g.frontier.position();return f.active?{domain:'region',x:f.x,y:f.y,z:f.z,inside:f.inside}:{domain:'local',x:g.player.x,y:g.player.y,z:0,inside:null};},fail=reason=>{message=reason;return{ok:false,reason};},alive=()=>g.state==='playing'&&!g.gameOver&&g.player&&!g.player.dead&&g.player.health>0,driving=()=>g.expeditions.driving()||g.frontier.position().car?.driving;
function plantUsable(id){return amountTaken(id)===0&&!g.worldEvolution?.structureDestroyed(id.split(':')[0]);}
function refreshPower(){poweredSites=new Set(Object.entries(state.plants).filter(([id,s])=>s.on&&s.fuel>0&&s.condition>0&&plantUsable(id)).map(([id])=>id.split(':')[0]));connectedPanels=new Set(state.panels);}
function resolve(id){const w=world();if(w!==cachedWorld){cachedWorld=w;objectCache.clear();}if(!objectCache.has(id))objectCache.set(id,objectIn(w,id));return objectCache.get(id);}
function amountTaken(id){return g.frontier.takenAmount?g.frontier.takenAmount(id):(g.frontier.snapshot().taken[id]||0);}
function lockType(o){if(o.sealed131)return{name:'Réserve de ravitaillement',pins:4};return({car:{name:'Coffre de véhicule',pins:3},medical:{name:'Armoire médicale',pins:4},wardrobe:{name:'Casier personnel',pins:2},crate:{name:'Caisse cadenassée',pins:3},electricalRack:{name:'Baie technique verrouillée',pins:4}})[o.kind]||null;}
function blocksLoot(o){if(!o||o.id?.startsWith('local:'))return false;if(state.plants[o.id]?.on)return true;if(o.sealed131)return!g.worldOps131?.opened(o.poi);if(state.unlocked.includes(o.id)||(Number.isFinite(o.left)?o.amount-o.left:amountTaken(o.id))>0)return false;return!!lockType(o)&&G.hash(g.world.seed,o.id,'lock134')/4294967296<R.lockChance;}
function panel(p,z){const q=G.global(p,p.w/2+1.05,1.1);return{id:p.id+':panel:'+z,...q,poi:p.id,z,kind:'panel',label:'Tableau de distribution',domain:'region',point:q};}
function decorate(o){const lock=!state.plants[o.id]?.on&&blocksLoot(o),plant=state.plants[o.id],type=lockType(o);return{...o,domain:'region',type:lock?'lock':o.kind==='generator'?'generator':o.kind==='panel'?'panel':null,label:lock?type.name:o.kind==='generator'?'Groupe électrogène':o.label,lock,plant:plant?{...plant}:null,pins:type?.pins};}
function nearby(){const f=g.frontier.position();if(!f.active){return [...g.world.buildings.values()].filter(b=>!b.dead&&b.health>0&&b.completed&&(b.type==='generator'||b.def.generatorFuel)&&g.workerCanWorkAt(g.player,b,R.localReach)).map(b=>({id:'local:'+b.id,domain:'local',x:b.x,y:b.y,z:0,inside:null,type:'generator',kind:'localGenerator',label:b.def.name,health:b.health,maxHealth:b.maxHealth}));}const taken=Object.fromEntries(world().containers(f.x,f.y,3,f.z,f.inside).map(o=>[o.id,amountTaken(o.id)])),objects=Survey.targets(world(),f,taken,R.reach).map(decorate).filter(o=>o.type);for(const p of world().nearPOI(f.x,f.y,20)){if(!p.levels.includes(f.z)||f.z!==0&&p.id!==f.inside||!p.levels.some(z=>world().plan(p,z).objects.some(o=>o.kind==='generator')))continue;const o=panel(p,f.z);if(Math.hypot(o.x-f.x,o.y-f.y)<=R.reach&&world().line(f,o,f.z,f.inside,null,.025))objects.push(decorate(o));}return objects.sort((a,b)=>Math.hypot(a.x-f.x,a.y-f.y)-Math.hypot(b.x-f.x,b.y-f.y));}
function danger(){const p=pos();if(p.domain==='local')return g.nearbyZombies(p.x,p.y,R.danger*32).some(e=>!e.dead&&e.health>0);return[...g.frontier.contacts(),...(g.worldEvolution?.groupMembers?.()||[]),...(g.succession133?.contacts?.()||[])].some(e=>e.hp>0&&e.z===p.z&&(p.z===0||e.poi===p.inside)&&Math.hypot(e.x-p.x,e.y-p.y)<R.danger);}
function target(id){return nearby().find(o=>o.id===id);}
function handsFree(){return g.player.reload<=0&&!g.selectedBuild&&!g.fieldcraft?.context?.().mounted&&!g.expansions.busy('interventions134');}
function preview(id,mode){const o=target(id);if(!alive()||!g.canIssueCommand()||driving()||g.player.reload>0||g.selectedBuild||g.fieldcraft?.context?.().mounted)return{ok:false,reason:'Commandant libre, à pied et hors poste de tir, rechargement ou placement requis.'};if(session||g.expansions.busy('interventions134'))return{ok:false,reason:'Terminez l’intervention en cours.'};if(!o)return{ok:false,reason:'Approchez le dispositif par un accès libre, au même étage.'};if(o.domain==='region'&&g.worldEvolution?.structureDestroyed(o.poi))return{ok:false,reason:'Ce bâtiment est détruit : son installation est hors service.'};if(danger())return{ok:false,reason:'Écartez les infectés avant cette intervention.'};const type=mode||o.type;let cost;if(type==='lock'){if(!o.lock)return{ok:false,reason:'Le verrou est déjà ouvert.'};cost=R.lock.cost;}else if(type==='generator'){if(o.plant?.on)return{ok:false,reason:'Arrêtez le groupe avant sa révision.'};if(!['generator','localGenerator'].includes(o.kind))return{ok:false,reason:'Cette intervention demande un groupe électrogène.'};if(o.domain==='region'&&amountTaken(o.id)>0)return{ok:false,reason:'Groupe cannibalisé : ses pièces ont déjà été récupérées.'};if(o.kind==='localGenerator'&&o.health>=o.maxHealth||o.plant?.condition>=100)return{ok:false,reason:'Ce groupe ne demande aucune réparation.'};cost=o.domain==='local'?R.localRepair.cost:R.generator.cost;}else if(type==='panel'){if(o.kind!=='panel'||state.panels.includes(id))return{ok:false,reason:'Distribution déjà rétablie.'};cost=R.panel.cost;}else return{ok:false,reason:'Intervention inconnue.'};if(Object.keys(state.attempts).length>=R.maxRecords&&!state.attempts[id]||(state.attempts[id]||0)>=1e6)return{ok:false,reason:'Carnet d’interventions complet.'};if(!C.canAfford(g.player.carry,cost))return{ok:false,reason:'Sac : '+C.resourceText(cost)+' nécessaires.'};return{ok:true,o,type,cost:{...cost}};}
function begin(id,mode){const q=preview(id,mode);if(!q.ok)return fail(q.reason);C.spend(g.player.carry,q.cost);state.attempts[id]=(state.attempts[id]||0)+1;const seed=G.hash(g.world.seed,id,state.attempts[id]),targets=Array.from({length:q.type==='lock'?(q.o.pins||R.lock.pins):R.generator.steps},(_,i)=>G.hash(seed,i)%R.lock.notches);session={id,type:q.type,o:q.o,position:pos(),health:g.player.health,errors:0,step:0,dial:0,targets,selected:[],switches:[false,false,false,false],desired:Array.from({length:4},(_,i)=>!!(G.hash(seed,i,'panel')%2)),cost:q.cost};if(session.desired.every(v=>!v))session.desired[0]=true;message='Matériel engagé. Annuler abandonne cette tentative.';g.releaseInputs();if(g.activeOverlay===g.ui.commandModal)g.showCommand(false);g.save(false);g.interventionsUI134?.open();return{ok:true};}
function cancel(reason='Intervention interrompue. Les consommables engagés restent utilisés.'){if(!session)return false;session=null;message=reason;g.interventionsUI134?.close();return true;}
function validSession(){if(!session||!alive()||g.paused||g.activeOverlay||driving()||!handsFree()||g.player.health<session.health)return false;const p=pos(),q=session.position,o=target(session.id);return p.domain===q.domain&&p.z===q.z&&p.inside===q.inside&&Math.hypot(p.x-q.x,p.y-q.y)<=R.moveTolerance*(p.domain==='local'?32:1)&&!!o&&!(o.domain==='region'&&g.worldEvolution?.structureDestroyed(o.poi))&&!(session.type==='generator'&&o.domain==='region'&&!plantUsable(o.id))&&!danger();}
function mistake(){session.errors++;g.frontier.signalAt({...pos(),z:pos().z},R.noise);message=session.type==='lock'?'Le mécanisme résiste. Ajustez avant de forcer.':'Diagnostic refusé. Relisez les indicateurs.';if(session.errors>=R[session.type].mistakes){cancel('Tentative échouée : outil consommable usé. Préparez-en un autre.');g.save(false);return{ok:false,reason:message};}return{ok:false,reason:message};}
function finish(){const s=session;if(!validSession()){cancel();return{ok:false,reason:message};}if(s.type==='lock'){if(s.o.sealed131){authorized=s.o.poi;const ok=g.worldOps131?.completeInterventionReserve(s.o.poi);authorized=null;if(!ok){cancel('Scellé indisponible.');return{ok:false,reason:message};}}else state.unlocked.push(s.id);message='Verrou ouvert. Le stock reste dans son contenant ; maintenez E pour le fouiller.';}if(s.type==='generator'){if(s.o.domain==='local'){const b=g.world.buildings.get(Number(s.id.split(':')[1]));b.health=Math.min(b.maxHealth,b.health+R.localRepair.health);g.refreshMetrics(true);message='Intégrité du groupe restaurée. Sa production habituelle et ses coûts de carburant sont conservés.';}else{const previous=state.plants[s.id]||{fuel:0,on:false};state.plants[s.id]={...previous,condition:100};message='Groupe révisé. Ajoutez du carburant, démarrez puis rétablissez le tableau.';}}if(s.type==='panel'){state.panels.push(s.id);message='Distribution rétablie pour cet étage. Un groupe alimenté doit tourner sur ce site.';}session=null;refreshPower();g.audio.ui?.();g.notify?.(message,'good');g.save(false);g.interventionsUI134?.close();return{ok:true};}
function act(action,value){if(!session)return fail('Aucune intervention en cours.');if(!validSession()){cancel('Intervention interrompue : position ou sécurité modifiée.');return{ok:false,reason:message};}const s=session;if(action==='adjust'&&Number.isInteger(value)){s.dial=((s.dial+value)%R.lock.notches+R.lock.notches)%R.lock.notches;message=s.type==='lock'?'Position '+(s.dial+1)+' : testez la résistance du mécanisme.': 'Réglez le cadran sur le repère indiqué.';return{ok:true};}if(action==='toggle'&&s.type==='panel'&&Number.isInteger(value)&&value>=0&&value<4){s.switches[value]=!s.switches[value];return{ok:true};}if(action!=='confirm')return fail('Commande inconnue.');if(s.type==='panel'){if(s.switches.some((v,i)=>v!==s.desired[i]))return mistake();return finish();}if(s.dial!==s.targets[s.step])return mistake();s.step++;s.dial=0;message=s.type==='lock'?'Goupille libérée. Passez à la suivante.':'Module stabilisé. Passez au réglage suivant.';return s.step===s.targets.length?finish():{ok:true};}
function depthEntries(domain,v,view){if(domain!=='region')return[];const entries=[];for(const p of v.world.nearPOI(v.x,v.y,35)){if(v.inside!==p.id||!p.levels.includes(v.z)||v.z!==0&&p.id!==v.inside||!p.levels.some(z=>v.world.plan(p,z).objects.some(o=>o.kind==='generator')))continue;const q=panel(p,v.z);if(q.x<view.l||q.x>view.r||q.y<view.t||q.y>view.b)continue;const on=powered(p.id,v.z),connected=state.panels.includes(q.id);entries.push({kind:'interventions134',id:q.id,depth:q.y,draw:c=>{c.save();c.translate(q.x,q.y);c.rotate(p.a);c.fillStyle='#293730';c.fillRect(-.4,-.28,.8,.56);c.strokeStyle='#b4b69a';c.lineWidth=.04;c.strokeRect(-.4,-.28,.8,.56);c.fillStyle=on?'#acd583':connected?'#d7b465':'#a07665';c.fillRect(-.27,-.15,.14,.14);c.fillRect(-.04,-.15,.14,.14);c.fillStyle='#d7d1af';c.font='.20px sans-serif';c.fillText('⚡',.12,.15);c.restore();}});}return entries;}
function servicePreview(id,mode){
const o=target(id),p=state.plants[id];
if(!alive()||!g.canIssueCommand()||driving()||!handsFree()||session)return{ok:false,reason:'Libérez vos mains et approchez le groupe à pied.'};
if(!o||o.type!=='generator'||o.domain!=='region'||!p)return{ok:false,reason:'Groupe accessible et révisé requis.'};
if(g.worldEvolution?.structureDestroyed(o.poi))return{ok:false,reason:'Ce bâtiment est détruit : son installation est hors service.'};
if(amountTaken(id)>0)return{ok:false,reason:'Groupe cannibalisé : ses pièces ont déjà été récupérées.'};
if((mode==='refuel'||!p.on)&&danger())return{ok:false,reason:'Écartez les infectés avant de ravitailler ou démarrer le groupe.'};
if(mode==='refuel'&&p.on)return{ok:false,reason:'Arrêtez le groupe avant de le ravitailler.'};
if(p.condition<=0||mode==='toggle'&&!p.on&&p.fuel<=0)return{ok:false,reason:'Révision et carburant requis avant le démarrage.'};
if(mode==='refuel'&&(p.fuel>=R.generator.tank||g.player.carry.fuel<=0))return{ok:false,reason:'Réservoir plein ou aucun carburant porté.'};
return{ok:true,o,p};
}
function toggle(id){const q=servicePreview(id,'toggle');if(!q.ok)return fail(q.reason);q.p.on=!q.p.on;refreshPower();message=q.p.on?'Groupe démarré. Son bruit attire les infectés proches.':'Groupe arrêté : le carburant restant est conservé.';g.save(false);return{ok:true};}
function refuel(id){const q=servicePreview(id,'refuel');if(!q.ok)return fail(q.reason);const p=q.p,n=Math.min(R.generator.refuel,R.generator.tank-p.fuel,g.player.carry.fuel);p.fuel+=n;g.player.carry.fuel-=n;message=n.toFixed(1)+' carburants versés depuis le sac.';g.save(false);return{ok:true,amount:n};}
function powerSources(){return Object.entries(state.plants).filter(([id,s])=>s.on&&s.fuel>0&&s.condition>0&&plantUsable(id)).map(([id,s])=>({...resolve(id),...s}));}
function powered(poi,z=0){return connectedPanels.has(poi+':panel:'+z)&&poweredSites.has(poi)&&!g.worldEvolution?.structureDestroyed(poi);}
function lights(){if(!g.frontier.active())return[];const f=g.frontier.position();return world().nearPOI(f.x,f.y,35).filter(p=>p.levels.includes(f.z)&&powered(p.id,f.z)).flatMap(p=>world().plan(p,f.z).rooms.map((r,i)=>({...G.global(p,r.x+r.w/2,r.y+r.h/2),id:p.id+':powered:'+i,z:f.z,inside:p.id,r:Math.min(R.lightRadius,Math.max(r.w,r.h)),color:'#e4d99e'})));}
function step(dt){if(session&&(!alive()||!validSession()))cancel();if(!alive()||g.paused||g.activeOverlay||!Number.isFinite(dt)||dt<=0)return;dt=Math.min(.1,dt);for(const[id,p]of Object.entries(state.plants))if(p.on){const o=resolve(id);if(!o||amountTaken(id)>0||g.worldEvolution?.structureDestroyed(o.poi)){p.on=false;continue;}const used=Math.min(dt,p.fuel/R.generator.burn,p.condition/R.generator.wear);p.fuel=Math.max(0,p.fuel-used*R.generator.burn);p.condition=Math.max(0,p.condition-used*R.generator.wear);if(p.fuel<1e-8||p.condition<1e-8){p.on=false;p.fuel=Math.max(0,p.fuel);p.condition=Math.max(0,p.condition);}if(g.frontier.active()){const origin={...o,inside:o.poi};g.frontier.signalAt(origin,R.noise);if(o.z===0)g.worldEvolution?.hear(origin,R.noise);}}refreshPower();}
function view(){const s=session;return{message,targets:(s?[]:nearby()).map(o=>({...o,quote:preview(o.id)})),session:s?{id:s.id,type:s.type,label:s.o.label,errors:s.errors,maxErrors:R[s.type].mistakes,step:s.step,steps:s.targets.length,dial:s.dial,notches:R.lock.notches,target:s.type==='generator'?s.targets[s.step]:undefined,feedback:s.type==='lock'?(s.dial===s.targets[s.step]?'souple':Math.abs(s.dial-s.targets[s.step])<=1?'résistance légère':'résistance forte'):null,switches:[...s.switches],desired:[...s.desired]}:null};}
function previewReserve(id){const p=world().pois.find(p=>p.id===id);return p?.frontier131?.reserve?preview(p.frontier131.reserve,'lock'):{ok:false,reason:'Aucune réserve à ouvrir.'};}
function beginReserve(id){const p=world().pois.find(p=>p.id===id);return p?.frontier131?.reserve?begin(p.frontier131.reserve,'lock'):fail('Aucune réserve à ouvrir.');}
function overview(){return{summary:message||'Intervenez au contact : coffres, casiers, armoires médicales, groupes et tableaux. Les consommables sont prélevés dès le début.',rows:[{label:'Verrous ouverts',value:state.unlocked.length},{label:'Groupes réparés',value:Object.keys(state.plants).length},{label:'Étages câblés',value:state.panels.length},{label:'À portée',value:nearby().length},{label:'Tentative',value:session?session.o.label:'Libre'}]};}
function actions(){const out=[];for(const o of nearby()){const q=preview(o.id);out.push({id:'work-'+o.id,label:(o.type==='lock'?'Crocheter · ':o.type==='panel'?'Rétablir · ':'Réviser · ')+o.label,disabled:!q.ok,reason:q.reason||C.resourceText(q.cost)+' du sac · consommés au début',run:()=>begin(o.id),close:true});if(o.plant){const fuel=servicePreview(o.id,'refuel'),toggleQuote=servicePreview(o.id,'toggle');out.push({id:'fuel-'+o.id,label:'Ravitailler le groupe',reason:fuel.reason||R.generator.refuel+' carburants maximum depuis le sac. Moteur arrêté.',disabled:!fuel.ok,run:()=>refuel(o.id)});out.push({id:'toggle-'+o.id,label:o.plant.on?'Arrêter le groupe':'Démarrer le groupe',reason:toggleQuote.reason||o.plant.fuel.toFixed(1)+' / '+R.generator.tank+' carburants · '+Math.floor(o.plant.condition)+' % état',disabled:!toggleQuote.ok,run:()=>toggle(o.id)});}}return out;}
const api={depthEntries,begin,preview,cancel,act,toggle,refuel,nearby,view,overview,actions,step,blocksLoot,lootReason:o=>state.plants[o.id]?.on?'Groupe en marche · arrêtez-le dans INTERVENTIONS avant récupération.':'Contenant verrouillé · INTERVENTIONS pour crocheter sur place.',powered,powerSources,lights,harvestFactor:o=>['pump','machine','sawBench','sterilizer','washer'].includes(o?.kind)&&powered(o.poi,o.z)?R.powerHarvestFactor:1,beginReserve,previewReserve,authorizesReserve:id=>authorized===id,busy:()=>!!session,snapshot:()=>validate(state)};g.interventions134=Object.freeze(api);g.expansions.register({id:'interventions134',title:'Interventions techniques',overview,actions,validate,snapshot:api.snapshot,busy:api.busy,restore:raw=>{state=validate(raw);refreshPower();session=null;message='';g.interventionsUI134?.close();},reset:()=>{state=initial();refreshPower();session=null;message='';g.interventionsUI134?.close();}});
wrap('update',(old,dt)=>{const r=old(dt);step(dt);return r;});wrap('returnToMenu',(old,...a)=>{cancel();return old(...a);});wrap('suspendForFocusLoss',(old,...a)=>{cancel('Intervention interrompue : fenêtre quittée.');return old(...a);});wrap('handlePressed',(old,...a)=>{if(session){g.releaseInputs();return;}return old(...a);});wrap('updatePlayer',(old,dt)=>{if(session)g.releaseInputs();return old(dt);});return api;}
const api={install,initial,validate,objectIn};root.DeadwallInterventions134=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root.DEADWALL&&root.document)install(root.DEADWALL);
})(globalThis);
