/* Electrical operations share Preparatifs; no extra permanent command tab. */
(function(root){
 'use strict';const g=root.DEADWALL,C=root.DeadwallCore;if(!g?.powerGrid)return;
 function mount(){if(g.powerGridUI)return;const get=id=>document.getElementById(id),host=get('coordinationPanel');if(!host)return;
  const el=(t,s,cl)=>{const n=document.createElement(t);if(s!==undefined)n.textContent=s;if(cl)n.className=cl;return n;},txt=(n,s)=>{if(n.textContent!==String(s))n.textContent=String(s)};
  const button=(title,id,fn)=>{const b=el('button',title);b.id=id;b.type='button';b.addEventListener('click',()=>{if(!b.disabled){fn();refresh(true)}});return b;};
  const section=el('section',undefined,'grid12'),metrics=el('div',undefined,'grid12-metrics'),kpi={};section.id='powerGridPanel';host.appendChild(section);section.append(el('small','RÉSEAU / RÉSERVES DE SECOURS'),el('h2','Garder du courant pour la nuit'),el('p','Stockez le surplus avant le crépuscule, une fois la demande active couverte. Les batteries démarrent vides et perdent 10 % de l’énergie reçue à la charge. Les circuits économisent du courant, pas les besoins des habitants.','grid12-intro'));
  for(const[id,label]of [['generation','Production directe'],['demand','Demande active'],['batteryOutput','Appoint batteries'],['charge','Réserve stockée']]){const b=el('article'),v=el('strong');b.append(el('small',label),v);metrics.append(b);kpi[id]=v;}section.append(metrics);
  const status=el('p','','grid12-status');status.id='powerGridStatus';status.setAttribute('role','status');section.append(status);
  const priority=el('div',undefined,'grid12-actions');priority.append(button('ORDRE HABITUEL','grid12Standard',()=>g.powerGrid.setPriority('standard')),button('ÉCLAIRAGE D’ABORD','grid12Lights',()=>g.powerGrid.setPriority('lights')));section.append(priority,el('p','La priorité lumineuse sert les balises, lampadaires et projecteurs avant les autres consommateurs. La priorité de construction existante départage ensuite les bâtiments d’une même catégorie.','grid12-note'));
  const batteryTitle=el('h3','Réserves locales'),batteries=el('div',undefined,'grid12-batteries');batteries.id='grid12Batteries';section.append(batteryTitle,batteries);
  const batteryRows=new Map();let batKey='initial',circuitKey='initial',last=-Infinity,page=0,filter='all',search='';
  const select=(options,id,change)=>{const s=el('select');s.id=id;for(const[v,t]of options){const o=el('option',t);o.value=v;s.append(o)}s.addEventListener('change',()=>{change(s.value);refresh(true)});return s;};
  section.append(el('p','AUTO : charge au surplus, se décharge sur déficit. NUIT : charge au surplus, ne se décharge qu’après le calme. ISOLÉE : conserve sa réserve sans charger ni alimenter. Une batterie incendiée est déconnectée ; détruite, elle perd sa charge.','grid12-note'));
  const filters=el('div',undefined,'grid12-filters'),label=el('label','RECHERCHER UN CIRCUIT'),input=el('input');input.type='search';input.id='grid12Search';input.placeholder='Nom du bâtiment…';label.htmlFor=input.id;input.addEventListener('input',()=>{search=input.value;page=0;refresh(true)});
  filters.append(label,input,select([['all','Tous les consommateurs'],['short','Sans alimentation complète'],['off','Circuits coupés'],['night','Programme nocturne'],['day','Programme diurne']],'grid12Filter',v=>{filter=v;page=0}));section.append(el('h3','Régler les circuits'),filters);
  const list=el('div',undefined,'grid12-circuits');list.id='grid12Circuits';const pages=el('div',undefined,'grid12-pages'),count=el('span');pages.append(button('PRÉCÉDENTS','grid12Prev',()=>{page--}),count,button('SUIVANTS','grid12Next',()=>{page++}));section.append(list,pages,el('p','Les ordres de circuit concernent les bâtiments consommateurs d’électricité. Couper un logement éteint ses services et fenêtres, mais ne retire ni les places ni la nourriture des habitants. Une porte motorisée garde ici ses règles d’ouverture historiques. Le réseau reste global, sans câbles ajoutés.','grid12-note'));
  const quick=button('RÉSERVES ÉLECTRIQUES','grid12Open',()=>{g.coordinationUI.open();section.scrollIntoView({block:'nearest'})});quick.className='grid12-open';get('citySystemsDock')?.querySelector('div')?.appendChild(quick);
  function refresh(force=false){if(!force&&performance.now()-last<C.PowerGrid.RULES.refreshMs)return;last=performance.now();if(host.classList.contains('hidden'))return;const v=g.powerGrid.overview(),can=g.canIssueCommand();
   for(const[id,n]of Object.entries(kpi))txt(n,id==='charge'?Math.floor(v.charge)+' / '+v.capacity+' u·s':v[id].toFixed(1));
   const flow=v.chargeInput>0?'Charge : '+v.chargeInput.toFixed(1)+' unités de puissance, rendement 90 %. ':v.batteryOutput>0?'Décharge : '+v.batteryOutput.toFixed(1)+' unités de puissance. ':'';
   const reserve=v.shortfall>1e-7?'Puissance insuffisante : '+v.shortfall.toFixed(1)+' unités manquantes.':v.autonomy!==null?'Au plus '+C.formatTime(v.autonomy)+' de réserve à déficit constant, sans nouvelle charge. Les limites de débit peuvent raccourcir ce maintien.':'Pas de déficit de puissance à cet instant.';
   txt(status,flow+reserve);get('grid12Standard').setAttribute('aria-pressed',String(v.priority==='standard'));get('grid12Lights').setAttribute('aria-pressed',String(v.priority==='lights'));get('grid12Standard').disabled=get('grid12Lights').disabled=!can;
   const bk=v.batteries.map(b=>b.id).join(',');if(bk!==batKey){batKey=bk;batteries.replaceChildren();batteryRows.clear();if(!v.batteries.length)batteries.append(el('p','Aucune batterie achevée. L’armoire de secours devient disponible à l’Avant-poste ; les grandes réserves viennent avec les âges suivants.','grid12-note'));
    for(const b of v.batteries){const row=el('article',undefined,'grid12-battery'),title=el('strong',b.name+' #'+b.id),bar=el('progress'),info=el('p'),mode=select([['auto','AUTO — combler tout déficit'],['night','NUIT — conserver le jour'],['isolated','ISOLÉE — ne pas utiliser']],'grid12Battery-'+b.id,value=>g.powerGrid.setBattery(b.id,value));bar.max=b.capacity;bar.setAttribute('aria-label','Charge de '+b.name);mode.setAttribute('aria-label','Mode de '+b.name+' '+b.id);row.append(title,bar,info,mode);batteries.append(row);batteryRows.set(b.id,{bar,info,mode});}
   }
   for(const b of v.batteries){const r=batteryRows.get(b.id);r.bar.value=b.charge;txt(r.info,Math.floor(b.charge)+' / '+b.capacity+' u·s · débit '+b.output+' · '+(b.offline?'déconnectée par la situation du bâtiment':b.flow>0?'en charge':b.flow<0?'alimente le réseau':'en attente'));r.mode.value=b.mode;r.mode.disabled=!can;}
   const needle=root.DeadwallCoordination.searchable(search),shown=v.circuits.filter(b=>(!needle||root.DeadwallCoordination.searchable(b.name).includes(needle))&&(filter==='all'||filter==='short'&&!b.powered||filter==='off'&&b.disabled||['day','night'].includes(filter)&&b.mode===filter));
   const total=Math.max(1,Math.ceil(shown.length/12));page=Math.min(Math.max(0,page),total-1);const subset=shown.slice(page*12,page*12+12),ck=JSON.stringify(subset.map(b=>[b.id,b.mode,b.powered,Math.round(b.share*100),b.offline]));
   if(ck!==circuitKey){const focus=document.activeElement?.id;circuitKey=ck;list.replaceChildren();for(const b of subset){const row=el('article',undefined,'grid12-circuit'),copy=el('div');copy.append(el('strong',b.name+' #'+b.id),el('small',b.need+' unités · '+(b.disabled?'circuit coupé':b.powered?'alimenté':b.share>0?'alimentation partielle':'sans courant')+(b.offline?' · incident / secteur inactif':'')));
    const mode=select([['on','TOUJOURS'],['day','JOUR SEULEMENT'],['night','NUIT SEULEMENT'],['off','COUPÉ']],'grid12Circuit-'+b.id,value=>g.powerGrid.setCircuit(b.id,value));mode.setAttribute('aria-label','Circuit '+b.name+' '+b.id);mode.value=b.mode;mode.disabled=!can;row.append(copy,mode);list.append(row);}if(focus?.startsWith('grid12Circuit-'))get(focus)?.focus({preventScroll:true});}
   txt(count,shown.length+' circuits · page '+(page+1)+' / '+total);get('grid12Prev').disabled=page===0;get('grid12Next').disabled=page===total-1;
  }
  const old=g.updateUI.bind(g);g.updateUI=(...a)=>{const r=old(...a);refresh();return r;};
  const co=g.coordinationUI;g.coordinationUI=Object.freeze({...co,open:()=>{const r=co.open();refresh(true);return r;}});
  for(const id of ['preparationButton','coordinationTab'])get(id)?.addEventListener('click',()=>refresh(true));
  for(const name of ['startNew','restoreSave']){const prev=g[name].bind(g);g[name]=(...a)=>{const r=prev(...a);page=0;filter='all';search='';get('grid12Filter').value='all';input.value='';batKey=circuitKey='reset';batteries.replaceChildren();list.replaceChildren();refresh(true);return r;};}
  g.powerGridUI=Object.freeze({refresh});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(globalThis);
