(function(root){
 'use strict';const g=root.DEADWALL,C=root.DeadwallCore,R=C?.RECON_RULES;
 if(!g?.recon||!root.document)return;
 function mount(){if(g.reconUI)return;const get=id=>document.getElementById(id),field=get('commandPanel-field'),nav=field?.querySelector('.field-nav');if(!field||!nav)return;
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const button=(text,id,fn)=>{const b=el('button',text);b.type='button';b.id=id;b.addEventListener('click',()=>{if(!b.disabled&&!b.closest('[inert]')){fn();refresh(true)}});return b;};
  const text=(n,v)=>{v=String(v);if(n.textContent!==v)n.textContent=v;};
  const panel=el('section',undefined,'recon-panel hidden');panel.id='reconPanel';field.appendChild(panel);
  const tab=button('CARTE & EXPLORATION','reconTab',()=>g.recon.open());tab.dataset.fieldView='recon';nav.appendChild(tab);
  panel.append(el('small','D-17 / CARNET DE TERRAIN'),el('h2','Choisir sa sortie. Prévoir le retour.'),el('p','Les six quartiers sont déjà connus. Les découvertes et appels n’apparaissent qu’après leur repérage. La carte ne révèle pas les infectés et ne garantit aucun trajet sûr.','recon-intro'));
  const live=el('p','','recon-status');live.id='reconStatus';live.setAttribute('role','status');panel.appendChild(live);
  const grid=el('div',undefined,'recon-layout'),mapArea=el('article',undefined,'recon-map-card'),aside=el('aside',undefined,'recon-detail');grid.append(mapArea,aside);panel.appendChild(grid);
  const controls=el('div',undefined,'recon-controls'),canvas=el('canvas');canvas.id='reconMap';canvas.width=800;canvas.height=640;canvas.tabIndex=0;canvas.setAttribute('role','img');canvas.setAttribute('aria-label','Carte interactive de D-17. Glisser pour déplacer, plus et moins pour zoomer, flèches au clavier pour déplacer. Choisir les lieux également dans la liste.');
  let zoom=1,cx=2048,cy=2048,drag=null,rendered=null,last=-Infinity,listKey='',routeKey='',filterValue='all',searchValue='';
  const clamp=v=>Math.max(0,Math.min(4096,v));
  const scale=()=>Math.min(canvas.width,canvas.height)/4096*zoom;
  const pixel=p=>({x:canvas.width/2+(p.x-cx)*scale(),y:canvas.height/2+(p.y-cy)*scale()});
  const world=p=>({x:cx+(p.x-canvas.width/2)/scale(),y:cy+(p.y-canvas.height/2)/scale()});
  function setZoom(z,anchor={x:400,y:320}){const before=world(anchor);zoom=Math.max(1,Math.min(8,z));cx=clamp(before.x-(anchor.x-400)/scale());cy=clamp(before.y-(anchor.y-320)/scale());draw();}
  controls.append(button('−','reconZoomOut',()=>setZoom(zoom/1.4)),button('+','reconZoomIn',()=>setZoom(zoom*1.4)),button('TOUT D-17','reconFit',()=>{zoom=1;cx=cy=2048;draw()}),button('COMMANDANT','reconPlayer',()=>{cx=g.player.x;cy=g.player.y;zoom=3;draw()}),button('CENTRE','reconCore',()=>{const c=g.core();if(c){cx=c.x;cy=c.y;zoom=3;draw()}}));
  mapArea.append(controls,canvas,el('p','Glisser déplace la carte. Cliquer un symbole sélectionne le lieu, sans bouger le commandant. Au clavier : flèches, + / − et Début.','recon-note'));
  const legend=el('p','Bleu : découvertes connues. Ocre : étapes. Blanc : dépôts. Vert : alliés. Les flèches de front n’apparaissent que pendant l’alerte et l’assaut.','recon-note');mapArea.appendChild(legend);
  const selectionName=el('h3','Aucun lieu sélectionné'),selectionInfo=el('p','Choisissez un lieu connu sur la carte ou dans la liste.'),selectionText=el('p','','recon-note');aside.append(selectionName,selectionInfo,selectionText);
  const actions=el('div',undefined,'recon-controls'),add=button('AJOUTER AU PARCOURS','reconAdd',()=>{const s=g.recon.overview().selected;if(s)g.recon.enqueue(s.id)}),survey=button('MARQUER LE RELEVÉ','reconSurvey',()=>{const s=g.recon.overview().selected;if(s?.kind==='site')g.dayworks.focusSite(s.ref)});actions.append(add,survey);aside.appendChild(actions);
  const journey=el('section',undefined,'recon-journey'),routeInfo=el('p','','recon-note'),stops=el('div');stops.id='reconStops';journey.append(el('h3','Parcours préparé'),el('p','Quatre étapes maximum. La ligne calculée concerne la première étape. Passer à la suivante reste un ordre manuel.','recon-note'),routeInfo,stops);
  const commands=el('div',undefined,'recon-controls');commands.append(button('RETOUR AU CENTRE','reconHome',()=>g.recon.returnHome()),button('EFFACER LE PARCOURS','reconClear',()=>g.recon.clear()),button('TRACÉ AU SOL','reconOverlay',()=>{const v=g.recon.overview();g.recon.setOverlay(!v.overlay)}));journey.appendChild(commands);aside.appendChild(journey);
  aside.append(el('p','Les découvertes et leurs réserves sont sauvegardées. Ce parcours de préparation est temporaire : nouvelle partie ou reprise le remet à zéro. Aucun point ne transporte ni ne récolte à votre place.','recon-note'));
  const filters=el('div',undefined,'recon-filters'),label=el('label','RECHERCHER UN LIEU'),search=el('input'),filter=el('select');search.id='reconSearch';search.type='search';search.placeholder='Nom, matériau ou personne…';label.htmlFor=search.id;filter.id='reconFilter';filter.setAttribute('aria-label','Filtrer les points connus');
  for(const[v,t]of [['all','Tous les lieux connus'],['site','Découvertes à exploiter'],['survey','Relevés à effectuer'],['done','Réserves épuisées'],['call','Appels et escortes'],['depot','Dépôts']]){const o=el('option',t);o.value=v;filter.appendChild(o)}filters.append(label,search,filter);panel.appendChild(filters);
  const tally=el('p','','recon-note'),list=el('div',undefined,'recon-points');list.id='reconPointList';panel.append(tally,list);
  function setSelection(id){g.recon.choose(id);refresh(true);}
  function card(p){const n=el('article',undefined,'recon-point'),thumb=el('canvas');thumb.width=70;thumb.height=64;thumb.setAttribute('aria-hidden','true');if(p.kind==='site')root.DeadwallReconArt.draw(thumb.getContext('2d'),{id:p.ref,x:35,y:34,survey:p.survey,remaining:p.remaining});else{const c=thumb.getContext('2d');c.fillStyle=p.kind==='call'?'#9ab790':'#d9d4b0';c.font='bold 28px sans-serif';c.fillText(p.kind==='call'?'●':'⌂',22,43)}
   const copy=el('div');copy.append(el('strong',p.name),el('small',p.kind==='site'?(p.done?'Épuisé':p.survey<6?'À relever':'Prêt à récupérer')+' · '+C.RESOURCE_META[p.resource].label:p.kind==='call'?'Personne repérée · '+({waiting:'en attente',follow:'suit',hold:'attend',return:'en repli'}[p.status]):'Dépôt opérationnel'));
   const b=button('VOIR','reconPoint-'+p.id.replace(':','-'),()=>setSelection(p.id));n.append(thumb,copy,b);return n;
  }
  function draw(){if(!rendered||panel.classList.contains('hidden'))return;const ctx=canvas.getContext('2d'),v=rendered,s=scale();ctx.fillStyle='#101e17';ctx.fillRect(0,0,800,640);ctx.save();ctx.translate(400-cx*s,320-cy*s);ctx.scale(s,s);ctx.fillStyle='#213328';ctx.fillRect(0,0,4096,4096);ctx.strokeStyle='#435b45';ctx.lineWidth=1/s;
   for(let i=0;i<=4096;i+=256){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,4096);ctx.moveTo(0,i);ctx.lineTo(4096,i);ctx.stroke()}
   for(const r of g.infrastructure.snapshot().roads){ctx.fillStyle=r.progress===1?'#a99b73':'#635e41';ctx.fillRect(r.x*32,r.y*32,32,32)}
   for(const b of g.world.buildings.values())if(!b.dead){ctx.fillStyle=!b.completed?'#6e6852':b.def.gate?(b.gateMode==='closed'?'#d38f77':'#a1c7c4'):b.def.wall?'#aebdaa':'#708b70';ctx.fillRect(b.left,b.top,b.w*32,b.h*32)}
   if(v.route?.ok){ctx.strokeStyle='#e0c184';ctx.lineWidth=2/s;ctx.setLineDash([6/s,4/s]);ctx.beginPath();v.route.path.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke();ctx.setLineDash([])}ctx.restore();
   for(const site of g.world.sites||[]){const p=pixel(site);if(p.x<0||p.x>800||p.y<0||p.y>640)continue;ctx.font='11px sans-serif';ctx.fillStyle='#91a68a';ctx.textAlign='center';ctx.fillText(site.name,p.x,p.y-16)}
   for(const u of g.units)if(!u.dead){const p=pixel(u);ctx.fillStyle='#8cab7c';ctx.fillRect(p.x-2,p.y-2,4,4)}
   for(const t of g.territories.truckEntities()){const p=pixel(t);ctx.fillStyle='#adc4a7';ctx.fillRect(p.x-4,p.y-2,8,4)}
   for(const point of v.points){const p=pixel(point);if(p.x<0||p.x>800||p.y<0||p.y>640)continue;const q=v.queue.findIndex(n=>n.id===point.id),chosen=v.selected?.id===point.id;
    ctx.fillStyle=q>=0?'#f1d18a':point.kind==='depot'?'#e1dfc0':point.kind==='call'?'#a0c398':point.done?'#62796f':'#8fc1bc';ctx.beginPath();ctx.arc(p.x,p.y,chosen?8:5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#15251c';ctx.lineWidth=2;ctx.stroke();
    if(q>=0){ctx.fillStyle='#13221a';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(String(q+1),p.x,p.y+4)}if(chosen){ctx.strokeStyle='#f3dfad';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,13,0,Math.PI*2);ctx.stroke();}
   }
   const player=pixel(g.player);ctx.fillStyle='#f4e6be';ctx.beginPath();ctx.arc(player.x,player.y,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff0cd';ctx.beginPath();ctx.arc(player.x,player.y,10,0,Math.PI*2);ctx.stroke();
   if(['warning','assault'].includes(g.phase)){for(const f of g.fronts){const p={north:[400,20,Math.PI/2],south:[400,620,-Math.PI/2],east:[780,320,Math.PI],west:[20,320,0]}[f];if(!p)continue;ctx.save();ctx.translate(p[0],p[1]);ctx.rotate(p[2]);ctx.fillStyle='#d38f77';ctx.beginPath();ctx.moveTo(10,0);ctx.lineTo(-8,-7);ctx.lineTo(-8,7);ctx.fill();ctx.restore();}}
   ctx.font='11px sans-serif';ctx.textAlign='left';ctx.fillStyle='#d0d6bb';ctx.fillText('ZOOM ×'+zoom.toFixed(1)+' · D-17',12,624);
  }
  function refresh(force=false){if(panel.classList.contains('hidden'))return;if(!force&&performance.now()-last<R.refreshMs)return;last=performance.now();const v=g.recon.overview(force);rendered=v;
   text(live,'Vague '+g.wave+' · '+(g.phase==='calm'?'jour : '+C.formatTime(v.remaining):g.phase==='assault'?'assaut en cours':g.phase==='warning'?'alerte':'sécurisation')+' · Sac '+v.bag.toFixed(1)+' / '+v.capacity+' · '+v.points.filter(p=>p.kind==='site').length+' découvertes sur 18.');
   const p=v.selected;text(selectionName,p?.name||'Aucun lieu sélectionné');text(selectionText,p?.text||'Choisissez un lieu connu.');text(selectionInfo,p?(Math.round(p.distance)+' unités à vol d’oiseau'+(p.kind==='site'?' · '+p.remaining.toFixed(1)+' '+C.RESOURCE_META[p.resource].label.toLowerCase()+' · '+(p.survey>=6?'relevé terminé':p.survey.toFixed(1)+' / 6 s de relevé'):'')):'');
   add.disabled=!p||p.done||v.queue.some(n=>n.id===p.id)||v.queue.length>=4||!g.canIssueCommand()||g.player.dead;survey.disabled=!p||p.kind!=='site'||p.done||g.phase!=='calm'||!g.canIssueCommand();
   text(routeInfo,v.route?(v.route.ok?Math.round(v.route.distance)+' unités de trajet pour la première étape. ':'')+v.route.reason:v.message||'Ajoutez un lieu connu pour calculer le premier trajet.');get('reconOverlay').setAttribute('aria-pressed',String(v.overlay));
   const rkey=JSON.stringify(v.queue.map(p=>[p.id,p.name]));if(rkey!==routeKey){routeKey=rkey;stops.replaceChildren();for(const[pIndex,p]of v.queue.entries()){const row=el('div',undefined,'recon-stop');const up=button('↑','reconUp-'+pIndex,()=>g.recon.move(p.id,-1)),down=button('↓','reconDown-'+pIndex,()=>g.recon.move(p.id,1)),remove=button('RETIRER','reconRemove-'+pIndex,()=>g.recon.remove(p.id));up.disabled=pIndex===0;down.disabled=pIndex===v.queue.length-1;up.setAttribute('aria-label','Avancer '+p.name);down.setAttribute('aria-label','Reculer '+p.name);row.append(el('strong',(pIndex+1)+'. '+p.name),up,down,remove);stops.appendChild(row)}}
   const needle=root.DeadwallCoordination.searchable(searchValue),ps=v.points.filter(p=>(!needle||root.DeadwallCoordination.searchable(p.name+' '+p.text+' '+(C.RESOURCE_META[p.resource]?.label||'')).includes(needle))&&(filterValue==='all'||filterValue==='site'&&p.kind==='site'&&!p.done||filterValue==='survey'&&p.kind==='site'&&p.survey<6||filterValue==='done'&&p.done||['call','depot'].includes(filterValue)&&filterValue===p.kind)).sort((a,b)=>a.distance-b.distance);
   text(tally,ps.length+' lieux dans ce filtre. Les points inconnus ne sont pas listés.');const lkey=JSON.stringify(ps.map(p=>[p.id,p.done,p.survey>=6,p.status]));if(lkey!==listKey){listKey=lkey;list.replaceChildren(...ps.map(card));}draw();
  }
  search.addEventListener('input',()=>{searchValue=search.value;refresh(true)});filter.addEventListener('change',()=>{filterValue=filter.value;refresh(true)});
  const pos=e=>{const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*800/r.width,y:(e.clientY-r.top)*640/r.height}};
  canvas.addEventListener('pointerdown',e=>{if(drag||e.button!==0||e.isPrimary===false)return;e.preventDefault();const p=pos(e);drag={id:e.pointerId,start:p,last:p,moved:false};try{canvas.setPointerCapture(e.pointerId);}catch{drag=null;return;}canvas.focus({preventScroll:true})});
  canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;e.preventDefault();const p=pos(e);if(Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>6)drag.moved=true;if(drag.moved){cx=clamp(cx-(p.x-drag.last.x)/scale());cy=clamp(cy-(p.y-drag.last.y)/scale());draw()}drag.last=p;});
  canvas.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const old=drag;drag=null;if(!old.moved&&rendered){const p=pos(e),target=rendered.points.map(n=>({id:n.id,d:Math.hypot(pixel(n).x-p.x,pixel(n).y-p.y)})).filter(x=>x.d<16).sort((a,b)=>a.d-b.d)[0];if(target)setSelection(target.id)}if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)});
  for(const type of ['pointercancel','lostpointercapture'])canvas.addEventListener(type,e=>{if(drag?.id===e.pointerId)drag=null});
  canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(zoom*(e.deltaY<0?1.15:1/1.15),pos(e))},{passive:false});
  canvas.addEventListener('keydown',e=>{if(!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home','Equal','Minus','NumpadAdd','NumpadSubtract'].includes(e.code))return;e.preventDefault();e.stopPropagation();const step=100/scale();if(e.code==='Home'){cx=cy=2048;zoom=1}else if(['Equal','NumpadAdd'].includes(e.code))setZoom(zoom*1.4);else if(['Minus','NumpadSubtract'].includes(e.code))setZoom(zoom/1.4);else{cx=clamp(cx+(e.code==='ArrowRight'?step:e.code==='ArrowLeft'?-step:0));cy=clamp(cy+(e.code==='ArrowDown'?step:e.code==='ArrowUp'?-step:0))}draw()});
  function open(){for(const s of field.children)if(s.tagName==='SECTION')s.classList.toggle('hidden',s!==panel);for(const b of nav.querySelectorAll('button'))b.setAttribute('aria-pressed',String(b===tab));refresh(true);}
  nav.addEventListener('click',e=>{const b=e.target.closest('button');if(b&&b!==tab){panel.classList.add('hidden');tab.setAttribute('aria-pressed','false');drag=null}});
  function reset(){zoom=1;cx=cy=2048;drag=null;rendered=null;listKey=routeKey='';filter.value='all';search.value='';filterValue='all';searchValue='';last=-Infinity;refresh(true)}
  const old=g.updateUI.bind(g);g.updateUI=(...args)=>{const r=old(...args);refresh();return r};
  const mapButton=button('CARTE [M]','reconMapButton',()=>g.recon.open());get('minimapWrap')?.appendChild(mapButton);
  root.addEventListener('keydown',e=>{if(g.frontier?.active()||g.exploration125?.openMap)return;if(e.code!=='KeyM'||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target?.closest?.('input,textarea,select,button,summary,[contenteditable]')||g.state!=='playing'||g.gameOver)return;if(g.activeOverlay&&g.activeOverlay!==g.ui.commandModal)return;e.preventDefault();e.stopPropagation();if(!panel.classList.contains('hidden')&&g.activeOverlay===g.ui.commandModal)g.showCommand(false);else g.recon.open();},{capture:true});
  g.reconUI=Object.freeze({open,refresh,reset,view:()=>({zoom,cx,cy,dragging:Boolean(drag)})});
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(typeof globalThis!=='undefined'?globalThis:this);
