/* Checks paths inside the real D-17. Results never move actors or write saves. */
(function(root){'use strict';
const C=root.DeadwallCore||(typeof require==='function'?require('./core.js'):null),P=root.DeadwallAtlasProjection||(typeof require==='function'?require('./atlas-projection.js'):null),Routing=root.DeadwallFrontierRouting||(typeof require==='function'?require('./frontier-routing.js'):null),R=C.ReturnRouteRules;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),clone=o=>JSON.parse(JSON.stringify(o));
class Heap{constructor(){this.a=[];}push(id,cost){const v={id,cost};let i=this.a.length;this.a.push(v);while(i){const p=(i-1)>>1;if(this.a[p].cost<=cost)break;this.a[i]=this.a[p];i=p;}this.a[i]=v;}pop(){if(!this.a.length)return null;const first=this.a[0],v=this.a.pop();if(this.a.length){let i=0;while(i*2+1<this.a.length){let j=i*2+1;if(j+1<this.a.length&&this.a[j+1].cost<this.a[j].cost)j++;if(this.a[j].cost>=v.cost)break;this.a[i]=this.a[j];i=j;}this.a[i]=v;}return first;}}
function signature(g){return [g.world.seed,g.world.navigationVersion,g.core()?.id||0,g.worldEvolution?.vehicleProfile()?.w,g.worldEvolution?.vehicleProfile()?.h,...[...g.world.buildings.values()].map(b=>[b.id,b.type,b.gx,b.gy,b.rotation,+b.completed,+b.dead,+(b.health>0),b.gateMode].join(',')),...g.world.nodes.map(n=>[n.id,n.x,n.y,n.radius,n.renderSize,+n.depleted].join(',')),...C.Expeditions.SITES.map(s=>[s.id,s.x,s.y].join(','))].join('|');}
function clearance(g,mode){const radius=mode==='car'?C.Expeditions.RULES.carRadius:R.footRadius;return {radius,point:(x,y)=>mode==='car'?g.expeditions.carClear(x,y):g.friendlyPositionClear({radius},x,y)};}
function segment(clear,a,b){const steps=Math.max(1,Math.ceil(distance(a,b)/R.sample));for(let i=0;i<=steps;i++)if(!clear.point(a.x+(b.x-a.x)*i/steps,a.y+(b.y-a.y)*i/steps))return false;return true;}
function createSearch(g,mode,gridOffset=R.cell/2,destination=null){const clear=clearance(g,mode),N=C.WORLD_TILES,point=id=>({x:(id%N)*R.cell+gridOffset,y:Math.floor(id/N)*R.cell+gridOffset}),valid=new Int8Array(N*N),deadComponent=new Uint8Array(N*N),edges=new Map(),core=g.core();
function free(id){if(id<0||id>=N*N)return false;if(!valid[id]){const p=point(id);valid[id]=clear.point(p.x,p.y)?1:-1;}return valid[id]===1;}
function linked(i,j){const key=Math.min(i,j)*N*N+Math.max(i,j);if(!edges.has(key))edges.set(key,segment(clear,point(i),point(j)));return edges.get(key);}
function goal(p){if(destination)return distance(p,destination)<=R.linkRadius&&segment(clear,p,destination);return !!core&&core.health>0&&distance(p,core)<=C.Expeditions.RULES.homeRange&&g.fieldcraft.workAt({...p,radius:clear.radius},core,R.deliveryReach);}
function heuristic(p){if(destination)return distance(p,destination);if(!core)return 0;const dx=Math.max(0,core.left-R.deliveryReach-p.x,p.x-core.right-R.deliveryReach),dy=Math.max(0,core.top-R.deliveryReach-p.y,p.y-core.bottom-R.deliveryReach);return Math.hypot(dx,dy);}
function find(start){if(!core||core.dead||core.health<=0)return{status:'no-core',path:null,expanded:0};if(!clear.point(start.x,start.y))return{status:'entry-blocked',path:null,expanded:0};if(destination&&!clear.point(destination.x,destination.y))return{status:'entry-blocked',path:null,expanded:0};if(goal(start)){const units=destination?distance(start,destination):0;return{status:'connected',path:destination?[{...start},{...destination}]:[{...start}],expanded:0,units,metres:units/R.localUnitsPerMetre};}const costs=new Float64Array(N*N);costs.fill(Infinity);const parents=new Int32Array(N*N);parents.fill(-2);const visited=new Uint8Array(N*N),heap=new Heap();const gx=Math.floor(start.x/R.cell),gy=Math.floor(start.y/R.cell);for(let y=Math.max(0,gy-2);y<=Math.min(N-1,gy+2);y++)for(let x=Math.max(0,gx-2);x<=Math.min(N-1,gx+2);x++){const id=y*N+x,p=point(id);if(!deadComponent[id]&&distance(start,p)<=R.linkRadius&&free(id)&&segment(clear,start,p)){costs[id]=distance(start,p);parents[id]=-1;heap.push(id,costs[id]+heuristic(p));}}
let count=0,end=-1;while(heap.a.length&&count<R.maxExpanded){const {id}=heap.pop();if(visited[id])continue;visited[id]=1;count++;const p=point(id);if(goal(p)){end=id;break;}for(const [dx,dy]of [[1,0],[0,1],[-1,0],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const x=id%N+dx,y=Math.floor(id/N)+dy;if(x<0||y<0||x>=N||y>=N)continue;const next=y*N+x;if(visited[next]||!free(next)||!linked(id,next))continue;const cost=costs[id]+R.cell*Math.hypot(dx,dy);if(cost<costs[next]){costs[next]=cost;parents[next]=id;heap.push(next,cost+heuristic(point(next)));}}}
if(end<0){if(!heap.a.length)for(let i=0;i<visited.length;i++)if(visited[i])deadComponent[i]=1;return{status:count>=R.maxExpanded?'limit':'no-path',path:null,expanded:count};}const raw=destination?[{...destination}]:[];for(let id=end;id>=0;id=parents[id])raw.push(point(id));raw.push({...start});raw.reverse();const path=[raw[0]];for(let i=0;i<raw.length-1;){let j=Math.min(raw.length-1,i+R.maxSimplifyLookAhead);while(j>i+1&&!segment(clear,raw[i],raw[j]))j--;path.push(raw[j]);i=j;}let units=0;for(let i=1;i<path.length;i++)units+=distance(path[i-1],path[i]);return{status:'connected',path,expanded:count,units,metres:units/R.localUnitsPerMetre};}
return {find,clear,segment:(a,b)=>segment(clear,a,b)};}
function adaptiveSearch(g,mode,destination=null){const variants=R.gridOffsets.map(offset=>createSearch(g,mode,offset,destination));return{find(start){let result=null,expanded=0;for(const variant of variants){result=variant.find(start);expanded+=result.expanded;if(result.path||result.status==='entry-blocked'||result.status==='no-core')break;}return{...result,expanded};}};}
// Reuse the same bounded local search for a departure, without changing the
// player's selected return diagnostic or moving any actor.
function departures(g,mode,origin){
 const search=adaptiveSearch(g,mode,origin),out=[];
 for(const gate of P.gatesFor(g))for(const offset of R.gateOffsets){const ew=gate.id==='east'||gate.id==='west',entry={x:gate.localX+(ew?0:offset),y:gate.localY+(ew?offset:0)},route=search.find(entry);if(!route.path)continue;
  out.push({...gate,region:{x:gate.x+(ew?0:offset/32),y:gate.y+(ew?offset/32:0)},entry,localPath:route.path.slice().reverse(),localMetres:route.metres});break;
 }
 return out;
}
// The regional road suggestion must go around the separate local domain.
function outsideWorld(world){return Routing.outsideWorld(world,P.home(world));}
function install(g){if(g.returnRoutes)return g.returnRoutes;let home=g.world,current=null,chosen=null,caches=new Map(),revision=0,regionalLine=[];
function reset(){if(home!==g.world){home=g.world;current=null;chosen=null;caches.clear();revision++;}}
function stale(){reset();return !!current&&current.signature!==signature(g);}
function verify(mode='foot'){reset();if(!['foot','car'].includes(mode))throw Error('Gabarit de retour inconnu');const mark=signature(g);let saved=caches.get(mode);if(!saved||saved.signature!==mark){const search=adaptiveSearch(g,mode),gates=[];for(const gate of P.gatesFor(g)){let best=null,central=null,expanded=0,entryAvailable=false,limited=false;for(const offset of R.gateOffsets){const ew=gate.id==='east'||gate.id==='west',entry={x:gate.localX+(ew?0:offset),y:gate.localY+(ew?offset:0)},route=search.find(entry);expanded+=route.expanded;if(!['entry-blocked','no-core'].includes(route.status))entryAvailable=true;if(route.status==='limit')limited=true;if(offset===0)central=route.status;if(route.path&&(!best||route.units<best.units))best={...route,offset,entry};}
const ew=gate.id==='east'||gate.id==='west',region={x:gate.x+(ew?0:(best?.offset||0)/32),y:gate.y+(ew?(best?.offset||0)/32:0)};gates.push({id:gate.id,name:gate.name,status:best?'connected':central==='no-core'?'no-core':limited?'limit':entryAvailable?'no-path':'entry-blocked',central,region,expanded,...(best?{offset:best.offset,entry:best.entry,path:best.path,worldPath:best.path.map(p=>P.toRegion(p.x,p.y,g)),localUnits:best.units,localMetres:best.metres,localFuel:mode==='car'?best.units*C.Expeditions.RULES.fuelPerUnit:0}:{path:null,worldPath:null})});}saved={signature:mark,mode,gates};caches.set(mode,saved);}current={...clone(saved),checkedAt:g.elapsed};revision++;if(chosen&&!current.gates.find(q=>q.id===chosen)?.path)chosen=null;return snapshot();}
function snapshot(){reset();if(!current)return{checked:false,stale:false,selected:null,revision};return{checked:true,stale:stale(),mode:current.mode,checkedAt:current.checkedAt,gates:clone(current.gates).map(gate=>{if(!gate.path)return gate;const v=g.expeditions.car(),rate=g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre,ratio=rate/(C.WorldEvolution?.RULES.vehicles.break.fuel??C.Frontier.RULES.fuelPerMetre),base=gate.localUnits*C.Expeditions.RULES.fuelPerUnit*ratio;return{...gate,localFuel:current.mode==='car'?(g.travel131?.snapshot().tuning?g.travel131.fuelCost(gate.localMetres,C.Expeditions.RULES.fuelPerUnit*32*ratio,v?.id??null):base):0};}),selected:chosen,revision};}
function select(id){reset();if(!current||stale()||!current.gates.find(gate=>gate.id===id)?.path)return false;chosen=id;regionalLine=[];revision++;budget(id);return true;}
function budget(gateId=chosen){reset();if(!current||stale())return null;const f=g.frontier.overview(),v=g.expeditions.car(),usingCar=current.mode==='car'&&v&&v.health>0,fromRegion=usingCar?!!f.car:f.active,origin=usingCar?(f.car?{x:f.car.x,y:f.car.y,z:0}:{...P.toRegion(v.x,v.y,g),z:0}):P.playerPosition(g,f),gate=current.gates.find(q=>q.id===gateId);if(!gate?.path)return null;let road=null,localUnits=gate.localUnits,localPath=gate.worldPath;
if(origin.z!==0)return {status:'level-required',mode:current.mode};if(fromRegion){const exterior=outsideWorld(f.world);road=exterior.roads.length?Routing.route(exterior,origin,{drive:{a:gate.region,b:gate.region}}):null;if(!road)return{status:'regional-no-path',mode:current.mode};}else{const start=usingCar&&!f.car?{x:v.x,y:v.y}:{x:g.player.x,y:g.player.y};const direct=adaptiveSearch(g,current.mode).find(start);if(!direct.path)return{status:direct.status,mode:current.mode};localUnits=direct.units;localPath=direct.path.map(p=>P.toRegion(p.x,p.y,g));}
const regionMetres=road?.metres||0,localMetres=localUnits/32,rate=current.mode==='car'?(g.worldEvolution?.vehicleProfile()?.fuel??C.Frontier.RULES.fuelPerMetre):0,ratio=rate/(C.WorldEvolution?.RULES.vehicles.break.fuel??C.Frontier.RULES.fuelPerMetre),localRate=C.Expeditions.RULES.fuelPerUnit*32*ratio,tuning=g.travel131?.snapshot().tuning,tuned=!!tuning&&tuning.id===v?.id,cost=(metres,r)=>g.travel131?.fuelCost(metres,r,v?.id??null)??metres*r;
// The return burns regional metres first; maintenance cannot start over at D-17.
const localCost=(regional,local)=>tuned?cost(regional+local,localRate)-cost(regional,localRate):local*32*C.Expeditions.RULES.fuelPerUnit*ratio,regionFuel=cost(regionMetres,rate),localFuel=localCost(regionMetres,localMetres),reserve=rate>0?(g.fieldSupplies?.snapshot().reserve??2):0,detour=C.FieldSupplies.RULES.detourFactor,withDetour=tuned?cost(regionMetres*detour,rate)+localCost(regionMetres*detour,localMetres*detour):(localFuel+regionFuel)*detour,required=withDetour+reserve,available=v&&v.health>0?v.fuel+(f.car||!f.active?v.cargo.fuel:0)+g.player.carry.fuel:0;
if(gateId===chosen)regionalLine=road?.path||[];return {status:'connected',mode:current.mode,gate:gate.id,name:gate.name,regionMetres,localMetres,localFuel,regionFuel,required,available,shortfall:Math.max(0,required-available),reserve,localPath,regionalPath:road?.path||[],fromRegion,originKind:usingCar?'vehicle':'commander',vehicleUsable:!!v&&v.health>0,position:{x:origin.x,y:origin.y,z:origin.z},note:'Retour seul. Route régionale indicative ; segment D-17 contrôlé dans la géométrie courante.'};}
function overlay(){reset();if(!current||!chosen||stale())return null;const gate=current.gates.find(q=>q.id===chosen);return gate?.path?{mode:current.mode,gate:gate.id,path:clone(gate.worldPath),regionalPath:clone(regionalLine),entry:{...gate.region},metres:gate.localMetres}:null;}
const rally=g.drawRally.bind(g);g.drawRally=(ctx,...a)=>{const result=rally(ctx,...a),route=overlay();if(route&&!g.frontier.active()){ctx.save();ctx.strokeStyle='rgba(117,216,191,.75)';ctx.lineWidth=3/Math.max(.5,g.camera.zoom);ctx.setLineDash([12,8]);ctx.beginPath();route.path.forEach((p,i)=>{const q=P.toLocal(p.x,p.y,g);i?ctx.lineTo(q.x,q.y):ctx.moveTo(q.x,q.y)});ctx.stroke();ctx.restore();}return result;};
g.returnRoutes=Object.freeze({verify,snapshot,select,budget,overlay,clear:()=>{current=null;chosen=null;revision++;},isStale:stale});return g.returnRoutes;}
const api={install,signature,createSearch,adaptiveSearch,departures,segment,outsideWorld};root.DeadwallReturnRoutes=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;
})(globalThis);
