/* Growth and night preparation live inside the existing Preparatifs dossier. */
(function(root){
 'use strict';const g=root.DEADWALL,C=root.DeadwallCore;if(!g?.urban||!g.nightwatch)return;
 function mount(){if(g.urbanUI)return;const get=id=>document.getElementById(id),panel=get('coordinationPanel');if(!panel)return;
  const el=(t,s,cl)=>{const n=document.createElement(t);if(s!==undefined)n.textContent=s;if(cl)n.className=cl;return n;};
  const button=(s,id,fn)=>{const b=el('button',s);b.id=id;b.type='button';b.addEventListener('click',()=>{if(!b.disabled){fn();refresh(true)}});return b;};const text=(n,t)=>{if(n.textContent!==String(t))n.textContent=String(t)};
  const block=el('section',undefined,'urban-block'),h=el('h2','Du refuge à la mégaville'),brief=el('p'),bar=el('progress'),ages=el('div',undefined,'urban-ages');bar.id='urbanProgress';bar.setAttribute('aria-label','Pic historique de construction vers le prochain âge');
  block.append(el('small','CROISSANCE / ÂGES DE LA CITÉ'),h,brief,bar,ages,el('p','Les seuils utilisent le score des constructions achevées. Un âge atteint reste connu, même après des pertes ; les bâtiments requis, les matériaux et l’alimentation restent à rétablir. Les logements ne créent pas de personnes.','urban-note'));
  const growth=el('article',undefined,'urban-growth'),remaining=el('p'),potential=el('p'),jobs=el('ul'),manage=button('VOIR LES CHANTIERS','urbanManageJobs',()=>{g.citadel.open();g.citadelUI?.choose('works',true);});
  remaining.id='urbanRemaining';remaining.setAttribute('role','status');potential.id='urbanPotential';jobs.id='urbanPendingJobs';growth.append(el('h3','Préparer le prochain âge'),remaining,potential,jobs,manage,el('p','Potentiel conditionnel : les chantiers suspendus ou bloqués doivent aussi être terminés et rester debout. Les ouvriers, les trajets et les accès restent nécessaires.','urban-note'));block.append(growth);
  const light=el('article',undefined,'urban-light'),title=el('h3'),nightText=el('p'),torch=button('TORCHE [L]','urbanTorch',()=>g.urban.flashlight(!g.urban.snapshot().flashlight));light.append(title,nightText,torch,el('p','La torche autonome suit votre visée. Les lumières fixes exigent une alimentation complète ; les murs coupent les faisceaux. Les tirs automatiques ne prennent pas pour cible un infecté plongé dans l’obscurité. Les refuges sans consommateur électrique n’éclairent plus gratuitement les nuits noires.','urban-note'));
  const orient=el('div',undefined,'urban-orient'),sel=el('select');sel.id='urbanLightSelect';sel.setAttribute('aria-label','Projecteur à orienter');orient.append(sel);for(const[v,n]of ['EST','SUD','OUEST','NORD'].entries())orient.append(button(n,'urbanDirection'+v,()=>g.urban.direction(Number(sel.value),v)));light.append(orient);block.append(light);
  const catalogue=el('div',undefined,'urban-new'),nextTitle=el('h3'),nextCatalogue=el('div',undefined,'urban-new');catalogue.id='urbanCurrentModels';nextTitle.id='urbanNextTitle';nextCatalogue.id='urbanNextModels';block.append(el('h3','Modèles de l’âge atteint'),catalogue,nextTitle,el('p','Coûts par chantier, à payer depuis le dépôt. Les modèles du prochain âge restent verrouillés jusque-là ; plans de terrain, emplacement et accès restent à vérifier dans le catalogue.','urban-note'),nextCatalogue);panel.append(block);
  const mini=button('NUIT & ÉCLAIRAGE','urbanNightHud',()=>{g.coordinationUI.open();block.scrollIntoView({block:'nearest'});});mini.className='urban-night-hud';g.ui.rightPanel?.insertBefore(mini,g.ui.rightPanel.firstChild);
  const torchHud=button('LUMIÈRE [L]','urbanTorchHud',()=>g.urban.flashlight(!g.urban.snapshot().flashlight));torchHud.className='urban-torch-hud';get('touchControls')?.appendChild(torchHud);
  let catalogueKey='',jobsKey='',lightsKey='',last=-Infinity;
  for(const t of C.CITY_TIERS){const a=el('div',undefined,'urban-age');a.dataset.age=t.id;a.append(el('strong',t.name),el('small',t.requiredScore+' pts'));ages.append(a);}
  function refresh(force=false){if(!force&&performance.now()-last<500)return;last=performance.now();const playing=g.state==='playing'&&!g.gameOver,lighting=g.urban.lightingState(),forecast=g.nightwatch.forecast(),dark=g.nightwatch.isBlackout();mini.classList.toggle('hidden',!playing);torchHud.classList.toggle('hidden',!playing);text(mini,dark?'NUIT NOIRE · ÉCLAIRAGE VITAL':forecast?'CE SOIR · NUIT NOIRE':'NUIT ORDINAIRE · PRÉPARATIFS');mini.dataset.dark=String(forecast);torch.disabled=torchHud.disabled=!g.canIssueCommand()||g.player.dead;torchHud.setAttribute('aria-pressed',String(lighting.flashlight));text(torchHud,lighting.flashlight?'TORCHE ALLUMÉE [L]':'TORCHE ÉTEINTE [L]');
   if(panel.closest('.hidden'))return;
   const v=g.urban.planning();
   text(h,v.age.name);text(brief,'Score construit : '+g.cityScore.toFixed(1)+' · Pic atteint : '+v.peakScore.toFixed(1)+' · '+v.available+' modèles actuellement visibles'+(v.next?' · Prochain âge : '+v.next.name+' à '+v.next.requiredScore+' points.':'. Dernier âge atteint : la partie et la construction continuent.'));
   bar.max=v.next?.requiredScore||Math.max(1,v.peakScore);bar.value=v.peakScore;for(const a of ages.children)a.dataset.reached=String(Number(a.dataset.age)<=v.age.id);
   text(remaining,v.next?v.remaining.toFixed(1)+' points construits supplémentaires pour '+v.next.name+' (seuil : '+v.next.requiredScore+').':'Dernier âge atteint. Les chantiers et la défense de D-17 continuent.');
   text(potential,v.pending.length?v.pending.length+' chantier(s) financé(s) · +'+v.pendingScore.toFixed(1)+' points à leur achèvement · Score si tous restent debout : '+v.potentialScore.toFixed(1)+(v.next?' · '+(v.remainingAfterPending>0?v.remainingAfterPending.toFixed(1)+' points encore à financer et construire pour '+v.next.name+'.':'Le potentiel couvre le seuil de '+v.next.name+'.'):''):'Aucun chantier en cours. Le financement seul ne donne aucun point.');
   manage.disabled=!g.canIssueCommand()||g.player.dead;
   const jk=v.pending.map(b=>b.id+':'+b.name+':'+b.score+':'+Math.floor(b.progress*100)).join(',');if(jk!==jobsKey){jobsKey=jk;jobs.replaceChildren();for(const b of v.pending.slice(0,6))jobs.append(el('li',b.name+' #'+b.id+' · '+Math.floor(b.progress*100)+' % · +'+b.score+' points à l’achèvement'));if(v.pending.length>6)jobs.append(el('li',(v.pending.length-6)+' autre(s) chantier(s) : consulter la gestion des chantiers.'));}jobs.classList.toggle('hidden',!v.pending.length);
   text(title,dark?'Nuit noire en cours':forecast?'Nuit noire annoncée pour ce soir':'Préparer le réseau lumineux');text(nightText,'Nuits noires aux vagues 4, 7, 10, puis tous les trois assauts. Sans lumière, le terrain est masqué en noir. Électricité : '+(g.powerGenerated+(g.powerBatteryOutput||0)).toFixed(0)+' / '+g.powerUsed.toFixed(0)+'. La mini-carte ne révèle pas les infectés non éclairés.');torch.setAttribute('aria-pressed',String(v.flashlight));text(torch,v.flashlight?'ÉTEINDRE LA TORCHE [L]':'ALLUMER LA TORCHE [L]');
   const ls=[...g.world.buildings.values()].filter(b=>!b.dead&&b.completed&&b.def.beamHalfAngle),lk=ls.map(b=>b.id+':'+b.rotation).join(',');if(lk!==lightsKey){lightsKey=lk;const chosen=sel.value;sel.replaceChildren();for(const b of ls){const o=el('option',b.def.name+' #'+b.id+' · '+['EST','SUD','OUEST','NORD'][b.rotation]);o.value=b.id;sel.append(o);}if(ls.some(b=>String(b.id)===chosen))sel.value=chosen;}for(const b of orient.querySelectorAll('button'))b.disabled=!ls.length||!g.canIssueCommand();
   text(nextTitle,v.next?'Au prochain âge · '+v.next.name:'Tous les âges sont connus');
   const key=JSON.stringify([v.age.id,...v.currentModels,...v.nextModels]);if(key!==catalogueKey){catalogueKey=key;const render=(node,models)=>{node.replaceChildren();for(const d of models){const card=el('article',undefined,'urban-card');card.dataset.model=d.id;const status=el('p',d.requires?'Prérequis : '+d.requirementName+(d.requirementMet?' terminé.':' à construire et achever.'):'Aucun bâtiment prérequis.','urban-note');card.append(el('strong',d.name),el('p',d.description),el('small','Coût : '+C.resourceText(d.cost)+' · +'+d.score+' points'),status,el('p',Object.keys(d.missing).length?'Manque au dépôt : '+C.resourceText(d.missing)+'.':'Matériaux présents au dépôt.','urban-note'));node.append(card);}};render(catalogue,v.currentModels);render(nextCatalogue,v.nextModels);}
  }
  const old=g.updateUI.bind(g);g.updateUI=(...a)=>{const r=old(...a);refresh();return r;};
  root.addEventListener('keydown',e=>{if(e.code!=='KeyL'||e.repeat||e.ctrlKey||e.metaKey||e.altKey||e.target?.closest?.('input,textarea,select,button,summary,[contenteditable]')||!g.canIssueCommand())return;e.preventDefault();g.urban.flashlight(!g.urban.snapshot().flashlight);refresh(true);},{capture:true});
  sel.addEventListener('change',()=>refresh(true));
  for(const id of ['coordinationTab','preparationButton'])get(id)?.addEventListener('click',()=>refresh(true));
  const coordination=g.coordinationUI;if(coordination)g.coordinationUI=Object.freeze({...coordination,open:()=>{const r=coordination.open();refresh(true);return r;}});
  g.urbanUI=Object.freeze({refresh});refresh(true);
 }
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(globalThis);
