/* Four field operations in actual distant buildings; stocks never regenerate on streaming. */
(function(root){'use strict';
const C=root.DeadwallCore||(typeof require==='function'?require('./core.js'):null),G=root.DeadwallFrontierGeometry||(typeof require==='function'?require('./frontier-geometry.js'):null),W=root.DeadwallFrontierWorld||(typeof require==='function'?require('./frontier-world.js'):null),R=C.WorldOpsRules131,copy=v=>JSON.parse(JSON.stringify(v)),worlds=new Map();
const initial=()=>({version:1,relays:{},secured:[],opened:[],surveyed:[]});
function reference(full){if(!full)return null;const key=full.worldSeed+':'+full.frontier?.generation;if(!worlds.has(key)){worlds.set(key,W.create(full.worldSeed,full.frontier?.generation||3));if(worlds.size>3)worlds.delete(worlds.keys().next().value);}return worlds.get(key);}
function normalize(raw,full){if(raw===undefined)return initial();const bad=()=>{throw Error('Registre des régions lointaines invalide.');};if(!raw||raw.version!==1||Object.keys(raw).some(k=>!['version','relays','secured','opened','surveyed'].includes(k)))bad();const s=initial(),w=reference(full),by=w?new Map(w.pois.map(p=>[p.id,p])):null;
 for(const key of ['secured','opened','surveyed']){if(!Array.isArray(raw[key])||raw[key].length>R.maxRecords||new Set(raw[key]).size!==raw[key].length)bad();s[key]=raw[key].map(id=>{if(typeof id!=='string'||!(key==='surveyed'?/^S\d+_\d+$/:/^P\d{4}$/).test(id))bad();if(w&&(key==='surveyed'?!w.sectors.some(t=>t.id===id):!by.has(id)))bad();return id;});}
 if(!raw.relays||typeof raw.relays!=='object'||Array.isArray(raw.relays)||Object.keys(raw.relays).length>R.maxRecords)bad();
 for(const[id,stock]of Object.entries(raw.relays)){if(!/^P\d{4}$/.test(id)||!stock||Object.keys(stock).some(k=>!C.RESOURCE_KEYS.includes(k)))bad();if(by&&by.get(id)?.occupation!=='allied'&&!s.secured.includes(id))bad();const bag=C.makeBag();for(const k of C.RESOURCE_KEYS){const v=stock[k];if(!Number.isFinite(v)||v<0||v>R.relayCapacity)bad();bag[k]=v;}if(C.bagTotal(bag)>R.relayCapacity+.000001)bad();s.relays[id]=bag;}
 if(full){if(full.frontier?.generation<5&&(Object.keys(s.relays).length||s.secured.length||s.opened.length||s.surveyed.length))bad();const seen=new Set(full.frontier?.seen||[]);for(const id of [...Object.keys(s.relays),...s.secured,...s.opened])if(!seen.has(id))bad();for(const id of s.surveyed)if(w.sectors.find(t=>t.id===id).sites.some(site=>!seen.has(site)))bad();for(const id of s.opened)if(!by.get(id)?.frontier131?.reserve)bad();for(const id of s.secured){const p=by.get(id);if(p?.occupation!=='infected')bad();for(let i=0;i<w.threatCount(p);i++)if(full.frontier.enemies[id+':e'+i]!==0)bad();}for(const p of w.pois)if(p.frontier131?.reserve&&(full.frontier.taken[p.frontier131.reserve]||0)>0&&!s.opened.includes(p.id))bad();}
 return s;
}
function install(g){if(g.worldOps131)return g.worldOps131;if(!g.expansions)return null;let state=initial(),task=null,message='';
 const pos=()=>g.frontier.position(),world=()=>g.frontier.world(),can=()=>g.expansions.canAct(),fail=reason=>{message=reason;return{ok:false,reason};},done=t=>{message=t;g.audio.ui?.();g.notify?.(t,'good');g.save(false);return{ok:true};};
 const nearHome=()=>!pos().active&&g.core()&&g.workerCanWorkAt(g.player,g.core(),100),target=p=>G.global(p,p.w/2,-2),near=p=>{const f=pos(),q=target(p);return f.active&&f.z===0&&!f.car?.driving&&Math.hypot(f.x-q.x,f.y-q.y)<=R.reach&&world().line(f,q,0,null,null,.05);};
 function nearby(){const f=pos();if(!f.active||f.generation<5)return null;return world().nearPOI(f.x,f.y,60).filter(p=>p.generation>=5).sort((a,b)=>Math.hypot(a.x-f.x,a.y-f.y)-Math.hypot(b.x-f.x,b.y-f.y))[0]||null;}
 function safe(){const f=pos();return!g.frontier.contacts().some(e=>Math.hypot(e.x-f.x,e.y-f.y)<R.danger&&e.z===f.z)&&!(g.worldEvolution?.groupMembers()||[]).some(e=>Math.hypot(e.x-f.x,e.y-f.y)<R.danger);}
 function cleared(p){for(let i=0;i<world().threatCount(p);i++)if(g.frontier.enemyHealth(p.id+':e'+i)!==0)return false;return true;}
 function preview(kind,id){if(kind==='reserve'&&g.interventions134)return g.interventions134.previewReserve(id);if(!can()||g.player.dead||g.player.health<=0)return{ok:false,reason:'Commandant indisponible.'};if(task||g.expansions.busy('world131'))return{ok:false,reason:'Une intervention est déjà en cours.'};const p=world().pois.find(p=>p.id===id);if(!p||p.generation<5||!near(p))return{ok:false,reason:'Rejoignez à pied l’entrée du site lointain.'};if(!safe())return{ok:false,reason:'Éloignez les infectés de l’entrée.'};if(g.player.reload>0)return{ok:false,reason:'Terminez le rechargement.'};const rule=R[kind];if(!rule)return{ok:false,reason:'Opération inconnue.'};let source=g.player.carry;
  if(kind==='relay'){if(state.relays[id])return{ok:false,reason:'Relais déjà ouvert.'};if(p.occupation!=='allied'&&!state.secured.includes(id))return{ok:false,reason:'Un site infesté doit être entièrement sécurisé.'};}
  if(kind==='secure'&&(p.occupation!=='infected'||state.secured.includes(id)||!cleared(p)))return{ok:false,reason:'Éliminez les occupants de tous les étages avant de certifier le site.'};
  if(kind==='reserve'&&(!p.frontier131.reserve||state.opened.includes(id)))return{ok:false,reason:'Aucune réserve scellée à ouvrir.'};
  if(kind==='survey'&&state.surveyed.includes(p.sector))return{ok:false,reason:'Carrefour déjà relevé.'};
  if(kind==='rest'){source=state.relays[id];if(!source)return{ok:false,reason:'Ouvrez et ravitaillez ce relais.'};if(g.player.health>=g.player.maxHealth)return{ok:false,reason:'Aucun soin nécessaire.'};}
  if(!C.canAfford(source,rule.cost))return{ok:false,reason:kind==='rest'?'Relais : 2 vivres et 1 médicament nécessaires.':'Fournitures insuffisantes dans le sac.'};return{ok:true,seconds:rule.seconds,cost:rule.cost,p,source};
 }
 function begin(kind,id=nearby()?.id){if(kind==='reserve'&&g.interventions134)return g.interventions134.beginReserve(id);const q=preview(kind,id);if(!q.ok)return fail(q.reason);const f=pos();task={kind,id,x:f.x,y:f.y,z:f.z,inside:f.inside,elapsed:0,seconds:q.seconds,health:g.player.health};g.releaseInputs();return{ok:true};}
 const cancel=()=>{if(!task)return false;task=null;message='Intervention interrompue, fournitures conservées.';return true;};
 function finish(t,q){C.spend(q.source,q.cost);g.frontier.revealSites([t.id]);if(t.kind==='relay'){state.relays[t.id]=C.makeBag();message='Relais ouvert et vide. Déposez vos fournitures pour les prochains voyages.';}
  if(t.kind==='secure'){state.secured.push(t.id);g.frontier.annotate(t.id,'cleared');message='Site dégagé : un relais peut y être aménagé. Les migrations peuvent encore revenir.';}
  if(t.kind==='reserve'){state.opened.push(t.id);message='Scellé retiré. Rejoignez la caisse extérieure et maintenez E pour prélever son stock fini.';}
  if(t.kind==='survey'){state.surveyed.push(q.p.sector);const sector=world().sectors.find(s=>s.id===q.p.sector);g.frontier.revealSites(sector?.sites||[]);message='Plan du secteur relevé. Ses accès figurent maintenant dans le carnet et le GPS.';}
  if(t.kind==='rest'){g.player.health=Math.min(g.player.maxHealth,g.player.health+R.rest.health);message='Soins de relais terminés. Les fournitures ont été prélevées dans sa réserve.';}
  done(message);
 }
 function step(dt){if(!task||g.state!=='playing'||g.paused||g.activeOverlay||g.gameOver||!Number.isFinite(dt)||dt<=0)return;const f=pos(),t=task;task=null;const q=preview(t.kind,t.id);task=t;const moving=[...g.input.keys,...g.input.pressed].some(k=>/^Key[WAZQSDERF]$|^Arrow|^Page/.test(k));if(!q.ok||!f.active||f.z!==t.z||f.inside!==t.inside||Math.hypot(f.x-t.x,f.y-t.y)>R.moveTolerance||g.player.health<t.health||g.input.mouseDown||g.input.touchFire||moving){cancel();return;}t.elapsed+=Math.min(.1,dt);g.frontier.signalAt(f,R.workNoise);if(t.elapsed>=q.seconds){task=null;finish(t,q);}}
 function transfer(id,direction){const p=world().pois.find(p=>p.id===id),stock=state.relays[id];if(!can()||task||g.expansions.busy('world131')||!p||!stock||!near(p)||!safe())return fail('Approchez un relais libre et sûr à pied.');const source=direction==='store'?g.player.carry:direction==='take'?stock:null,targetBag=direction==='store'?stock:g.player.carry;if(!source)return fail('Transfert inconnu.');let room=(direction==='store'?R.relayCapacity:g.player.carryCapacity)-C.bagTotal(targetBag),total=0;for(const k of C.RESOURCE_KEYS){const n=Math.max(0,Math.min(room,source[k]));source[k]-=n;targetBag[k]+=n;room-=n;total+=n;}return total?done(Math.floor(total)+' fournitures transférées.'):fail('Sac ou relais plein, ou réserve vide.');}
 function expand(){if(!can()||!nearHome()||g.expansions.busy('world131'))return fail('Rejoignez le dépôt de D-17 avec le commandant libre.');if(pos().generation!==4)return fail('Le noyau régional doit être de génération 4.');const data=g.serialize();if(data.expansions127?.modules.lore131)data.expansions127.modules.lore131.siteGeneration??=4;data.frontier.generation=5;try{g.restoreSave(data);}catch(error){return fail(error.message);}return done('Relevés étendus à 24,576 km de côté. Les anciens lieux et prélèvements sont conservés.');}
 function overview(){const f=pos(),p=nearby(),w=f.generation>=5?world():null;return{summary:'Régions lointaines : ouvrir des relais, dégager des bâtiments, récupérer des réserves finies et relever les accès.',rows:[{label:'Carte',value:((w?.size||8192)/1000).toFixed(3)+' km de côté'},{label:'Relais',value:Object.keys(state.relays).length},{label:'Sites dégagés',value:state.secured.length},{label:'Réserves ouvertes',value:state.opened.length},{label:'Secteurs relevés',value:state.surveyed.length},{label:'Site proche',value:p?.name||'Aucun site lointain à proximité'},{label:'Travail',value:task?Math.floor(task.elapsed/task.seconds*100)+' %':message||'Approchez l’entrée d’un site'}],near:p?.id||null,state:copy(state),task:task?{kind:task.kind,progress:task.elapsed/task.seconds}:null,message};}
 function actions(){const p=nearby(),a=[];if(pos().generation===4)a.push({id:'expand131',label:'Étendre les relevés régionaux',reason:'Au dépôt : ouvrir les routes au-delà des 8 km historiques.',disabled:!nearHome()||!can(),run:expand,close:true});for(const[k,label]of [['relay','Aménager ce relais'],['secure','Certifier le site dégagé'],['reserve','Ouvrir la réserve scellée'],['survey','Relever le plan du carrefour'],['rest','Recevoir les soins du relais']]){const q=preview(k,p?.id);a.push({id:k,label,disabled:!q.ok,reason:q.reason||(k==='reserve'&&g.interventions134?'Mini-jeu sur le contenant · ':q.seconds+' s sur place · ')+Object.entries(q.cost).map(([r,n])=>n+' '+C.RESOURCE_META[r].label).join(', '),run:()=>begin(k,p.id),close:true});}if(p&&state.relays[p.id])for(const [dir,label]of [['store','Déposer le sac au relais'],['take','Reprendre les fournitures']])a.push({id:dir,label,disabled:!!task||!near(p),reason:Math.floor(C.bagTotal(state.relays[p.id]))+' / '+R.relayCapacity+' fournitures',run:()=>transfer(p.id,dir),close:true});if(task)a.push({id:'cancel',label:'Interrompre',run:()=>({ok:cancel()}),close:true});return a;}
 function depthEntries(v,view){if(v.z!==0)return[];const entries=[];for(const p of v.world.nearPOI(v.x,v.y,80)){const stock=state.relays[p.id],mapped=state.surveyed.includes(p.sector);if(!stock&&!mapped)continue;const q=G.global(p,p.w/2+1.6,-2);if(q.x<view.l||q.x>view.r||q.y<view.t||q.y>view.b)continue;entries.push({kind:'world131',id:'world131:'+p.id,depth:q.y,draw:c=>{c.save();c.strokeStyle='#d8cc9e';c.lineWidth=.08;c.beginPath();c.moveTo(q.x,q.y);c.lineTo(q.x,q.y-1.3);c.stroke();c.fillStyle=stock?'#86a681':'#c4ac73';c.fillRect(q.x,q.y-1.3,.55,.4);if(stock){c.fillStyle='#5f6953';c.fillRect(q.x-.65,q.y-.4,.45,.4);c.fillStyle='#c1caa2';c.fillRect(q.x-.65,q.y-.43,.45,.1);}c.restore();}});}return entries;}
 function completeInterventionReserve(id){if(!g.interventions134?.authorizesReserve(id)||state.opened.includes(id))return false;const p=world().pois.find(p=>p.id===id);if(!p?.frontier131?.reserve)return false;g.frontier.revealSites([id]);state.opened.push(id);return true;}
 const api={completeInterventionReserve,overview,actions,preview,begin,cancel,step,expand,transfer,opened:id=>state.opened.includes(id),snapshot:()=>copy(state),busy:()=>!!task,activity:()=>task?{kind:task.kind,progress:task.elapsed/task.seconds}:null,depthEntries};g.worldOps131=Object.freeze(api);
 g.expansions.register({id:'world131',title:'Monde & relais',overview,actions,validate:normalize,snapshot:api.snapshot,restore:raw=>{state=normalize(raw);task=null;message='';},reset:()=>{state=initial();task=null;message='';},busy:api.busy});
 const unavailable=()=>!g.player||g.player.dead||g.player.health<=0||g.gameOver||g.state!=='playing';
 const update=g.update.bind(g);g.update=dt=>{if(task&&unavailable())cancel();const r=update(dt);if(task&&unavailable())cancel();step(dt);return r;};const menu=g.returnToMenu.bind(g);g.returnToMenu=(...a)=>{cancel();return menu(...a);};
 const start=g.startNew.bind(g);g.startNew=(...a)=>{const r=start(...a);if(r!==false&&g.state==='playing'&&pos().generation===4){const data=g.serialize();data.frontier.generation=root.DeadwallGeography135?7:5;if(data.frontier.generation>=6){const home=root.DeadwallGeography135.home(data.worldSeed,data.frontier.generation);data.frontier.x=home.maxX+2;data.frontier.y=home.y;}g.restoreSave(data);g.save(false);}return r;};return api;
}
const api={install,normalize,initial};root.DeadwallWorldPack131=api;if(typeof module!=='undefined'&&module.exports)module.exports=api;if(root.DEADWALL&&root.document)install(root.DEADWALL);
})(globalThis);
